### ISSUE TITLE
nix builds don't work on OSX any more

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#1018]
playground and meadow don't build on Mojave, they probably need updated version of nixpkgs. Presumably many of IOHK nix projects have the same issues.

```
[11 of 11] Compiling Server           ( src/Server.hs, dist/build/Server.o )
ld: warning: /nix/store/xsa7nkp8nippm62vg7q2gx5ysv8qyzlf-libiconv-osx-10.11.6/lib/libiconv.dylib, ignoring unexpected dylib file
ld: warning: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation, ignoring unexpected dylib file
/nix/store/w9avgn80c1vqsn9bpm1x5401qknlc966-cctools-binutils-darwin/bin/ranlib: object: dist/build/libHSmeadow-0.1.0.0-8IAYThHEhtLB5oYKwmx5Qd-ghc8.6.4.a(cryptlib.o) malformed object (unknown load command 1)
`ranlib' failed in phase `Ranlib'. (Exit code: 1)
time.setupCompilerEnvironmentPhase 4
time.unpackPhase 0
time.patchPhase 0
time.compileBuildDriverPhase 3
time.configurePhase.user 1.919
time.configurePhase.system 0.555
time.configurePhase.real 2.768
time.configurePhase 3
time.buildPhase.user 12.095
time.buildPhase.system 2.113
time.buildPhase.real 14.773
builder for '/nix/store/q6cyd1vhlmrm9bpk5v23mm8q57vq429z-meadow-0.1.0.0.drv' failed with exit code 1
```

**Comment by michaelpj** [comment]
cc @angerman 

Might this be solved by going to 19.03? That seems like a good reason to do so.

**Comment by shmish111** [comment]
I had a quick look but it looks like you need a good working knowledge of https://github.com/input-output-hk/nixpkgs to play around, just overriding the `NIX_PATH=custom_nixpkgs` with a NixOS nixpkgs causes `unexpected argument 'enablePhaseMetrics'` so I presume there is some custom nix tools stuff that needs to be in whatever nixpkgs you use.

Is there any documentation on this?

Other Haskell projects are building on my OSX machine using latest stable NixOS nixpkgs so I think it's just a matter of the latest OSX updates not being in the iohk nixpkgs.

**Comment by michaelpj** [comment]
We have a customized fork of nixpkgs, alas :(

I know devops are looking into upgrading to 19.03, I don't think this is something we can easily do unilaterally.

**Comment by angerman** [comment]
There is iohk-19.03 branch on iohk/nixpkgs

Out CI is unable to build that though. See input-output-hk/tools#4. @input-output-hk/DevOps need to upgrade our Mac builders first.

**Comment by michaelpj** [comment]
Fixed since I upgraded our nixpkgs.
