### ISSUE TITLE
Compression for Plutus Core

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#1035]
As Duncan does not want C code into Plutus machinery (due to security problems), we should look into possibly writing our own library (with Merkle trees?). However, we might want something simpler in the meantime. 

cc @michaelpj @mchakravarty

**Comment by michaelpj** [comment]
See https://github.com/input-output-hk/plutus/issues/471

**Comment by kwxm** [comment]
Yeah, see #471.  I think we can close this.
