### ISSUE TITLE
GHCi doesn't work with Plutus

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#1046]
I tried to run `cabal new-repl` on `plutus-use-cases`  and got:

```
1 of 11] Compiling Language.PlutusTx.Coordination.Contracts.CrowdFunding ( src/Language/PlutusTx/Coordination/Contracts/CrowdFunding.hs, interpreted )
GHC Core to PLC plugin: Error: Reference to a name which is not a local, a builtin, or an external INLINABLE function: Variable and
       No unfolding
Context: Converting definition of: validCollection
Context: Converting definition of: mkValidator
Context: Converting expr at "plutus-use-cases-0.1.0.0-inplace:Language.PlutusTx.Coordination.Contracts.CrowdFunding:(110,8)-(110,48)"
```

I don't know how much of a priority this is, but it should be noted as a bug. cc @michaelpj

**Comment by michaelpj** [comment]
Yeah, you need `-fobject-code` and `-fno-ignore-interface-pragmas`. I'll put a caveat in the readme and see if I can put those in an appropriate place in the cabal file.

**Comment by mateusap1** [comment]
I'm getting this ame error even though my cabal file has `-fobject-code` and `-fno-ignore-interface-pragmas`

**Comment by mateusap1** [comment]
Now that I looked at it more carefully, it's probably an error with the editor, because it works with `cabal build` or `cabal repl`

**Comment by j-mueller** [comment]
Probably also `-fplugin-opt PlutusTx.Plugin:defer-errors`

**Comment by mateusap1** [comment]
Wow that fixed it, thank you so much!
