### ISSUE TITLE
Benchmarks wired to plutus-tx output

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#1099]
Currently, our benchmarks are checked into the repo - which is good for reproducibility, but may mean they are not benchmarking current/sensible things. 

For that reason, we should (in line with Michael's suggestion) create a separate cabal library for benchmarks and have it depend on `plutus-tx`, `plutus-use-cases`, etc.

**Comment by michaelpj** [comment]
We've got some now.
