### ISSUE TITLE
Typeclasses

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1109]
What would it take to support typeclasses?

The problem is not the dictionaries: we can model the dictionary-passing just fine. The problem is the *creation* of the dictionaries. In particular, almost all typeclass instance definitions delegate to other instances defined outside the package, with those in `base` being used particularly often.

We can't see the definitions for the `base` instance dictionaries because (surprise surprise) they're typically not `INLINABLE`. The way we handle this for *functions* in `base` is to replace them with our own versions - hence the Plutus  Tx Prelude - but we can't do that for *instances*.

So we need a way to see the bodies of, realistically, everything in all our dependencies. Which means something like https://github.com/input-output-hk/plutus/issues/982.

**Comment by mchakravarty** [comment]
We could define our own versions of the type classes.

**Comment by michaelpj** [comment]
> We could define our own versions of the type classes.

That's.... a very good point. We could do that. I had this tied up in my mind with "why we can't use other people's libraries", but if we just want to use typeclasses in *our* code... why not?

I should definitely try this out, it would make a lot of things much nicer.
