### ISSUE TITLE
Link to gihub commit on plyayground

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#1125]
It would be nice if we could see not only what version you are currently using but also have a link to the github page for that commit

**Comment by michaelpj** [comment]
Maybe we *don't* want to do this? We can nearly get rid of the need for the applications to know the commit, which would let us get rid of the magic git substitution stuff.

**Comment by shmish111** [comment]
The idea was that you could see on the alpha env what code you are looking at but TBH I think it's better that we just say it _should_ be master or close.
