### ISSUE TITLE
Annotating all top-level bindings is both annoying and insufficient

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1129]
At the moment we have to annotate all top-level bindings as `INLINABLE`.

This is annoying, but it's also insufficient: despite our best efforts, GHC can add new top-level bindings that we have to care about, notably specializations. (It seems to specialize inside even `INLINABLE` unfoldings, which is annoying.) These may then lack unfoldings, so we fail.

Really we just want to say "give me unfoldings for everything in this module. We hoped to use `-fexpose-all-unfoldings` for that, but it falls foul of https://github.com/input-output-hk/plutus/issues/1085.

It looks like the only long-term solution to this is https://github.com/input-output-hk/plutus/issues/982.

**Comment by mchakravarty** [comment]
Why does `-fexpose-all-unfoldings` the situation worse with PLC stability?

**Comment by michaelpj** [comment]
As I said in https://github.com/input-output-hk/plutus/issues/1085, the problem is that `-fexpose-all-unfoldings` puts in *post*-optimization Core, which makes us very sensitive to even minor compiler differences. e.g. I'm worried it might differ between native and JS, for example. `INLINABLE` keeps the *pre*-optimization Core (except, apparently, it specializes it a bit :angry: ), because it's trying to make it possible for rewrite rules to fire after inlining. So `INLINABLE` works much better for our purposes.

**Comment by AriFordsham** [comment]
@michaelpj In my opinon the main issue here is not the keystroke burden of `{-# INLINABLE #-}`. If Plutus combatibility could be enabled with just a compiler flag and no source changes, then, by providing a slot-in `base` replacement package (see [here](https://mail.haskell.org/pipermail/haskell-cafe/2016-December/125879.html) you would be able to use any Haskel package on Plutus, and have access to the whole Haskell ecosystem.

The biggest annoyance to me when writing Plutus contracts is not having to annotate functions, but not being able to reach for my favorite Haskell combinators when I need them (from base or elsewhere).
