### ISSUE TITLE
Mutually recursive datatypes

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1134]
We know how to do it, it's just a case of implementing it.

I think @effectfully is interested, but someone else may have to do it depending on time.

**Comment by michaelpj** [comment]
"We know how to do this" meaning "it's in the paper".

**Comment by effectfully** [comment]
It's even [implemented](https://github.com/input-output-hk/plutus/blob/be7876c7948bfd8bd72c763947811d10b1222c90/papers/unraveling-recursion/code/src/Compilation/Encode/Core.agda), just not in Haskell.
