### ISSUE TITLE
Verifiably establish how a PLC program was produced

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1138]
Suppose that I want to use a script S, either locking outputs with it myself, or unlocking outputs locked by it.

Now, I want to know what S *does*, otherwise I'm at risk of being manipulated. After all, we're on the blockchain, everything is supposed to be public.

I can certainly look at S directly, run it, etc, but this may be a lot harder than having access to the source that it was compiled from. 

So I want some way to get back from the compiled artifact to a "source-level" version of that.

# Verifiable links

However, this link needs to be *verifiable*, otherwise a malicious actor can just lie and give you some innocuous source instead of the malicious source they actually compiled. Options:
- Certified compilation
    - This would be a massive research effort in its own right
- Signatures by trusted parties
    - This is the easiest approach, but requires adding a trusted party into the system.
- Re-run the process yourself and verify that the output is identical

## Reproducible compilation

The last option seems viable, but has its own problems: it requires the "source-level" version to be a *perfect* description of how the artifact was produced, *and* for the process to be entirely deterministic.

(We are sensitive to all sorts of variance in the inputs and the environment. The most obvious is compiler versions (see e.g. https://github.com/input-output-hk/plutus/issues/1085), but there is a whole bunch of software involved in getting the final artifact which can be sensitive to locales, timestamps, platform, god knows what.)

We can probably make the process deterministic (i.e. make GHC and cabal deterministic) given that everything else is fixed. 

When it comes to making sure everything else is fixed, we could use Nix for this purpose. They have had a lot of experience solving similar problems (and they're not [half bad](https://r13y.com/) on the determinism front either). However, this would require that end users use Nix.

# Parameterized validators

Another spanner in the works is the fact that validator scripts are not always compile-time constants, often they are parameterized and have the parameters passed to them at runtime via lifting. So we would need to not only reproduce the compilation, but also the execution of the program that computes the validator script, including interactions with the outside world (e.g. with the user setting the parameters).

Quoting an email:
> The only thing I can think of to mitigate this is to strongly discourage the use of non-constant validators, and encourage people to put the parameters in the data script. That requires us to be able to decode the data script if we want legibility, but we wanted to do that anyway. That would complicate e.g. making parameterized instances of state machines where you really want to put the *state* in the data script, but we could probably work around that.
>
>The real killer is cases where the script address matters, e.g. monetary policy scripts. There we've been suggesting that you put a salt into the validator script to make sure it has a different hash from previous monetary policy scripts (and hence controls a different currency) - but this means that you need to parameterize them. And you do need the parameterization: in some cases you may want to make lots of monetary policy scripts, e.g. if you're using NFTs as roles where you have a new currency for each instance of the contract you produce.

(Related: https://github.com/input-output-hk/plutus/issues/1137)

**Comment by michaelpj** [comment]
This relates to https://github.com/input-output-hk/plutus/issues/1140, in that if we use a description of how to produce the validator as the identifying metadata discussed in that issue, then we would solve this issue too (but would have to solve all the same problems also).

**Comment by michaelpj** [comment]
Email discussion: https://groups.google.com/a/iohk.io/forum/?hl=en-GB#!topic/plutus/6rbLEqRxBFs

**Comment by kwxm** [comment]
What about Marlowe?  Will solving these problems for Haskell contracts suffice for Marlowe as well, or is more required there? Might Marlowe code be sufficiently stereotypical that the problem is actually easier?
