### ISSUE TITLE
mockchain: consider transaction cost when validating a transaction

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1139]
The mockchain should have a (configurable) function `minFee :: Tx -> Ada` that computes the required fee for a transaction. The default implementation of `txFee` can just be `const 1`. In [`validateTransaction`](https://github.com/input-output-hk/plutus/blob/master/plutus-wallet-api/ledger/Ledger/Index.hs#L122) we should then test that the transaction's `txFee` field is at least as great as `minFee`.

Then we need to change the wallet implementation to consider the fee as well, for example in [`signTxAndSubmit`](https://github.com/input-output-hk/plutus/blob/master/plutus-wallet-api/src/Wallet/API.hs#L461)

**Comment by michaelpj** [comment]
Ideally we should also pass the remaining fee into the script evaluation, although it will ignore it for the moment.

**Comment by raduom** [comment]
Can I use [this](https://cardanodocs.com/cardano/transaction-fees/) page for the initial implementation of transaction fees, rather than returning 1?

**Comment by michaelpj** [comment]
I don't think those pages are remotely true any more, alas. Is there anything in the ledger spec about fees?

Note that I don't think it's worth being *too* clever about the fees here. This is a mock implementation, and fees aren't really the interesting bit (for us). Realistically, you're going to ask the wallet how much it costs, it's going to tell you, and then you pay that. As long as we model the back and forth there I don't think it matters too much what that function is (maybe `rand(0.5, 1)` to avoid people hard-coding ;) ).
