### ISSUE TITLE
run plutus docs on playground servers and change tutorial link

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#1149]
we want the `.docs` to be deployed as a folder in the nginx instance of the playground servers. We also want to change the "Tutorial" link to point to this now relative folder called for example https://alpha.plutus.iohkdev.io/docs

**Comment by michaelpj** [comment]
"Tutorial" should point to `/docs/tutorial` and "API" should point to `/docs/haddock`. There isn't currently a page at `/docs`, maybe there should be?
