### ISSUE TITLE
Rename Meadow -> Marlowe Playground

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1166]
Two bits to do:
- Public facing strings (high priority)
- Internal stuff: project names, etc (low priority)

**Comment by shmish111** [comment]
Public facing stuff done.

**Comment by shmish111** [comment]
I've applied this to alpha env and normally I would move this to done however since it requires a careful deployment to prod I will not mark as done until it's done in prod

**Comment by shmish111** [comment]
There's one more change that we'd like to make and that's the address https://prod.meadow.marlowe.iohkdev.io/ which we would like to change to https://prod.playground.marlowe.iohkdev.io/

This will require a perm redirect which can be set up on the AWS ALB as well as setting up the actual DNS details which @disassembler or his team will need to do for us.
