### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1168]
It's wildly out of date. I also think we should probably just have one for the whole repo - I'm not sure we're ready for the bookkeeping of having more than one.

**Comment by michaelpj** [comment]
Hm, also I think this also gets linked to github currently. Is that right @shmish111 ? Maybe we should also be packaging it up with the playgrounds deployment.

**Comment by shmish111** [comment]
looks like it, yes
