### ISSUE TITLE
Build with stack

### ISSUE THREAD

**Issue by pasca** [input-output-hk/plutus#1180]
when it tried to run with stack using master branch i got this

MacBook-Pro-2:plutus pasca$ stack build
Cloning ab14502279c92084f06aa6222a17873275279e63 from https://github.com/shmish111/servant-purescript.git
Unsupported tarball from /private/var/folders/0k/ppr3t67s6tl22frfsmylcn8h0000gn/T/with-repo-archive13549/foo.tar: File located at "examples/central-counter/frontend/setupPath.sh" is a symbolic link to absolute path /home/robert/projects/gonimo-front/setupPath.sh

tried with stack repl also got same issue, anything i miss? thanks

**Comment by michaelpj** [comment]
Hm, I also get that now. I wonder if it's something to do with the new version of Stack?

**Comment by michaelpj** [comment]
Yep, new versions of Stack have broken Git dependencies in some cases. Wonderful. I raised [a ticket](https://github.com/commercialhaskell/stack/issues/4913) upstream. I might be able to fix it here too, let me see.
