### ISSUE TITLE
redirect https://prod.meadow.marlowe.iohkdev.io/ to https://prod.playground.marlowe.iohkdev.io/

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#1210]
Due to the meadow rebrand to Marlowe Playground we need to change the prod url

@disassembler is setting up DNS for the new domain and I will get the AWS ALB to redirect old to new

**Comment by michaelpj** [comment]
Did this happen?

**Comment by shmish111** [comment]
not yet
