### ISSUE TITLE
Issues compiling any code on the Plutus Playground

### ISSUE THREAD

**Issue by pjcspro** [input-output-hk/plutus#1243]
Hey, 

When I compile any code in the plutus playground, including the default demos, I get the following error:

```
DecodingError: ("Unexpected token < in JSON at position 0" : Nil)
Please try again or contact support for assistance.
```

The token is not always `<`. Also got `S` instead.

On Firefox I got the error:

```
DecodingError: ("JSON.parse: unexpected character at line 1 column 1 of the JSON data" : Nil)
Please try again or contact support for assistance.
```

URL used: https://testnet.iohkdev.io/plutus/tools/playground/

Issue happens on Chrome, Brave, Firefox and Safari

**Comment by pjcspro** [comment]
![plutus error](https://user-images.githubusercontent.com/46036035/60758509-5c007c00-a00f-11e9-8f48-19ab38819c0b.png)

**Comment by j-mueller** [comment]
Hm, all requests fail with a `500` error, looks like something is wrong with the backend @shmish111

**Comment by shmish111** [comment]
Looks like the disks are full on the playground machines, we can clear out some garbage now and then make sure this happens regularly to avoid issues in the future.

**Comment by shmish111** [comment]
https://github.com/input-output-hk/plutus/pull/1274

**Comment by shmish111** [comment]
Ready to be deployed by @disassembler

**Comment by shmish111** [comment]
I've applied this to alpha env and normally I would move this to done however since it's a production bug I will not move it to done until it's deployed in production.

**Comment by Proxiweb** [comment]
compilation bug is back on playground

**Comment by pjcspro** [comment]
@shmish111 Will you please clean the disks again?

**Comment by shmish111** [comment]
Done @pjcspro , sorry about that, we are trying to get a deployment arranged asap.

**Comment by pjcspro** [comment]
Perfect, working again. Thanks
