### ISSUE TITLE
purty purescript code

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#1287]
https://gitlab.com/joneshf/purty is now good enough for use in this project so we should add a `fixPurty` script, a required test to check all purescript code is formatted and also do the formatting for the first time.

**Comment by shmish111** [comment]
Once https://github.com/input-output-hk/plutus/pull/1286 is merged we need 3 more PRs:

1. format marlowe-playground-client code
2. format plutus-playground-client code
3. add a required test for all purescript code

**Comment by shmish111** [comment]
This unfortunately requires us to upgrade to purescript 0.13 in order to format everything, there were some issues with code that was formatted. For now we have the `fixPurty` script and we can ignore files that it breaks but we cannot enforce purty until we have upgraded purescript and made sure everything works.

**Comment by shmish111** [comment]
I had a quick attempt at upgrading PS and if I upgrade the package sets to the latest version then all libraries compile however Halogen 5 release candidate is used. I think we need to wait until the stable version of Halogen 5 is released and then upgrade PS and Halogen at the same time. It doesn't look like it will be more than a couple of days work.

**Comment by shmish111** [comment]
requires https://github.com/input-output-hk/plutus/issues/1297

**Comment by michaelpj** [comment]
Done, I think.
