### ISSUE TITLE
support multiple modes of execution in plc-agda

### ISSUE THREAD

**Issue by jmchapman** [input-output-hk/plutus#1356]
There are currently two possible execution paths in plc-agda: extrinsic reduction via progress and extrinsic CK machine execution.

Add a command line flag to support both:

$ plc-agda --help
plc-agda - a Plutus Core implementation written in Agda

Usage: plc-agda --file FILENAME [--ck]
  run a Plutus Core program

Available options:
  --file FILENAME          Plutus Core source file
  --ck                     Whether to execute using the CK machine
  -h,--help                Show this help text

**Comment by michaelpj** [comment]
Somewhat bikeshedding, but what about mirroring the options for `plc`?

**Comment by jmchapman** [comment]
good idea. I hadn't spotted the mode option for `plc` before. I only have evaluate at the moment but I will move towards mirroring.

**Comment by michaelpj** [comment]
Actually, the more I think about it the more it seems like `plc-agda` should have exactly the same options as `plc` - just with some of them not implemented yet. It would make them easy to test against each other!

**Comment by jmchapman** [comment]
I have implemented an exact subset. I agree about making it easier to test.

**Comment by jmchapman** [comment]
I made a new issue for adding the remaining command line options: #1367
