### ISSUE TITLE
`Ledger.Ada.Ada` is confusing

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1359]
In the emulator, we have a module `Ledger.Ada` whose name refers to Ada *the currency*. There is a type `Ada` as a unit of that currency. The `Ada` type is just a newtype wrapper around `Integer`, so it should actually be called `Lovelace`. This is confusing (and it will get more confusing when fees are added to the mockchain).

To address this we should:

* Rename functions such as `adaValueOf` to `lovelaceValueOf` (and maybe add a new `adaValueOf` that creates the correct amount of lovelace)
* Change / rename the types to `data Ada = Lovelace Integer` or `newtype Lovelace = Lovelace Integer`

**Comment by j-mueller** [comment]
I'd prefer `newtype Lovelace = Lovelace Integer` in the emulator, and whenever we display `Lovelace` values we can convert them to Ada if they are large enough

**Comment by michaelpj** [comment]
I think we're just in for some inevitable confusion due to the fact the currency has the same name as a unit of that currency. I think we can make it reasonably clear, though.

My suggestion:
- The type `Ada` remains called `Ada` - after all, the *type* of thing it is is some Ada-the-currency.
- The constructor of `Ada` becomes `Lovelace`, to make it obvious that that's the unit of the Integer.
- We rename the functions that make `Ada` something like this (verbose but reduces confusion):
    - `adaValueInLovelace`
    - `adaValueInAda` 
- When displaying Ada we do something like `Ada: 400 Lovelace` or `Ada: 100 Ada` to clearly state the currency name and the unit separately.

**Comment by mchakravarty** [comment]
I am very much in favour of @michaelpj's suggestion.

**Comment by michaelpj** [comment]
As for other currencies, I think for consistency we should display them as something like `Foo: 100 tokens`. Maybe if we have extra metadata for human-readable currencies that could include a unit scheme?

**Comment by nau** [comment]
I like the idea of renaming the constructor of `Ada` to `Lovelace`.

What if we rename those functions to just `valueInLovelace` and expect calls to be qualified `Ada.valueInLovelace`?
Maybe use `Double` for values in Ada?

And for displaying I'd suggest to follow the industry `standard` of using decimal points: 0.0004 for 400 Lovelace, and 100.0 for 100 Ada. That's how cryptocurrencies are displayed on most of exchanges and even in Daedalus.

**Comment by mchakravarty** [comment]
> Maybe use `Double` for values in Ada?

No, please no floating-point values. They are the death of precise calculations.

**Comment by michaelpj** [comment]
I don't mind whether we display small amounts of Ada as `400 Lovelace` or `0.0004 Ada`. It's the same thing. But they should definitely be *represented* as an integral number of Lovelace.

**Comment by nau** [comment]
Of course, representation should only be as `Integer`. But we could add helper functions to convert to/from `Double`. Not for calculation and representation.

**Comment by michaelpj** [comment]
But why would you need that? Anything which is programmatically working with these things should be representing them as integers, otherwise as Manuel says you have precision issues. So I'm not sure when you would want `Double -> Ada`.

**Comment by nau** [comment]
That would be helpful for expressing constants like 12.5 Ada, instead of 12500000, which is hard to read.

**Comment by mchakravarty** [comment]
We need to keep a strict separation between representation and presentation. `12.5 Ada`, `400 Lovelace` are great for presentation (e.g., in a Wallet or the Playgrounds), but bad for representation. Conversion to and from presentation should only happen at the edges of the system.

@nau I think, you want https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Fixed.html#t:Micro

**Comment by michaelpj** [comment]
I don't object to a correctly fixed-point type conversion function to Ada, let's add that.

**Comment by michaelpj** [comment]
I think we can just do this.
