### ISSUE TITLE
It's hard to run the `plutus-playground-server` tests

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1361]
In particular, you can't run them with `cabal new-test`. 

The reason is that they need a GHC with e.g. `plutus-tx` in its package db. When building with Nix this works fine, since the ambient GHC when running the tests has this property. However, if you are just using a generic GHC and allowing cabal to wire up the local packages during compilation, then the GHC that's there during the test run won't have the package in its db.

I don't know of an easy way to solve this, but it sure would be nice if we figured out a way.

**Comment by shmish111** [comment]
it used to work with stack and now it doesn't. I don't really think there is an easy way but I could take a look again. It took me quite a while to work out how to get it working with nix 😄 😭

**Comment by shmish111** [comment]
Just to add to the randomness, this is currently working with `stack test` but not `cabal new-test`.

**Comment by michaelpj** [comment]
My understanding for why this happens is:

- The tests need a GHC with the relevant dependencies in order to run.
- Cabal handles dependencies by hiding all the packages and explicitly passing flags to make the appropriate packages visible on every invocation.
    - Consequently, any user-initiated calls to GHC won't see any of the dependencies (because they're all hidden).
- Stack sets up the package db so that all the dependencies are there and *not* hidden, and then doesn't pass any flags (or maybe it sets `CABAL_CONFIG`, I forget).
    - Consequently, any user initiated calls to GHC will see the dependencies.
- Nix sets up the package db similarly to Stack, so behaves the same.

Ultimately, this is pretty fragile, because we're relying on the build tool setting up the environment in a particular way which none of them guarantee :man_shrugging:

**Comment by michaelpj** [comment]
A possible way to "fix" this:
- Turning the test stanza into an executable stanza.
- Making a separate derivation that runs the executable with the correct GHC in scope.
- Making it easy to get an env for running the tests, so that you can do e.g. `nix-shell default.nix -A specialEnv; cabal new-run ....`
