### ISSUE TITLE
Coin selection needs to consider existing transaction inputs

### ISSUE THREAD

**Issue by raduom** [input-output-hk/plutus#1381]
When we run coin selection we only take as input the value that we want to spend. However, we always take the inputs that coin selection provides (and the change) and add them to an existing transaction.

This may cause trouble if the transaction already contains an input that the coin selection has chosen.

A possible fix would be to have coin selection take a list of inputs that cannot be used.

**Comment by michaelpj** [comment]
A concrete example: in our test chains we give each wallet a single large input to spend. If they create a transaction spending that, and then need an additional input to cover fees, at the moment they will be forced to pick the same input again, which would make an invalid transaction.

Of course, in this case filtering out the used input would result in there being *no* available inputs, but this is a case where we have no choice but to have some kind of failure (or ask the user to "make change").

**Comment by raduom** [comment]
Actually coin selection is not wrong since it receives a list of input transactions it can select from.

What needs changing is the wallet API interface, specifically, ` createPaymentWithChange :: Value -> m (Set.Set TxIn, Maybe TxOut)`

**Comment by michaelpj** [comment]
Regardless, coin selection is going in either the wallet or the signing process, but not the node client, so we don't need to worry about it here.

**Comment by raduom** [comment]
I think that with the new contract API the developers will not be able to call the `createPaymentWithChange` function, so we don't really need to do anything here.

**Comment by raduom** [comment]
I am thinking we can close this one. @j-mueller am I right in assuming that the contract developer will not be able to call `createPaymentWithChange` directly?
