### ISSUE TITLE
Non-standard numeric hierarchy?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1386]
Plutus Tx currently has no numeric typeclasses. We have a couple of options:
- Add `Num`
- Add our own numeric typeclasses.

Why do the second? A few reasons:
- `Num` is kind of a bad typeclass, and we don't want most of it.
- We do have some slightly unusual types around: `Value` is a group and an `Integer`-module.

**Comment by mchakravarty** [comment]
Hmm, good point. The standard numeric setup of Haskell doesn't seem like a good fit for on-chain code, especially as we don't even have the PLC primitives to support most of it.
