### ISSUE TITLE
`Lift` doesn't work right with type aliases

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1409]
In particular, dependencies aren't tracked properly.

The actual code works... by coincidence. We generate things like `typeRep (Proxy @Syn)`, and this actually works because *Haskell* resolves the synonyms later when we're doing type class resolution.

But at the TH time we don't see through them to get the dependencies right.

**Comment by effectfully** [comment]
(How did you even discover this?)

**Comment by michaelpj** [comment]
(Jann hit an issue, I noticed that the dependency order was clearly wrong as the scoping was broken in the output, guessed that it was type synonyms, managed to make a reproducer. So, a lot of guesswork 😅 )
