### ISSUE TITLE
Logging/error handling in contracts

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1428]
There's nothing in the new interface at the moment, so I'm using `error` :crying_cat_face:

**Comment by j-mueller** [comment]
@michaelpj which would you prefer, adding an error constructor to `Resumable`, or adding support in the tests for `Contract .... (Either e a)` so that you could use `ExceptT` ?

**Comment by michaelpj** [comment]
I'm not 100% sure. I think the second option *should* be fine. I think we definitely want to use this outside the tests though: there are all sorts of things that might go wrong during contract execution that we need to report to the user.
