### ISSUE TITLE
Plutus book: fungible token chapter -> why do we need to repeat info about how much tokens we want to forge in RedeemerScript?

### ISSUE THREAD

**Issue by srghma** [input-output-hk/plutus#1429]
at 

https://github.com/input-output-hk/plutus/blob/827b33e33f77c1afcad32087a06745f8e3426467/plutus-book/doc/token/fungible.adoc#L37-L47

why it cant be just 

`type FungibleValidator = () -> () -> PendingTx -> Bool`

we already duplicate info about how much tokens we want to forge in txForge (https://github.com/input-output-hk/plutus/blob/827b33e33f77c1afcad32087a06745f8e3426467/plutus-book/doc/token/fungible.adoc#L172), txOutputs (https://github.com/input-output-hk/plutus/blob/827b33e33f77c1afcad32087a06745f8e3426467/plutus-book/doc/token/fungible.adoc#L170) and now at txInputs (https://github.com/input-output-hk/plutus/blob/827b33e33f77c1afcad32087a06745f8e3426467/plutus-book/doc/token/fungible.adoc#L169

why?

**Comment by michaelpj** [comment]
@brunjlar I think this is for you.
