### ISSUE TITLE
Plutus Book: lifts and unsafe lifts

### ISSUE THREAD

**Issue by Kevmate** [input-output-hk/plutus#1430]
I have been working through the Plutus book and tutorial and I can't get the bit about lifts to work. In the text it says:
    addOneToN :: Integer -> CompiledCode Integer
    addOneToN n = addOne `applyCode` unsafeLiftCode n

But when I paste the following code into the Plutus Playground, it comes up "Cannot interpret unsafe functions". Surely the tutorial should be giving examples that work in the playground?

If I change it to liftCode I get the error:
    • Couldn't match type ‘CompiledCode Integer’ with ‘Integer’
      Expected type: CompiledCode Integer
        Actual type: CompiledCode (CompiledCode Integer)

Is it me? I am fishing in the dark, perhaps, but I feel that the tutorial is not meant for outsiders?

That code:
import Language.PlutusTx
import Language.PlutusTx.Prelude
import qualified Language.PlutusTx.Lift as Lift
import qualified Language.PlutusTx.Builtins as Builtins
import Playground.Contract
double :: CompiledCode (Integer -> Integer)
double = $$(compile [|| \(x:: Integer) -> x `Builtins.addInteger` x ||])
doubleNum :: Integer -> CompiledCode Integer
doubleNum n = double `applyCode` Lift.unsafeLiftCode n

**Comment by michaelpj** [comment]
Hm, this is an unfortunate interaction of the Playground attempting to prevent you from running `unsafePerformIO`. I think it just looks for "unsafe".

Probably the simplest thing to do is rename those functions. We probably want the Playground to be paranoid.

cc @shmish111

**Comment by shmish111** [comment]
Indeed, if you move the functions into a library then you should be able to use them. I couldn't think of a better/easier way to prevent people from just doing anything they want on the servers.
