### ISSUE TITLE
playground: on-chain code -> trace works when validatorScript fails, but doesnt work when validatorScript succeeds

### ISSUE THREAD

**Issue by srghma** [input-output-hk/plutus#1431]
on https://alpha.plutus.iohkdev.io/

doesnt work on success

![2019-09-13-21:44:42-screenshot](https://user-images.githubusercontent.com/7573215/64886889-e567a680-d66f-11e9-95df-315b6d1251fa.png)
![2019-09-13-21:36:14-screenshot](https://user-images.githubusercontent.com/7573215/64886904-eb5d8780-d66f-11e9-97d1-9aff504903bd.png)

but works on error

![2019-09-13-21:35:44-screenshot](https://user-images.githubusercontent.com/7573215/64886927-f44e5900-d66f-11e9-8c63-df7cc07a2a3d.png)
![2019-09-13-21:35:47-screenshot](https://user-images.githubusercontent.com/7573215/64886937-fa443a00-d66f-11e9-8a4b-eb9f3b393ac6.png)

expected - should trace on success too

**Comment by srghma** [comment]
hmm, isn't it same as https://github.com/input-output-hk/plutus/issues/1428

**Comment by michaelpj** [comment]
Not quite, that's about the off-chain code.

**Comment by michaelpj** [comment]
I thought this was a known issue (that you don't get logging on success), but I can't find the issue.
