### ISSUE TITLE
Restrict data scripts (and redeemers?) to contain only data.

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1436]
Currently validators, redeemers, and data scripts can all be arbitrary Plutus Core terms. In the case of data scripts this has caused some difficulty: see https://github.com/input-output-hk/plutus/issues/1141 and https://github.com/input-output-hk/plutus/issues/426 .

It's been suggested that we could restrict data scripts to contain only data specified by some simple fixed type, for example structures built up from base types and nested tuples: see the email thread at https://mail.google.com/mail/u/0/?ogbl#inbox/FMfcgxwDqxQczLcnGvbLXpCsflSVHRJJ and the Plutus call for 10th September 2019 at https://drive.google.com/file/d/14KxQZp6AUnWw3PUdJeTGrsOD1w3r6bId/view?usp=sharing

The main advantage of this is that the contents of the outgoing data scripts from a transaction could be embedded directly in the `PendingTx` structure where they are directly accessible to the validators of inputs, providing a simple and clean solution to  the problem of validating those data scripts. 

Manuel also suggests making _redeemers_ data-only, arguing that this will make transactions more transparent to external agents, such as blockchain explorers.  The question now is whether this will restrict the capabilities of Plutus contracts unduly.

**Comment by kwxm** [comment]
Question: does Marlowe ever need to use higher-order redeeemers or data scripts?

**Comment by nau** [comment]
No, Marlowe does not need any higher-order redeemers, nor data scripts. All we need are simple data structures to store contract's state, actions, and content.
Though, I would prefer to have a mechanism to serialize/deserialize Haskell data types with multiple (named) fields directly, without going through nested tuples.
Otherwise, I support the idea of having data scripts easily analyzable by external tools.

**Comment by mchakravarty** [comment]
Let's turn this around. Unless somebody comes with a good reason why we cannot make data scripts and redeemers into data, we'll do it. (If in doubt, simple is better.)

**Comment by michaelpj** [comment]
I'm going to leave this open until the spec is updated, but a lot of the implementation is done now.

**Comment by kwxm** [comment]
The spec is in reasonable shape now where Data is concerned. I'll merge that shortly once the tests have finished.

**Comment by kwxm** [comment]
I've now merged the specification, so I'll close this.
