### ISSUE TITLE
Implement generic data for data scripts

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1465]
Implementation plan:
1. Write generic `Data` type.
2. Rewrite our examples so they use `Data` everywhere.
    - This should iron out any kinks in the representation, and reveal how awkward it is to work with.
3. Change the ledger representation of data scripts to be serialised `Data`
    - The validator scripts shouldn't change at this stage.
4. Remove `Sealed`, put data scripts into `PendingTx` as `Data`.

I plan to PR 1+2, then 3, then 4.

**Comment by michaelpj** [comment]
Ah, and
5. Make `PendingTx` into `Data`.

**Comment by kwxm** [comment]
Is there any pressing reason to make `PendingTx` into `Data`?  I don't have any objections, I'm just curious; I suppose it'd be nice for consistency though.  If you do this it'd be interesting if you could compare how big/complicated the corresponding Plutus Core is before and after the change.

**Comment by kwxm** [comment]
Apart from that, a big thumbs up for this.

**Comment by michaelpj** [comment]
It makes specifying the system easier, no? As we discussed before, as long as we have something the validating node has to lift as a Haskell type we have an implicit dependency on Haskell.

**Comment by michaelpj** [comment]
I'll make more issues for other things, so I'll close this when the other PR is in.
