### ISSUE TITLE
Handle state passing in state machine library

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1482]
We can pull the current state from the outputs in the UTXO.

My inclination is that the library should assert that there is precisely one such - it's then the responsibility of the user to make sure that happens using a token or somesuch. Then we can e.g. have `getState :: m State` and so on.

**Comment by kwxm** [comment]
This is the thing that I was never able to get to the bottom of when trying to specify the `Sealed` business: how the validator knows that the data script that it's looking at is the one that contains the state,  and not another data script that just happens to have the same type.  The idea of using a token to identify it makes sense.  I thought that we could maybe do this by adding a flag to outputs saying "this is the output whose data script contains the state", but then someone malicious could presumably cause problems for the next stage by supplying another output with that flag set.  Using an NFT would avoid that, and it would generalise (I think) if we ever want to make things really unpleasant for ourselves by allowing state machines to pass state to multiple future transactions (and merge incoming state from multiple previous ones).

**Comment by michaelpj** [comment]
Yup, this is a general issue. Pretty much anything you put in an output can be replicated by an attacker (you could maybe sign the data, though). 

But the problem we're trying to solve is identifying a unique thing on the chain, and I think a token is a natural solution for that. Plus yeah, I think it generalizes (you have a token class for "threads" and everybody gets one, or you have one non-fungible token for each "thread" if you need to know which one is which).
