### ISSUE TITLE
Remove Sealed from docs

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1487]
Particularly: the book and the EUTXO spec.

**Comment by kwxm** [comment]
I'll deal with the EUTXO spec.  It'll be a pleasure to get rid of what it currently has about `Sealed`.

**Comment by michaelpj** [comment]
There will be some more changes if we make `PendingTx` into `Data`, and if we handle `Data` with builtin types, but we can do those later.

**Comment by kwxm** [comment]
Can we close this now?

**Comment by michaelpj** [comment]
It's still in the book...

**Comment by michaelpj** [comment]
The book is going to need a rewrite, so this is done enough.
