### ISSUE TITLE
Match has not been compiled for: GHC.Integer.Type.Integer

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1495]
I wanted to port the `Ratio` stuff from the swap contract to the standard library and got the error

```
Exception: Error: Unexpected error during compilation, please report this to the Plutus team: Match has not been compiled for: GHC.Integer.Type.Integer
```

To reproduce, checkout 249dce73b65cadbdded1b10e0aab5cba30c396a6 on the `j-mueller/rational` branch and `cabal new-test plutus-tx-tests`

**Comment by j-mueller** [comment]
Here's a diff with all the changes:

https://github.com/input-output-hk/plutus/compare/j-mueller/rational

**Comment by michaelpj** [comment]
I think I hit this too - it's strictness analysis messing with us. Try copying the `OPTIONS_GHC` from the swap contract. But leave the bug open.

To summarise: based on strictness GHC will sometimes insert pattern matches on `Integer`, which don't work. I'm not sure there's much we can do about that, but I can probably detect it and give a better error message.

**Comment by j-mueller** [comment]
Copying `OPTIONS_GHC` didn't do anything but your mention of strictness reminded me that GHC's `Ratio` is defined as `Ratio a = !a :% !a` whereas ours doesn't have the strict fields. So I changed it back to our own definition and it worked (also had to replace the pattern matches on `Integer` literals with guards to ensure it uses our builting `==` instead of `Integer.eq`). I'll make a proper PR of this shortly.

I also hit another `Unexpected error during compilation`:  `Scrutinee's type was not a type constructor application` in 58ef3db4abab91abf335ff64cf2d97d6fc7b8927 / https://github.com/input-output-hk/plutus/compare/j-mueller/scrutinees-type (in which I replaced the pattern matches, but still used GHC's `Ratio`) - do you want a new issue for that?

**Comment by michaelpj** [comment]
Yikes, not sure what that is. Another issue would be great.

**Comment by michaelpj** [comment]
Never mind, I've got fixes for both.
