### ISSUE TITLE
Changing wording in the Marlowe in Blockly

### ISSUE THREAD

**Issue by simonjohnthompson** [input-output-hk/plutus#1506]
Based on feedback from users, change wording to avoid misconceptions and to make the representation more compact.

1. Replace `Refund` by `Close`.
2. Add a newline in the `When` construct before `continue as`.
3. In `Value` shorten thus:
  `Available Money from account number X with owner Y` to `Available from account X owner Y`
  `Constant value X` to `Constant X`
  `Negate value X` to `Negate X`
   `Use value with id X` to `Use id X`
  `use value of choice …` to `value chosen for X by Y, default Z`
4. In `Observation` remove all the initial occurrences of `value`.
5. TO DISCUSS: change all the `is equal to` etc. to symbols `=` etc.

**Comment by michaelpj** [comment]
Is this just in Blockly? I think renaming `Refund` to `Close` in Marlowe proper would be good.

**Comment by simonjohnthompson** [comment]
> Is this just in Blockly? I think renaming `Refund` to `Close` in Marlowe proper would be good.

Michael, thanks. Yes that first change is meant to be in the whole of Marlowe. I should have separated these into two issues, as the rest are about the Blockly rendering.
