### ISSUE TITLE
Put more information into PendingTx

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1513]
In particular data and redeemer for all spent inputs.

**Comment by michaelpj** [comment]
Manuel says this might help us do something clever in Hydra.

**Comment by michaelpj** [comment]
This made me look at `PendingTx`, and I'm a little dissatisfied and not sure how to resolve it. Here are a list of gripes:
- We get a special member for the current input, but we can't cross-reference it to the main list of inputs, which might confuse us.
    - If we just got an index into the list, things could go wrong from it being out of range, or from the input we get not being a script input, so more error cases to handle.
- The parameterization of `PendingTxIn` is clunky, especially once we add a `DataScript` to that tuple. We should at least be using a datatype of some kind.
- It's unclear *how much* information about the input we should give. If we're including the `DataScript` we're including some information about the *output* too, so it's more of a "input-output match" than just an input. Perhaps we should use a type that makes that more explicit?
    - There is `Index.InOutMatch`, perhaps a `PendingTx` version of that would work.
- The "input witnesses" are sort of inlined instead of being on the side. Or at least that's what we claim ... there is no signature for a pub key input even though we say there should be.

**Comment by j-mueller** [comment]
> The "input witnesses" are sort of inlined instead of being on the side. Or at least that's what we claim ... there is no signature for a pub key input even though we say there should be.

Doesn't the core node validate all signatures before running the script? So I'm not sure what we would do with the signatures in the script, other than call `validateSignature` again.

**Comment by michaelpj** [comment]
Well, we want to at least know which keys signed the message. And the witnesses are in `PendingTx`, it's just that we talk about it slightly inconsistently like they're supposed to be on the input.

**Comment by michaelpj** [comment]
We should also include the values of spend outputs. Basically, we should include all information about the input/output match. 

We would need this to e.g. do "merging" contracts that want to check their value is combined properly.

**Comment by michaelpj** [comment]
Also, changing `PendingTx a` -> `(PendingTx, a)` will probably make it easier to define the type externally.

**Comment by michaelpj** [comment]
Okay, name bikeshedding: the overall type should be a named datatype probably, not just a pair. But what should we call these things? 

Some ideas:
- For the outer type:
    - `TxInfo`
    - `ValidationData` (note that this is what the Shelley spec is currently using)
    - `PendingTx` (although this feels wrong somehow, since it's the tx plus something)
    - `ScriptContext`
- For the inner type:
    - `TxInfo`
    - `PendingTx`

I think my preference is probably `data ValidationData a = ValidationData PendingTx a`, although maybe we're overusing the word "data".
