### ISSUE TITLE
Be more liberal with out representation of transactions

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1515]
We have some properties which we need to hold:
1. `Value`s on transaction outputs are strictly positive.
2. `Value` in fees is `Ada` only.
3. `Value` in fees is non-negative.

At the moment, we partially establish this with the types:
- In the spec, we use a non-negative quantity type for outputs and fees. We don't do this in the implementation.
- In the spec and the implementation, we use a different type for fees that is only `Ada`.

However, I think there's something to be said for liberalising this and instead enforcing these conditions in the ledger rules. Specifically:
- Outputs should just have arbitrary `Value`s on them.
- Fees should just be an arbitrary `Value`.

This is what they do in the main ledger spec, and here are a couple of related reasons that I want this.

1. System compositionality

A system with negative output values or arbitrary fee values makes *sense*, it's just not quite the system that we want. So it's nice to be able to specify the bit that's just the multi-currency part, and then have separate rules that enforce the particular conditions that we want (fees in Ada, positive outputs).

Making them orthogonal also makes them easier to reason about. For example, the rule for balancing is then exactly the same as the rule in the base ledger, which makes it easy to justify.

2. Future proofing

We already have people asking if fees will be able to be paid in currencies other than Ada. Maybe one day we will - and that change would simply amount to dropping the additional rule stating that fees must be Ada. The rest of the system would remain the same, and we wouldn't have to change the representation of anything.

Similarly for negative output values (I have an idea for where those could be used, even!).

**Comment by michaelpj** [comment]
Jann asked me what my idea for negative outputs was, so just as an example:

If we have batch transactions (which I think we should), we can allow "questionable" states during the validation of the batch, so long as it's all normal by the end. In particular, we could allow negative outputs during the batch, but not at the end. This means you can do the "borrow money from yourself" trick inside a batch, which is quite neat.

If we did what I propose in this issue, that would just require a small tweak to the ledger rules.

**Comment by j-mueller** [comment]
>we can allow "questionable" states during the validation of the batch, so long as it's all normal by the end.

Almost like a miniature sidechain!

**Comment by kwxm** [comment]
I find the idea of negative values in outputs very disturbing: it seems like asking for trouble.  If someone manages to create a negative output where they're not supposed to then all kinds of things could go wrong.  You presumably don't want someone contributing -£100 to your crowdfunding campaign, for example.  Yes, we can put checks it to make sure that things don't go wrong, but surely it's much safer just to rule out negative values in the first place?

With things like this, I think we really need to get lots of opinions before proceeding.

**Comment by michaelpj** [comment]
> Yes, we can put checks it to make sure that things don't go wrong, but surely it's much safer just to rule out negative values in the first place?

I mean, you always have to do a check, this just changes where you do it. Note that both the current implementation and the Shelley ledger spec do exactly that: allow any values and check in the validity rules.

> If someone manages to create a negative output where they're not supposed to then all kinds of things could go wrong.

Yes, absolutely. So I think at the very least they should never be allowed in the main UTXO. Maybe they should never be allowed at all! But I think that's a discussion we should have later, and I don't think we gain anything from making the *representation* of outputs disallow it.

**Comment by michaelpj** [comment]
Also, I'm more keen relaxing the type of fees if anything.

**Comment by dcoutts** [comment]
In the current Shelley specs we enforce that fees are positive via a rule rather than implicitly with the type (in fact it's that the fee is at least the min fee). Of course right now the fee is implicitly only ADA.

I think it'd make a lot of sense to keep to this style and say that a fee is a value (multi-currency map) and enforce in the utxo rules that the fee is only ADA, and is over the minimum fee.

**Comment by mchakravarty** [comment]
@dcoutts 

> I think it'd make a lot of sense to keep to this style and say that a fee is a value (multi-currency map) and enforce in the utxo rules that the fee is only ADA, and is over the minimum fee.

What do you see as the advantage?

**Comment by mchakravarty** [comment]
@michaelpj wrote,

> If we have batch transactions (which I think we should), we can allow "questionable" states during the validation of the batch, so long as it's all normal by the end. In particular, we could allow negative outputs during the batch, but not at the end.

Don't forget that after a block has been created, this batching is no longer part of the representation — it is just a bunch of transactions in a block. On block validation, the validating now will now be faced with this questionable state in the middle of a non-batched, standard sequence of transactions.

**Comment by michaelpj** [comment]
> Don't forget that after a block has been created, this batching is no longer part of the representation — it is just a bunch of transactions in a block. 

That depends. In my proposal it is part of the representation. Anyway, I'm just spitballing with that bit of the proposal ;)
