### ISSUE TITLE
Consider abstracting away base types in the EUTXO spec

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1517]
At the moment we define quantities to be integers, similarly slots. We could however just say that quantites can be any group, and slots can be any totally ordered type. This would:
- Make it clear what properties we actually require.
- Allow potentially varying the base types, e.g. a double-ended ledger that used integers for slots and could add transactions at the beginning too.

**Comment by kwxm** [comment]
I thought about making quantities group elements before, and I'm highly dubious.

1.  Suppose you've got a non-abelian group.  How do you make transactions balance?  There's a lot of adding things together, and if you're non-abelian the order is going to be important for both the inputs and the outputs.  Let's say your group is the free group on {x,y,z} and you've got inputs worth x+y+z, -z-y+x, -2x (I _really_ want to write those multiplicatively).  There's six different ways of adding them together.  If you add them together in the order given you get 0, but if you add them in the order 2,1,3 you get -z-y+2x+y+z-2x (decidedly nonzero), and so on.  Which order do you choose?  I guess we'd have to specify some ordering for the inputs (currently unordered), and similarly for the outputs. Does the owner of an input get any say about what position it's consumed in?  That could be important.  We also have to worry about forging, and maybe fees.  What if you have _two_ nonabelian currencies in the same transaction?  Maybe you'll want to add the first one up in one order but the second in another: that's not going to work.

2.  Given 1, let's restrict to abelian groups, for example ℤ_12.  We can have a transaction with no inputs at all and outputs worth 1,5,9,6, and 3 and it'll balance, so you can produce unlimited numbers of tokens out of thin air.  I suppose that could lead to some very interesting games/puzzles, but it makes me nervous. 

3.  Suppose we disallow 1 and 2.  That'll restrict us to torsion-free abelian groups.  We probably also want them to be finitely generated so we have some chance of representing them in a computer program.  That means that we're looking at finitely-generated torsion-free abelian groups, and those are precisely groups isomorphic to some product ℤ x ℤ x ...x ℤ.  I don't know if that brings us much benefit over our current choice of ℤ.

**Comment by michaelpj** [comment]
> Suppose you've got a non-abelian group. How do you make transactions balance?

Agreed, it should be an abelian group.

> Given 1, let's restrict to abelian groups, for example ℤ_12. We can have a transaction with no inputs at all and outputs worth 1,5,9,6, and 3 and it'll balance, so you can produce unlimited numbers of tokens out of thin air.

I really don't see any problem with this - this is how a ledger where your values come from Z_12 *should* work. This seems to me like complaining that if you define topology abstractly then you can have topologies on propositions, whereas clearly only spaces should have topologies!

> We probably also want them to be finitely generated so we have some chance of representing them in a computer program. 

Do we? I'm unsure how much we should consider ourselves to be giving a mathematical description of the semantics and how much we should be giving something that can definitely be realised. FSFs is going in the latter direction, but here I think it's not too big a deal and you can just not instantiate it to things you can't compute with!

Even if we accept everything you've said... thinking like a computer scientist, we can take products of finitely presented groups, and generally build lots of interesting structures out of them. Sure, maybe everything is isomorphic to Z, but I think it's *much* clearer to say "pick your own (sensible) group" than "all sensible groups are isomorphic to Z, so we'll use that".

Plus, using an arbitrary group restricts us to using the group operations, which makes it clear what's going on Z has lots of *other* structure that we *could* use and then nobody would notice that our construction wasn't valid for other groups. Just stick a sneaky multiplication in there somewhere.

**Comment by kwxm** [comment]
OK, I think I can cope with that.  Non-abelian was just too frightening!  

However, now we've got abelian groups, that's the same thing as ℤ-modules: if you've got n units of a currency then it always makes sense to talk about 20n units as well.  I think you used that elsewhere, so maybe we should do the same thing here.

Re your last point, sometimes we _do_ want to allow more structure, like comparisons in ℤ (have I reached my crowdfunding target yet?).  I guess that saying you've got an abelian group doesn't rule out using other properties if they're available.

**Comment by michaelpj** [comment]
Meditating on this: quantities also need to be ordered! We keep talking about things being "positive", which requires us to say they're greater than zero.

But, crucially we only want to require a partial order, because the maps are only partially ordered.

I actually think this is a good example of something that's obscured by us using Z - the order here being some additional structure that we happen to use!

**Comment by kwxm** [comment]
> Meditating on this: quantities also need to be ordered!

Good luck with that.  

 ℤ_5: 0 < 1 => 0+0+0+0 < 1+1+1+1, so 0<4.  Now 0+1 < 4+1, so 1 <  0, and so on.

I think this is just a case where there's no abstraction that coves everything you might want.  Maybe your tokens have colours and you want a way of mixing the colours or something.

**Comment by michaelpj** [comment]
Sure, so this disallows cyclic groups (a shame, I kind of liked the idea of crazy ledgers over them).

I do think it's helpful to just have a list of the properties you actually need. If we need colours, then we can add that. But we currently don't, so it's helpful to be able to look and see what we do actually need.

**Comment by michaelpj** [comment]
https://en.wikipedia.org/wiki/Partially_ordered_group
