### ISSUE TITLE
Signed pieces of `Data`

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1519]
I have a piece of `Data`, and a signature of that data from a third party. Now I want to verify that signature in my validator script using `verifySignature`. I can't do that at the moment because I don't know the `ByteString` of the message that was signed :(

Perhaps we should change the `verifySignature` primitive to take a `Data` as the message.

**Comment by michaelpj** [comment]
We had this problem before. Generally, we want to work with deserialized data as much as possible, but signatures only work on serialized data.

I don't have a good solution for this. All schemes for preserving this information to later on can be tampered with.

**Comment by michaelpj** [comment]
And it would be nice to avoid re-serializing the `Data`!

**Comment by j-mueller** [comment]
> We had this problem before 

I know, but I couldn't find an issue for it

What about changing `verifySignature` to take `Data`? I think it makes sense if you do #1518. Right now, `verifySignature` is not very useful.

**Comment by michaelpj** [comment]
That's equivalent to adding `serialiseData :: Data -> bytestring` and leaving `verifySignature` as is (provided that we're okay with exposing the serialization of `Data`, which I'm unsure about). 

The problem is that it's potentially computationally wasteful. But maybe that's okay.

**Comment by michaelpj** [comment]
Jann came up with a nice way of doing this in https://github.com/input-output-hk/plutus/pull/1834, since we typically have the hash->data mapping for various things from the PendingTx.
