### ISSUE TITLE
Consider storing programs on-chain with types erased

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1524]
We've always intended that it be possible to erase PLC to the untyped lambda calculus. However, in the past having the types on chain has been a security asset: because we're applying programs written by multiple people together, ensuring that they typecheck rules out any chance that providing e.g. a malicious ill-typed redeemer could do something unexpected.

However, now our redeemers and data aren't scripts, they're just `Data`. They get encoded into PLC, but only by the validating node, which we trust (or which will be checked by others).

So the only code left is the validator. Now, someone could submit an output locked by an ill-typed validator, but the only person they'd be screwing over is themselves (likely).

So I think it would now be safe for us to store our programs erased on-chain, which would save us a *lot* of space. I need to run some numbers, but I suspect a lot of a PLC program is types.

**Comment by michaelpj** [comment]
Some unscientific numbers ahead.

Comparing the AST sizes of some of our current use-cases vs "erased AST sizes" where I ignored:
- types
- type abstractions and applications
- wrap and unwrap

Gives:

| Program | AST size | Erased AST size | Erased size proportion |
| --- | --- | --- | --- |
| Crowdfunding | 32728 | 7078 | 21% |
| Vesting | 29538 | 6860 | 23% |
| Futures | 26238 | 6208 | 23% |
| Game | 13512 | 3232 | 24% |
| MultisigStateMachine | 47973 | 11963 | 25% |
| Escrow | 37475 | 7964 | 21 % |

That's pretty big! So we can save 75-80% by erasure.

**Comment by michaelpj** [comment]
That said, I guess (haven't tested) that a lot of this is duplication, so the savings from compression probably compete with this.

**Comment by kwxm** [comment]
Does CBOR preserve sharing? If you have a heap structure with multiple nodes all actually being pointers to the same thing, is the same true if you serialise it and then deserialise it again, or does the shared node get replicated?  (I'm too lazy to look it up.)

**Comment by kwxm** [comment]
Also, a reminder that the CEK machine can throw various `MachineException` errors if it encounters  unexpected things during execution (like `unwrap` applied to something that isn't wrapped).  These will never occur if the program's well-typed (one hopes), so we never have to worry about them at the moment.  Without typechecking (and depending on the mechanics of invocation of the interpreter) someone could potentially torpedo a transaction by supplying a malformed validator that causes an exception. Presumably it wouldn't be too hard to fix this if it's a problem (return `error` instead, for example), but we should remember that there's a potential danger here.

**Comment by michaelpj** [comment]
CBOR does not have a concept of pointers or anything, so no, it doesn't preserve sharing.

Yes, of course we should catch any evaluation exceptions.

**Comment by kwxm** [comment]
See also #1592

**Comment by kwxm** [comment]
Following the Plutus call on the 18th of February 2020 It looks as if we're going ahead with this. We should make a plan.

**Comment by michaelpj** [comment]
-> https://jira.iohk.io/browse/SCP-60
