### ISSUE TITLE
Binary cache configuration for nixOS is misleading

### ISSUE THREAD

**Issue by praduca** [input-output-hk/plutus#1527]
I'm trying to install leksah on nixOS, and folowing the instructions i get directed to folow the binarbynary cache setup from plutus. The problem is that it says to edit `\etc\nix\nix.conf`, but under nixOS this file is automatically generated from `\etc\nixos\configuration.nix`. 

> If you are a not a trusted user (or you do not know whether you are a trusted user), then edit /etc/nix/nix.conf. If you are not a trusted user, you may edit ~/.config/nix/nix.conf instead.

**Comment by michaelpj** [comment]
Hah, I think I assumed NixOS users would know what they are doing! I'll add a section for them.
