### ISSUE TITLE
PLC specification doesn't need to mention validation.

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1571]
The PLC specification still talks about applying scripts to scripts, so we should modify that now that we just have `Data` instead of data scripts and redeemer scripts .  On the other hand, maybe it doesn't need to say anything about validation at all.

**Comment by michaelpj** [comment]
The PLC spec shouldn't really talk about validation at all, I agree.

**Comment by kwxm** [comment]
Yeah, let's get rid of the stuff about validation now.  We can refer to the book/EUTXO spec for that.  If we still want an example we could use something else.

**Comment by michaelpj** [comment]
This got done.
