### ISSUE TITLE
Add "OwnPubKey" effect

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1599]
Whenever the wallet's own public key is needed we just get it via an endpoint. This is confusing and also unnecessary, because it's a request that can be handled by the wallet directly without prompting the user. So we should add an effect `OwnPubKey` to take care of this.

**Comment by michaelpj** [comment]
I don't quite see why it shouldn't be an endpoint? There are endpoints that don't prompt the user, e.g. the blockchain event ones. Besides - that leaves it up to the wallet whether it wants to ask the user (which it might, if it's paranoid).

And even thought the wallet has it, the smart contract bundle doesn't, so it does need to ask for it!

**Comment by j-mueller** [comment]
> There are endpoints that don't prompt the user, e.g. the blockchain event ones

I'd been using the term endpoint just for endpoints that prompt the user, and "effects" for the ones that don't. But I'm happy to call everything an endpoint, and I completely agree with what you wrote.

**Comment by michaelpj** [comment]
Ah, that wasn't obvious since they're all endpoints in the code :) in that case we're in agreement!

I think to some degree we should treat them as homogeneous from the contract's point of view - it ultimately doesn't know how the wallet is going to handle them (e.g. will it prompt the user).

**Comment by j-mueller** [comment]
#1604
