### ISSUE TITLE
Typechecking Plutus IR

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1608]
It would be nice to be able to typecheck Plutus IR. The language was designed so that you can compile it without typechecking, but from a theoretical point of view we *should* be able to do so, and we should also be able to give better error messages.

Ideally we'd be able to reuse much of the PLC typechecker, since the languages are very similar.

**Comment by effectfully** [comment]
> Ideally we'd be able to reuse much of the PLC typechecker, since the languages are very similar.

How would we do that? Tagless final? Just define type checking of each constructor as a separate function (receiving a continuation on how to proceed for subterms) and reuse the functions?

Or maybe just merge the ASTs and index the merged AST by this type:

```haskell
data Stage = Core | IR
```

? Like this:

```haskell
data Term stage where
    Var :: Term stage
    Lam :: Name -> Term stage -> Term stage
    Let :: Recursivity -> [Binding] -> Term IR -> Term IR
    ...
```

And just reuse everything that we already have in Core for IR at a very low cost. And if something works only on Core, we can always define that to work over `Term Core`. That would save us plenty of typing and maintenance burden.

**Comment by michaelpj** [comment]
> How would we do that? Tagless final? Just define type checking of each constructor as a separate function (receiving a continuation on how to proceed for subterms) and reuse the functions?

Either of those could work. 

In the past I've wondered whether we could do something fancy with recursion schemes and define the IR as the fixpoint of an extension of the Core term algebra. But that founders because the IR terms are defined with two mutually recursive types, which is a pain to do with recursion schemes.

> Or maybe just merge the ASTs and index the unified AST by this type

I'm not wild about infecting the PLC AST with IR stuff. Plus we add a type variable to everything, and frankly `Term` already has plenty.

**Comment by effectfully** [comment]
> Either of those could work.

I'd prefer the latter.

> But that founders because the IR terms are defined with two mutually recursive types, which is a pain to do with recursion schemes.

Have you seen [syntax-tree](http://hackage.haskell.org/package/syntax-tree-0.1.0.1/candidate)? Not that I'm a huge fan of such approaches, but might be worth trying it out.

> I'm not wild about infecting the PLC AST with IR stuff. Plus we add a type variable to everything, and frankly `Term` already has plenty.

Yeah. That would so much more manageable with proper modules (like those in Agda).

**Comment by michaelpj** [comment]
> Have you seen syntax-tree? Not that I'm a huge fan of such approaches, but might be worth trying it out.

Looks interesting, but somewhat ferocious. Would need some learning, I think. Also, we want to avoid making it a more painful to use the syntax tree elsewhere.

**Comment by kwxm** [comment]
Good idea!  More typed IRs => more compiler robustness.  

Bear in mind that we're probably going to need yet another type of AST for untyped/Merkelised PLC.  Trying to squeeze everything into a single type might get a bit messy.  Having separate ASTs and typecheckers would add to the maintenance burden, but you might be able to argue (somewhat feebly) that it would improve robustness if the different stages were handled by independent checkers.
