### ISSUE TITLE
Unify `tyname` and `name`

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#1612]
Originally we split names into type-level names and term-level names, because the annotation machinery required them to be distinct. But then I removed the annotation machinery and correct me if I wrong, but I think none of the algorithms requires to distinguish between type-level and term-level names. However the renamer does benefit from this distinction: most of the stuff is implemented there in a type-driven manner and I'd hate to lose this. So, how about merging `tyname` and `name` into a single entity like this:

```haskell
data Level = TypeLevel | TermLevel

data Name (level :: Level) ann = Name
    { nameAnn :: ann
    , nameText :: Text
    , nameUniq :: Unique
    }
```

This gives us a convenient way of handling things. We no longer need to define duplicate functions like

```haskell
mapNameString :: (T.Text -> T.Text) -> Name ann -> Name ann
mapNameString f name = name { nameString = f $ nameString name }

mapTyNameString :: (T.Text -> T.Text) -> TyName ann -> TyName ann
mapTyNameString f (TyName name) = TyName $ mapNameString f name
```

while we still can distinguish between type-level and term-level names and even instantiate them differently like in

```haskell
data SomeOtherName (level :: Level) where
    SomeTypeName :: Foo -> SomeOtherName TypeLevel
    SomeTermName :: Bar -> SomeOtherName TermLevel
```

That would save us from typing `Term uni tyname name ann` and `Term uni TyName Name ann`, which is quite repetitive. Instead we will be able to write `Term uni name ann` and `Term uni Name ann`.

**Comment by michaelpj** [comment]
Seems fine.
