### ISSUE TITLE
Compare size of PLC and PIR ASTs to estimate savings from explicit datatypes/recursion

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1615]
We could add datatypes/contstructors/recursion into PLC. This would save space, since we wouldn't have all the encoding artifacts.

We could get an estimate of the improvement by comparing the PIR sizes, since that has those features.

**Comment by kwxm** [comment]
Doing this might also facilitate analysis of PLC code.  Usually the first thing you do if you want to do some static analysis is to construct a control flow graph, but that's not so easy when you don't have explicit branches or loops. 

Presumably there was some rationale for _not_ doing this when PLC was first designed, so we might end up rehashing old arguments that were never documented.
