### ISSUE TITLE
Replace `hedgehog` with `QuickCheck`

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#1620]
It is notoriously hard to write shrinkers in `hedgehog` and the built-in shrinker is not appropriate in our case as we want fancy strategies like

- turn `((\x : a) -> y) z` into `[z/x] y`
- and the same for type instantiation
- turn any non-constant term of a builtin type into a constant
- turn a constant application into its value
- reduce `unwrap-wrap`
- maybe replace a subterm with an `error` call

I.e. we basically need to inline the CK machine in the shrinker + add some additional fake reductions that simplify the term (and we have to somehow make sure shrinking never loops). We use type-preserving shrinking in the compiler in the other project and it proved to be of a great value (see [this issue](https://github.com/effectfully/tiny-lang/issues/8)).

However since currently the untyped generator is not likely to generate anything well-typed, this is not too urgent as dropping parts of a term should work well for terms that are not even well-scoped, because no invariant can be broken for such a term (as they all are already broken).

But for tests of the type checker (as well as the kind checker) we will surely need a more careful shrinker.

**Comment by michaelpj** [comment]
Hm, if the shrinker is essentially just "run a step of the CK machine", I wouldn't have thought that would be too hard to add (you certainly *can* have custom shrinkers in Hedgehog!).
