### ISSUE TITLE
Review pretty-printing of everything

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1633]
Especially:
- `Value` is often printed badly.
- Hashes are sometimes printed as hex (I think only if we use `LedgerBytes`), and sometimes as the `ByteString` `show`, which is quite bad.

Ideally everything should have a *sane* `Pretty* instance and we shouldn't use `Show`.

**Comment by j-mueller** [comment]
FYI I've just done a bit of work of this but it is buried in another branch (will be up soon)
