### ISSUE TITLE
Fixpoint combinator isn't shared

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1657]
I have a feeling that every time we compile a letrec we have a new copy of the fixpoint operator. We should check, and if so we should share it.

This may require support for "floating" definitions throughout the PIR compiler, which is something I've been meaning to add anyway.

**Comment by effectfully** [comment]
> I have a feeling that every time we compile a letrec we have a new copy of the fixpoint operator. 

I believe this is indeed the case.

I had a plan to define stdlib terms in the state monad: each time we want to use one definition inside another, we either create that definition and add it to the cache or use the already cached version. In the end we run the state monad and turn each cached definition into an (inlined) let-binding. This way we don't need to float definitions afterwards and can produce optimized terms directly (producing unoptimized terms first and then optimizing them is just pointlessly inefficient).

But as with every other plan I had regarding Plutus...

**Comment by michaelpj** [comment]
I still think we should do this in the Plutus IR compiler.

> I had a plan to define stdlib terms in the state monad: each time we want to use one definition inside another, we either create that definition and add it to the cache or use the already cached version. In the end we run the state monad and turn each cached definition into an (inlined) let-binding.

That's what the `DefT` monad in Plutus IR does (except not inlined). We literally wrote a language to make adding definitions easy, let's use it ;)

**Comment by michaelpj** [comment]
I have a fairly straightforward branch that fixes this, I think. Will put something up later.

**Comment by effectfully** [comment]
> That's what the DefT monad in Plutus IR does (except not inlined). We literally wrote a language to make adding definitions easy, let's use it ;)

I create PLC terms on the fly in the constant application machinery. The full definitions of `true`, `false`, `unitval`, etc get generated every time there is an application returning a value of those types. We should track what's in the scope regardless of Plutus IR (although in the case of evaluation it's of course too late to bind new variables, so the scope information should come from Plutus IR and the evaluator should use and preserve it).

The stdlib is also currently used a lot during unlifting, but I'm not sure how stable that is. Anyway, I do really want to be able to create optimized Plutus Core terms as creating Plutus Core terms is something that I do a lot. If we only needed to optimize what comes from Plutus Tx, I'd be absolutely fine with doing everything on the Plutus IR side, but the Plutus Core codebase is also a source of Plutus Core terms, so we have to account for this.

Note that we can be generic over `TermLike` as we have `let`s there.

**Comment by michaelpj** [comment]
I don't think my PR precludes that, anyway, it's a pretty small change to the PLC side.

`Definitions` can't quite be generic over `TermLike` since it also handles recursive things and datatypes, but we could have a neutered version, I guess.
