### ISSUE TITLE
Could not load module 'Wallet' when compiling code using the playground

### ISSUE THREAD

**Issue by dnikolovv** [input-output-hk/plutus#1665]
Compiling code that uses the `Wallet` module using the Playground fails with `Could not load module 'Wallet'.`

![image](https://user-images.githubusercontent.com/18270328/69313591-abe88400-0c3a-11ea-8829-21a450ce2583.png)

Steps to reproduce:

1. Run the latest version of the Playground
2. Attempt to compile some code that uses the `Wallet` module (e.g. [MultiSigStateMachine]( https://github.com/input-output-hk/plutus/blob/master/plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/MultiSigStateMachine.hs))

**Comment by michaelpj** [comment]
@krisajenkins @j-mueller Is this because of the changes to use the new API?

**Comment by j-mueller** [comment]
Yeah that's quite likely

**Comment by j-mueller** [comment]
`MultiSigStateMachine` is a bit out of date anyway (it still requires you to pass the state in manually, instead of reading it from the utxo set). I'm going to update it now. See also https://github.com/input-output-hk/plutus/issues/1200

**Comment by michaelpj** [comment]
Okay, so they should either:
- be using the new API for their examples
- use a commit from before the playground changes.
Is that right?

**Comment by j-mueller** [comment]
>  Is that right?

Yes that's correcz

**Comment by dnikolovv** [comment]
Using commit 6acecafc0c4dd51442850929632c77c74022b562 results in another error:

![image](https://user-images.githubusercontent.com/18270328/69561167-99ad7380-0fb5-11ea-8ff4-a29977daf5e0.png)

This is shown regardless of what you're trying to compile.

**Comment by j-mueller** [comment]
I haven't seen that error before, I'm not sure why it's looking for a `main` method. Can you create a gist with the contract you were trying to run?

Also, there's now a PR with an updated version of the multi sig state machine: #1678

**Comment by dnikolovv** [comment]
@j-mueller The main method error appears on every contract using the playground from commit 6acecafc0c4dd51442850929632c77c74022b562. The picture is taken using one of the example ones (I think Game).

Since this is a past commit maybe the `main` method error isn't that important.

I'll be trying the updated `MultiSigStateMachine` on the most recent playground version. Thanks!

**Comment by j-mueller** [comment]
Ok, if it doesn't happen on more current versions then I'd write it off as a fluke :)

**Comment by dnikolovv** [comment]
@j-mueller The error still persists when trying to compile the updated `MultiSigStateMachine` script.

![image](https://user-images.githubusercontent.com/18270328/69899032-81e53f00-1369-11ea-86e1-c3a392de9292.png)

This is using the Playground from commit This is using the Playground from commit b70e9eae5a463daf2ac4bdfc5ed6f1a3fc18df08.

**Comment by j-mueller** [comment]
Apparently it can't find the `plutus-wallet-api` package. I found the place where package is added to the options that are passed to GHCI: https://github.com/input-output-hk/plutus/blob/master/plutus-playground-server/src/Playground/Interpreter.hs#L208 but unfortunately the comment above that line sounds as if the error you are seeing is a known bug.

One workaround is to re-export the state machine related modules under `Playground.Contract` (or better `Playground.Contract.StateMachine`)

**Comment by j-mueller** [comment]
Although it does work for some imports from `plutus-wallet-api`, namely the `Ledger.*` modules

**Comment by j-mueller** [comment]
If anyone wants to reproduce this, add `import Language.PlutusTx.StateMachine` to one of the samples

**Comment by j-mueller** [comment]
`plutus-wallet-api.cabal` has an internal package named `plutus-ledger`. I can import any of the modules exposed by `plutus-ledger` (for example, `import Data.Aeson.Extras` works) but I can't seem to be able to import any of the modules defined in the `plutus-wallet-api` library itself (for example, `import Wallet.Graph` doesn't work)

**Comment by dnikolovv** [comment]
@j-mueller Sounds like a fun bug. Is there anything I can do to help?

**Comment by michaelpj** [comment]
This seems like a GHC bug that we fixed a while ago. We *should* be using a patched GHC with the fix, but I'm now not sure what's going on.

**Comment by j-mueller** [comment]
@dnikolovv The `Language.Plutus.Contract.StateMachine` module has all the exports that are needed for the multi sig state machine contract in its current form and importing it seems to work OK.

Here is a version of it that compiles on https://alpha.plutus.iohkdev.io/: https://gist.github.com/j-mueller/db9bb00b6b45fe7e475e75473c1e778b

**Comment by dnikolovv** [comment]
Great! Thank you guys.
