### ISSUE TITLE
Question: How to implement the voting smart contract in cardano Plutus language?

### ISSUE THREAD

**Issue by srghma** [input-output-hk/plutus#1687]
Sorry for posting this here
This is copy of https://stackoverflow.com/questions/59006158/how-to-implement-the-voting-smart-contract-in-cardano-plutus-language

______

Contact is created with locked in reward, voters vote for addresses, after the deadline winners that can collect the reward.

The voting is inherently stateful. Is it possible to implement it in cardano?

What is the data script type?
What is the redeemer script type?

______

For example this is a implementation for tezos in liquidity language found here http://www.liquidity-lang.org/

```ocaml
(* Smart contract for voting. Winners of vote split the contract
   balance at the end of the voting period. *)

(** Type of storage for this contract *)
type storage = {
  voters : (address, unit) big_map; (** Used to register voters *)
  votes : (string, nat) map; (** Keep track of vote counts *)
  addresses : (string, key_hash) map; (** Addresses for payout *)
  deadline : timestamp; (** Deadline after which vote closes *)
}

(** Initial storage *)
let%init storage addresses = {
  (* Initialize vote counts to zero *)
  votes = Map.fold (fun ((name, _kh), votes) ->
      Map.add name 0p votes
    ) addresses Map;
  addresses;
  voters = BigMap ; (* No voters *)
  deadline = Current.time () + 3600 * 24 (* 1 day from now *)
}

(** Entry point for voting.
    @param choice A string corresponding to the candidate *)
let%entry vote choice storage =
  (* Only allowed while voting period is ongoing *)
  if Current.time () > storage.deadline then failwith "Voting closed";
  (* Voter must send at least 5tz to vote *)
  if Current.amount () < 5.00tz then
    failwith "Not enough money, at least 5tz to vote";
  (* Voter cannot vote twice *)
  if Map.mem (Current.sender ()) storage.voters then
    failwith ("Has already voted", Current.sender ());
  let votes = storage.votes in
  match Map.find choice votes with
  | None ->
    (* Vote must be for an existing candidate *)
    failwith ("Bad vote", choice)
  | Some x ->
    (* Increase vote count for candidate *)
    let storage = storage.votes <- Map.add choice (x + 1p) votes in
    (* Register voter *)
    let storage =
      storage.voters <- Map.add (Current.sender ()) () storage.voters in
    (* Return updated storage *)
    ([], storage)

(* Auxiliary function : returns the list of candidates with the
   maximum number of votes (there can be more than one in case of
   draw). *)
let find_winners votes =
  let winners, _max =
    Map.fold (fun ((name, nb), (winners, max)) ->
        if nb = max then
          name :: winners, max
        else if nb > max then
          [name], nb
        else winners, max
      ) votes ([], 0p) in
  winners

(** Entry point for paying winning candidates. *)
let%entry payout () storage =
  (* Only allowed once voting period is over *)
  if Current.time () <= storage.deadline then failwith "Voting ongoing";
  (* Indentify winners of vote *)
  let winners = find_winners storage.votes in
  (* Balance of contract is split equally between winners *)
  let amount = match Current.balance () / List.length winners with
    | None -> failwith "No winners"
    | Some (v, _rem) -> v in
  (* Generate transfer operations *)
  let operations = List.map (fun name ->
      let dest = match Map.find name storage.addresses with
        | None -> failwith () (* This cannot happen *)
        | Some d -> d in
      Account.transfer ~amount ~dest
    ) winners in
  (* Return list of operations. Storage is unchanged *)
  operations, storage
```

**Comment by michaelpj** [comment]
This is an interesting example!

Initially I thought you could implement this in a "stateless" way like the crowdfunding example, but you really need "fairness" here, i.e. you can't leave it up to the winner to decide which votes count (whereas the crowdfunding owner has an incentive to pull in all the contributions).

So then there are two ways you can go:
- Implement it with a state machine (as it's stateful). We have some examples in this repository and we're actively working on making this nice and easy.
- Enforce fairness. You could begin the contract by issuing a number of "voting tokens", and only allow completion if a certain proportion of them are present.

I think this would be a nice example, and we should consider adding it to `plutus-use-cases`.

**Comment by j-mueller** [comment]
Yes it's a good example 👍 especially the second option with the voting tokens as we don't have anything comparable at the moment

**Comment by srghma** [comment]
> Implement it with a state machine

Cool, but seems like it's not very concurrent option based on what I read here https://github.com/input-output-hk/plutus/blob/6acecafc0c4dd51442850929632c77c74022b562/plutus-wallet-api/src/Language/PlutusTx/StateMachine.hs#L63

(it works by creation new transaction with exactly one output but with new dataScript)

- Meaning having starting tx, voter 1 and voter 2
- voter 2 will be able to vote only after
- - voter 1 votes by creating new tx with input - starting tx, output - new tx1 with updated state
- - then voter 2 listens for new transactions
- - finds new one
- - voter 2 votes by creating new tx with input - tx1, output - tx2 with updated state

So, they can't core in parallel and double spend starting tx

_______

> and only allow completion if a certain proportion of them are present.

But by definition of task the voting is ended by the deadline

_______

> Initially I thought you could implement this in a "stateless" way like the crowdfunding example, but you really need "fairness" here, i.e. you can't leave it up to the winner to decide which votes count (whereas the crowdfunding owner has an incentive to pull in all the contributions).

Of course, didn't think about it

**Comment by mchakravarty** [comment]
How about the following use of tokens? We replicate the voting state machine by issuing `p` voting machine tickets (in a forging transaction with `n` outputs. Each of them is locked by script that implements the "linear" sorting state machine. After the voting deadlines expires, we require to post one transaction with `p` inputs that collects all the voting tokens and combines the `p` linear state machine results into a final result. This then gives us parallelism of degree `p` (which can be a parameter to the contract).

Given that a blockchain has a fairly limited throughput, for a reasonable value of `p`, I'd assume, you'll get a behaviour similar to what you are seeing in an account-based chain.

**Comment by michaelpj** [comment]
> But by definition of task the voting is ended by the deadline

Yes, but we'd here be adding a fairness condition. The person who computes the final result acts as the vote counter: the contract should ensure that they can only do this after the deadline, and with the tokens we can additionally ensure that a given fraction of the ballots are present.

> How about the following use of tokens? We replicate the voting state machine by issuing p voting machine tickets...

Yes, ideally we'd have library for such "splitting" state machines! In a sense, the version I proposed with the ballot tokens is like a very specialized version of this, where all participants get a machine, and it only has one state transition from `NotVoted` to `Voted`, and then the final one that sums up all the votes.
