### ISSUE TITLE
How does off-chain code know when a transaction has failed to validate?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1690]
There's an obvious mechanism for finding out when a transaction has validated: when you see a block with it in come past, you know it's validated.

However, there is no good way to know if a transaction has *failed* to validate. You have a few ways you can approximate:
- If your transaction has a finite upper bound on its validity interval (effectively a finite TTL), then if that time passes and you haven't seen it, then you'll never see it.
- If your transaction spends an output, and you see that output being removed from the UTXO, then you know your transaction will never validate.
- If your transaction fails at stage 2 validation and gets publicly posted on the chain as a failure, you know it failed!

(Some of these assume you're running appropriately powerful wallet backends that track such things.)

This *mostly* covers it: as far as I can tell the only remaining case is where you fail stage 1 validation due to a malformed transaction, missing witnesses, insufficient basic fees, which are predictable failures so really shouldn't happen. I guess you also don't know if the transaction failed to make it to the mempool.

So maybe this is okay? We should perhaps encourage people to set finite upper validity limits on their transactions by default, since that's the only thing that's guaranteed to eventually tell you that the transaction didn't make it (it's also low overhead: you only need to know the current slot).

**Comment by mchakravarty** [comment]
Yes, precisely.

IMO we should provide library functionality that makes it easy to subscribe to an event that combines the criteria you mentioned and additionally deem it good practise to put reasonable slot range bounds on transactions (and also have library functionality for the common cases).

BTW, I think, we have over time identified a variety of items that we consider good practice when using Plutus. I think, we should have these things in one place (maybe as part of the tutorial and eventually probably also in the book).
