### ISSUE TITLE
Fix PLC AST CBOR

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1696]
In language-plutus-core/src/Language/PlutusCore/CBOR.hs there's a lot of code that looks like this:

```
instance ( Serialise ann
         , Serialise (tyname ann)
         , Serialise (name ann)
         ) => Serialise (Term tyname name ann) where
    encode = cata a where
        a (VarF ann n)           = encodeTag 0 <> encode ann <> encode n
        a (TyAbsF ann tn k t)    = encodeTag 1 <> encode ann <> encode tn <> encode k <> t
        a (LamAbsF ann n ty t)   = encodeTag 2 <> encode ann <> encode n <> encode ty <> t
        a (ApplyF ann t t')      = encodeTag 3 <> encode ann <> t <> t'
        ...
```
`encode`Tag shouldn't be used for this: it's used in CBOR for writing tags which tell you what type of thing is coming up next.  Instead we should probably use a `Word8` for tags representing constructors (see `encodeWord8`).

See also #1693.

`cborg` tutorial: http://hackage.haskell.org/package/serialise-0.2.1.0/docs/Codec-Serialise-Tutorial.html

**Comment by kwxm** [comment]
It turns out that `cborg` can derive instances automatically for datatypes: 

```
-- with `DerivingStrategies`
data Animal = ...
            deriving stock (Generic)
            deriving anyclass (Serialise)
```

**Comment by michaelpj** [comment]
Yes, we use the derived instances for pretty much everything else. The reason PLC itself needs a hand-written encoding is described in the note at the top of the file: basically we need it to be stable, and not accidentally change if we reorder the constructors or something.

**Comment by kwxm** [comment]
I was just curious.  I tried the generic version and it makes the serialised ASTs a *lot* bigger, increasing the size by about 60%.  Here's a sample of what the two versions look like (manual version on the left, generic version on the right).  It looks like that all the way through.

![CBOR-diff](https://user-images.githubusercontent.com/2124565/69899120-bea93a00-1359-11ea-88a2-b39b15636904.png)

I think it's encoding our trees as nested tuples, rather than flat sequences. We definitely don't want to do that. On the bright side, using `encodeWord8` instead of `encodeTag` doesn't change the size of the CBOR at all, so I'll put in a PR to do that.

**Comment by kwxm** [comment]
Also, do we ever expect to serialise ASTs with non-unit annotations?  Currently the CBOR contains an extra byte for the unit annotation attached to every node and name in the AST.  Not encoding those allows us to save about an extra 30% in the uncompressed size in the final column of the table at https://github.com/input-output-hk/plutus/blob/master/docs/plutus-core/Erasure-Merklisation.md, giving a total reduction in AST size by a factor of 15-16 even before compression.  We also save about 7% in the compressed CBOR.

If we do that then there's probably no reason to include annotations in the on-chain AST either.

**Comment by effectfully** [comment]
>  Currently the CBOR contains an extra byte for the unit annotation attached to every node and name in the AST.

This is weird, given that encoding/decoding of `()` is implemented like that:

```haskell
-- The () type need never be written to disk: values of singleton type
-- can be reconstructed from the type alone
instance Serialize () where
    put ()  = return ()
    get     = return ()
```

I guess we should ask Duncan about that?

**Comment by kwxm** [comment]
Where do you see this?  Here's some test code and its output:
```
  putStrLn . show $ toFlatTerm $ encode (4::Word8,"string"::String)
  putStrLn "----------"
  putStrLn . show $ toFlatTerm $ encode (4::Word8,())
  putStrLn "----------"
  putStrLn . show $ toFlatTerm $ encode ((),())
  putStrLn "----------"
  putStrLn . show $ toFlatTerm $ encode ()
  putStrLn "----------"
  putStrLn $ "(Word, Int): " ++ show (serialise (11::Word, 22::Int))
  putStrLn "----------"
  putStrLn $ "((),()): " ++ show (serialise ((),()))
  putStrLn "----------"
  putStrLn $ "(): " ++ show (serialise ())
```
```
[TkListLen 2,TkInt 4,TkString "string"]
----------
[TkListLen 2,TkInt 4,TkNull]
----------
[TkListLen 2,TkNull,TkNull]
----------
[TkNull]
----------
(Word, Int): "\130\v\SYN"
----------
((),()): "\130\246\246"
----------
(): "\246"
```
It's definitely writing 0xf6/246 for (): you can see it doing that if you look for `TkNull` and `nullMP` in the cborg source.

**Comment by michaelpj** [comment]
Sure looks like it's encoding them as null: http://hackage.haskell.org/package/serialise-0.2.1.0/docs/src/Codec.Serialise.Class.html#line-205

I think my previous position was that we shouldn't worry about it because we should compress it all away. We could also really-really strip them to avoid encoding them at all.

**Comment by effectfully** [comment]
> Where do you see this?

Sorry, I'm an idiot: I looked into `Data.Serialize`, which belongs to the `cereal` package, not `serialize`.

**Comment by kwxm** [comment]
Done in #1698.
