### ISSUE TITLE
EUXTO model doc is missing rule for validity intervals

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1702]
They're mentioned in the prose, but they need a rule in the transaction validity rules.

@polinavino not sure whether validity intervals have made it into the new spec, but they should be there!

**Comment by polinavino** [comment]
There is one for the end of the interval. I'll add one for the start (there was only the `ttl` in the current ledger spec, which is the time to live, or the end of the validity interval)

**Comment by michaelpj** [comment]
Note that our intervals can be open/closed at either end and have "infinity" values so you can have the endpoints be unconstrained. We might want to simplify that, although it's quite useful.

**Comment by kwxm** [comment]
We don't really say very much about slots at all. I don't think we acutalyl say what a slot or a slot number is (although maybe an earlier version did and I took it out on the assumption that readers would know the general Cardano background).  I suppose that with out simplified model of the ledger (one transaction per slot, no empty slots) we can just make the current slot number equal to the length of the current ledger plus 1 (or maybe 2, depending on whether we start at 1 or 0).

It's perhaps questionable whether checking that we're inside the validity interval belongs in this document at all (although I'm not arguing against it): there are lots of factors that affect whether a core node decides to attempt to validate a transaction, and not all of them are relevant to the EUTXO model at all.  This particular issue does feel like it's on the border between the ledger and the EUTXO model, so we should pin down exactly where it belongs.

[A bit later...]  Hold on: I've just noticed that Note 9 says "note that the check that the current slot number is within a transaction's validity range takes place before validation is initiated, and the slot number is not passed to the validator".  I think this must have been written be @michaelpj.   If we accept that then maybe the slot check _doesn't_ belong in the validity rules.

**Comment by michaelpj** [comment]
> We don't really say very much about slots at all. I don't think we acutually say what a slot or a slot number is (although maybe an earlier version did and I took it out on the assumption that readers would know the general Cardano background).

Yeah, I guess we would need to say something about the current slot number. I would just say that we have some abstract, monotone function `slotNum :: Ledger -> Slot` that tells us what the slot number is, and leave it at that. That's my general strategy: if we don't want to go into the details, add an abstract function that tells you the thing and leave it at that.

> "note that the check that the current slot number is within a transaction's validity range takes place before validation is initiated, and the slot number is not passed to the validator"

I don't think I wrote that. The fact that the slot number isn't passed to the validator script doesn't mean we don't check the interval during validation!

There isn't really a phase before validation in which this check could occur, but I've realised one good reason why it doesn't fit nicely into validation: not being in range is not a validation failure per se. In particular, if the lower bound hasn't been reached yet, then the transaction should just hang around in the mempool.

We could be stricter, and say that it *is* part of validity checking that the validity range is satisfied, and then just say that a real system may choose to leave transactions that will be valid in the future until they are in range.

**Comment by kwxm** [comment]
> I don't think I wrote that.

You're right: it was me!  See  https://github.com/input-output-hk/plutus/commit/f6ef7b7bd5dae423b02c78a16aa539c9fcbb1546#diff-c84fed432201911b702c0b100a7711ab. I have no memory of writing that.

> There isn't really a phase before validation in which this check could occur

Where does this stuff happen then?  When a slot leader is processing transactions, there must be a phase when it has a bunch of candidates and makes a decision about which one it's going to process next, and checking the validity interval must happen either during or before that.  I should take a proper look at @polinavino's document...
