### ISSUE TITLE
State machine test are slow

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1716]
![grafik](https://user-images.githubusercontent.com/1771361/70232028-c737b100-175b-11ea-8bdf-565ba5572e45.png)
![grafik](https://user-images.githubusercontent.com/1771361/70232071-d9b1ea80-175b-11ea-863e-fd4378ded029.png)

**Comment by j-mueller** [comment]
Most of the time seems to be spent executing the scripts 

```

COST CENTRE            MODULE                                 SRC                                                             %time %alloc

renameTypeM            Language.PlutusCore.Rename.Internal    src/Language/PlutusCore/Rename/Internal.hs:(47,1)-(55,49)        12.8   12.4
lookupName             Language.PlutusCore.Name               src/Language/PlutusCore/Name.hs:154:1-39                          9.0    9.7
withFreshenedName      Language.PlutusCore.Rename.Monad       src/Language/PlutusCore/Rename/Monad.hs:(121,1)-(123,75)          8.7    7.3
normalizeTypesInM      Language.PlutusCore.Normalize.Internal src/Language/PlutusCore/Normalize/Internal.hs:(206,1)-(207,75)    8.3    9.6
renameNameM            Language.PlutusCore.Rename.Monad       src/Language/PlutusCore/Rename/Monad.hs:(110,1)-(114,48)          6.7    5.5
markNonFreshTerm       Language.PlutusCore.Quote              src/Language/PlutusCore/Quote.hs:108:1-55                         6.6    9.0
toBuilder              Codec.CBOR.Write                       src/Codec/CBOR/Write.hs:(85,1)-(162,13)                           6.5    5.3
validatorHash          Ledger.Scripts                         ledger/Ledger/Scripts.hs:(283,1)-(286,17)                         5.9    5.4
normalizeTypeM         Language.PlutusCore.Normalize.Internal src/Language/PlutusCore/Normalize/Internal.hs:(161,1)-(183,29)    5.0    6.7
<<$>>                  PlutusPrelude                          prelude/PlutusPrelude.hs:207:1-41                                 4.3    4.3
lookupNameM            Language.PlutusCore.Rename.Monad       src/Language/PlutusCore/Rename/Monad.hs:104:1-70                  4.0    3.1
<<*>>                  PlutusPrelude                          prelude/PlutusPrelude.hs:210:1-48                                 3.5    3.2
deserialiseIncremental Codec.CBOR.Read                        src/Codec/CBOR/Read.hs:(165,1)-(167,46)                           2.3    4.0
renameTermM            Language.PlutusCore.Rename.Internal    src/Language/PlutusCore/Rename/Internal.hs:(61,1)-(73,48)         1.9    2.2
toBuilder              Codec.CBOR.ByteArray.Sliced            src/Codec/CBOR/ByteArray/Sliced.hs:(81,1)-(94,31)                 1.7    1.5
insertByName           Language.PlutusCore.Name               src/Language/PlutusCore/Name.hs:124:1-43                          1.7    1.7
nameUnique             Language.PlutusCore.Name               src/Language/PlutusCore/Name.hs:55:7-16                           1.6    0.0
lookupUnique           Language.PlutusCore.Name               src/Language/PlutusCore/Name.hs:150:1-57                          1.3    0.2
freshUnique            Language.PlutusCore.Quote              src/Language/PlutusCore/Quote.hs:(163,1)-(166,14)                 1.2    0.6
withExtendedTypeVarEnv Language.PlutusCore.Normalize.Internal src/Language/PlutusCore/Normalize/Internal.hs:(132,1)-(133,70)    1.2    1.3
deserialiseIncremental Codec.Serialise                        src/Codec/Serialise.hs:92:1-64                                    0.2    2.4
```

Full report (running the first two tests in `Spec.MultiSigStateMachine`): https://gist.github.com/j-mueller/5969377204fbc4a64a31c653e3c05ae1

**Comment by j-mueller** [comment]
Is there any way to speed up script execution @effectfully ?

**Comment by effectfully** [comment]
I'll look at this closely tomorrow. But

> Most of the time seems to be spent executing the scripts

it doesn't seem to be the case. These:

```
renameTypeM            Language.PlutusCore.Rename.Internal    src/Language/PlutusCore/Rename/Internal.hs:(47,1)-(55,49)        12.8   12.4
normalizeTypesInM      Language.PlutusCore.Normalize.Internal src/Language/PlutusCore/Normalize/Internal.hs:(206,1)-(207,75)    8.3    9.6
renameNameM            Language.PlutusCore.Rename.Monad       src/Language/PlutusCore/Rename/Monad.hs:(110,1)-(114,48)          6.7    5.5
markNonFreshTerm       Language.PlutusCore.Quote              src/Language/PlutusCore/Quote.hs:108:1-55                         6.6    9.0
normalizeTypeM         Language.PlutusCore.Normalize.Internal src/Language/PlutusCore/Normalize/Internal.hs:(161,1)-(183,29)    5.0    6.7
<<$>>                  PlutusPrelude                          prelude/PlutusPrelude.hs:207:1-41                                 4.3    4.3
<<*>>                  PlutusPrelude                          prelude/PlutusPrelude.hs:210:1-48                                 3.5    3.2
```

are about normalization of all types in a term and type-checking of the term.

And these:

```
lookupName             Language.PlutusCore.Name               src/Language/PlutusCore/Name.hs:154:1-39                          9.0    9.7
withFreshenedName      Language.PlutusCore.Rename.Monad       src/Language/PlutusCore/Rename/Monad.hs:(121,1)-(123,75)          8.7    7.3
lookupNameM            Language.PlutusCore.Rename.Monad       src/Language/PlutusCore/Rename/Monad.hs:104:1-70                  4.0    3.1
deserialiseIncremental Codec.CBOR.Read                        src/Codec/CBOR/Read.hs:(165,1)-(167,46)                           2.3    4.0
renameTermM            Language.PlutusCore.Rename.Internal    src/Language/PlutusCore/Rename/Internal.hs:(61,1)-(73,48)         1.9    2.2
```

are about renaming of a term.

Nothing of that seems to be related to actual execution.

**Comment by effectfully** [comment]
Pinging @michaelpj

**Comment by j-mueller** [comment]
Ah yes sorry, I mentally put everything that happens in `Language.PlutusCore` into "script execution" but you're right.

**Comment by michaelpj** [comment]
That's a lot of time spent renaming... 

I wonder if we just have a lot of normalizing to do. We do normalize all the types in the program when we create the "on-chain" program, which is potentially quite expensive. Maybe we're doing this lots of times?

I wish I had a better flame-graph visualization of this, maybe we can use Matthew Pickering's recent speedscope work.

**Comment by j-mueller** [comment]
Yeah I remember reading about it but I couldn't remember the name. Unfortunately `hs-speedscope` has a warning that it only works with GHC 8.10 event logs

**Comment by j-mueller** [comment]
Although there is `ghc-prof-flamegraph` which I'm going to try out

**Comment by j-mueller** [comment]
Flame graph: https://github.com/input-output-hk/plutus/blob/df4d0451c89b4e104e5374334eb3ae5264cf3a5c/plutus-use-cases-test.prof.svg

**Comment by michaelpj** [comment]
Hm, so it looks like the typed tx stuff is creating the validator script a lot, which is resulting in a lot of normalization. That seems fixable.

**Comment by kwxm** [comment]
What does that graph cover, @j-mueller?  Is it still the multisig state machine example?  The tests for that and the futures example both take *much* longer than the other examples (20-30s compared to 1s or less), so it might be informative to compare the graph with a similar one for one of the faster examples.

**Comment by kwxm** [comment]
For comparison, I profiled the crowdfunding and escrow contracts.  This took a while: `stack test --profile plutus-use-cases` looked as if it should work, but failed with a massive plugin error, possibly because it was inserting profiling code in stuff that was supposed to get lifted to PLC.  I tried cabal, , but got version problems until I tried inside `nix-shelll`.  That eventually worked, but it turned out that Jann's instructions above are slightly incorrect. I think there's a `--enable-profiling` flag missing in the second command: I could only get it to work with

```
cabal new-build --enable-profiling plutus-use-cases-test 
cabal new-run--enable-profiling plutus-use-cases-test -- +RTS -p
```
(with suitable edits to Spec.hs in plutus-use-cases so that it only mentioned the particular contract I was interested in).  

Anyway, here are the graphs for the (crowdfunding example)[https://github.com/input-output-hk/plutus/blob/kwxm/tmp-flamegraph/crowdfunding-test.svg] and the (escrow example)[https://github.com/input-output-hk/plutus/blob/kwxm/tmp-flamegraph/escrow-test.svg].

**Comment by j-mueller** [comment]
> For comparison, I profiled the crowdfunding and escrow contracts. 

Thanks!

> it looks like the typed tx stuff is creating the validator script a lot

Yeah looks like a lot of that is driven by `Ledger.Typed.Scripts.scriptAddress`. Perhaps we should make `Address` a field of `ScriptInstance`? I'll see if that helps.

**Comment by michaelpj** [comment]
I'd be interested to see the flamegraphs of the versions with the fix, too. Might be more low-hanging fruit!

**Comment by j-mueller** [comment]
For the record the fix is in #1717 

I'll change the futures contract to use the new state machine client lib and then do another round of profiling.

**Comment by michaelpj** [comment]
Most of the obscenely long ones seem to have been fixed, the futures tests are still slow though.

**Comment by j-mueller** [comment]
Yeah I am working on those at the moment

**Comment by j-mueller** [comment]
The futures tests were improved in #1723
