### ISSUE TITLE
Playground: State Machine error and current state

### ISSUE THREAD

**Issue by SeldeOn** [input-output-hk/plutus#1732]
When trying to implement state machine having the bytestring as state in online plutus playground I'm getting a compilation error (function Language.PlutusTx.StateMachine.mkValidator): 

GHC Core to PLC plugin: Error: Reference to a name which is not a local, a builtin, or an external INLINABLE function: Variable Data.ByteString.Lazy.Internal.eq No unfolding Context: Compiling definition of: Main.dtxTransition Context: Compiling definition of: Main.stateMachine Context: Compiling expr at "main:Main:(70,8)-(71,50)"

I am guessing that the state machine is not fully implemented in plutus playground. Is there at least some part of functioning state machine present (some data type possible for state) or is there a way to implement a similar one with 8 constant states in online plutus playground? Does the implementation in the local version make a change?

**Comment by j-mueller** [comment]
The error doesn't have to do with the state machine itself, it's coming from the plugin that transforms the Haskell code to Plutus core. 

> I am guessing that the state machine is not fully implemented in plutus playground

If the playground is recent enough the state machine should be supported - what environment are you using, https://prod.playground.plutus.iohkdev.io/? Can you post some code that reproduces the error?

> is there a way to implement a similar one with 8 constant states in online plutus playground

Maybe something like

```haskell
data State = State1 | State2 | ... | State8
PlutusTx.makeLift ''State 
``` 

?

**Comment by SeldeOn** [comment]
Originally, I had my custom data type as state but I got:
```
error:
    • GHC stage restriction:
        instance for ‘Eq
                        DEMOtxState’ is used in a top-level splice, quasi-quote, or annotation,
        and must be imported, not defined locally
    • In the expression: SM.mkValidator (stateMachine txData')
      In the Template Haskell quotation
        [|| \ (txData' :: DEMOtxData)
              -> SM.mkValidator (stateMachine txData') ||]
      In the first argument of ‘compileScript’, namely
        ‘[|| \ (txData' :: DEMOtxData)
               -> SM.mkValidator (stateMachine txData') ||]’
   |
68 |         SM.mkValidator (stateMachine txData') ||]) 
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

so I change it into the bytestring:

```haskell
import qualified Language.PlutusTx.StateMachine as SM
import qualified Language.PlutusTx as PlutusTx
import Playground.Contract
import Wallet
import qualified Ledger.Validation as V
import Language.PlutusTx.Prelude
import Ledger (Address, scriptAddress, ValidatorScript (ValidatorScript), RedeemerScript (RedeemerScript), 
               DataScript (DataScript), compileScript, PendingTx, lifted, plcSHA2_256, applyScript)

data DEMOtxData = DEMOtxData { txInitiator :: PubKey
                             , txExecutor :: PubKey
                             } deriving (Generic, ToJSON, FromJSON, ToSchema)

PlutusTx.makeLift ''DEMOtxData

data DEMOtxState = Initial | Requested | Promised | Declined | Quitted | Stated | Rejected | Accepted | Stopped
    deriving (Generic, ToJSON, FromJSON, ToSchema)

PlutusTx.makeLift ''DEMOtxState

data DEMOtxAct = Request | Promise | Decline | Quit | State | Reject | Accept | Stop
    deriving (Generic, ToJSON, FromJSON, ToSchema)

PlutusTx.makeLift ''DEMOtxAct

data DEMOtxInput = DEMOtxInput { act :: DEMOtxAct
                               , key :: PubKey
                               } deriving (Generic, ToJSON, FromJSON, ToSchema)

PlutusTx.makeLift ''DEMOtxInput

dtxTransition :: DEMOtxData -> ByteString -> DEMOtxInput -> Maybe ByteString --trasitions and checks according only to inputs
dtxTransition txData state input
    | txInitiator txData == key input = case (state, act input) of
        ("Initial", Request)      -> Just "Requested"
        ("Declined", Request)     -> Just "Requested"
        ("Declined", Quit)        -> Just "Quitted"
        ("Stated", Accept)        -> Just "Accepted"
        ("Stated", Reject)        -> Just "Rejected"
        _                         -> Nothing
    | txExecutor txData == key input = case (state, act input) of
        ("Requested", Promise)    -> Just "Promised"
        ("Requested", Decline)    -> Just "Declined"
        ("Promised", State)       -> Just "Stated"
        ("Rejected", State)       -> Just "Stated"
        ("Rejected", Stop)        -> Just "Stopped"
        _                         -> Nothing
    | otherwise = Nothing

dtxCheck :: ByteString -> DEMOtxInput -> PendingTx -> Bool --ckecks according to pendinTx
dtxCheck state input tx = (tx `V.txSignedBy` key input)

dtxFinal :: ByteString -> Bool
dtxFinal "Quitted" = True
dtxFinal "Stopped" = True
dtxFinal "Accepte" = True
dtxFinal _ = False

stateMachine :: DEMOtxData -> SM.StateMachine ByteString DEMOtxInput
stateMachine txData = SM.StateMachine { smTransition = dtxTransition txData
                                      , smCheck = dtxCheck
                                      , smFinal = dtxFinal
                                      }

mkDTXValidator :: DEMOtxData -> ValidatorScript
mkDTXValidator txData = ValidatorScript $ 
    $$(Ledger.compileScript [|| \(txData' :: DEMOtxData) ->
        SM.mkValidator (stateMachine txData') ||]) 
    `Ledger.applyScript` 
    Ledger.lifted txData

$(mkFunctions [])
```
I was using [https://prod.playground.plutus.iohkdev.io/](https://prod.playground.plutus.iohkdev.io/), and now I am trying local Playground (September release). Now I am getting:

```
error:
    Could not load module `Language.PlutusTx.StateMachine'
    It is a member of the hidden package `plutus-wallet-api-0.1.0.0'.
    You can run `:set -package plutus-wallet-api' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v to see a list of the files searched for.
  |
1 | import qualified Language.PlutusTx.StateMachine as SM
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Any steps to enable plutus-wallet-api in plutusPlaygroundImage?

Thanks.

**Comment by j-mueller** [comment]
> GHC Core to PLC plugin: Error: Reference to a name which is not a local, a builtin, or an external INLINABLE function: Variable Data.ByteString.Lazy.Internal.eq No unfolding Context: Compiling definition of: Main.dtxTransition Context: Compiling definition of: Main.stateMachine Context: Compiling expr at "main:Main:(70,8)-(71,50)"

I created a separate issue for that in #1737

> Originally, I had my custom data type as state but I got: (...)

To get around this you could write `mkDTXValidator` like this:

```haskell
mkDTXValidator :: DEMOtxData -> ValidatorScript
mkDTXValidator txData = 
    let validator txData = SM.mkValidator (stateMachine txData) in
    ValidatorScript $ 
        $$(Ledger.compileScript [|| validator ||]) 
        `Ledger.applyScript` 
        Ledger.lifted txData
```

and change the state type back to `DEMOtxData`, then it compiles on https://prod.playground.plutus.iohkdev.io/

**Comment by SeldeOn** [comment]
That works. Thanks.

I would also like to clone the exact release that is on https://prod.playground.plutus.iohkdev.io/. The brach called prod or plc-with-sizes-final doesn't seem to be it. Can I ask for the right one?
