### ISSUE TITLE
On dependencies

### ISSUE THREAD

**Issue by angerman** [input-output-hk/plutus#1743]
Building plutus with more specialized compiles, quickly get's a bit tricky. 
Let's assume I want to build `plutus-use-cases:exe:contract-guessing-game`, this depends on `plutus-contract:lib:plutus-contract`, bring brings in `servant` and `tasty` as well as `plutus-tx` and `plutus-wallet-api`.

- `plutus-tx`, I believe we need for the plugin, and as `cabal` files do not offer a separate `plugin-depends` fields we just have to add it to the `build-depends`? If so (@michaelpj?), could we guard `plutus-tx` globally by some additional flag? Say `-fplutus-tx-dep` and have that default to `True`. Otherwise it is expected that the plugin is provided by some other means?
- `servant` I assume for the API to expose from the contract?
- `tasty`, and this one really confuses me. Why does `contract-guessing-game` transitively depend on `tasty`? Shouldn't tasty (or any test-library) only be a dependency of the test-suites? These dependencis often bring in terminal and other low level dependencies that a more esoteric compiler might just not be able to support?

Through `plutus-wallet-api` the `contract-guessing-game` depens on `hedgehog` as well, which I don't fully understand why that would be necessary. If this all boils down to some instance issues, should we add some `-ftest-support` flag, defaulting to `True` that adds the dependencies and also adds CPP macros around the instances?

Do we want to test contracts with esoteric compilers? Absolutely! But these often require much more low level features that will need to be implemented some way and aren't yet.

**Comment by j-mueller** [comment]
The `tasty` dependency comes from `plutus-contract`, in particular the `Language.Plutus.Contract.Test` module. The reason it's in there, instead of `plutus-contract-tasty` or whatever, is to avoid having yet another package (I'm not opposed to separating it out if that makes your life easier though!)

**Comment by angerman** [comment]
@j-mueller I'd be absolutely in favour of doing that! It would trim the dependency graph quite a bit and make it more concise. I think we'd want to aim for conciseness wrt to the plutus sdk as well. I think, that ideally the plutus sdk should contain the minimal set of dependencies we can get away with.

NB: I wish we had great tooling that would show us how much a package actually depends on another one. And if say `A -> B` for symbol `f`, and `B` is non-trivial (not just a single small module), but comes with multiple modules and multiple dependencies, of which `f` doesn't use most or any at all, inlining `f` into `A` would yield a much smaller transitive dependency set for `A`. So I'd like toolin that would show me how much of my package depends on the dependencies. Do I use 1%, 10%, 50%, 100% of the dependency and its dependencies? Weeder does this for the 0% or more case, but relies on stack build products iirc.

**Comment by michaelpj** [comment]
I'm a bit confused about what you're suggesting for `plutus-tx`? Indeed, AFAIK the only way to get plugins available is `build-depends`. Why do you want to disable the dependency? Surely then things won't compile because they're missing the plugin?

`servant` gives me pause. Our plan has been for the compiled contract bundles to expose a HTTP interface for things to talk to them. Hence: `servant`. But now that I think about it, I imagine that a HTTP library is hard to cross-compile :grimacing: Is there a sensible solution for a Haskell app to compile to a JS HTTP server?

Jann's covered the `tasty` stuff. Generally, we haven't exerted much discipline with our dependencies, but we could have more! The `hedgehog` dependency is for a similar reason: we export test helpers, in this case generators. I guess we need to split those out too (multiple public libraries per package is probably too fresh...).

**Comment by angerman** [comment]
> I'm a bit confused about what you're suggesting for `plutus-tx`? Indeed, AFAIK the only way to get plugins available is `build-depends`. Why do you want to disable the dependency? Surely then things won't compile because they're missing the plugin?

As I said, this is mostly a defect in cabal. However the general case would be `-package-db /path/to/host-pkg-db`, and `{-# OPTIONS_GHC -fplugin=... #-}`. The fact that it works by just adding it as a dependency is something I consider a coincidence.
> 
> `servant` gives me pause. Our plan has been for the compiled contract bundles to expose a HTTP interface for things to talk to them. Hence: `servant`. But now that I think about it, I imagine that a HTTP library is hard to cross-compile 😬 Is there a sensible solution for a Haskell app to compile to a JS HTTP server?

Conceptually, this would be what backpack would be useful for, I believe. I'm not really opposed to servant as a dependency, and @luite has hacked up some WAI adapter for JS. So this can all work. We just need to make sure that we have the conditionals to switch (htttp) backends.
> 
> Jann's covered the `tasty` stuff. Generally, we haven't exerted much discipline with our dependencies, but we could have more! The `hedgehog` dependency is for a similar reason: we export test helpers, in this case generators. I guess we need to split those out too (multiple public libraries per package is probably too fresh...).

Right. I believe moving the test and generators out of the core sdk would be quite helpful in the long run.

**Comment by michaelpj** [comment]
> As I said, this is mostly a defect in cabal. However the general case would be -package-db /path/to/host-pkg-db, and {-# OPTIONS_GHC -fplugin=... #-}. The fact that it works by just adding it as a dependency is something I consider a coincidence.

It's [the recommended way](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/extending_ghc.html#using-compiler-plugins) of using plugins, and every existing plugin uses it, so until `cabal` learns `native-build-depends` that's what we're using!

I still don't understand what your suggestion is: how could we have a flag that turns off the dependency? That would just make things not compile.

You still need the `OPTIONS_GHC` pragma in general, but we fix that up with TH.

> Conceptually, this would be what backpack would be useful for, I believe. I'm not really opposed to servant as a dependency, and @luite has hacked up some WAI adapter for JS. So this can all work. We just need to make sure that we have the conditionals to switch (htttp) backends.

Okay, that sounds fine. The usage should be fairly limited, so I think it's okay if it's a bit hacky.

> Right. I believe moving the test and generators out of the core sdk would be quite helpful in the long run.

**Comment by angerman** [comment]
> > As I said, this is mostly a defect in cabal. However the general case would be -package-db /path/to/host-pkg-db, and {-# OPTIONS_GHC -fplugin=... #-}. The fact that it works by just adding it as a dependency is something I consider a coincidence.
> 
> It's [the recommended way](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/extending_ghc.html#using-compiler-plugins) of using plugins, and every existing plugin uses it, so until `cabal` learns `native-build-depends` that's what we're using!

I don't think I'd call
> At the moment, the only way to specify a dependency on a plugin in Cabal is to put it in build-depends

the *recommended way*; but let's not split hairs here.

> 
> I still don't understand what your suggestion is: how could we have a flag that turns off the dependency? That would just make things not compile.

Why not? Let's assume for a moment we have a ghc that *ships* with a package database that contains the plutus compiler plugin. Does the contact I am compiling really need to depend on the plutus compiler plugin? If so, how? Why would it not compile without directly depending on the plugin?

**Comment by michaelpj** [comment]
> I don't think I'd call
> >    At the moment, the only way to specify a dependency on a plugin in Cabal is to put it in build-depends
>
> the recommended way; but let's not split hairs here.

Its the way that anyone who's trying to use the plugin for real is going to default to using it, so :man_shrugging: 

> Why not? Let's assume for a moment we have a ghc that ships with a package database that contains the plutus compiler plugin.

Oh I see. You want a flag for `plugin_provided_manually`. Yes, sure, that would work.

**Comment by j-mueller** [comment]
The `tasty` and `playground-common` dependencies were removed in #1763

**Comment by michaelpj** [comment]
I think this is done - if there's more to do please open a more specific issue.
