### ISSUE TITLE
Could we provide some means of accessing applied validators during tests?

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1752]
It's useful to be able to look at realistic validator scripts (eg for experiments with Merklisation or cost models), and the example contracts are a good source of these.  However, to get something runnable you have to apply the validators to sensible arguments, and these can be quite difficult to construct.  The tests in `plutus-use-cases` do this, but the validators and their arguments are only available by the time you get to `Ledger.Scripts.runScript` or `Ledger.Index.checkValidInputs`.  I managed to do what I wanted by modifying `runScript` to apply my own functions to the validators and their arguments both before and after application, and then using `trace` to output the results.  This was good because I could then just type `stack test plutus-use-cases` to automatically run the experiments on all the vallidators (and with different inputs leading to different execution paths), but it's not exactly elegant.

Could we modify the mockchain framework in some way to allow extra actions to be included in the tests, to be run at a point where the validators and their arguments are all available?  This is just a tentative suggestion: I don't know if it's actually a good idea, or what a good way to do it would be.

**Comment by michaelpj** [comment]
What about some dumping options? So we could tell it to dump applied scripts to (a directory of) files, and then you could parse them and run your tests on them.

**Comment by kwxm** [comment]
Note that textual dumps of these things aren't parsable because (a) the parser can't handle extensible built-in names (`trace`, for example) and (b) the scripts re-use PLC keywords for other things (eg, all of the built-in functions are  wrapped in a lambda of the same name; also variables called `con` appear quite a lot).  I think we don't really need keywords because everything's disambiguated by position, but we had a debate some time ago and decided that we should have keywords for some reason.

That's all irrelevant though: we could dump serialised versions.  A minor problem is that you get lots of different versions of the same scripts which follow different execution paths (which is exactly what we want), so you'd need to be able to pass in a name allowing you to keep track of which is which.  I guess you'd need to do something along those lines no matter what we do though.
