### ISSUE TITLE
Document the Plutus.xxx modules

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#1776]
A high-level overview of the Plutus modules and how they relate to one another

**Comment by j-mueller** [comment]
It should go into architecture.adoc

**Comment by michaelpj** [comment]
Maybe have sub-documents per package in the package and then include them all?

**Comment by michaelpj** [comment]
Also s/modules/packages?

**Comment by j-mueller** [comment]
I wrote modules because some of the things that Manuel mentioned in the call are implemented in different modules that live in the same package. But it probably makes sense to describe the packages as well.

**Comment by michaelpj** [comment]
Yeah, although sometimes that means our packages need to change. e.g. I think we maybe really should split out `plutus-ledger` (and maybe kill the remaining bits of `plutus-wallet-api` or fold them into `plutus-contract`).
