### ISSUE TITLE
Isolate `ghc` dependency

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1790]
This is problematic in a cross setting. We only need it for the plugin, and the plugin will be provided otherwise when doing cross.

So the plan is:
- Split out `plutus-tx-plugin`.
- Wrangle the dependencies so it *only* contains the plugin stuff.
- Make all the `plutus-tx-plugin` dependencies conditional on `impl(ghcjs) && os(ghcjs)`.

**Comment by michaelpj** [comment]
Not sure what to call `plutus-tx`-minus-the-plugin. `plutus-tx` sounds like it's everything, `plutus-tx-lib` is a bit generic.

**Comment by kwxm** [comment]
> Not sure what to call `plutus-tx`-minus-the-plugin. `plutus-tx` sounds like it's everything, `plutus-tx-lib` is a bit generic.

`plutus-plughole`
