### ISSUE TITLE
Spending policies for currencies

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1791]
Something that comes up every now and again is that people want to have some kind of "spending policy" for a currency, that imposes some conditions that must be satisfied whenever you spend some of that currency. Some examples:
- All transactions involving that currency must be approved (signed) by some particular key.
- The currency can only be held by a set of approved users (e.g. role tokens passing between a set of users determined at the start of the contract).
- Transactions with that currency must pay a fee to some address in order to be able to use it.
    - This is a pretty real use-case, e.g. taking fees out of transactions using a token

----

One idea I came up with for this was multiple validators on outputs, but we decided that wasn't really going to work. (See https://groups.google.com/a/iohk.io/d/msg/plutus/3LkNU63RJzI/uTkPBoq8DQAJ for discussion.)

---

We could also have some script that ran on every transaction that used a currency. If we adopted the "separate MPS" script proposal (https://groups.google.com/a/iohk.io/d/msg/plutus/asXbLbPEV9I/TvmE-OCYCAAJ), then the MPS could be suitable for this: we could extend the forging rule to say that we run the MPS whenever the currency is forged *or* used, and the MPS can act as a spending policy or forging policy depending on the shape of the transaction.

However, this would require running a script on *every* transaction that used a currency, with no way to opt out, which seems like a lot of overhead for people who don't care about this use case.

More ideas needed!

**Comment by j-mueller** [comment]
Two other implementation ideas:

* State machine with a list of accounts and balances. A direct implementation of ERC-20, without using the multi currency feature. Probably a bad idea because the state gets big (making every transaction that changes it more expensive), and because it creates a bottleneck on the single output that holds the state.
* A modification of the [`PubKey`](https://github.com/input-output-hk/plutus/blob/master/plutus-use-cases/src/Language/PlutusTx/Coordination/Contracts/PubKey.hs#L28) contract - we use the MPS to ensure that the new currency only gets paid to outputs that are locked by our custom pubkey contract, and the custom pubkey contract enforces the spending policy and ensures that the new outputs are again locked by the custom pubkey contract.

**Comment by j-mueller** [comment]
I think the 2nd idea is relatively clean, the pubkey contract would have a well-known address, and the data script would simply be the public key, so it would be easy to use.

**Comment by michaelpj** [comment]
It has similar issues to the multiple validators suggestion, in that you can't then use your tokens in any other kind of smart contract, and they're essentially restricted to person-to-person transfers.

**Comment by michaelpj** [comment]
Okay, this looks like it's an increasingly live issue, so here's some thoughts.

-----

Idea 1: proper currency specification objects

At the moment `CurrencyID` is just directly the hash of a script (the MPS). But it could be the hash of something else! Let's define:
```
data CurrencySpec = 
    SimpleCurrency ScriptHash -- MPS only
    | FancyCurrency ScriptHash ScriptHash -- MPS and spending policy script (SPS)
    -- maybe other kinds? SPS but no MPS? etc.
```
Now, on the tx instead of `forgeScripts :: [ScriptHash]` we put `currencySpecs :: Map CurrencySpecHash CurrencySpec` (using the usual hash-lookup map thing that we do for attached data).

Validation:
- For every currency that is forged *or used*, we look up the currency spec, and:
    - If it is forged, we run the MPS
    - If it is used and the spec has a SPS, we run that

This has one *howling* problem: we now have to attach the currency spec every time we use a currency, *even if that currency has no spending policy*, because we can't know that until we look at the actual spec. So if I send you some tokens, you can't use those without knowing the spec. Which is a massive usability regression.

----

Idea 2: structured currency identifiers

We have a similar problem with addresses. Addresses could just be a hash, but then we wouldn't know what kind of witness we needed.

So rather than having `CurrencyID` just be a hash, we could have:
```
data CurrencyID = 
    SimpleCurrencyID CurrencySpecHash
    | FancyCurrecnyID CurrencySpecHash
```
i.e. we add an extra bit of information that tells us what kind of spec we're expecting. This would let us tell from the currency identifier that we don't have a spending policy, and hence that we don't need the currency spec unless we're forging.

(What happens if someone lies? i.e. makes a currency ID with the hash of a currency spec that has a SPS, but tags it as a `SimpleCurrencyID`. Well: a) that's a different currency identifier from the one that is correctly tagged, so they're not fungible, and b) it would fail a consistency check when used, so you wouldn't be able to forge any.)

**Comment by mchakravarty** [comment]
Another reason why this is a bad idea is that it won't work with Hydra. Basically, you will only be able to use spending policies on the mainchain.

**Comment by michaelpj** [comment]
Hmm yes, I guess Hydra doesn't enforce that validation proceeds according to the main chain (i.e. an acceptable option is for everyone just to agree on a redistribution of the funds?).

Of course, this also has consequences for other smart contract state machines allowing themselves to be moved into Hydra - most couldn't trust it if that's true.

All the approaches to spending policies also have the issue that they won't work with other smart contracts, since they won't know how to satisfy the policy (or where to get the currency spec from).

**Comment by mchakravarty** [comment]
The situation is different for normal state machine contracts. They only need to trust one of the head members to apply them correctly and in the Hydra protocol, there is a clear point, where a contract can make that decision (to go into a particular head or not). For spending policies that wouldn't be the case (and I can't see how the same ideas that we use for state machines could be applied).

**Comment by michaelpj** [comment]
> The situation is different for normal state machine contracts. They only need to trust one of the head members to apply them correctly

Surely this is the same for spending policies: they'd need to trust one of the head members to run them correctly?

**Comment by polinavino** [comment]
I think I am not understanding something here, but why is it not possible to have a spending policy that is a regular UTxO output-locking script, i.e., if in the `forge` field there is 
`currencyID |-> tokens` (say this is `value1`),

then in the transaction outputs we have
`ix |-> (spending_policy_script_hash, value1, data_value_hash)`

**Comment by michaelpj** [comment]
Sure, you can have a "viral" spending policy, but it has a number of downsides (see the linked discussion on "multiple validators" above which discusses it).

It's not clear that we've come up with a clearly better solution, but I want one ;)

**Comment by polinavino** [comment]
Could we have both the spending policy and the forging policy in the forging script as a pair of scripts `(s_forge, s_spend)` and only run the forging script when forging is being done, like

```evalMPSscript (s_forge, s_spend) cid tx_forge spent_outputs ... =
   cid \notin (dom tx_forge) => (evalOneScr s_spend ...)
   cid \in (dom tx_forge) =>  (evalOneScr s_forge ...)
   ```

Though, a spending policy would have to be part of the forging script too (it could be the same or different than the spending policy of the spending policy script).

**Comment by michaelpj** [comment]
The problem with Hydra is that if everyone is colluding in a Hydra head, they can redistribute the funds how they like (I think: Manuel can correct me). 

This is also kind of a problem for smart contracts, in that they might not be run properly inside the head, but e.g. a state machine has to "consent" to being put into a Hydra head by allowing the initial transaction that collects its output. I argued that the same is true for a currency with a spending policy: the spending policy will get run when the funds get put into the head, so it should be able to allow/deny this depending on whether it trusts the participant. So I'm not sure there is a problem.

Structured currency IDs (or maybe we should call them "currency addresses") is my IMO the best idea so far. 

Note that currencies with spending policies still have massive usability issues, so in practice every piece of generic code would have to add a guard "and fail if anything that's being spent has a spending policy because I don't know how to do that". So even allowing them imposes a burden on the rest of the ecosystem.

**Comment by polinavino** [comment]
I am picturing, with a hydra contract for e.g.

- suppose the spending policy requires every time a currency cid changes is spent, the issuer must get a certain amount of ada
- suppose some cid is locked by hydra and changes  hands a whole lot of times during its time being locked by a hydra contract
- everyone involved in the hydra contract colludes and says that the only change of hands that occurred at all during this hydra contract is the final result that goes back on chain
- the issuer never gets the ada from all the times the token was actually spent during the contract execution

This would be different than for regular contracts when each transfer is on-chain. Is this "a bargain" for hydra users, or real cheating?

**Comment by michaelpj** [comment]
This is no different from what happens if you "transfer" a multi-stage contract like a state machine into a hydra head. So as far as I can tell they're both equally bad or equally not bad. If we think the script can just refuse to let an output go into a head, and that's good enough, then it's good enough in both cases.

**Comment by polinavino** [comment]
Yeah, I meant any kind of contract done inside hydra vs a contract executed fully on chain. And yes, if it is possible for a spending policy to know whether its tokens are going into a hydra head (how? the address is just a script hash..), imposing this restriction sounds like a reasonable way to deal with this issue

**Comment by polinavino** [comment]
Also, is there any funny business that can happen with forging currency inside hydra? Like, tokens are forged too early by a colluding hydra group, but then by the time funds go back on-chain, it is a later slot and the forging script validates?

**Comment by michaelpj** [comment]
We thought about that one: the overall hydra protocol has to preserve value, so it can't do forging or burning.

**Comment by polinavino** [comment]
As in, there is a clause in the script that is the hydra head that says that when the head is spent (hydra funds are going back on chain), the forge field is 0?

**Comment by michaelpj** [comment]
I don't exactly know the details that we ended up with.
