### ISSUE TITLE
Error handling in Plutus Core

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#1806]
Do we want any of `catchError`, `onError` or `finally` in Plutus Core? They can either be hardcoded or [defined as builtins](https://github.com/input-output-hk/plutus/blob/4e781f6007c3c1199bbdebb48b84e0d411e67982/language-plutus-core/test/Evaluation/DynamicBuiltins/Definition.hs#L126-L230) (provided an abstract machine supports that). One advantage is that one can catch an unreasonable error thrown in some library (which unfortunately does happen), the disadvantage is that this greatly complicates Plutus Core (adds weird ways to organize control flow, makes us less confident in the implementation, etc).

**Comment by reactormonk** [comment]
Doesn't that mean we're basically introducing gotos into the lambda calculus? I'd go the Elm route here and simply forbid compiling code which contains `Debug.crash` in production mode. That should cover basically everything except for division by 0 errors.

**Comment by michaelpj** [comment]
`error` is actually how we signal validation failure, and also thrown by some builtins (e.g. div by zero), so forbidding it would be a fairly major change of direction.

**Comment by reactormonk** [comment]
Forbid compiling anything but builtin code from having `error` - or rather, library code. But then there is no real distinction between library code and application code, so that doesn't seem to be very productive - probably best to say "no, you can't recover from error, please don't write library code containing it".

**Comment by michaelpj** [comment]
> probably best to say "no, you can't recover from error, please don't write library code containing it".

I agree :)

**Comment by effectfully** [comment]
We can't define `catchError` anymore due to changes in the builtins machinery, so I'm closing this.
