### ISSUE TITLE
Could we get rid of unlifting if builtin functions only worked with builtin types?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1815]
We no longer need unlifting to make sense of values that have been put on chain (since they're all just `Data`). So that's one thing.

The other fundamental usage of unlifting is to convert the arguments to builtins from PLC terms to Haskell values so we can run the denotation of the builtin on it.

This lets us e.g. have builtin functions that consume booleans.

But what if we required that builtin functions only used builtin types? Then:
- We don't need unlifting, since the arguments would always just be `(con <value of haskell type>)` (I think?)
- We could just make bool/unit etc into builtin types

Adding bool/unit as builtin types wouldn't even cost us much. Right now we represent them as Scott-encoded data, but even though in the enclosing compiled program the "actual" representation of booleans is also Scott-encoded, within the body that type is abstracted out, and so we can't just freely use the output of say `lessThanInteger` as a boolean. Instead we have to put in an adapter, see https://github.com/input-output-hk/plutus/blob/master/plutus-tx-plugin/src/Language/PlutusTx/Compiler/Builtins.hs#L77 and accompanying code.

We'd still need this adapter if the type that came out of the builtin was a builtin boolean, but it wouldn't be any *worse* than the current situation.

**Comment by michaelpj** [comment]
Oh, and this would also simplify the specification. Right now it's not clear what types can be used in the schema of builtins, this would make it clear: only builtin types.

**Comment by effectfully** [comment]
> Oh, and this would also simplify the specification. Right now it's not clear what types can be used in the schema of builtins, this would make it clear: only builtin types.

... and we can have `forall`s as in `forall a b. a -> b -> a` or `forall a. list a -> list a` (with `list` being in the universe). In the implementation we also have `EvaluationResult` (once the evaluation-changing PR gets merged, we won't be able to apply `EvaluationResult` to an argument of a function, but we still need to be able to apply it to the result of a function in order to indicate the function may throw an `Error`). The current API is pretty convenient, I tried other ways to do these things, but they were not as convenient, so even if we completely remove all unlifing of values, it will perhaps make sense to keep the API.

If we add `Bool` and `()` to the universe, I believe it will greatly simplify things, although I also think that I can implement unlifting of values of such types in a sensible way (but just adding the types to the universe is certainly simpler, so why not).

**Comment by mchakravarty** [comment]
That seems like a very sensible route to me.

**Comment by michaelpj** [comment]
Simon pointed out to me that this becomes less clear if we ever have polymorphic builtin types. Suppose we had `Set a` as a builtin type. Then how can we write `insert :: a -> Set a -> Set a` as a builtin, if builtins can only work with builtin types?

Maybe we could somehow make an exception for polymorphic types, but it complicates the story. Of course, the story would be complicated if we did unlifting too, indeed I vaguely recall that this is what the current `OpaqueTerm` stuff is for.

**Comment by effectfully** [comment]
That's what I addressed with

> and we can have `forall`s as in `forall a b. a -> b -> a` or `forall a. list a -> list a` (with list being in the universe)

polymorphic types are orthogonal to unlifting and we currently do support them. Right now they interoperate with unlifting (we have a `reverse : all a. list a -> list a` test case), but once we remove unlifting, this machinery should also work with universes. I haven't checked this yet, though, there might be surprises.

> the story would be complicated if we did unlifting too, indeed I vaguely recall that this is what the current `OpaqueTerm` stuff is for.

Yes, but the `OpaqueTerm` thing is a pretty simple one, I'd say, so I'm going to keep it.

**Comment by effectfully** [comment]
> If we add `Bool` and `()` to the universe, I believe it will greatly simplify things

Just realized it will allow to remove the entire evaluator-passing machinery, which is a great simplification.

**Comment by michaelpj** [comment]
Roman, would you say this is done now?

**Comment by effectfully** [comment]
Once #1889 is merged.

**Comment by effectfully** [comment]
Done in #1889.
