### ISSUE TITLE
Unify default-extensions

### ISSUE THREAD

**Issue by reactormonk** [input-output-hk/plutus#1826]
Source: https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/ + `DerivingVia`.

```
default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
```

**Comment by michaelpj** [comment]
Ones I'm not convinced by:
- `ApplicativeDo` (rarely used)
- `NoImplicitPrelude` (really? it's not in that post either)
- `DataKinds`/`TypeFamilies`/`TypeFamilyDependencies` (these are pretty new, perhaps better to have them obviously marked).

**Comment by reactormonk** [comment]
- `NoImplicitPrelude` kinda snuck in, I copied the list from a personal project. Don't we have `PlutusPrelude` as a quasi-replacement?
- `ApplicaitveDo` I prefer the `ado` from PureScript, but :man_shrugging:, it's what we go. A bit hard to enforce applicative combination. Deleted it.
- typelevel stuff is a bit newer, depends on your definition of "new", but they are benign, so should be fine?

**Comment by effectfully** [comment]
I would also include `LambdaCase`. I wouldn't include `ApplicativeDo` (from my experience it doesn't work very well in Haskell, although I don't remember what problems I had there). I'd include `GADTs` and `TypeFamilies`, but probably not `TypeFamilyDependencies` (not a big deal though).
