### ISSUE TITLE
Builtins don't get budgeted if they don't have arguments

### ISSUE THREAD

**Issue by reactormonk** [input-output-hk/plutus#1842]
See https://github.com/input-output-hk/plutus/pull/1833/files#diff-def749a774ba31ff1e8f50719cd7414dR70

We currently don't have any builtins that are constants, but this might come up in the future.

**Comment by kwxm** [comment]
The saturated builtins PR is going to disallow builtins with no arguments (or at least throw an error if it finds one).  I think we're going to put off thinking about such things for the time being.

**Comment by kwxm** [comment]
See JIRA issue SCP-779.
