### ISSUE TITLE
Add Ada constructor to Marlowe Token datatype

### ISSUE THREAD

**Issue by nau** [input-output-hk/plutus#1856]
Add `Ada` constructor to `Token` datatype to avoid using (Token "" "") to represent Ada values.
This appears a lot in pretty-printing, Blockly, Show, etc.

**Comment by michaelpj** [comment]
I don't want to do this because this is not how we expect things to be represented in the real version.

I don't mind if you want to change the pretty-printing though.

**Comment by nau** [comment]
That's for Marlowe `Token` datatype only, though, not the Ledger stuff.
