### ISSUE TITLE
formalisation's treatment of error in reduction semantics doesn't match spec

### ISSUE THREAD

**Issue by jmchapman** [input-output-hk/plutus#1871]
Currently, in the Agda formalisation an error term is any term that contains an error in it. The spec has exactly one error term (`error`) and has a catchall reduction rule that reduces any term to error when one of its subterms reduces to error. I am going to try the spec approach as it has the advantage that a term can either be error exclusive or it can reduce. In the currently formalisation a term can be an error term and reduce.

**Comment by kwxm** [comment]
See also #948.
