### ISSUE TITLE
An `if-then-else` expr is wrongly optimized away to its branch.

### ISSUE THREAD

**Issue by bezirg** [input-output-hk/plutus#1872]
In the following program, the doctest passes:

```
{-# LANGUAGE TemplateHaskell     #-} 
{-# LANGUAGE DataKinds           #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE NoImplicitPrelude   #-}
module MyExample where

import qualified Language.PlutusCore.Universe as PLC 
import Language.PlutusTx 
import Language.PlutusTx.Builtins 
import Language.PlutusTx.Prelude 

-- $setup 
-- >>> import Language.PlutusTx
-- >>> import Language.PlutusCore
-- >>> import Data.Text.Prettyprint.Doc


cpSameBranch :: CompiledCode PLC.DefaultUni Integer
cpSameBranch = $$(compile [|| if ((1`divideInteger`0)`equalsInteger`0)
                              then 1
                              else 1 ||])

{- | >>> pretty $ getPir cpSameBranch
(program (con 1))
-}
```

The correct behaviour is not to optimize this, because the predicate should evaluate to DivideByZero.

**Comment by reactormonk** [comment]
This is regular Haskell behavior, so I'd say "not a bug".

```
main = do
  print $ if ((1/0) == 0) then 1 else 1
```

```
$ ghc test.hs && ./test
1
```

**Comment by bezirg** [comment]
@reactormonk : the code that you wrote uses the (/) :: Fractional a => a -> a -> a , which I would think will default to `Double`. `1/0` returns a normal value `Infinity` , instead of throwing an exception.

What I am referring to is the `div` === `divideInteger`. If you use the `div :: Integral a => a -> a -> a` instead in your example it should throw an exception Divide by zero:

```
main = do
  print $ if ((1`div`0) == 0) then 1 else 1
```

**Comment by reactormonk** [comment]
Yeah, can confirm, there's an exception. Oops.

**Comment by bezirg** [comment]
I think there is something going wrong with pir Optimizer. When I run with `-fplugin-opt=Language.PlutusTx.Plugin:dont-optimize` , this bug does not occur anymore.

**Comment by michaelpj** [comment]
So, without dead-code elimination, we get (essentially) this:
```
(let                                                                                                                                                                  
        (nonrec)                                                                                                                                                            
        (termbind                                                                                                                                                           
                (strict)                                                                                                                                                          
                (vardecl                                                                                                                                                          
                        wild Bool                                                                                                                                                       
                )                                                                                                                                                                 
                [                                                                                                                                                                 
                        [                                                                                                                                                               
                                equalsInteger                                                                                                                                                 
                                [                                                                                                                                                             
                                        [                                                                                                                                                           
                                                divideInteger                                                                                                                                             
                                                (con
                                                        1
                                                )
                                        ]
                                        (con 0
                                        )
                                ]
                        ]
                        (con 0)
                ]
        )
        (con 1)
```
This is a *dead* let-binding around `(con 1)`. But the RHS of the let-binding is strict, and evaluating it is an error, so this is *not* safe to remove. I think that's the actual bug: we can't remove strict, non-value let bindings.

Amusingly this is essentially the same problem as we saw earlier this week with *moving* strict non-value let bindings.

**Comment by michaelpj** [comment]
A problem: builtins are not values. The plugin generates lots of bindings that just wrap builtin functions so we can get the names right, e.g. `let addInteger = builtin addInteger in ...`

Now, we know these won't evaluate because they're *functions*, but at the PIR level we don't know that.

I see two options:
1. Say that builtins are values. Hope we don't add any nullary builtins that we care about.
2. Eta-expand all the defintions so they're obviously values.

I'm leaning towards 2. at the moment.

**Comment by effectfully** [comment]
> Say that builtins are values. Hope we don't add any nullary builtins that we care about.

More corner cases to the god of corner cases. Would treating builtins as values make sense from the metatheory point of view?

> Eta-expand all the defintions so they're obviously values.

Much prefer this option. Also plays well with saturated builtins. Pinging @kwxm

**Comment by kwxm** [comment]
> Much prefer this option. Also plays well with saturated builtins. Pinging @kwxm

I've lost track: what exactly is the situation with saturated builtins these days?  The PLC spec currently requires them, but I think the machines work OK with unsaturated ones. Are we going to enforce the saturation requirement?

**Comment by effectfully** [comment]
> Edit: I see that we have an issue for this at #1144.

Responded there.
