### ISSUE TITLE
Remove gas computations from typechecker/normaliser?

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1881]
I see that the code in `TypeCheck.Internal` and `Normalize.Internal` contains gas computations.  It seems unlikely that we're going to be doing typechecking on the chain, so should we remove the gas-related stuff eventually?  That would simplify things a bit, which is probably good.

**Comment by michaelpj** [comment]
Yes, that seems likely.

**Comment by michaelpj** [comment]
We should also be able to remove the corresponding sections from the spec.
