### ISSUE TITLE
Untyped builtin application

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1898]
In https://github.com/input-output-hk/plutus/pull/1870 there's a pull request which adds syntax for untyped PLC, together with reduction rules, a CK machine, and an erasure function from standard PLC terms to untyped ones.  The question arises of what happens to applications of built-in functions: we can write `[(builtin AddInteger) t_1 t_2]` in the untyped syntax and there's no guarantee that t_1 and t_2 have sensible types.  Now this is OK with the present implementation because we're secretly using typed Haskell to evaluate these things and we'll presumably get a type error here (I'm assuming we'll be using the same evaluation mechanism (or a very similar one) for typed and untyped PLC). 

 However, I think that the Plutus Core specification shouldn't be too tightly tied to the current implementation, and ideally it shouldn't mention Haskell or rely on the implementation language being typed (maybe someone will decide to speed things up by writing a PLC evaluator in C, or compiling PLC directly to machine language or something; also maybe PLC validators will still be in existence in 50 years and being processed by languages that don't even exist now). 

So how should we deal with applying built-in functions in an untyped world?  I've modified the PR to say that the semantics of untyped PLC are defined only for terms/programs that have been obtained by erasing types from well-typed typed PLC programs.  This allows us to delegate the semantics of built-in functions to the typed level. Denoting type erasure by ⟦⟧, we have 

 ```   [(builtin b) ⟦t_1⟧ ... ⟦t_n⟧) = ⟦[(builtin b) t_1 ... t_n]⟧ ``` 

This says that the meaning of applying a builtin in the untyped world to a bunch of erased terms (on the left) is what you get by applying the same builtin to the unerased terms in the typed world and then erasing types to get back to the untyped world. 

Given this (which I think would effectively be what happens if we use the same builtin application mechanism for typed and untyped terms), I think you should be able to prove that there's some kind of (very strong) bisimulation between evaluation of a term in the typed world and the evaluation of its erasure in the untyped world. 

 A disadvantage of this approach is that the semantics of untyped reduction are only defined for erased typed terms, and there are large numbers of untyped terms whose semantics are completely undefined.  I think this probably means that if a validator is going to be evaluated on-chain, anyone who's interested will need to have access to the typed version of the validator to make sure that it erases to the correct thing: you don't want things with undefined semantics being evaluated on the chain, especially if your evaluator is written in an unsafe language.  Maybe this is covered by an as-yet-unresolved problem that we have, namely how to ensure that a PLC validator was obtained from a particular Haskell source version. 

 Given Roman's ongoing work on builtins, it looks as if we have to be a bit more precise about what builtins can actually do (they probably have to be parametrically polymorphic, for example), so maybe firming that up will help with this issue. Do we want to have run-time type tags for builtin types?  Maybe that would enable us to give semantics to every term in the untyped world (which would then perhaps not be so untyped after all).

**Comment by michaelpj** [comment]
> Now this is OK with the present implementation because we're secretly using typed Haskell to evaluate these things and we'll presumably get a type error here (I'm assuming we'll be using the same evaluation mechanism (or a very similar one) for typed and untyped PLC).

> However, I think that the Plutus Core specification shouldn't be too tightly tied to the current implementation, and ideally it shouldn't mention Haskell or rely on the implementation language being typed

I don't think it's a huge issue to say that:
- Builtins are always typed.
- Evaluation of a builtin always has a step where you try and interpret each argument as a value of the correct type in the "host language". This may fail.
    - In the typed version, it should not fail so long as you've typechecked it (but our syntax isn't intrinsically typed, so the machine always has to deal with the possibility of evaluating ill-typed ASTs!)
    - The reason this is doable is because the arguments are going to be values, and this check is basically just going to check if they're a `con` of the right type.

Is it weird to have "typed" builtins in untyped PLC? I claim not: I think even erased PLC is still typed, it's just not *statically* typed, and therefore we have just the sort of dynamic type checks that we'd expect in that situation.

> This says that the meaning of applying a builtin in the untyped world to a bunch of erased terms (on the left) is what you get by applying the same builtin to the unerased terms in the typed world and then erasing types to get back to the untyped world.

This seems a bit magical: we need to be able to "unerase" things. I think my version is simpler - it also turns erased things into typed things, but in quite a specific way.

> A disadvantage of this approach is that the semantics of untyped reduction are only defined for erased typed terms, and there are large numbers of untyped terms whose semantics are completely undefined. I think this probably means that if a validator is going to be evaluated on-chain, anyone who's interested will need to have access to the typed version of the validator to make sure that it erases to the correct thing: you don't want things with undefined semantics being evaluated on the chain, especially if your evaluator is written in an unsafe language. 

Yeah, this seems bad. I think this just means we shouldn't do that :p We could fix this by either:
- Saying that builtins reduce *if* they fit the typed builtin pattern. In this case such terms are simply stuck, not undefined.
- Using my approach. Then such terms have a perfectly good semantics: error. Which is arguably what we want.

> Do we want to have run-time type tags for builtin types?

Yes, I think we do. In constants at least. Perhaps this is our main point of disagreement: as I said above, I think we should still have a strongly typed language, just not statically typed.

**Comment by kwxm** [comment]
> 
> I don't think it's a huge issue to say that:
> 
>     * Builtins are always typed.
> 
>     * Evaluation of a builtin always has a step where you try and interpret each argument as a value of the correct type in the "host language". This may fail.
>       
>       * In the typed version, it should not fail so long as you've typechecked it (but our syntax isn't intrinsically typed, so the machine always has to deal with the possibility of evaluating ill-typed ASTs!)
>       * The reason this is doable is because the arguments are going to be values, and this check is basically just going to check if they're a `con` of the right type.

Right.  I think that needs us to start specifying things about builtins though, and that might get out of hand.  Can we merge this in its present state (after a bit of tidying up) and then fix it later (but soon)?  I don't think this issue interferes with the substance of the untyped stuff, and we might want to start implementing that some time.

> This seems a bit magical: we need to be able to "unerase" things. I think my version is simpler - it also turns erased things into typed things, but in quite a specific way.

It _looks_ as if it's doing that, but I claim it isn't really.  I'm pretty certain that we should be able to prove that if we start with a well typed term _M_ and erase it, then evaluate it in the untyped setting, after _n_ steps we'll have exactly the erasure of what you get by evaluating _M_ for _n_ steps in the typed setting, so the magical unerasure thing doesn't actually have to do anything (assuming that the builtin evaluation mechanism isn't dispatching on types or something).  I'm not proposing this as a permanent solution, just a temporary workaround until we get round to specifying how builtins work, which I think will be non-trivial.

> > Do we want to have run-time type tags for builtin types?
> 
> Yes, I think we do. In constants at least. Perhaps this is our main point of disagreement: as I said above, I think we should still have a strongly typed language, just not statically typed.

I'm not really disagreeing on that point, it just wasn't clear to me whether we were actually planning to do that, so I was trying to come up with a workaround.

**Comment by michaelpj** [comment]
> Can we merge this in its present state (after a bit of tidying up) and then fix it later (but soon)? I don't think this issue interferes with the substance of the untyped stuff, and we might want to start implementing that some time.

Yes, I don't think this is a blocker for the current stuff at all! (we're not talking about that PR, I think?)

> It looks as if it's doing that, but I claim it isn't really. I'm pretty certain that we should be able to prove that if we start with a well typed term M and erase it, then evaluate it in the untyped setting, after n steps we'll have exactly the erasure of what you get by evaluating M for n steps in the typed setting, so the magical unerasure thing doesn't actually have to do anything (assuming that the builtin evaluation mechanism isn't dispatching on types or something).

I don't quite understand this: we still end up with a bit of untyped syntax, that we (by your rule) have to turn into typed syntax in order to evaluate it.

**Comment by kwxm** [comment]
> Yes, I don't think this is a blocker for the current stuff at all! (we're not talking about that PR, I think?)

What PR?  I just mean merging the specification to get it out of the way.

> I don't quite understand this: we still end up with a bit of untyped syntax, that we (by your rule) have to turn into typed syntax in order to evaluate it.

I don't think so.  It just says that if you're evaluating a builtin on a bunch of untyped terms then you get the same result as you would if you evaluate it on corresponding typed terms, and I claim (but have no intention of proving) that for anything we get by evaluating the erasure of a well-typed term, there's a well-typed term hiding in the background.  We don't actually have to recover that, we just have to believe that the builtin evaluation mechanism treats the two things in the same way. We really do have to _believe_ that at he moment because we don't have a specification (but I implemented an untyped CK machine and it worked, so I'm moderately confident).  In the absence of a specification we have to take something somewhere on faith. I originally just said that builtin evaluation was modified in an obvious way, but you (rightly) pointed out that that was a bit dodgy and I've been trying to fix it for the last two days.   Maybe we should just go back to that and say that a detailed specification of evaluation for typed and untyped builtin evaluation will follow, but for the time being you just have to assume it does the right thing.

**Comment by kwxm** [comment]
To rephrase that, I think that _if_ you believe that the big table of semantics for builtins is a reasonable specification of the meaning of builtin evaluation in the typed world, _then_ what I've written gives you perfectly good semantics for builtin evaluation in the typed world, modulo my imaginary theorem.  It may not be a semantics that you can implement, but it is nevertheless a semantics.

**Comment by michaelpj** [comment]
> We don't actually have to recover that, we just have to believe that the builtin evaluation mechanism treats the two things in the same way.

How can it treat the two things in the same way, when one is of type `TypedAST` and one is of type `UntypedAST`? It *must* translate one into the other at some point! I think the devil is in the details here.

> It may not be a semantics that you can implement, but it is nevertheless a semantics.

Ah, I see. I am assuming we wanted to reflect what's implemented ;) I don't think it's that useful to add a semantics that we won't want in the long term - I'd rather just leave it out for now.

**Comment by effectfully** [comment]
> Do we want to have run-time type tags for builtin types? 

We unlift constants during evaluation by checking for equality the type tag of a constant with the type tag representing the expected type of the argument. The resulting type of that check is `Maybe (a :~: b)` where `a` is the actual type of the constant and `b` is the expected one. So the only way we can unlift a constant is by getting `Just Refl` from the equality check, so that `a` and `b` become the same and we can return a constant whose actual type is precisely the expected one.

I.e. we have runtime type tags for built-in types and good luck not having them without resorting to `unsafeCoerce`, regardless of whether it's typed or untyped Plutus Core.

**Comment by kwxm** [comment]
> I think the devil is in the details here.

Yes, that's the whole problem!!!  I think sorting out the details involves giving a reasonable (but abstract) specification of how builtins are supposed to be evaluated, but I don't think now's the time to do that.  I'll alter it to say something vague about RTTI for builtin types and move on.

**Comment by kwxm** [comment]
> I.e. we have runtime type tags for built-in types and good luck not having them without resorting to `unsafeCoerce`, regardless of whether it's typed or untyped Plutus Core.

Good!  I think that will solve this problem.  Once you've finalised all this stuff we can try to write down something a bit more precise.

**Comment by kwxm** [comment]
I've added a note to the specification which I hope will explain what's going on.  We should return to this when we have a proper specification of builtins.
