### ISSUE TITLE
Delay and force in typed PLC?

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1899]
Roman mentioned delay and force in a recent PR comment (can't find it now) and the issue also came up in the Plutus call on 17th March in connection with compilation of matches.  I've added explicit `delay` and `force` operations in untyped PLC to deal with the computational aspects of type abstraction and instantiation.  Should we be bold and add them to the typed version of Plutus Core as well?

**Comment by michaelpj** [comment]
The downside of doing this is that we need to type them in typed PLC, which means we need a unit type, as a really-builtin builtin or otherwise.

**Comment by kwxm** [comment]
Reallly?  Isn't the type of `(delay e)` just the same as that of `e`, and similarly for `force`? I don't see where units come into it.

**Comment by michaelpj** [comment]
Oh, interesting. Doesn't that mess with progress, or something? That would mean that `(\x. x) (delay 1)` would be well-typed but couldn't progress.

**Comment by kwxm** [comment]
Wouldn't that progress to `(delay 1)`, and then you'd eventually need to get to a `force` to progress further?  If we believe that these are OK in the untyped setting then surely they'd be OK in the typed setting as well (and once we have them in the untyped setting you might argue that it'd be a pity not to be able to use them for things that we currently use unit-based thunks for in the typed setting).

**Comment by michaelpj** [comment]
Er, sorry, more like this: `(delay (\x. x)) (con 1)`

> If we believe that these are OK in the untyped setting then surely they'd be OK in the typed setting as well

Well, in my head I'd still assumed that they were typed such that the only thing you can do with a `delay` is `force` it. Which means they can't just have the same type as the underlying expression. Maybe it should be some special type constructor like `Delayed a`.

**Comment by kwxm** [comment]
OK, I believe you now.  Doing it with thunks, the type of `e:t` turns into `unit -> t`, so we'd have to reflect that change in the type of `delay e` as well.  Maybe that adds too much complexity.  It's a slight pity to have this available in the eventual target language and not be able to make use of it in the intermediate language though.

**Comment by michaelpj** [comment]
Yeah, it would be nice to be able to use it in PLC proper, but not a huge deal.

**Comment by kwxm** [comment]
OK, let's keep it in mind then.  I'll keep this issue open for the rest of the day in case anyone else has any comments, then close it tomorrow.

**Comment by kwxm** [comment]
Let's close this.  It looks as if having to modify the type system would make things a bit too complicated.  We could keep it in mind in case we ever need to shrink script sizes a bit.
