### ISSUE TITLE
Can we change the syntax for built-in constants in Plutus Core?

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1936]
The Plutus Core syntax currently requires you to say `(con integer)` to denote a type and `(con 12345)` to denote a constant.  From the point of view of parsing, this has been OK up until now because no literal constant looked like a type name, so you could tell from what follows whether you've got a type or a constant.  However, with the advent of extensible builtins this becomes problematic. Suppose we have a constant called `nil`: does `(con nil)` represent a constant or a type?

I'd like to suggest that we write `(con integer 12345)`, `(con  bytestring #fc32)` and so on.  This has several advantages.  

* It removes the ambiguity.
* Literal constants are currently dealt with in the lexer, so you have to change that every time you add a new type of constant. This would allow us to parse constants in the parser instead (see below).
* Another problem is that when you parse constants in the lexer you have to decide right then what the type of the constant is, and that makes it hard to re-use concrete syntax for different types (integer and short for example).
* If we tell it what the type is then when we see `(con sometype ...)` we can just save the `...` in a string and then extract the value using an appropriate function in the parser rather than in the lexer. (Some care might be required if your constant can contain a right parenthesis, as in `()`).  Since you know what type you're expecting it's OK for different types to use the same syntax.
* I think we could eventually pass small applicative constant-parsers into the main parser to deal with parsing of new extensible types, without requiring the implementer of the type to alter the lexer or parser.

**Comment by kwxm** [comment]
I'd also quite like to change the syntax for types at the same time.  `(con integer)` makes sense if you're regarding builtin types as constants in the type-level calculus, but `integer` isn't what people would normally think of as a constant. The obvious thing to write would be `(type integer)`.  That might require a little care in the lexer because we use `(type)` for the base kind, but I don't think that's a major problem.

**Comment by michaelpj** [comment]
> I'd like to suggest that we write (con integer 12345), (con bytestring #fc32) and so on. This has several advantages.

I think `(con <type tag> <type-specific-format>)` is good. Using the name of the builtin type as the tag also seems reasonable.

> I'd also quite like to change the syntax for types at the same time. (con integer) makes sense if you're regarding builtin types as constants in the type-level calculus, but integer isn't what people would normally think of as a constant. The obvious thing to write would be (type integer).

What about `(builtin integer)`?
- It's a builtin type, so this mirrors builtin functions.
- We say "builtin type" and "builtin function" a lot, so it's not as confusing as "type constant"
- It doesn't use `type`.
- Constants remain special, but they *are* a bit special, so I think that's okay.

**Comment by kwxm** [comment]
> What about `(builtin integer)`?

The syntax already allows builtin applications with no arguments or type arguments, so that would clash.  (I think that's maybe because we allow builtins which have type arguments but no term arguments and ones which have term arguments but no type arguments, and it might be a bit tricky to exclude both. @effectfully  said something about this a while ago). I think it's OK to have a clash though: you can make the lexer context-sensitive enough to know when it's expecting a type.

**Comment by michaelpj** [comment]
> I think it's OK to have a clash though: you can make the lexer context-sensitive enough to know when it's expecting a type.

Quite: we already handle this clash between `(con integer)` and `(con 1)`.

**Comment by kwxm** [comment]
> Quite: we already handle this clash between `(con integer)` and `(con 1)`.

Ah, but that's easy because the lexer has a special pattern for integer constants, so it can tell that one's a type and one's a value without worrying about the surrounding context.  It's less easy (but still possible) to tell the difference between `(con bool)` and `(con true)`.  Things will be simpler with type tags.

**Comment by effectfully** [comment]
> I'd like to suggest that we write (con integer 12345), (con bytestring #fc32) and so on. 

I definitely support that.

> I think we could eventually pass small applicative constant-parsers into the main parser to deal with parsing of new extensible types, without requiring the implementer of the type to alter the lexer or parser.

I think it'll be just a matter of having a ``uni `Everywhere` Parse`` constraint where `Parse` is a type class encapsulating parsing of values of a type.

> `(type integer)`
> `(builtin integer)`

I'm a weirdo, so I like `(meta integer)`. `type` doesn't look sufficiently meta-y and `builtin` looks term-level-y to me for some reason. `(meta integer)` reads very well.

> (I think that's maybe because we allow builtins which have type arguments but no term arguments and ones which have term arguments but no type arguments, and it might be a bit tricky to exclude both. @effectfully said something about this a while ago)

I've tried dealing with `nil : all a. list a` and failed. There was something wrong with the CEK machine. We probably should just forbid built-in functions that do not receive any term-level arguments.

>  It's less easy (but still possible) to tell the difference between `(con bool)` and `(con true)`.

Only for correct programs. If the input is not correct, then anything can appear anywhere and it would be nice to distinguish between the type and term levels just to report a better error (but that train has already left the station).

**Comment by kwxm** [comment]
Closed in favour of SCP-429.
