### ISSUE TITLE
Add an option to prettyprint PLC without indentation

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#1949]
If you print a large PLC program the output can be massive (many gigabytes) because of leading spaces.  I find that if I print out out applied validators I get lines with 700 or more spaces at the front, and 97% of the output consists of space characters, and I have to feed them through `sed` to make them manageable.  It would be convenient if we could optionally not have the leading spaces.

**Comment by michaelpj** [comment]
It would be pretty unreadable without indentation too, but I guess maybe it's still better?

**Comment by kwxm** [comment]
Part of the reason for this is that @jmchapman wanted some big PLC programs to test his Agda stuff a while ago, and the stuff I was getting was far too big in its raw form. CBOR's probably a better way to pass programs around.

**Comment by effectfully** [comment]
> It would be pretty unreadable without indentation too, but I guess maybe it's still better?

Are you suggesting that with the indentation it is not pretty unreadable? :)

**Comment by kwxm** [comment]
Closed in favour of SCP-429.
