### ISSUE TITLE
'Found invalid marker' being thrown in GHCi

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [input-output-hk/plutus#1956]
I've created a minimum reproducible example of this error [here](https://github.com/FinleyMcIlwaine/plutus-repl-issue).

On NixOS with GHC 8.8.2.

Running `cabal v2-repl` in that project causes this error:
```
$ cabal v2-repl
...
GHC Core to PLC plugin: Found invalid marker, not applied correctly
  plc
> 
```
While `cabal v2-build` compiles things successfully.

This error did not occur before the [commit updating to GHC 8.8](https://github.com/input-output-hk/plutus/commit/bb965c748f13f83cab956ad58cfc27c0e6da1ea5). I did some testing and found that the error did show up as a result of the changes introduced in that commit.

After examining [Language.PlutusTx.Plugin](https://github.com/input-output-hk/plutus/blob/master/plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs), this appears to be the result of the changes that were made [here](https://github.com/input-output-hk/plutus/blob/d7607bfc8d560db2de591ade3fdf84b85ce14e5a/plutus-tx-plugin/src/Language/PlutusTx/Plugin.hs#L220), though that is just my hunch! I am not nearly familiar enough with GHC to be confident in that hunch.

Happy to provide any other information if necessary!

**Comment by j-mueller** [comment]
Can you try adding the following to your cabal file 

```
ghc-options: -fobject-code -fno-ignore-interface-pragmas -fno-omit-interface-pragmas
```

(I didn't try this but that's what the README says: https://github.com/input-output-hk/plutus/blob/master/plutus-tx/README.md)

**Comment by michaelpj** [comment]
Yeah, although that's not normally the way it fails, but I'd be interested to see if it's changed.

**Comment by FinleyMcIlwaine** [comment]
Yep, those flags fixed it! Thank you! Interesting that this popped up only after updating GHC.
