### ISSUE TITLE
Try using haskell.nix's support for static builds for the Marlowe lambda

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#1960]
`haskell.nix` has [some support](https://github.com/input-output-hk/haskell.nix/blob/master/builder/comp-builder.nix#L98) for building executables statically. Perhaps with the right setup we could just add an executable component to `marlowe-symbolic`, build it statically with maybe some extra `optL` flags, and it might work.

This would be a bit simpler than our current dance with a manual `ghc` invocation.

**Comment by shmish111** [comment]
Created https://jira.iohk.io/browse/SCP-288

**Comment by michaelpj** [comment]
No need to duplicate, then. I'll close this (the text is still here for reference.)
