### ISSUE TITLE
Fix sample plc file in `language-plutus-core/bench`

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#2029]
`stack bench language-plutus-core` fails because one of the benchmarks (`type-check`) involves deserialising the CBOR file `script.plci`, which was created using an old version of the serialisation code.  It's not clear what the source of this file was, so it's not easy to re-create it.  We should put a PLC source file in here together with the serialised version in order to make it easier to update the benchmarks.  I have no idea where the CBOR file came from, so we should use something different, probably a validator from one of the sample contracts.  (I noticed this a while ago then forgot all about it).

**Comment by michaelpj** [comment]
It also doesn't seem like we should need to start with a checked-in serialized file either. TBH, those benchmarks could probably do with a do-over.

**Comment by reactormonk** [comment]
TBH, pick any PLC code. They haven't been picked for any specific reason, I mostly took a bit of PLC code I found somewhere and ran it through the CeK to check if everything looks ok and to track changes of the cost model.
