### ISSUE TITLE
Remove the need for `IterationID` in `Resumable`

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#2055]
* When we have a resumable program such as `(ask "A" >> ask "B") `select` (ask "C")` and provide it with an answer for `"A"` only, we want to avoid it evaluating the `ask "C"` branch and only proceed with `ask "B"`
* This is achieved by the `IterationID` type, which is a counter that increases every time we descend into the tree. After the evaluation of the program has finished we delete all requests that have an `IterationID` lower than the maximum iteration ID that was recorded. So in the example above, we would delete the request for `ask "C"` before returning the list of requests, so the environment (user) would never think to respond to the request `ask "C"`.
* However, it would be much better if the request for `ask "C"` was never added to the list of requests in the first place. When we have an answer for `ask "A"` we should not evaluate the `ask "C"` branch at all, instead of evaluating it and then deleting its request right away.
* It seems like this should be achievable with the right combination of `msplit` and `replyC` although I haven't been able to figure out what that combination is.

**Comment by michaelpj** [comment]
I'm going to move this to JIRA I think.

**Comment by michaelpj** [comment]
https://jira.iohk.io/browse/SCP-710
