### ISSUE TITLE
Create dynamic SlotRange

### ISSUE THREAD

**Issue by jordanjoewatson** [input-output-hk/plutus#2068]
When trying to write smart contracts I can't create dynamic slot ranges.

e.g. if i want to create a Time To Live field for a contract so it executes if something hasn't happened in the last 10 slots from the current time

    W.intervalFrom (currentSlot - campaignTTL cmp)

**Comment by michaelpj** [comment]
That's deliberate. Scripts don't get access to the current slot because that would make execution (and hence costs) non-deterministic, which makes life a lot harder.

**Comment by michaelpj** [comment]
You can get the current slot in the *off-chain* code, however, and use that.
