### ISSUE TITLE
The addition of plotly breaks `nix-shell` on macOS.

### ISSUE THREAD

**Issue by raduom** [input-output-hk/plutus#2157]
The addition of plotly breaks `nix-shell` on macOS.

There seems to be a problem with `iconv`. The linker does not find the library when building R (r-hexbin). Here is a log file: [nix-shell.log](https://github.com/input-output-hk/plutus/files/4911391/nix-shell.log)

Quick fix: remove plotly from `shell.nix`.

Upgrading to R-4.0.0 may fix everything on MacOs.
I have tried using this [fix](https://github.com/NixOS/nixpkgs/pull/36179/files), but it failed to work.

**Comment by michaelpj** [comment]
Proposed workaround: just only add it to the shell if the platform is linux, so it works for Simon at least. Include an note that it'll be fixed when we upgrade to 20.09 if we still care.
