### ISSUE TITLE
Modelling contracts in Marlowe section on home playground has bad punctuation and other issues

### ISSUE THREAD

**Issue by greggdourgarian** [input-output-hk/plutus#2340]
1.   Comma in wrong place 2.  No period at end of last sentence 3.  Not sure why this paragraph is there...it doesn't offer much help and clutters the screen and a link to the well written documentation pages would be better

Marlowe is designed to support the execution of financial contracts on blockchain, and specifically to work on Cardano. Contracts are built by putting together a small number of constructs that in combination can be used to describe many different kinds of financial contract

**Comment by james-iohk** [comment]
Hi @greggdourgarian, thanks for this report and sorry for the delay in getting back to you. I can see that this doc file has since been updated (see 2368a8cde7). You may check again for it's correctness and if there are any improvements you'd like to propose feel free to create a PR.
