### ISSUE TITLE
Errors when building Plutus project

### ISSUE THREAD

**Issue by klemzy** [input-output-hk/plutus#2471]
Hi,

I have been trying to build the plutus project on my machine, however there were some errors during compilation. 

OS: **OS X Big Sur 11.0.1**
GHC: **8.10.1 (I have also tried with 8.10.2 and 8.6.5)**
Cabal: **3.2.0.0**
Nix: **2.3.8**

I tried building with nix and cabal and on both i received different errors. I have installed the command line tools as well, not sure why nix is reporting that it can't find the command. It works if I run the command line tools in my CLI.

nix build command: **nix build -f default.nix --show-trace**
cabal build command: **cabal v2-build all**

I have also attached the error messages.

[cabal-build-error.txt](https://github.com/input-output-hk/plutus/files/5544826/cabal-build-error.txt)
[nix-build-error.txt](https://github.com/input-output-hk/plutus/files/5544827/nix-build-error.txt)

Thanks for your help!

**Comment by michaelpj** [comment]
You're building GHC, which suggests you haven't followed the instructions about setting up the binary cache (marked IMPORTANT).

**Comment by klemzy** [comment]
Thanks! You were right. I added nix.conf and managed to make some progress. When trying the following command **nix build -f default.nix --show-trace** i still got:

_warning: unable to download 'https://iohk.cachix.org/ihch6kp0apxkqfyxia71zbgjm44pwmpr.narinfo': HTTP error 524; retrying in 319 ms
warning: unable to download 'https://iohk.cachix.org/ihch6kp0apxkqfyxia71zbgjm44pwmpr.narinfo': HTTP error 524; retrying in 614 ms
trace: Using index-state: 2020-11-10T00:00:00Z for Agda
trace: To materialize the output entirely, pass a writable path as the `materialized` argument and pass that path to /nix/store/hx0hliqr3pbih4kzz4przj688glnvw6p-generateMaterialized
warning: unable to download 'https://iohk.cachix.org/c2dzvw2mqvzzldq2bggz4ixbnpnygdck.narinfo': HTTP error 524; retrying in 303 ms
warning: unable to download 'https://iohk.cachix.org/35mgsrhh8lmdrxkxb6x1s6xhaxby1gy9.narinfo': HTTP error 524; retrying in 328 ms
warning: unable to download 'https://iohk.cachix.org/1vl9n166v4bpnf4c7ali43hs0bbn5dcm.narinfo': HTTP error 524; retrying in 300 ms
warning: dumping very large path (> 256 MiB); this may run out of memory
trace: Using index-state: 2020-11-10T00:00:00Z for stylish-haskell
trace: To materialize the output entirely, pass a writable path as the `materialized` argument and pass that path to /nix/store/ym3qb7z3ahl9in2dc2h6h7a0wnmr4dg3-generateMaterialized
[15 built, 2494 copied (9484.5 MiB), 1063.7 MiB DL]
error: a 'x86_64-linux' with features {} is required to build '/nix/store/0yq23vxqqywmvbh10gyk18z67wyrv2nh-app.hs.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}_

However with **nix build -f default.nix docs** the command succeeded.

**Comment by michaelpj** [comment]
The error message is telling you that you've asked to build something in `default.nix` that can't be built on a Mac, but only on Linux. This is true - you won't be able to build everything. But you probably want to build specific things anyway.

**Comment by klemzy** [comment]
Got it. Thanks! For now I have everything I need.
