### ISSUE TITLE
Cannot build Agda derivation

### ISSUE THREAD

**Issue by eed551** [input-output-hk/plutus#2583]
Launching 
> nix build -f default.nix plutus.haskell.packages.plutus-core
I get
>> (...)
 [296 of 369] Compiling Agda.TypeChecking.Unquote ( src/full/Agda/TypeChecking/Unquote.hs, dist/build/Agda/TypeChecking/Unquote.o, dist/build/Agda/TypeChecking/Unquote.dyn_o )
  /nix/store/f95jkch26wxmqd076bcm976qrn7ml46i-stdenv-linux/setup: line 1303:   118 Killed                  $SETUP_HS build lib:Agda -j$(($NIX_BUILD_CORES > 4 ? 4 : $NIX_BUILD_CORES))
cannot build derivation '/nix/store/vk8ca2lfzglsgwdj8wb5cvzyar86xihb-agda.drv': 1 dependencies couldn't be built

The file '/nix/store/vk8ca2lfzglsgwdj8wb5cvzyar86xihb-agda.drv' exists indeed but I have no idea why I get this issue.

**Comment by michaelpj** [comment]
We're not supporting other uses of the repo at the moment.
