### ISSUE TITLE
Invalid Option -b When Trying To `docker run` Plutus Playground

### ISSUE THREAD

**Issue by robkorn** [input-output-hk/plutus#2606]
In the `master` branch when following the instructions to run a local plutus playground in a docker container, the following error occurs:
```
> docker run --mount 'type=bind,source=/tmp,target=/tmp' -p 8080:8080 plutus-playgrounds:i7q4njjcbgn7h1b4ykbsyi9l08mcpbxi
Invalid option -b
```
I took a quick look and it appears that in the `docker.nix` file the `-b` flag is used, but apparently is deprecated or currently does not exist?

**Comment by j-mueller** [comment]
The docker image for the Playground hasn't been updated in a while. If you want to run the Playground locally try following the instructions in the READMEs for `plutus-playground-client` and `plutus-playground-server`.

**Comment by divpools** [comment]
Is this issue going to be resolved anytime soon? Is there a temporary fix for this?

**Comment by michaelpj** [comment]
No, this issue is not going to be resolved, and we have removed the docker images for the playgrounds.
