### ISSUE TITLE
The /example project doesn't build

### ISSUE THREAD

**Issue by jaccokrijnen** [input-output-hk/plutus#2636]
Following the README, I get 

```
cabal: Could not resolve dependencies:
[__0] trying: example-0.1.0.0 (user goal)
[__1] unknown package: plutus-core (dependency of example)
[__1] fail (backjumping, conflict set: example, plutus-core)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: example, plutus-core
```

At some point `language-plutus-core` was renamed to `plutus-core`. The `example/cabal.project` file defines some github sources, which point to an older commit of this repo `73234550dc2b2c6209975789845bb5ef6abdf6bc`, where it still has the old directory name. I have tried
- Pointing the github sources to a more recent commit of this repo, which fails on a transitive dependency. After some changes to `cabal.project` it eventually fails because `plutus-tx-plugin` depends on a newer version of ghc than 8.8.3. I had no luck updating `shell.nix` to use a newer ghc.

- Updating `example.cabal` to depend on `language-plutus-core` instead of `plutus-core`, but got some compile errors in `language-plutus-core`, probably also due to a mismatch in GHC versions/libraries

- In the end I just checked out an old commit of the whole repo and /example did build (e300450f61f7e77cf0455171dff4f41290050299)

**Comment by FinleyMcIlwaine** [comment]
@jaccokrijnen I've submitted a PR (linked above) that should fix this issue for both the `shell.nix` and VSCode devcontainer configuration for the example project. If you get the chance, feel free to test out those changes and give this another try. If it works or is broken again in some way, please leave a comment noting so on the PR. Thanks for your help!

**Comment by jaccokrijnen** [comment]
Thanks! The example builds for me now.

However, when I want to add some more dependencies, it seems `plutus-contract` and `plutus-core` are in conflict. (I'm trying to build some of the examples from https://prod.playground.plutus.iohkdev.io/ )

* `plutus-contract` requires an `aeson >= 1.5.1` to build (uses a recently added `Ord` instance of `Aeson.Types.Value`).
`plutus-core` requires `aeson < 1.5` as a transitive dependency through `monoidal-containers`.


I also had to add some other constraints for the transitive dependencies of `plutus-ledger-api` and `plutus-contract` before arriving at the above problem.

* `plutus-ledger-api` won't build because of its `base16-bytestring` dependency, for which it doesn't have any version bounds and `< 1.0` is required (breaking changes since 1.0.0.0).

* `plutus-contract` requires `row-types < 1.0` , `aeson >= 1.5.2`

**Comment by michaelpj** [comment]
Probably it will only solve in combination with our pinned index-state in `cabal.project`. You probably want to pin it to the same as we do.

**Comment by michaelpj** [comment]
Or possibly this is to do with the fact that we all use the package set generated by stack. Possibly I need to just revisit that...

**Comment by jaccokrijnen** [comment]
Should I open a different issue for the problem in my last comment? That is, I cannot depend on both `plutus-core` and `plutus-contract` at the same time (even when setting the `index-state` to what is being used in the top-level directory of this repo).

**Comment by michaelpj** [comment]
We have a bunch of `allow-newer` constraints in `cabal.project`. You probably need all of those too. We should get rid of those, but until we do the solver won't be happy.

**Comment by jaccokrijnen** [comment]
I managed to get things running by running `nix-shell` from the project root's `shell.nix`, instead of `example/shell.nix` (copying `index-state` and `allow-newer` didn't work out). I didn't look into why that worked, butthe ghc version are sligthly different: `ghc-8.10.2.20201118` vs `ghc-8.10.2`.

**Comment by tstaetter** [comment]
I get a slightly different error message in the devcontainer:

```bash
[devcontainer]$ cabal build plutus-starter-pab
Previous HEAD position was 1f20481b1 Disable the plutus-playground-server tests (#4085)
HEAD is now at 9f6c71101 SCP-3031 (#4211)
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.RemoteRepo {remoteRepoName = RepoName
"hackage.haskell.org", remoteRepoURI = http://hackage.haskell.org/,
remoteRepoSecure = Just True, remoteRepoRootKeys =
["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}
Warning: Requested index-state 2021-08-14T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state ().
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: plutus-core-0.1.0.0 (user goal)
[__1] unknown package: plutus-core:happy:exe.happy (dependency of plutus-core)
[__1] fail (backjumping, conflict set: plutus-core,
plutus-core:happy:exe.happy)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: plutus-core,
plutus-core:happy:exe.happy
```

any ideas what's causing it? I tried several fixes, nothing works out :/
