### ISSUE TITLE
Fault OR my human errors

### ISSUE THREAD

**Issue by Camash1** [input-output-hk/plutus#2649]
This is the message which appears:

If you have anyway of helping, please reach out kindly.

An unexpected error has occurred, please raise a support issue at https://github.com/input-output-hk/plutus/issues/new: (ContractParseError { column: 285, message: "Syntax error at line 1 col 285:\n\n When [(Case (Notify (ChoseSomething (ChoiceId \"Support\" (Role \"Cam\")))) (When [(Case (Deposit (Role \"Cam\") (Role \"Cam\") (Token \"\" \"\") (Constant 20)) (Pay (Role \"Cam\") (Party (Role \"Cam\")) (Token \"\" \"\") (Constant 20) (When [(Case (Notify TrueObs) (If TrueObs (When [(Case (Deposit (PK \"EarthKin\"\n ^\nUnexpected string token: \"EarthKin\". Instead, I was expecting to see one of the following:\n\nA WS token based on:\n ws → ● %WS\n someWS$ebnf$1 → someWS$ebnf$1 ● ws\n someWS → ● someWS$ebnf$1\n party → lparen \"PK\" ● someWS base16 rparen\n action → lparen \"Deposit\" someWS ● party someWS party someWS token someWS value rparen\n case → lparen \"Case\" someWS ● action someWS contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n contract → lparen \"If\" someWS observation someWS ● contract someWS contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n contract → lparen \"Pay\" someWS party someWS payee someWS token someWS value someWS ● contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n topContract$ebnf$1 → topContract$ebnf$1 ● cases\n topContract → \"When\" someWS lsquare ● topContract$ebnf$1 rsquare someWS timeout someWS contract\n main → main$ebnf$1 ● topContract main$ebnf$2\nA NL token based on:\n ws → ● %NL\n someWS$ebnf$1 → someWS$ebnf$1 ● ws\n someWS → ● someWS$ebnf$1\n party → lparen \"PK\" ● someWS base16 rparen\n action → lparen \"Deposit\" someWS ● party someWS party someWS token someWS value rparen\n case → lparen \"Case\" someWS ● action someWS contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n contract → lparen \"If\" someWS observation someWS ● contract someWS contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n contract → lparen \"Pay\" someWS party someWS payee someWS token someWS value someWS ● contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n topContract$ebnf$1 → topContract$ebnf$1 ● cases\n topContract → \"When\" someWS lsquare ● topContract$ebnf$1 rsquare someWS timeout someWS contract\n main → main$ebnf$1 ● topContract main$ebnf$2\nA base16 token based on:\n base16 → ● %base16\n party → lparen \"PK\" someWS ● base16 rparen\n action → lparen \"Deposit\" someWS ● party someWS party someWS token someWS value rparen\n case → lparen \"Case\" someWS ● action someWS contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n contract → lparen \"If\" someWS observation someWS ● contract someWS contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n contract → lparen \"Pay\" someWS party someWS payee someWS token someWS value someWS ● contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n contract$ebnf$1 → contract$ebnf$1 ● cases\n contract → lparen \"When\" someWS lsquare ● contract$ebnf$1 rsquare someWS timeout someWS contract rparen\n case → lparen \"Case\" someWS action someWS ● contract rparen\n cases → ● case\n topContract$ebnf$1 → topContract$ebnf$1 ● cases\n topContract → \"When\" someWS lsquare ● topContract$ebnf$1 rsquare someWS timeout someWS contract\n main → main$ebnf$1 ● topContract main$ebnf$2\n", row: 1, token: "EarthKin" })

**Comment by palas** [comment]
Thank you. It looks like this is the same problem as in https://github.com/input-output-hk/plutus/issues/2604
The `PK` construct only accepts a base16 string, so replacing it with a `Role` should solve the problem, but we will look into making the error message more friendly
