### ISSUE TITLE
The new monetary policy mechanism seems contradictory in the tutorial

### ISSUE THREAD

**Issue by CawlBelisarius** [input-output-hk/plutus#2665]
The [tutorial](https://playground.plutus.iohkdev.io/tutorial/tutorials/basic-forging-policies.html) seems contradictory here - on the one hand it says

> Forging policies, like validators, receive some information from the validating node:
> 
> * The [redeemer](https://playground.plutus.iohkdev.io/tutorial/reference/glossary.html#term-redeemer), which is some script-specific data specified by the party performing the forging.
> * The [forging context](https://playground.plutus.iohkdev.io/tutorial/reference/glossary.html#term-forging-context), which contains a representation of the spending transaction, as well as the hash of the forging policy which is currently being run.

but then, in the examples below, there seems to be only the forging context provided:

```
oneAtATimePolicy :: PolicyCtx -> Bool
oneAtATimePolicy ctx =
    -- 'ownCurrencySymbol' lets us get our own hash (= currency symbol)
    -- from the context
    let ownSymbol = ownCurrencySymbol ctx
        txinfo = policyCtxTxInfo ctx
        forged = txInfoForge txinfo
    -- Here we're looking at some specific token name, which we
    -- will assume we've got from elsewhere for now.
    in valueOf forged ownSymbol tname == 1
```

the same seems to be implied by the [code](https://github.com/input-output-hk/plutus/blob/60d10d65a615aec6d41f2014a0cc6706807ad836/plutus-ledger/src/Ledger/Typed/Scripts/Validators.hs):

```
type WrappedValidatorType = Data -> Data -> Data -> ()
type WrappedMonetaryPolicyType = Data -> ()
```

It appears the way to link up arbitrary validator logic with Data and Redeemers is this:

```
forwardToValidator :: ValidatorHash -> PolicyCtx -> Bool
forwardToValidator h PolicyCtx{policyCtxTxInfo=TxInfo{txInfoInputs}} =
    let checkHash (Just (vh, _, _)) = vh == h
        checkHash _                 = False
    in any (checkHash . Validation.txInInfoWitness) txInfoInputs
```

Anyways, some clarification on that would be swell :)

**Comment by j-mueller** [comment]
The tutorial is wrong, there is no redeemer for forging policies. They really only get a single argument, the `PolicyCtx`.

**Comment by michaelpj** [comment]
Forging policies will get a redeemer in the mainnet version, we need to fix that at some point.

**Comment by j-mueller** [comment]
Thanks. Then the code is wrong, not the tutorial :)

**Comment by CawlBelisarius** [comment]
Thanks!
