### ISSUE TITLE
Error when adapting GameStateMachine example to run on the playground

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#2700]
Hello, I am trying to get the `GameStateMachine.hs` example that is available in the `plutus-use-cases` folder running on Plutus playground.
Since the original contract does not compile on the playground, I followed the [tutorial ](https://docs.cardano.org/projects/plutus/en/latest/tutorials/basic-apps.html) and I suspect that it was lacking the obligatory public interface to run on the playground:
```hs
endpoints :: Contract SplitSchema T.Text ()
``` 
As well as missing the import `import Playground.Contract`.

I have tried to define this inspired on what it is available in the "regular" Game examples, so I have added:

```hs
game :: Contract GameStateMachineSchema GameError ()
game = lock `select` guess

endpoints :: Contract GameStateMachineSchema GameError ()
endpoints = game

mkSchemaDefinitions ''GameStateMachineSchema
```

And I also changed LockArgs and GuessArgs adding  `IotsType, ToSchema, ToArgument` to `deriving anyclass`:
```hs
data LockArgs =
    LockArgs
        { lockArgsSecret :: String
        -- ^ The secret
        , lockArgsValue  :: Value
        -- ^ Value that is locked by the contract initially
        } deriving stock ( Show, Generic)
          deriving anyclass (ToJSON, FromJSON, IotsType, ToSchema, ToArgument)
```
Same for `GuessArgs`.

I have also removed the `module Language.PlutusTx.Coordination.Contracts.Game` declaration to avoid the following error upon compilation:
![imagem](https://user-images.githubusercontent.com/48067609/107076261-173c5880-67e3-11eb-987f-0636fd031340.png)

When I try to do a simulation on the playground I get the error in the file for the following inputs:
**Error**:
[error_gamestatemachine_playground.txt](https://github.com/input-output-hk/plutus/files/5934616/error_gamestatemachine_playground.txt)
**The inputs**:
![imagem](https://user-images.githubusercontent.com/48067609/107076537-78fcc280-67e3-11eb-9d29-0940a5e86c7a.png)

What am I doing incorrectly?

Thank you for your time and support.

Diagnostic info:
- I was using the:
    - [x] Plutus Playground
    - [ ] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: https://gist.github.com/LendaDeAfonselio/7edc6639712ef6aaf83093e4f1dcd78c

**Comment by LendaDeAfonselio** [comment]
Hello, 
I have noticed that this issue had activity therefore I decided to post the following update:
I have got the contract running on playground with the following results:
![imagem](https://user-images.githubusercontent.com/48067609/107659773-6c62e900-6c7f-11eb-9eb0-afe2ab7a8b03.png)
![imagem](https://user-images.githubusercontent.com/48067609/107659821-7e448c00-6c7f-11eb-8713-bd5bb2d6f324.png)

I have updated the aforementioned [gist ](https://gist.github.com/LendaDeAfonselio/7edc6639712ef6aaf83093e4f1dcd78c) to contain the updates I made to the code in case it is useful.

Thank you

**Comment by j-mueller** [comment]
The contract says that you can only make a guess if you can present a token that represents the right to make a guess. (It's a contrived example just demonstrating how to use tokens for authorisation).

After calling `lock` on wallet 1, the token is in the possession of wallet 1. That is why you have the pink bar with 1 token in the "Final Balances" chart. We need to transfer the token to wallet 2 before wallet 2 can make a guess.

We could do that by adding an endpoint for giving the token to another wallet. Here's how it could work: https://gist.github.com/j-mueller/d38fbc173d5d06f0a2c41963ca8fc275 (note the function `transferToken` and the place where it is used, as well as the changes to the schema)

Here's an action sequence that works with the new definition:
![grafik](https://user-images.githubusercontent.com/1771361/107970625-a69af600-6fb1-11eb-9ed2-2259aa24d94c.png)

**Comment by LendaDeAfonselio** [comment]
Thank you for the explanation contract, I was wondering the "role" that the token after seeing that it stayed in `Wallet#1` and with the new endpoint it makes perfect sense.

I continued to explore the possibilities of the contract and I found the following scenario:
![imagem](https://user-images.githubusercontent.com/48067609/108062090-35ab1b00-7051-11eb-88a3-3888d6bc4c21.png)
![imagem](https://user-images.githubusercontent.com/48067609/108062215-60956f00-7051-11eb-8455-4422cf7ca3c0.png)


In this scenario locking twice will make Wallets #1 and #2 lose their funds. Therefore I checked the state before running
` _ <- mapError (review _GameSMError) $ SM.runInitialise client (Initialised sym "guess" secret) lockArgsValue` in the lock endpoint and only run `SM.runInitialise` and the following operations if `Nothing` is returned.
Is this the best way to approach this type of situation or are there better built-in options built into Plutus that allow `SM.runInitialise` only and only if the state has not been initialized? 

Thank you once again and sorry if this question is out of the scope of this github issue.

**Comment by j-mueller** [comment]
The key is in the error message `ChooserError: Found 2 outputs, expected 1`. There are two instances of the state machine and the client doesn't know which one to use. We plan to address this with thread tokens that uniquely identify state machine instances.

Making sure that there is at most one instance of the game running is a solution. Note that you can use `Language.Plutus.Contract.StateMachine.getOnChainState` to check if an instance exists.

If you do want to have several instances running at the same time you could work around the issue by making sure the two instances have to different addresses. This could be achieved by including a nonce in the script that will result in the script having a different hash.

> Why do the errors on the playground have to be "generic"? For this particular case, why is GameError invalid?

I don't think there's a technical reason for it, just the way it is implemented in the playground interpreter. It's also on our list of things to fix :)
