### ISSUE TITLE
Plutus Playground - Executing the hello world, don't show the right log

### ISSUE THREAD

**Issue by Katekko** [input-output-hk/plutus#2722]
Link: https://gist.github.com/Katekko/7d48f76bfb31124f3066350033f094ba

Just trying to execute the hello world example and seems not to work.

![image](https://user-images.githubusercontent.com/13632735/107702143-94127b00-6c98-11eb-9295-8c15997fb5f8.png)

![image](https://user-images.githubusercontent.com/13632735/107702104-8a891300-6c98-11eb-9a49-35998ffefe21.png)

![image](https://user-images.githubusercontent.com/13632735/107702076-81984180-6c98-11eb-8659-a343ec19fd56.png)

**Comment by Katekko** [comment]
The problem was the tutorial don't show the right image for config your simulator, is missing the action that you need to wait the bloc completes, without it you will not see the slot 2.

With this PR approved, the mistake will not occurs anymore.
https://github.com/input-output-hk/plutus/pull/2727

**Comment by j-mueller** [comment]
Yeah the image was wrong, the simulation for the "Hello, world" app is correct and contains the wait action. Thanks for fixing it.
