### ISSUE TITLE
 Possible mistake in Writing a basic Plutus app in the Plutus Playground tutorial - Endpoint section 

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#2742]
Hello,

In the section `Deplying the app on the Playground` of the tutorial named `Writing a basic Plutus app in the Plutus Playground` there is repeated code on the part that explains the endpoints:
![imagem](https://user-images.githubusercontent.com/48067609/108199052-5d16ec00-7114-11eb-9331-b4c372e8037d.png)
I believe that the second snippet of code is should be the definition of `endpoints` and therefore should be:
```hs
endpoints = (lock >>= lockFunds . mkSplitData) `select` (unlock >>= unlockFunds . mkSplitData)
```
As it is in the [cardano docs tutorial](https://docs.cardano.org/projects/plutus/en/latest/tutorials/basic-apps.html#deploying-the-app-on-the-playground)

I have seen this exact problem being pointed [in the forum](https://forum.cardano.org/t/possible-mistake-in-writing-a-basic-plutus-app-in-the-plutus-playground-tutorial-endpoint-section/46013) but since no one acknowledged it I decided to also post it here.

Thank you for your time and comprehension.

Diagnostic info:
- I was using the:
    - [x] Plutus Playground
    - [ ] Marlowe Playground
- Link to gist with saved setup that reproduces the issue:

**Comment by j-mueller** [comment]
Yes that was a bug in the docs which is fixed on master (where the documentation on docs.cardano.org comes from).
