### ISSUE TITLE
 /examples project does not build 

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#2764]
Hello I was trying to run plutus locally in order to be able to develop smart contracts that use libraries that I cannot use in the plutus playground.

I have:

1. Installed Nix (2.3.10)
2. Setup the IOHK binary cache
3. Used nix-shell in the root directory

I am able to build plutus-core from the root using: `$nix build -f default.nix plutus.haskell.packages.plutus-core` and docs.site using `$nix build -f default.nix docs.site`

After doing the steps mentioned above, I followed the steps in the example folder to build the project.

Developing with nix I have the following error:

```bash
cabal: Error parsing project file /home/afonso/plutus/example/cabal.project:9:
"<eitherParsec>" (line 1, column 13):
unexpected 'p'
expecting space or end of input
```

Developing with Docker and VSCode I get:
```bash
HEAD is now at 9435a76 Merge pull request #72 from input-output-hk/erikd/fix-warnings
HEAD is now at fa3a9b1c3 SCP-1589 - Static analysis for finding which Close constructs return money (#2641)
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: playground-common-0.1.0.0 (user goal)
[__1] unknown package: iots-export (dependency of playground-common)
[__1] fail (backjumping, conflict set: iots-export, playground-common)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: playground-common, iots-export
```

This is a repetition of something I have posted on the [cardano forum](https://forum.cardano.org/t/examples-project-does-not-build/46397) and I got informed that my best chance at getting answers for this problem was by opening an issue.
At least one other person is also running into this problem.

Does anybody know what I can be doing wrong?
Thank you in advance!

**Comment by j-mueller** [comment]
Looks like the `iots-export` packages was missing from the example `cabal.project`. Then I can build it in a `nix-shell` .
