### ISSUE TITLE
Change unstableMakeIsData to PlutusTx.makeIsData ''SplitData

### ISSUE THREAD

**Issue by ysha123** [input-output-hk/plutus#2772]
Diagnostic info:
- I was using the:
    - [ ] Plutus Playground and following the tutorial here: https://docs.cardano.org/projects/plutus/en/latest/tutorials/basic-apps.html
- Link to gist with saved setup that reproduces the issue: https://docs.cardano.org/projects/plutus/en/latest/tutorials/basic-apps.html

In this tutorial, you show the following lines of code:

```
PlutusTx.unstableMakeIsData ''SplitData
PlutusTx.makeLift ''SplitData

```
Using this one receives a 
`
error:
Not in scope: ‘PlutusTx.unstableMakeIsData’
Module ‘Language.PlutusTx’ does not export ‘unstableMakeIsData’.
|
26 | PlutusTx.unstableMakeIsData ''SplitData
`
If changing it to `PlutusTx.makeIsData ''SplitData` the code works fine. I think this should be fixed. I am not an expert but seems that unstableMakeIsData is not part of the PlutusTX package anymore.

Thanks!

**Comment by michaelpj** [comment]
The playground and the docs are out of sync, I think. This is a risk of deploying the docs from master as we are...

**Comment by tjmcewan** [comment]
So this is also the reason behind the imports failing?

Docs say this:
```
import           Plutus.Contract
import qualified PlutusTx               as PlutusTx
import           PlutusTx.Prelude
```

I needed to change to this:
```
import           Language.Plutus.Contract
import qualified Language.PlutusTx               as PlutusTx
import           Language.PlutusTx.Prelude
```

**Comment by james-iohk** [comment]
@ysha123 Fyi, these documents have now been moved to https://docs.cardano.org/projects/plutus/en/latest/plutus/tutorials/basic-apps.html. Using 476409eae I have confirmed that this basic app example does now compile using `PlutusTx.unstableMakieIsData`.

@tjmcewan Using 476409eae I have confirmed it is possible to import the way the docs define it (not with `Language.`).

Please give it another go with a more recent version and raise a new issue using one of our updated templates if you have any further issues. Thanks.
