### ISSUE TITLE
Docs site fails to search

### ISSUE THREAD

**Issue by anooprh** [input-output-hk/plutus#2790]
Diagnostic info:
- I was using the:
    - [ ] Plutus Playground
    - [ ] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: 

This is an issue w.r.t docs. I'm trying to find the definition and specs of `logInfo` in https://playground.plutus.iohkdev.io/tutorial/haddock/index.html by going to the quick jump, but the docs site fails to load it with an error message `Failed to load file 'doc-index.json' containing definitions in this package.`

I'm using brave browser Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (64-bit) on windows. 

Attaching Screenshot

![image](https://user-images.githubusercontent.com/2604518/109306325-08d2e100-7865-11eb-901b-cee133c2d378.png)

**Comment by j-mueller** [comment]
Thans. We won't be able to look into this right away, but we plan on fixing this before the Goguen release.

**Comment by james-iohk** [comment]
@anooprh Thanks for raising this. We've fixed this issue and it is now deployed in our staging environment [see here](https://staging.plutus.iohkdev.io/doc/haddock/index.html). It will be deployed into the production environment in due course.
