### ISSUE TITLE
"Expected a response from Github with an authorization code. Didn't get one!"

### ISSUE THREAD

**Issue by jamiepratt** [input-output-hk/plutus#2792]
Diagnostic info:
- I was using the:
    - [*] Plutus Playground
    - [ ] Marlowe Playground

After pressing the button for GitHub login and approving on GitHub I get this message:

"Expected a response from Github with an authorization code. Didn't get one!"

at:

https://playground.plutus.iohkdev.io/api/oauth/github/callback

**Comment by j-mueller** [comment]
This is a known issue with the github auth flow. It doesn't affect the login though - If you reload the playground after this, loading and saving gists should work.

**Comment by jamiepratt** [comment]
Thanks. Yes, that works. Should you work around this known issue with GitHub or are they going to fix it??

**Comment by j-mueller** [comment]
As far as I can tell it's an issue with _our implementation of_ the github workflow. So it's on us to fix it.

**Comment by james-iohk** [comment]
I have raised an issue internally as low priority.

**Comment by luigy** [comment]
https://playground.plutus.iohkdev.io those messages shouldn't be reached anymore know that deployment has been updated.

The issue was that after login it was redirecting to a page that previously wasn't being handled properly. Please reopen if you're still seeing issues
