### ISSUE TITLE
Sudden error in Marlowe "blockly"; couldn't view project as Marlowe, can't send to simulator, or save the project

### ISSUE THREAD

**Issue by DomenicGolez** [input-output-hk/plutus#2794]
Diagnostic info:
- I was using the:
    - [ ] Plutus Playground
    - [x] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: 

An error just showed up while I was trying the Scratch-like UI for Marlowe. I have no idea when exactly this happened, but I can't send this project to the simulator or view the process as Marlowe:

> An unexpected error has occurred, please raise a support issue at https://github.com/input-output-hk/plutus/issues/new: { error: Could not match character '"', pos: 11 }

![image](https://user-images.githubusercontent.com/76480066/109393925-57fd3c80-795f-11eb-8fc2-552d1e103a5f.png)

I also couldn't save the project:

![image](https://user-images.githubusercontent.com/76480066/109394078-1325d580-7960-11eb-9059-4de9546683c3.png)

**Comment by palas** [comment]
Sorry, I have tried copying the blocks as shown in the snapshot and I couldn't reproduce any of the errors. It may have been solved already
