### ISSUE TITLE
CSS Footer Bug on iPad

### ISSUE THREAD

**Issue by krishanik** [input-output-hk/plutus#2842]
[x] Plutus Playground

Plutus Playground > Simulation tab: Footer bugs into the middle of the page on iPad:
![image](https://user-images.githubusercontent.com/4742570/110667714-d44b1780-81ca-11eb-81b3-2297b921be02.png)
This feels like an flexbox issue.

Would be happy to fix when #2857 is resolved

**Comment by james-iohk** [comment]
Hi @krishanik, thanks for reporting this. I am not able to recreate this using dev tools (I do not own an iPad). Are you still experiencing this? If yes, are you willing to propose a fix seeing as #2857 is now unblocked?

**Comment by james-iohk** [comment]
I'm closing this issue but feel free to reopen if bug is reproducible.
