### ISSUE TITLE
npm run start -> plutus-playground-generate-purs: not found

### ISSUE THREAD

**Issue by krishanik** [input-output-hk/plutus#2857]
Ubuntu 20.04.1 LTS
npm 6.13.4
node v12.16.0
```
$ cd plutus-playground-client && npm run start
sh: 1: plutus-playground-generate-purs: not found
```

**Comment by krishanik** [comment]
as stated in plutus-playground-client README.md

> Note: The workflow described here relies heavily on Nix. This means you should either be working inside a nix-shell environment or use tools such as lorri or nix-direnv or similar to provide a suitable environment.

my solution is running `npm run start` inside nix-shell

**Comment by Dentro2000** [comment]
Hi, I have same result running command inside nix-shell. Can anybody help? 

macOS Monterey 12.2.1 M1 chip
npm 8.11.0
node v18.3.0

`[nix-shell:~/Documents/Repo/plutus-apps/plutus-playground-client]$  npm start

> plutus-playground-client@1.0.0 start
> plutus-playground-generate-purs && npm install && npm run install:spago && npm run build:webpack:dev

sh: line 1: plutus-playground-generate-purs: command not found

[nix-shell:~/Documents/Repo/plutus-apps/plutus-playground-client]$ `
