### ISSUE TITLE
nix build failed

### ISSUE THREAD

**Issue by krishanik** [input-output-hk/plutus#2859]
Ubuntu 20.04.1 LTS
nix (Nix) 2.3.3

```
git clone git@github.com:input-output-hk/plutus.git
cd plutus
nix build
```

```
trace: To materialize project.plan-nix for Agda entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To materialize project.plan-nix for stylish-haskell entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
builder for '/nix/store/1ijf5h1jxviwxjmgwxhz9hagh2rc8rq2-shellcheck.drv' failed with exit code 2; last 10 log lines:
  rm -rf "$dot_node_gyp"
  
  For more information:
    https://www.shellcheck.net/wiki/SC1007 -- Remove space after = if trying to...
    https://www.shellcheck.net/wiki/SC2034 -- mygid appears unused. Verify use ...
    https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  ./plutus-playground-client/node_modules/node-gyp/test/docker.sh [ FAILED ]
  ./plutus-playground-client/node_modules/constants-browserify/build.sh [ PASSED ]
  ./plutus-playground-client/node_modules/buffer/bin/update-authors.sh [ PASSED ]
  Total Failed Files: 2
[1 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/1ijf5h1jxviwxjmgwxhz9hagh2rc8rq2-shellcheck.drv', '/nix/store/g8w6f2q8iykpcgrzjb32rppdplv3rcwn-terraform-fmt.drv', '/nix/store/pnnc2mry7y2mmkxsa7r2mrvz9msyikwc-stylish-check.drv' failed
```

**Comment by Alebat** [comment]
I have a similar problem on WSL with:
Ubuntu 20.04.1 LTS
nix (Nix) 2.3.10 - (installed with `sudo mkdir -m 0755 /nix && chown $USER /nix` `sh <(curl -L https://nixos.org/nix/install)`)
`git clone git@github.com:input-output-hk/plutus.git
cd plutus
nix build`
`[...]
building '/nix/store/723jb4vqyr1z5pwq6c2qzf1rlavh7cr1-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0.drv'...
builder for '/nix/store/723jb4vqyr1z5pwq6c2qzf1rlavh7cr1-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0.drv' failed with exit code 1; last 10 log lines:
  configuring
  Configure flags:
  --prefix=/nix/store/r0808lp65a8a6xwk8s43zxhqx3bs94dy-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0 lib:prettyprinter-configurable --package-db=clear --package-db=/nix/store/yl70gamg8n0x69vkycsqf9g93wcaj7zb-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0-config/lib/ghc-8.10.4.20210212/package.conf.d --exact-configuration --dependency=prettyprinter=prettyprinter-1.7.0-9YjuSqasuU58xkNfFeECaA --dependency=microlens=microlens-0.4.12.0-LWmCgM3D0eIxbRgAEzd8k --dependency=rts=rts --dependency=ghc-heap=ghc-heap-8.10.4.20210212 --dependency=ghc-prim=ghc-prim-0.6.1 --dependency=integer-gmp=integer-gmp-1.0.3.0 --dependency=base=base-4.14.1.0 --dependency=deepseq=deepseq-1.4.4.0 --dependency=array=array-0.5.4.0 --dependency=ghc-boot-th=ghc-boot-th-8.10.4.20210212 --dependency=pretty=pretty-1.1.3.6 --dependency=template-haskell=template-haskell-2.16.0.0 --dependency=ghc-boot=ghc-boot-8.10.4.20210212 --dependency=ghc=ghc-8.10.4.20210212 --dependency=Cabal=Cabal-3.2.1.0 --dependency=array=array-0.5.4.0 --dependency=binary=binary-0.8.8.0 --dependency=bytestring=bytestring-0.10.12.0 --dependency=containers=containers-0.6.2.1 --dependency=directory=directory-1.3.6.0 --dependency=filepath=filepath-1.4.2.1 --dependency=ghc-boot=ghc-boot-8.10.4.20210212 --dependency=ghc-compact=ghc-compact-0.1.0.0 --dependency=ghc-prim=ghc-prim-0.6.1 --dependency=hpc=hpc-0.6.1.0 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.14.0 --dependency=process=process-1.6.9.0 --dependency=text=text-1.2.4.1 --dependency=time=time-1.9.3 --dependency=transformers=transformers-0.5.6.2 --dependency=unix=unix-2.7.2.2 --dependency=xhtml=xhtml-3000.2.2.1 --dependency=terminfo=terminfo-0.4.1.4 --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld.gold --ghc-option=-optl-fuse-ld=gold --ld-option=-fuse-ld=gold --with-ar=ar --with-strip=strip --disable-executable-stripping --disable-library-stripping --disable-library-profiling --disable-executable-profiling --enable-static --enable-shared --disable-coverage --enable-library-for-ghci --enable-split-sections
  Configuring library for prettyprinter-configurable-0.1.0.0..
  Warning: The flag --disable-executable-profiling is deprecated. Please use
  --disable-profiling instead.
  Warning: 'hs-source-dirs: doctest' directory does not exist.
  Warning: 'hs-source-dirs: test' directory does not exist.
  building
  ghc-pkg: {handle: dist/package.conf.inplace/package.cache.lock}: hLock: invalid argument (Invalid argument)
cannot build derivation '/nix/store/6l4hk64nzrgh10mc1q40x5lbvn0qi3ka-plutus-core-lib-plutus-core-0.1.0.0.drv': 1 dependencies couldn't be built
[9 built (1 failed), 290 copied (3010.5 MiB), 476.8 MiB DL]
error: build of '/nix/store/6l4hk64nzrgh10mc1q40x5lbvn0qi3ka-plutus-core-lib-plutus-core-0.1.0.0.drv' failed`

**Comment by Alebat** [comment]
I have a similar problem on WSL with:
Ubuntu 20.04.1 LTS
nix (Nix) 2.3.10 - (installed with `sudo mkdir -m 0755 /nix && chown $USER /nix` `sh <(curl -L https://nixos.org/nix/install)`)

```
git clone git@github.com:input-output-hk/plutus.git
cd plutus
nix build
```

```
[...]
building '/nix/store/723jb4vqyr1z5pwq6c2qzf1rlavh7cr1-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0.drv'...
builder for '/nix/store/723jb4vqyr1z5pwq6c2qzf1rlavh7cr1-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0.drv' failed with exit code 1; last 10 log lines:
  configuring
  Configure flags:
  --prefix=/nix/store/r0808lp65a8a6xwk8s43zxhqx3bs94dy-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0 lib:prettyprinter-configurable --package-db=clear --package-db=/nix/store/yl70gamg8n0x69vkycsqf9g93wcaj7zb-prettyprinter-configurable-lib-prettyprinter-configurable-0.1.0.0-config/lib/ghc-8.10.4.20210212/package.conf.d --exact-configuration --dependency=prettyprinter=prettyprinter-1.7.0-9YjuSqasuU58xkNfFeECaA --dependency=microlens=microlens-0.4.12.0-LWmCgM3D0eIxbRgAEzd8k --dependency=rts=rts --dependency=ghc-heap=ghc-heap-8.10.4.20210212 --dependency=ghc-prim=ghc-prim-0.6.1 --dependency=integer-gmp=integer-gmp-1.0.3.0 --dependency=base=base-4.14.1.0 --dependency=deepseq=deepseq-1.4.4.0 --dependency=array=array-0.5.4.0 --dependency=ghc-boot-th=ghc-boot-th-8.10.4.20210212 --dependency=pretty=pretty-1.1.3.6 --dependency=template-haskell=template-haskell-2.16.0.0 --dependency=ghc-boot=ghc-boot-8.10.4.20210212 --dependency=ghc=ghc-8.10.4.20210212 --dependency=Cabal=Cabal-3.2.1.0 --dependency=array=array-0.5.4.0 --dependency=binary=binary-0.8.8.0 --dependency=bytestring=bytestring-0.10.12.0 --dependency=containers=containers-0.6.2.1 --dependency=directory=directory-1.3.6.0 --dependency=filepath=filepath-1.4.2.1 --dependency=ghc-boot=ghc-boot-8.10.4.20210212 --dependency=ghc-compact=ghc-compact-0.1.0.0 --dependency=ghc-prim=ghc-prim-0.6.1 --dependency=hpc=hpc-0.6.1.0 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.14.0 --dependency=process=process-1.6.9.0 --dependency=text=text-1.2.4.1 --dependency=time=time-1.9.3 --dependency=transformers=transformers-0.5.6.2 --dependency=unix=unix-2.7.2.2 --dependency=xhtml=xhtml-3000.2.2.1 --dependency=terminfo=terminfo-0.4.1.4 --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld.gold --ghc-option=-optl-fuse-ld=gold --ld-option=-fuse-ld=gold --with-ar=ar --with-strip=strip --disable-executable-stripping --disable-library-stripping --disable-library-profiling --disable-executable-profiling --enable-static --enable-shared --disable-coverage --enable-library-for-ghci --enable-split-sections
  Configuring library for prettyprinter-configurable-0.1.0.0..
  Warning: The flag --disable-executable-profiling is deprecated. Please use
  --disable-profiling instead.
  Warning: 'hs-source-dirs: doctest' directory does not exist.
  Warning: 'hs-source-dirs: test' directory does not exist.
  building
  ghc-pkg: {handle: dist/package.conf.inplace/package.cache.lock}: hLock: invalid argument (Invalid argument)
cannot build derivation '/nix/store/6l4hk64nzrgh10mc1q40x5lbvn0qi3ka-plutus-core-lib-plutus-core-0.1.0.0.drv': 1 dependencies couldn't be built
[9 built (1 failed), 290 copied (3010.5 MiB), 476.8 MiB DL]
error: build of '/nix/store/6l4hk64nzrgh10mc1q40x5lbvn0qi3ka-plutus-core-lib-plutus-core-0.1.0.0.drv' failed
```

**Comment by james-iohk** [comment]
Hi @krishanik, sorry for the delay in getting back to you. I am not able to reproduce what you're seeing on my Ubuntu env, although I am using nix-env 2.3.8, I don't think this should matter. Are you still experiencing this?

I'd recommend taking a look at this documentation. It may benefit @Alebat too. https://github.com/nstankov-bg/docs.plutus-community.com/tree/main/book/docs/setup

Do let me know if your problems are resolved, I'll leave this issue open for a few days.
