### ISSUE TITLE
Inlined and collapsed blocks do not round-trip properly - Marlowe blocks editor

### ISSUE THREAD

**Issue by BeksOmega** [input-output-hk/plutus#2898]
Diagnostic info:
- I was using the:
    - [ ] Plutus Playground
    - [X] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: https://gist.github.com/BeksOmega/7d4e4e8d9f261f2fb7ea584c8280d280

### Description

When round-tripping through the Marlowe text representation, information about which blocks were inlined or collapsed is lost.

This could become quite annoying if people are working with long contracts where they want to compress or hide information.

### Steps to reproduce

1) Open up the linked project.
2) Inline the assert block and collapse the close block (via the right-click context menu) so that it looks like this:
![modified-contract](https://user-images.githubusercontent.com/25440652/112354290-c5b03600-8c89-11eb-9315-3878a7318f60.png)
3) View as Marlowe
4) View as Blocks
5) Observe how the blocks are not identical to before.

### Suggested solution

I think that ideally when converting the Marlowe back to blocks it should try to preserve as many of the block-settings as possible. But I'm not sure how the Marlowe to (I assume?) XML conversion works, so I'm not sure how possible this is.

### Alternative solution

Remove the inline and disable options from the right-click context menu, using the same method described in #2897

**Comment by james-iohk** [comment]
Closing as this is marked as `wontfix`
