### ISSUE TITLE
Contract compilation fails with HttpExceptionRequest

### ISSUE THREAD

**Issue by bklppr** [input-output-hk/plutus#2971]
Diagnostic info:
- I was using the:
    - [X] Plutus Playground
    - [ ] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: 

I followed these setup instructions: https://www.reddit.com/r/cardano/comments/mmzut6/macos_plutus_playground_build_instructions/

I can start the Plutus playground and go to the app but when I try to compile one of the existing example contracts I get a compilation error shown at the bottom:
```
ConnectionError (HttpExceptionRequest Request { host = "localhost" port = 8080 secure = False requestHeaders = [("Accept","application/json;charset=utf-8,application/json"),("Content-Type","application/json;charset=utf-8")] path = "/runghc" queryString = "" method = "POST" proxy = Nothing rawBody = False redirectCount = 10 responseTimeout = ResponseTimeoutDefault requestVersion = HTTP/1.1 } (InternalException Network.Socket.recvBuf: resource vanished (Connection reset by peer)))
```

I'm using MacOS 11.1 Big Sur with Firefox Version 87.0

Sorry if this is not the right place to ask this.

**Comment by bklppr** [comment]
Was due to some port binding issue

**Comment by kenil042288** [comment]
Can you please tell me how you fixed this port binding issue?

**Comment by bklppr** [comment]
In the end I had to change the port 8080 in the source files to a different one (I used 8085), that did the trick

**Comment by kenil042288** [comment]
Doesnt the source file have 8009?  

plutus/plutus-playground-client/webpack.config.js 

has "port: 8009" in its code

**Comment by bklppr** [comment]
8009 is the client port (the one you will enter in the browser).
8080 is the server port, that was the one causing the issue for me.

**Comment by kenil042288** [comment]
Ah, okay, thanks.  I went in and changed 8080 to 8085 for all plutus-related files in the repository.. but now I can't even get a success when I do npm run start.  

I get a bunch of errors:

`Error: Cannot find module 'mini-css-extract-plugin'
Require stack:
- /home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/webpack.config.js
- /home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/webpack.config.js:4:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/webpack.config.js',
    '/home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/galloppingturtle/my-plutus2/plutus/plutus-playground-client/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plutus-playground-client@1.0.0 webpack:server: `webpack-dev-server --progress --inline --hot --mode=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plutus-playground-client@1.0.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/galloppingturtle/.npm/_logs/2021-05-09T20_13_17_042Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plutus-playground-client@1.0.0 start: `npm install && plutus-playground-generate-purs && npm run purs:compile && npm run webpack:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plutus-playground-client@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/galloppingturtle/.npm/_logs/2021-05-09T20_13_17_063Z-debug.log`

**Comment by bklppr** [comment]
Hmm, unfortunately I‘m not good with that stuff but I can share the steps that got me there (which someone else shared with me):

- change 8080 to 8085 in plutus-playground-client and plutus-playground-server
- start a nix shell
- go into plutus-playground-server
- run cabal build
- run plutus-playground-server command
- in new terminal, start nix shell
- go into plutus-playground-client
- run npm run start

Hope that helps!

**Comment by trungswat** [comment]
@bklppr thank you for your help.

But please let me know where about you change the port in both plutus-playground-client and server.

**Comment by bklppr** [comment]
I opened both folders in VSCode and did a search & replace over all files
