### ISSUE TITLE
Playground client not accessible remotely

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#2973]
This issue came up while taking part in the pioneer program

> On MacOS there seem to be numerous issues with compiling the English Auction contract. Instead of trying to resolve those, I moved to a Debial10 hosted on GCE. I got the contract compiled and the playground server/client started.
>
> However, because this is a remote machine I cannot access the playground-client on: https://localhost:8009
>
> Instead, I'd like the playground-client to bind to 0.0.0.0, so that I can use the remote IP.

CrossRef: https://github.com/input-output-hk/plutus-pioneer-program/issues/3

Diagnostic info:
- I was using the:
    - [x] Plutus Playground

**Comment by tdiesler** [comment]
Adding host: "0.0.0.0" in plutus/plutus-playground-client/webpack.config.js seems to work ...

```
    devServer: {
        contentBase: path.join(__dirname, "dist"),
        compress: true,
        host: "0.0.0.0",
        port: 8009,
        https: true,
        proxy: {
            "/api": {
                target: 'http://localhost:8080'
            }
        }
    },
```

Not sure if this can generally be done to go forward.

**Comment by KevinHock** [comment]
For security reasons, defaulting to 0000 seems not good

**Comment by yangzai** [comment]
I spent a long time tweaking my router and firewalls before realising it was a webpack issue: https://webpack.js.org/configuration/dev-server/#devserverhost

**Comment by kk-hainq** [comment]
One can also SSH tunnel from the cloud to the local machine with something like:
```
ssh -i xxx.pem -N -L 8009:localhost:8009 xxx@xx.xxx.xx.xxx
```
To access the client through https://localhost:8009 just fine.

**Comment by tdiesler** [comment]
I think we can close this
