### ISSUE TITLE
References to non-existant nix command (`plutus-playground.server-invoker`)

### ISSUE THREAD

**Issue by r-tde** [input-output-hk/plutus#2988]
Diagnostic info:
- I was using the:
    - [x] Plutus Playground
- Link to gist with saved setup that reproduces the issue: 
    - Follow steps listed in [README](https://github.com/input-output-hk/plutus/blob/master/plutus-playground-server/README.md) 

References to an non-existant nix command/package - `plutus-playground.server-invoker` found in both `plutus-playground-client` and `plutus-playground-server`. This means you can't start the web interface using these commands.

**Comment by michaelpj** [comment]
@gilligan I think you killed these, right?

**Comment by r-tde** [comment]
@michaelpj so would we be the commands to start the server "properly"? running the `plutus-playground.server` & `plutus-playground.client` result in a running node server but it returns 404 on any and every request. Even though `generated` was generated.

**Comment by ak3n** [comment]
To start the server properly you need to start two `nix-shell` sessions with server and client in `plutus-playground-client`:

```
nix-shell
cd plutus-playground-client
plutus-playground-server
```

```
nix-shell
cd plutus-playground-client
npm run start
```
