### ISSUE TITLE
 21 | import           Formatting                            (fprintLn, (%)) -- | not on Formatting module

### ISSUE THREAD

**Issue by whosystem** [input-output-hk/plutus#3027]
Diagnostic info:
Building all executables for `plutus-metatheory' once. After a successful build of all of them, only specified executables will be rebuilt.
marlowe-symbolic         > configure (lib)
marlowe-symbolic         > Configuring marlowe-symbolic-0.3.0.0...
plutus-metatheory        > configure (lib + exe)
marlowe-symbolic         > build (lib)
marlowe-symbolic         > Preprocessing library for marlowe-symbolic-0.3.0.0..
marlowe-symbolic         > Building library for marlowe-symbolic-0.3.0.0..
marlowe-symbolic         > [3 of 3] Compiling Marlowe.Symbolic.Server
marlowe-symbolic         > 
marlowe-symbolic         > /home/cardano/plutus/marlowe-symbolic/src/Marlowe/Symbolic/Server.hs:21:57: error:
marlowe-symbolic         >     Module ‘Formatting’ does not export ‘fprintLn’
marlowe-symbolic         >    |
marlowe-symbolic         > 21 | import           Formatting                            (fprintLn, (%)) -- | not on Formatting module
- I was building the:
    - [ x] Plutus Playground
    - [ x] Marlowe Playground
- Link to gist with saved setup that reproduces the issue: 
- --- OS version and space info ------ 
cardano@ubscardano:~/plutus/xxx$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
uname -a 
Linux ubscardano 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            5.9G     0  5.9G   0% /dev
tmpfs           1.2G  1.6M  1.2G   1% /run
/dev/sda2       492G  133G  334G  29% /
tmpfs           6.0G  147M  5.8G   3% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           6.0G     0  6.0G   0% /sys/fs/cgroup
/dev/loop2      100M  100M     0 100% /snap/core/10958
/dev/loop1      200M  200M     0 100% /snap/code/62
/dev/loop0      200M  200M     0 100% /snap/code/61
/dev/loop3       56M   56M     0 100% /snap/core18/1997
/dev/loop4       56M   56M     0 100% /snap/core18/1988
/dev/loop5      100M  100M     0 100% /snap/core/10908
/dev/loop6       62M   62M     0 100% /snap/core20/904
/dev/loop8       33M   33M     0 100% /snap/snapd/11588
/dev/loop7       62M   62M     0 100% /snap/core20/975
/dev/loop9      324M  324M     0 100% /snap/kde-frameworks-5-qt-5-15-core20/14
/dev/loop10     291M  291M     0 100% /snap/kde-frameworks-5-qt-5-14-core18/4
/dev/loop11     241M  241M     0 100% /snap/zoom-client/138
/dev/loop12      33M   33M     0 100% /snap/snapd/11402
/dev/loop13     109M  109M     0 100% /snap/umbrello/44
/dev/loop14      16M   16M     0 100% /snap/umbrello/41
/dev/loop15      71M   71M     0 100% /snap/lxd/19647
/dev/loop16     241M  241M     0 100% /snap/zoom-client/139
/dev/loop17      70M   70M     0 100% /snap/lxd/19188
/dev/loop18      57M   57M     0 100% /snap/teamtime/12
Videos          1.9T  1.1T  779G  59% /media/sf_Videos
cardano         1.9T  1.1T  779G  59% /media/sf_cardano
tmpfs           1.2G   40K  1.2G   1% /run/user/1001
/dev/sdb1       3.8G  1.1G  2.8G  27% /media/cardano/VB-BLUE

**Comment by ak3n** [comment]
Feel free to reopen the issue if you have questions.
