### ISSUE TITLE
Build items line by line in a shell for loop - where is it running out of space ??? builder for '/nix/store/pqhwhj6yw46kk8vvgb9b6h0adg0v9m1s-docker-image-plutus-devcontainer.tar.gz.drv' failed with exit code 2; last 4 log lines:

### ISSUE THREAD

**Issue by whosystem** [input-output-hk/plutus#3043]
<----- System info 
**MEMORY AVAILABLE 11.8 GB most amount used 5GB **
![Screenshot from 2021-04-20 19-40-43](https://user-images.githubusercontent.com/79116695/115484681-70c3f900-a210-11eb-9d63-d81d99cf4cee.png)

 pushd /nix/store
/nix/store ~/src
cardano@ubscardano:/nix/store$ df -h .  **There is  320G of free space**
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       492G  148G  320G  32% /
cardano@ubscardano:/nix/store$ 

cardano@ubscardano:~/plutus/xxx$ lsb_release -a |  **Ubuntu version**
-- | --
No LSB modules are available. |  
Distributor ID: | Ubuntu
Description: | Ubuntu 20.04.2 LTS
Release: | 20.04
Codename: | focal
[nix-shell:~/plutus]$ uname -a |  
Linux ubscardano 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 GNU/Linux |  **Kernel Version **

[nix-shell:~/plutus]$ df -h  **SPACE AVAILABLE**
Filesystem      Size  Used Avail Use% Mounted on
udev            5.9G     0  5.9G   0% /dev
tmpfs           1.2G  1.6M  1.2G   1% /run
/dev/sda2       492G  147G  320G  32% /
tmpfs           6.0G   92M  5.9G   2% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           6.0G     0  6.0G   0% /sys/fs/cgroup
/dev/loop0      200M  200M     0 100% /snap/code/61
/dev/loop2      200M  200M     0 100% /snap/code/62
/dev/loop3      100M  100M     0 100% /snap/core/10958
/dev/loop4      100M  100M     0 100% /snap/core/10908
/dev/loop1       56M   56M     0 100% /snap/core18/1988
/dev/loop5       62M   62M     0 100% /snap/core20/904
/dev/loop7      291M  291M     0 100% /snap/kde-frameworks-5-qt-5-14-core18/4
/dev/loop6       70M   70M     0 100% /snap/lxd/19188
/dev/loop8       71M   71M     0 100% /snap/lxd/19647
/dev/loop9       56M   56M     0 100% /snap/core18/1997
/dev/loop10      62M   62M     0 100% /snap/core20/975
/dev/loop11     324M  324M     0 100% /snap/kde-frameworks-5-qt-5-15-core20/14
/dev/loop12      57M   57M     0 100% /snap/teamtime/12
/dev/loop13      16M   16M     0 100% /snap/umbrello/41
/dev/loop14     109M  109M     0 100% /snap/umbrello/44
/dev/loop15     241M  241M     0 100% /snap/zoom-client/139
/dev/loop16      33M   33M     0 100% /snap/snapd/11402
/dev/loop17     241M  241M     0 100% /snap/zoom-client/141
/dev/loop18      33M   33M     0 100% /snap/snapd/11588
Videos          1.9T  1.1T  749G  60% /media/sf_Videos
cardano         1.9T  1.1T  749G  60% /media/sf_cardano
tmpfs           1.2G  176K  1.2G   1% /run/user/1001

----> 

<---- message 
**RAN**
git fetch 
nix-shell
nix_ update 
nix build 
nix-shell --run fix-purty

**whatever did not build I ran again**
[nix-shell:~/plutus]$ !sh 
sh -x buildit.sh  
+ LST='/nix/store/0k3nwdfxc694mbb3b3bpnv98wdnp1kyq-plutus-docs.drv /nix/store/1rqwr0p8yygk8zrn50r8cd3rn8lvgv18-marlowe-marketplace-client.drv /nix/store/1zcwql0spfmz6w7l11658zwsvbkhcjfx-plutus-playground-client.drv /nix/store/4255qgcli5k2qg3y16x7hbl63wh14r8h-purty-check.drv /nix/store/5iisq492s5q42lgpcpi0anm04fclriml-vm-test-run-all.drv /nix/store/6fpxhn9vbhk3519mp2v8z405nprl3w9w-haddock-join.drv /nix/store/bgy45ypa6iaf626a0rsm0bnd0qnihpgw-terraform-fmt.drv /nix/store/ip787psabg1zkww099afj2jckpfprkwq-stylish-check.drv /nix/store/lrzkz6l32w5zp5iy0kf2g1q5saybw7m2-nixpkgs-fmt.drv /nix/store/mpy70chdlmqxammv0mx5xxwsvxdmzi9j-shellcheck.drv /nix/store/pqhwhj6yw46kk8vvgb9b6h0adg0v9m1s-docker-image-plutus-devcontainer.tar.gz.drv'
+ for xx in $LST
+ nix build /nix/store/0k3nwdfxc694mbb3b3bpnv98wdnp1kyq-plutus-docs.drv
builder for '/nix/store/xqjqx3rz00qndd8bxqv1a9vw3anlgpbd-playground-common-lib-playground-common-0.1.0.0.drv' failed with exit code 1; last 10 log lines:
  [14 of 21] Compiling Playground.TH    ( src/Playground/TH.hs, dist/build/Playground/TH.o, dist/build/Playground/TH.dyn_o )
  [15 of 21] Compiling Playground.Contract ( src/Playground/Contract.hs, dist/build/Playground/Contract.o, dist/build/Playground/Contract.dyn_o )
  [16 of 21] Compiling Servant.Extra    ( src/Servant/Extra.hs, dist/build/Servant/Extra.o, dist/build/Servant/Extra.dyn_o )
  [17 of 21] Compiling Gist             ( src/Gist.hs, dist/build/Gist.o, dist/build/Gist.dyn_o )
  [18 of 21] Compiling Auth             ( src/Auth.hs, dist/build/Auth.o, dist/build/Auth.dyn_o )
  [19 of 21] Compiling PSGenerator.Common ( src/PSGenerator/Common.hs, dist/build/PSGenerator/Common.o, dist/build/PSGenerator/Common.dyn_o )
  [20 of 21] Compiling Servant.Prometheus ( src/Servant/Prometheus.hs, dist/build/Servant/Prometheus.o, dist/build/Servant/Prometheus.dyn_o )
  [21 of 21] Compiling System.IO.Extras ( src/System/IO/Extras.hs, dist/build/System/IO/Extras.o, dist/build/System/IO/Extras.dyn_o )
  /nix/store/c1gipyfc161lm0fqfg65k4ak7yl2i17i-binutils-2.34/bin/ranlib: dist/build/libHSplayground-common-0.1.0.0-CIjwVmEbPHc4YmqispPVna-ghc8.10.2.20201118.a: No space left on device
  `ranlib' failed in phase `Ranlib'. (Exit code: 1)
cannot build derivation '/nix/store/ww9h2adas417p1sr3mbykxr0lbyllsgf-marlowe-dashboard-server-lib-marlowe-dashboard-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/khx27w059d1gvn9ri4vqfqdlcqsfwbvy-marlowe-playground-server-lib-marlowe-playground-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xsa9157i2y206c1023zc573dhx74s20d-playground-common-lib-playground-common-0.1.0.0-haddock.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/148iqdi41n0wy99wc9dxw4algz97v8l7-plutus-pab-lib-plutus-pab-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hgy7ipmrpdgimh1f31gzkzg2gd125b4m-plutus-playground-server-lib-plutus-playground-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sv3vfyga21z5mbk90m806avzpby46adh-plutus-use-cases-lib-plutus-use-cases-0.1.0.0-config.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/739ch0v8fjqyigcc9222wri7xgakcphb-plutus-use-cases-lib-plutus-use-cases-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s4c5cr0x2k4hhqz7f6s181hndlvlarj8-web-ghc-lib-web-ghc-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6fpxhn9vbhk3519mp2v8z405nprl3w9w-haddock-join.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0k3nwdfxc694mbb3b3bpnv98wdnp1kyq-plutus-docs.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/0k3nwdfxc694mbb3b3bpnv98wdnp1kyq-plutus-docs.drv' failed
+ for xx in $LST
+ nix build /nix/store/1rqwr0p8yygk8zrn50r8cd3rn8lvgv18-marlowe-marketplace-client.drv
builder for '/nix/store/1rqwr0p8yygk8zrn50r8cd3rn8lvgv18-marlowe-marketplace-client.drv' failed with exit code 1; last 10 log lines:
  at web-common-marlowe/src/Marlowe/Slot.purs:19:1 - 19:82 (line 19, column 1 - line 19, column 82)
  
    Module Data.Formatter.DateTime was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.
  
  
  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.
  
  
[0 built (1 failed)]
error: build of '/nix/store/1rqwr0p8yygk8zrn50r8cd3rn8lvgv18-marlowe-marketplace-client.drv' failed
+ for xx in $LST
+ nix build /nix/store/1zcwql0spfmz6w7l11658zwsvbkhcjfx-plutus-playground-client.drv
builder for '/nix/store/1zcwql0spfmz6w7l11658zwsvbkhcjfx-plutus-playground-client.drv' failed with exit code 1; last 10 log lines:
  npm ERR! errno 1
  npm ERR! plutus-playground-client@1.0.0 webpack: `DEBUG=purs-loader* DEBUG_DEPTH=100 webpack --progress --bail --mode=production -p`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the plutus-playground-client@1.0.0 webpack script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /build/.npm/_logs/2021-04-21T02_31_31_960Z-debug.log
  
[0 built (1 failed)]
error: build of '/nix/store/1zcwql0spfmz6w7l11658zwsvbkhcjfx-plutus-playground-client.drv' failed
+ for xx in $LST
+ nix build /nix/store/4255qgcli5k2qg3y16x7hbl63wh14r8h-purty-check.drv
builder for '/nix/store/4255qgcli5k2qg3y16x7hbl63wh14r8h-purty-check.drv' failed with exit code 1; last 3 log lines:
  *** purty-haskell found changes that need addressed first
  *** Please run `nix-shell --run fix-purty` and commit changes
  *** or apply the diff generated by hydra if you don't have nix.
[0 built (1 failed)]
error: build of '/nix/store/4255qgcli5k2qg3y16x7hbl63wh14r8h-purty-check.drv' failed
+ for xx in $LST
+ nix build /nix/store/5iisq492s5q42lgpcpi0anm04fclriml-vm-test-run-all.drv
builder for '/nix/store/xqjqx3rz00qndd8bxqv1a9vw3anlgpbd-playground-common-lib-playground-common-0.1.0.0.drv' failed with exit code 1; last 10 log lines:
  [14 of 21] Compiling Playground.TH    ( src/Playground/TH.hs, dist/build/Playground/TH.o, dist/build/Playground/TH.dyn_o )
  [15 of 21] Compiling Playground.Contract ( src/Playground/Contract.hs, dist/build/Playground/Contract.o, dist/build/Playground/Contract.dyn_o )
  [16 of 21] Compiling Servant.Extra    ( src/Servant/Extra.hs, dist/build/Servant/Extra.o, dist/build/Servant/Extra.dyn_o )
  [17 of 21] Compiling Gist             ( src/Gist.hs, dist/build/Gist.o, dist/build/Gist.dyn_o )
  [18 of 21] Compiling Auth             ( src/Auth.hs, dist/build/Auth.o, dist/build/Auth.dyn_o )
  [19 of 21] Compiling PSGenerator.Common ( src/PSGenerator/Common.hs, dist/build/PSGenerator/Common.o, dist/build/PSGenerator/Common.dyn_o )
  [20 of 21] Compiling Servant.Prometheus ( src/Servant/Prometheus.hs, dist/build/Servant/Prometheus.o, dist/build/Servant/Prometheus.dyn_o )
  [21 of 21] Compiling System.IO.Extras ( src/System/IO/Extras.hs, dist/build/System/IO/Extras.o, dist/build/System/IO/Extras.dyn_o )
  /nix/store/c1gipyfc161lm0fqfg65k4ak7yl2i17i-binutils-2.34/bin/ranlib: dist/build/libHSplayground-common-0.1.0.0-CIjwVmEbPHc4YmqispPVna-ghc8.10.2.20201118.a: No space left on device
  `ranlib' failed in phase `Ranlib'. (Exit code: 1)
cannot build derivation '/nix/store/ww9h2adas417p1sr3mbykxr0lbyllsgf-marlowe-dashboard-server-lib-marlowe-dashboard-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/khx27w059d1gvn9ri4vqfqdlcqsfwbvy-marlowe-playground-server-lib-marlowe-playground-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xsa9157i2y206c1023zc573dhx74s20d-playground-common-lib-playground-common-0.1.0.0-haddock.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/148iqdi41n0wy99wc9dxw4algz97v8l7-plutus-pab-lib-plutus-pab-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hgy7ipmrpdgimh1f31gzkzg2gd125b4m-plutus-playground-server-lib-plutus-playground-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sv3vfyga21z5mbk90m806avzpby46adh-plutus-use-cases-lib-plutus-use-cases-0.1.0.0-config.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/739ch0v8fjqyigcc9222wri7xgakcphb-plutus-use-cases-lib-plutus-use-cases-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s4c5cr0x2k4hhqz7f6s181hndlvlarj8-web-ghc-lib-web-ghc-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6fpxhn9vbhk3519mp2v8z405nprl3w9w-haddock-join.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0k3nwdfxc694mbb3b3bpnv98wdnp1kyq-plutus-docs.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wik7lswjwznnr662mbi55yb7cbccpl6x-nginx.conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lwx957x2zgc6m9fad80l61ind9vwq4a3-unit-nginx.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1gna3zngay13hapzsa5wf87bwdj0jd6x-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vrn6lgq4fasjhbvrccf9w3na7p1jav3p-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zcf6bagaayvdgncadm88rycqhic7gd8j-nixos-system-playgrounds-21.03pre-git.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/b96j8nl2iq0v84nrp5b5xd69xjs7csms-nixos-vm.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/w8mmr5470kcmbyq1h3ix4534zj87x4il-nixos-test-driver-all.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5iisq492s5q42lgpcpi0anm04fclriml-vm-test-run-all.drv': 1 dependencies couldn't be built
[1 built (1 failed)]
error: build of '/nix/store/5iisq492s5q42lgpcpi0anm04fclriml-vm-test-run-all.drv' failed
+ for xx in $LST
+ nix build /nix/store/6fpxhn9vbhk3519mp2v8z405nprl3w9w-haddock-join.drv
builder for '/nix/store/xqjqx3rz00qndd8bxqv1a9vw3anlgpbd-playground-common-lib-playground-common-0.1.0.0.drv' failed with exit code 1; last 10 log lines:
  [14 of 21] Compiling Playground.TH    ( src/Playground/TH.hs, dist/build/Playground/TH.o, dist/build/Playground/TH.dyn_o )
  [15 of 21] Compiling Playground.Contract ( src/Playground/Contract.hs, dist/build/Playground/Contract.o, dist/build/Playground/Contract.dyn_o )
  [16 of 21] Compiling Servant.Extra    ( src/Servant/Extra.hs, dist/build/Servant/Extra.o, dist/build/Servant/Extra.dyn_o )
  [17 of 21] Compiling Gist             ( src/Gist.hs, dist/build/Gist.o, dist/build/Gist.dyn_o )
  [18 of 21] Compiling Auth             ( src/Auth.hs, dist/build/Auth.o, dist/build/Auth.dyn_o )
  [19 of 21] Compiling PSGenerator.Common ( src/PSGenerator/Common.hs, dist/build/PSGenerator/Common.o, dist/build/PSGenerator/Common.dyn_o )
  [20 of 21] Compiling Servant.Prometheus ( src/Servant/Prometheus.hs, dist/build/Servant/Prometheus.o, dist/build/Servant/Prometheus.dyn_o )
  [21 of 21] Compiling System.IO.Extras ( src/System/IO/Extras.hs, dist/build/System/IO/Extras.o, dist/build/System/IO/Extras.dyn_o )
  /nix/store/c1gipyfc161lm0fqfg65k4ak7yl2i17i-binutils-2.34/bin/ranlib: dist/build/libHSplayground-common-0.1.0.0-CIjwVmEbPHc4YmqispPVna-ghc8.10.2.20201118.a: No space left on device
  `ranlib' failed in phase `Ranlib'. (Exit code: 1)
cannot build derivation '/nix/store/ww9h2adas417p1sr3mbykxr0lbyllsgf-marlowe-dashboard-server-lib-marlowe-dashboard-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/khx27w059d1gvn9ri4vqfqdlcqsfwbvy-marlowe-playground-server-lib-marlowe-playground-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/xsa9157i2y206c1023zc573dhx74s20d-playground-common-lib-playground-common-0.1.0.0-haddock.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/148iqdi41n0wy99wc9dxw4algz97v8l7-plutus-pab-lib-plutus-pab-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hgy7ipmrpdgimh1f31gzkzg2gd125b4m-plutus-playground-server-lib-plutus-playground-server-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sv3vfyga21z5mbk90m806avzpby46adh-plutus-use-cases-lib-plutus-use-cases-0.1.0.0-config.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/739ch0v8fjqyigcc9222wri7xgakcphb-plutus-use-cases-lib-plutus-use-cases-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/s4c5cr0x2k4hhqz7f6s181hndlvlarj8-web-ghc-lib-web-ghc-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6fpxhn9vbhk3519mp2v8z405nprl3w9w-haddock-join.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/6fpxhn9vbhk3519mp2v8z405nprl3w9w-haddock-join.drv' failed
+ for xx in $LST
+ nix build /nix/store/bgy45ypa6iaf626a0rsm0bnd0qnihpgw-terraform-fmt.drv
[1 built]
+ for xx in $LST
+ nix build /nix/store/ip787psabg1zkww099afj2jckpfprkwq-stylish-check.drv
builder for '/nix/store/ip787psabg1zkww099afj2jckpfprkwq-stylish-check.drv' failed with exit code 1; last 10 log lines:
  stylish-haskell: xxx/shelley-spec-ledger-0.1.0.0/src/Shelley/Spec/Ledger/BlockChain.hs: commitBuffer: invalid argument (invalid character)
  stylish-haskell: xxx/shelley-spec-ledger-0.1.0.0/src/Shelley/Spec/Ledger/EpochBoundary.hs: commitBuffer: invalid argument (invalid character)
  stylish-haskell: xxx/typed-protocols-0.1.0.0/src/Network/TypedProtocol/Core.hs: commitBuffer: invalid argument (invalid character)
  stylish-haskell: xxx/typed-protocols-0.1.0.0/src/Network/TypedProtocol/Proofs.hs: commitBuffer: invalid argument (invalid character)
  stylish-haskell: xxx/small-steps-0.1.0.0/src/Control/Iterate/SetAlgebra.hs: commitBuffer: invalid argument (invalid character)
  prettyprinter-configurable/Setup.hs: RealSrcSpan SrcSpanOneLine "prettyprinter-configurable/Setup.hs" 19 1 7: parse error on input `import'
  
  *** Stylish-haskell found changes that need addressed first
  *** Please run `nix-shell --run fix-stylish-haskell` and commit changes
  *** or apply the diff generated by hydra if you don't have nix.
[0 built (1 failed)]
error: build of '/nix/store/ip787psabg1zkww099afj2jckpfprkwq-stylish-check.drv' failed
+ for xx in $LST
+ nix build /nix/store/lrzkz6l32w5zp5iy0kf2g1q5saybw7m2-nixpkgs-fmt.drv
builder for '/nix/store/lrzkz6l32w5zp5iy0kf2g1q5saybw7m2-nixpkgs-fmt.drv' failed with exit code 1; last 4 log lines:
  68 / 177 would have been reformatted
  error: fail on changes
  *** nixpkgs-fmt found files that haven't been formatted
  *** Please run `nix-shell --run "nixpkgs-fmt ."` and commit the changes
[0 built (1 failed)]
error: build of '/nix/store/lrzkz6l32w5zp5iy0kf2g1q5saybw7m2-nixpkgs-fmt.drv' failed
+ for xx in $LST
+ nix build /nix/store/mpy70chdlmqxammv0mx5xxwsvxdmzi9j-shellcheck.drv
builder for '/nix/store/mpy70chdlmqxammv0mx5xxwsvxdmzi9j-shellcheck.drv' failed with exit code 32; last 10 log lines:
                    ^-^ SC2086: Double quote to prevent globbing and word splitting.
  
  Did you mean: 
         nix build "$xx"
  
  For more information:
    https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
  ./buildit.sh [ FAILED ]
  ./infrastructure/modules/existing-user/import.sh [ PASSED ]
  Total Failed Files: 32
[0 built (1 failed)]
error: build of '/nix/store/mpy70chdlmqxammv0mx5xxwsvxdmzi9j-shellcheck.drv' failed
+ for xx in $LST
+ nix build /nix/store/pqhwhj6yw46kk8vvgb9b6h0adg0v9m1s-docker-image-plutus-devcontainer.tar.gz.drv
builder for '/nix/store/pqhwhj6yw46kk8vvgb9b6h0adg0v9m1s-docker-image-plutus-devcontainer.tar.gz.drv' failed with exit code 2; last 4 log lines:
  Adding layer...
  tar: Removing leading `/' from member names
  tar: temp/layer.tar: Wrote only 2048 of 10240 bytes
  tar: Error is not recoverable: exiting now
note: build failure may have been caused by lack of free disk space
[0 built (1 failed)]
error: build of '/nix/store/pqhwhj6yw46kk8vvgb9b6h0adg0v9m1s-docker-image-plutus-devcontainer.tar.gz.drv' failed

--->
[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

A clear and specific description of what the bug is.

## System info (please complete the following information):

- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Plutus version or commit hash

## Screenshots and attachments

- If applicable, add screenshots, config files and/or logs to help explain the problem.
- If the issue is related to the Plutus Playground, please include a link to a gist that reproduces the issue

**Comment by ak3n** [comment]
The description is unclear and it's hard to understand what's going on. Can you please tell what are you trying to achieve, specify what commands did you run and in what order?

**Comment by ak3n** [comment]
I suspect the problem is with the missing nix cache configuration. Feel free to reopen the issue if you have questions.
