### ISSUE TITLE
nix-shell segfaulting at spago-packages.nix when building PAB

### ISSUE THREAD

**Issue by t1lde** [input-output-hk/plutus#3069]
## Area

*Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

I'm importing the plutus default.nix as part of a nix-shell to build a project, and when building plutus-pab the `nix-shell` command segfaults inconsistently.

With `nix-shell --verbose`  it shows:
```
...
evaluating file '/nix/store/p32cr144sj2v34a6w31ghm9q78gvhlja-plutus-src/plutus-pab-client/spago-packages.nix'
[1]    277606 segmentation fault (core dumped)  nix-shell --verbose
```

If I don't  include plutus-pab in the shell, then the rest of the plutus haskell libraries and haddock docs build just fine.

This may be specific to our project, however I don't think anything about the shell.nix we are using is incorrect - it has been working until recently (when we bumped the plutus repo commit version). This may well be a bug with nix itself.

We were experiencing some segfaults previously, more occasionally on older plutus versions, but trying nix-shell a few times would eventually succeed. In this case, I've managed to have it not segfault *once* but can't reproduce this.

## System and Version Info

- OS: Arch Linux

- `nix-shell --version`
 ```
nix-shell (Nix) 2.4pre20210326_dd77f71
```
- Plutus Version: 4b6062a1a4c2113d4575436eb8c759685e704a5f
- Nixpkgs version: nixpkgs-unstable
we use the nixpkgs version from the plutus nix expression directly, so it shouldn't affect the build but this may affect the nix-shell executable version.

## Also Reproduced On NixOS:

- OS: NixOS
- NixOS Version: nixos-unstable
- Plutus Version: 4b6062a1a4c2113d4575436eb8c759685e704a5f

## Other Commit Tried:

I also tried with plutus rev 3746610e53654a1167aeb4c6294c6096d16b0502 , as pinned by the `plutus-pioneer-program` repo.

**Comment by james-iohk** [comment]
Hey @t1lde, are you experiencing this issue when using stable build of nix-shell 2.3.8?

**Comment by t1lde** [comment]
Yep, looks like with a nix-shell via nixpkgs 20.09 works. Perhaps this is an issue to be raised with nix.

**Comment by james-iohk** [comment]
@t1lde Thanks for confirming. If we experience segfaults in a future stable release then it will be worth raising. Closing.
