### ISSUE TITLE
Compilation takes unreasonable amount of time/space when using INLINEABLE

### ISSUE THREAD

**Issue by emiflake** [input-output-hk/plutus#3080]
## Area

- [x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
- [ ] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
- [ ] *Marlowe* Related to Marlowe
- [ ] *Other* Any other topic (Playgrounds, etc.)

## Summary

Provided a large enough project with a validator and various `INLINEABLE` pragmas, the compiler will take a great amount of time in the typechecker phase, and will allocate large amounts of memory. When tracking the compilation with `-dshow-passes`, we get this message:
`!!! Renamer/typechecker [Main]: finished in 39227.54 milliseconds, allocated 38467.992 megabytes`. On a machine with less memory (like in Github Actions) this will _eventually_ (after 20+ minutes) run out of memory and crash:
`Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)`

## Steps to reproduce

Hard to describe the exact steps to reproduce, a sufficiently large validator involving many `INLINEABLE` terms scattered around will slowly consume all of the typechecker / simplifier's resouces. It's unclear if instances of typeclasses are the root cause here, because they pile up quickly when deriving.
We build using `stack build --no-nix --system-ghc -j1 --ghc-options="-dshow-passes"`.

## Expected behavior

The compilation of Plutus programs should be done in reasonable space and time. 

This behavior is probably _expected_ when it comes to GHC, because using INLINEABLE/INLINE a lot is prone to generating large trees, but since in Plutus it's the only way to produce on-chain code, perhaps a workaround should be provided.

## System info:

Locally:
- OS: NixOS
- Version: 20.09
- Plutus: cd49a84f19c536397b7516d2a378720400f5ee47

GitHub Actions:
- OS: Ubuntu
- Version: 20.04.2 LTS
- Plutus: cd49a84f19c536397b7516d2a378720400f5ee47

**Comment by ak3n** [comment]
Thanks for reporting!

How many endpoints do you have? Can you share the code?  

> stack build --no-nix --system-ghc

And what ghc version do you use?

**Comment by emiflake** [comment]
We're on GHC 8.10.2.20201118, and currently using 8 endpoints. And specifically they are appended to one another like so:
```hs
type Schema =
  BlockchainActions
    .\/ Endpoint "A" AParams
    .\/ Endpoint "B" BParams
    .\/ Endpoint "C" CParams
    .\/ Endpoint "D" DParams
    .\/ Endpoint "E" EParams
    .\/ SchemaQuery

-- Lives in other file
type SchemaQuery =
  Endpoint "QueryA" QAParams
    .\/ Endpoint "QueryB" QBParams
    .\/ Endpoint "QueryC" QCParams
```
You're right in pointing this out though, because increasing SchemaQuery with a bunch of more (dummy) endpoints causes this issue to increase drastically: Runs out of memory pretty much instantly even on 40GB RAM. I guess my original intuition on it being caused by INLINEABLE is sort of misguided, but this seems like a bug nonetheless. I've also tested if it works with having the two be manually merged together, but no, even still it consumes more or less the same amount of memory.

Is there already an issue that tracks this limitation?

**Comment by emiflake** [comment]
For reproducibility sake I've gone ahead and made a minimum git repo which behaves this way [here](https://github.com/emiflake/plutus-3080-minimum-example).

**Comment by ak3n** [comment]
This is great, thanks!

**Comment by ak3n** [comment]
@emiflake Please try `6d1a06a373ebaf8fd8408f23c9d72f96d922bbaf`. Should be fixed.

**Comment by emiflake** [comment]
Yep! That seems solved, thanks for your work. :slightly_smiling_face:
