### ISSUE TITLE
Missing access to transaction input `Datum`s in on-chain code

### ISSUE THREAD

**Issue by mputz86** [input-output-hk/plutus#3119]
## Area

[X] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

When validating a spending transaction, the `Datum`s of the spent inputs are not available via `ScriptContext`.
Precisely:
- The `txOutDatumHash` in the `txInfoInputs` (from `ScriptContext`) gives back a hash, so `Just ...`
- But using `findDatum` in [Plutus.V1.Ledger.Contexts](http://localhost:1234/plutus-ledger-api/html/Plutus-V1-Ledger-Contexts.html#t:TxInInfo) returns `Nothing`
- So the data was not added to `txInfoData`
  - Can be verified by viewing the `Tx` returned by `submiTx...`

## Steps to reproduce

(see attachments for an example demonstrating the issue)

- Build a contract which creates two UTxO with a `Datum`
- Create another transaction which spends both UTxO and
- try to access all `Datum` of all input UTxO via the `ScriptContext`

## Expected behavior

1. According to a discussion with @brunjlar (pioneer discord), all input `Datum` should be available per default via the `ScriptContext` in on-chain validation.
2. Maybe it would be worth to update the documentation on `txInfoData` in `TxInfo` (there is none at the moment)

## System info (please complete the following information):

- OS: macOS Big Sur
- Version: 11.2.3
- Plutus version or commit hash: master branch, commit, 2087467ca9262e97446f9bb7cc24ac8ad84e1cea

## Screenshots and attachments

- See [InputTxDatumsIssue.hs](https://github.com/mputz86/plutus-personal-playground/blob/e4c933d5d1bfd816fc2fddb9c67589f9421c9b02/src/InputTxDatumsIssue.hs) for an example which
  - Reproduces the error
  - Note: Latest version of this file already applies the workaround from the next section

## Additional context

- Workaround: By using `mustIncludeDatum`, the `Datum` of the inputs can be made available to the transaction and be validated on-chain (by using the `findDatum`). See latest [InputTxDatumsIssue.hs](https://github.com/mputz86/plutus-personal-playground/blob/e9cf9ad014f4f4a5f8d18eae5ddf74dde5eaa103/src/InputTxDatumsIssue.hs)

**Comment by ak3n** [comment]
@mputz86 Thanks for reporting this! Especially for prodiving the repository with code. :)

You can already test the fix in 965aa327545b1a054df36d961b2fb8ea6f53153f as it will take some time to land into master.

**Comment by blocknroll101** [comment]
@ak3n Thanks for the fast fix, works like a charm 😊 .

**Comment by mputz86** [comment]
@ak3n Thanks for the fast fix, works like a charm 😊 👍 .
