### ISSUE TITLE
Unable to use ByteString literals in on-chain code

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3156]
## Area

[*] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

I need to append some constant marker to a token name.
But when I use in on-chain code constant string literals that are meant to be ```ByteString``` ```\bs -> "a" <> bs``` 
I get an error of PLC plugin:

```
Core to PLC plugin: E043:Error: Reference to a name which is not a local, a builtin, 
or an external INLINABLE function: Variable GHC.List.$wlenAcc
           No unfolding
```

## Steps to reproduce

It happens when we use string literals for ```ByteString``` in on-chain code.

## Expected behavior

I would like to append some data to the ByteString in on-chain code.

## System info:

- OS: Manjaro, Linux
- Plutus version or commit hash: 62be7a2d6dff285ad72d5bc6f5f11991ffae888b

**Comment by ak3n** [comment]
Thanks for the issue!

Unfortunately, `ByteString` literals are not supported at all at the moment.

I may suggest to pass constants as a part of datum (fields in ADT) or as arguments for now.

**Comment by kevinhammond** [comment]
Yes, I hit this when trying to prepare the testnet exercises.  I worked around it by using an integer literal. I believe you could also use strings in datums and redeemers.  The problem I hit is partly down to staging in the Plutus compiler (byte strings have some dynamic component - they are not just calculated as compile-time constants).

**Comment by longngn** [comment]
Hi @ak3n, I know that your team is busy and thank you for all the hard work to put Plutus closer to the production launch. I would like to ask if this issue has a high priority on the roadmap? I believe that having this issue fixed would be a great improvement to the developer experience.

**Comment by anton-k** [comment]
Thanks for that!
