### ISSUE TITLE
null (Value.symbols $ lovelaceValueOf 1000) => False

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#3157]
## Area

[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

Value.symbols produces an empty list of CurrencySymbol

```
> lst = Value.symbols $ lovelaceValueOf 1000
> lst
[]
```

which I believe should evaluate to True when given to `null`

```
> null lst
False

> lst == []
False
```

**Comment by tdiesler** [comment]
Perhaps this is a display issue, because
```
> length lst
1
```

**Comment by tdiesler** [comment]
This works ...

```
isSingleAdaSymbol = length lst == 1 && show (head lst) == ""
```

**Comment by ak3n** [comment]
Yeah, it might be ambiguous because the `symbols` function returns a list of `CurrencySymbol`s. And `CurrencySymbol` has a `Show` instance without quotes. And since Ada has an empty symbol, the list with one item looks like an empty list.
