### ISSUE TITLE
Please restore nsswitch.conf in dev container

### ISSUE THREAD

**Issue by wutzebaer** [input-output-hk/plutus#3178]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[X] *Other* Any other topic (Playgrounds, etc.)

## Summary

Someone removed the nsswitch from the dev-container here: https://github.com/input-output-hk/plutus/commit/5dbd3b833b40217cb1a63d4f52351ae8876ba86c

The file tells the system to lookup the hosts file, but without the filt, it won't.

Thats why the container does not work (at least not in windows+wsl2).

My current workaround cen bee seen here: https://cardano.stackexchange.com/questions/382/problem-starting-a-plutus-devcontainer-in-windows/444#444

The problem is that node cannot resolve localhost without the file, even curl can't, for an explaination see https://superuser.com/questions/1648664/curl-6-could-not-resolve-host-localhost

## Steps to reproduce

1. create a dev container with the commit 5dbd3b833b40217cb1a63d4f52351ae8876ba86c or later
2. Try to run it with VSCode on windows 10 with wsl2 and docker for windows

## System info (please complete the following information):

- OS: Windows
- Version 10
- Plutus version or commit hash 5dbd3b833b40217cb1a63d4f52351ae8876ba86c

**Comment by silky** [comment]
Thanks for reporting this @wutzebaer , and for the solution! :)

I've added it back in in this repo, and also a new image has been built on dockerhub - https://hub.docker.com/r/inputoutput/plutus-starter-devcontainer - are you able to check if this works for you?

**Comment by wutzebaer** [comment]
Hi @silky i've tried commit b5836c354f45f089fc3801196e68fb492c21a88b it fixes the issue, thank you!

**Comment by luigy** [comment]
Looks like this has been resolved by @silky :). Closing for now, but please re-open if there is still something missing
