### ISSUE TITLE
Make ScriptContext available for state transition function smTransition

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3190]
## Area

[*] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Describe the feature you'd like

I'd like to have 

```haskell
smTransition ::  ScriptContext -> State s -> input -> Either String (TxConstraints Void Void, State s)
```
and no separate ```smCheck``` function.

Right now we have two validation functions for state machine: ```smTransition``` and ```smCheck```.
Is there a need for separate ```smCheck``` function if failure can be expressed with ```smTransition``` that returns ```Nothing```?
Sometimes you might need info from ```ScriptContext``` to be available at state transition. 
For example I would be happy to use ```txInfoValidRage``` inside transition to query the current time.

This way we can use only one function if we augment ```smTrnasition``` parameter list with ```ScriptContext```.

Current approach with splitting the transition function to two separate functions seems to be artificial from the user point of view.
It prohibits some useful usage scenarios and can be expressed in simpler way. But maybe there are some details of implementation that I'm not aware of.

**Comment by ak3n** [comment]
The idea is that it allows to apply the same logic in both places: creating transactions off-chain and validating them on-chain, without having to duplicate the logic. If your case is such that you need to depend on `ScriptContext` then it's better to write a custom validator.

`smCheck` might look unnecessary but it's an useful escape hatch for rare cases that require some clever checks on chain.
