### ISSUE TITLE
Plutus-Playground-Client Actions Blocks Not Incrementing Labels

### ISSUE THREAD

**Issue by getHashSet** [input-output-hk/plutus#3196]
## Area

- [ ] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
- [ ] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
- [ ] *Marlowe* Related to Marlowe
- [x] *Other* Any other topic (Playgrounds, etc.)

## Summary

When using multiple Wallets or multiple **Actions** with the same Wallet; Labels and Id's are not incrementing for actions. This causes an issue where selecting a label on one action results in changing the value of an input on a different action.

This was tested with Plutus-Pioneer [Homework 2 from Week 2](https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week02/src/Week02/Solution2.hs) using Plutus from commit 04ffe90 off the [master branch](https://github.com/input-output-hk/plutus).

## Steps to reproduce

1. Launch a local build of the plutus-playground from a browser that allows the inspection of elements on the DOM.

2. Paste the code from the **# Additional Context** section of this Issue ticket into the web editor.

3. Click **Compile**

4. Click **Simulate**

5. Instantiate the genesis transaction with at least **1 Wallet**. However this is reproducible by multiple wallets.

6. Select the **grab +** action for a wallet.

7. Select the **grab +** action for the same wallet or a second wallet.

8. Note that selecting the Bool value by its lable on the second Action Block will toggle the Bool value for the first action block.

9. Inspect the elements and not that both have a label targeting **_1** in the **for** property. Additionally the parent elements all share the same **ID** of **_1**.

## Expected behavior

Labels should increment with the block and select its own parent and sibling elements. Selecting a label in one action should not change the value of an input on another action.

## System info (please complete the following information):

- OS: Windows 10, Brave Browser
- Version 10.0.19041 Build 19041
- Plutus commit 04ffe90 master branch

## Screenshots and attachments

![image](https://user-images.githubusercontent.com/53285976/118405154-4147b700-b62b-11eb-9f98-fc27c41c3452.png)

## Additional context

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE NoImplicitPrelude #-}

module Week02.Homework1 where

import Control.Monad hiding (fmap)
import Data.Map as Map
import Data.Text (Text)
import Data.Void (Void)
import Ledger hiding (singleton)
import Ledger.Ada as Ada
import Ledger.Constraints as Constraints
import qualified Ledger.Scripts as Scripts
import qualified Ledger.Typed.Scripts as Scripts
import Playground.Contract (ensureKnownCurrencies, printJson, printSchemas, stage)
import Playground.TH (mkKnownCurrencies, mkSchemaDefinitions)
import Playground.Types (KnownCurrency (..))
import Plutus.Contract hiding (when)
import PlutusTx (Data (..))
import qualified PlutusTx
import PlutusTx.Prelude hiding (Semigroup (..), unless)
import Text.Printf (printf)
import Prelude (Semigroup (..))

{-# INLINEABLE mkValidator #-}
-- This should validate if and only if the two Booleans in the redeemer are equal!
mkValidator :: () -> (Bool, Bool) -> ScriptContext -> Bool
mkValidator _ (a, b) _ = a == b -- FIX ME!

data Typed

instance Scripts.ScriptType Typed where
  type DatumType Typed = ()
  type RedeemerType Typed = (Bool, Bool)

inst :: Scripts.ScriptInstance Typed
inst =
  Scripts.validator @Typed -- FIX ME!
    $$(PlutusTx.compile [||mkValidator||])
    $$(PlutusTx.compile [||wrap||])
  where
    wrap = Scripts.wrapValidator @() @(Bool, Bool)

validator :: Validator
validator = Scripts.validatorScript inst -- FIX ME!

-- valHash :: Ledger.ValidatorHash
-- valHash = Scripts.validatorHash validator -- FIX ME!

scrAddress :: Ledger.Address
scrAddress = scriptAddress validator -- FIX ME!

type GiftSchema =
  BlockchainActions
    .\/ Endpoint "give" Integer
    .\/ Endpoint "grab" (Bool, Bool)

give :: (HasBlockchainActions s, AsContractError e) => Integer -> Contract w s e ()
give amount = do
  let tx = mustPayToTheScript () $ Ada.lovelaceValueOf amount
  ledgerTx <- submitTxConstraints inst tx
  void $ awaitTxConfirmed $ txId ledgerTx
  logInfo @String $ printf "made a gift of %d lovelace" amount

grab :: forall w s e. (HasBlockchainActions s, AsContractError e) => (Bool, Bool) -> Contract w s e ()
grab bs = do
  utxos <- utxoAt scrAddress
  let orefs = fst <$> Map.toList utxos
      lookups =
        Constraints.unspentOutputs utxos
          <> Constraints.otherScript validator
      tx :: TxConstraints Void Void
      tx = mconcat [mustSpendScriptOutput oref $ Redeemer $ PlutusTx.toData bs | oref <- orefs]
  ledgerTx <- submitTxConstraintsWith @Void lookups tx
  void $ awaitTxConfirmed $ txId ledgerTx
  logInfo @String $ "collected gifts"

endpoints :: Contract () GiftSchema Text ()
endpoints = (give' `select` grab') >> endpoints
  where
    give' = endpoint @"give" >>= give
    grab' = endpoint @"grab" >>= grab

mkSchemaDefinitions ''GiftSchema

mkKnownCurrencies []
```

**Comment by luigy** [comment]
Thanks for the detailed report. I managed to reproduce and put up a tentative fix
