### ISSUE TITLE
Fetch the current balance of the contract

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#3247]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like
Greetings, I was coding a smart contract and I would like to know if there's any way to check the current balance of the contract when using a state machine.

## Describe alternatives you've considered
I know that there's a way of checking the current state (example):
```hs
currentState <- SM.getOnChainState client
case currentState of
        Just ((TypedScriptTxOut{tyTxOutData=(x)}, _), _) -> pure (Just x)
        _ -> pure Nothing
```
But I cannot discover if I can also use `getOnChainState` to fetch the Value of the deposit ADA on the contract.

Sorry that this is not really a feature request and just a general question but I didn't know where to ask :/
Thank you for your attention

**Comment by LendaDeAfonselio** [comment]
After analyzing the contracts `plutus-use-cases` and studying the API I discovered that this function should do the trick (tested on the playground using the Game example):
```hs
import           Ledger                    (Value, txOutTxOut)
import           Ledger.Contexts          as Cont
...
getFundsFromContract  :: AsContractError e => Contract GameSchema e (Value)
getFundsFromContract = do 
    utxos <-  utxoAt <contractAddress>
    let totalVal = foldMap (Cont.txOutValue . txOutTxOut) $ map snd $ Map.toList utxos
   -- optional log just to see if everything is ok
    logInfo @String $ show totalVal 
    return totalVal
```

**Comment by ak3n** [comment]
That's great!

Feel free to reopen or if you will have questions or issues.
