### ISSUE TITLE
Plutus Playground failing to recognize endpoints

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#3310]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary
Hello, I have been trying a multitude of smart contract on the _online_ version of the playground(https://playground.plutus.iohkdev.io/) and I am encountering some problems when trying to compile contracts with five or more endpoints.
For example when compiling this [BuyerSeller](https://gist.github.com/LendaDeAfonselio/362569be6987ca71cb3f0aec34dbcc39) contract the playground presents a message saying that the compilation failed and the endpoint request timed out. When I change the definition of the schema to:
```hs
type BuyerSellerSchema = 
    BlockchainActions
        .\/ Endpoint "acceptOrder" ()
        .\/ Endpoint "failedOrder" ()
        .\/ Endpoint "itemSold" (Integer)
        .\/ Endpoint "orderInit" (Integer)
        .\/ Endpoint "rejectOrder" ()
```
 and update the rest of the [code](https://gist.github.com/LendaDeAfonselio/08beffc4f283b6a29c8547c4dd58381e) I manage to compile the contract and run it successfully.

For this [fruit purchasing contract](https://gist.github.com/LendaDeAfonselio/a7ea2e2beb9053ebb36b9c4914ec003b) applying similar changes don't solve the problem.

Therefore I wanted to ask if this is something I'm missing regarding the definition of the schema, receiving parameters in endpoints, or something amongst those lines or if it is a current limitation of the playground.
Thank you for your time!
## Steps to reproduce
1. Copy the code from the gists to the Plutus playground
2. Compile

## Expected behavior
Being able to compile both of these contracts

## System info (please complete the following information):
N/A

## Additional context
Gists:
BuyerSeller: https://gist.github.com/LendaDeAfonselio/362569be6987ca71cb3f0aec34dbcc39
BuyerSellerV2: https://gist.github.com/LendaDeAfonselio/08beffc4f283b6a29c8547c4dd58381e
BuyFruit: https://gist.github.com/LendaDeAfonselio/a7ea2e2beb9053ebb36b9c4914ec003b

**Comment by ak3n** [comment]
Hi! Thanks for the question!

The problem might be with the outdated version of the released playground. The newest version of playground have fixes for endpoints type operators (including `.\/`) and should compile without problems.

Please try this staging https://staging.plutus.iohkdev.io/ it has the recent version of the Plutus playground. But staging still might be not good enough for big contracts as staging machine might have a limited resources and it's better to use the local playground.

Feel free to reopen the issue if you will have any questions!
