### ISSUE TITLE
PAB Uniswap example no longer working

### ISSUE THREAD

**Issue by brunjlar** [input-output-hk/plutus#3311]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

The `plutus-uniswap` example from `plutus-pab` is no longer working: It hangs after invoking the `funds` endpoint.

## Steps to reproduce

1. Enter a `nix-shell` in the top-level folder.
2. Change directory to `plutus-pab`.
3. Execute `cabal run plutus-uniswap`.
4. Notice in the log that only one "Uniswap user" contract is started and that the corresponding funds are never displayed.

## Expected behavior

The "Uniswap user" contract should be started for Wallets 1-4, and Wallet 2 should create a liquidity pool.

## System info (please complete the following information):

- OS: Arch Linux
- Version [e.g. 20.04]
- Plutus version or commit hash: 13da6d416b2b47cdb6f287ff078b9e759bb90b7f

## Additional context

It seems the `funds` endpoint is called before it is ready, and then the program blocks, because it is waiting for a status
change that never happens.

**Comment by luigy** [comment]
Thanks for the fix #3312 . Verified that this is now displaying funds in 1e1c4d3dc74b7f27b0a7b3b6f209f05df8ab0b0a . Please reopen if there are more things to fix for uniswap
