### ISSUE TITLE
How to make plutus work with ghcid+ cabal new-repl

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3330]
## Area

[*] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Describe the feature you'd like

It's cool to be able to work with plutus over ghcid and enable hot code reload with 

```
ghcid -c "cabal new-repl my-shiny-plutus-project"
```
But unfortunately Plutus plugin fails to load to ghci. Can you propose flags or command 
how to run it with ghcid? And it would be nice if that was documented in the README.md of the project.

**Comment by luigy** [comment]
@anton-k does even `cabal new-repl my-shiny-plutus-project` work?

**Comment by anton-k** [comment]
It does not work, although I can build with `cabal new-build`.
it means that flags are different for ghci and cabal build

**Comment by anton-k** [comment]
But being able to is  with ghcid is way better approach

**Comment by luigy** [comment]
@anton-k are you seeing similar plugin errors as in https://github.com/input-output-hk/plutus/issues/3186 ? You might want to try adding those pragmas though I still wonder how ghci ends up being invoked that it only fails there and not in build

**Comment by anton-k** [comment]
No it's not related. Because I it works with `cabal new-build`.
I've already set those pragmas

**Comment by anton-k** [comment]
I think we need to specify with ghci that we want to use that plugin. 
Or ghci uses another set of flags then `new-build`. It would be goot to know how to work around this

**Comment by luigy** [comment]
hmm in #3186 it was also working with `new-build` but failed in the interpreter but somehow the pragmas ended up being required in more files than in `new-buidl` for the `repl`

**Comment by anton-k** [comment]
Thanks, i'll try to investigate

вт, 8 июн. 2021 г., 20:01 Luigy Leon ***@***.***>:

**Comment by luigy** [comment]
I was assuming that this may be happening even after following the [plutux-tx readme](https://github.com/input-output-hk/plutus/tree/master/plutus-tx#building-projects-with-plutus-tx) ? if that's the case if you can get a minimal repro I would like to take a closer look

Another place that makes use of this is in the [plutus-starter repo](https://github.com/input-output-hk/plutus-starter/blob/be2c8332af28b2c4f0f4ecdc4bab7d2026ad8f72/plutus-starter.cabal#L41) linked from the plutus [readme](https://github.com/input-output-hk/plutus#how-to-depend-on-the-project-from-another-haskell-project) though discoverability could be better

**Comment by ak3n** [comment]
Well, I have tried `ghcid -c "cabal new-repl plutus-starter"` and it works fine.

I'm closing the issue, but feel free to reopen the issue if there will be any questions.
