### ISSUE TITLE
plutus starter error on upgrade plutus dependency

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#3332]
I am trying to upgrade plutus branch in plutus-starter project
source-repository-package
  type: git
  location: https://github.com/input-output-hk/plutus.git
  subdir: 
    freer-extras
    playground-common
    plutus-core 
    plutus-contract 
    plutus-ledger
    plutus-ledger-api 
    plutus-tx 
    plutus-tx-plugin 
    plutus-pab
    plutus-use-cases
    prettyprinter-configurable
    quickcheck-dynamic
    word-array
  tag: 6f834b5ca2276cb4bde0f25d8bf9518c3ff592b7

When I try to build it, I get next errors
Seems it was broken after merge
https://github.com/input-output-hk/plutus/pull/2933

Errors:
[ 7 of 20] Compiling Plutus.V1.Ledger.Scripts ( src/Plutus/V1/Ledger/Scripts.hs, dist/build/Plutus/V1/Ledger/Scripts.o, dist/build/Plutus/V1/Ledger/Scripts.dyn_o )

src/Plutus/V1/Ledger/Scripts.hs:86:21: error:
    • Overlapping instances for Flat [a]
        arising from the 'deriving' clause of a data type declaration
      Matching instances:
        instance [overlappable] Flat a => Flat [a]
          -- Defined in ‘Flat.Instances.Base’
        instance [overlapping] Flat [Haskell.Char]
          -- Defined in ‘Flat.Instances.Base’
      (The choice depends on the instantiation of ‘a’
       To pick the first instance above, use IncoherentInstances
       when compiling the other instance declarations)
    • When deriving the instance for (Flat Script)
   |
86 |   deriving newtype (Flat)
   |                     ^^^^

--------
[16 of 16] Compiling PlutusTx.Plugin  ( src/PlutusTx/Plugin.hs, dist/build/PlutusTx/Plugin.o, dist/build/PlutusTx/Plugin.dyn_o )

src/PlutusTx/Plugin.hs:289:38: error:
    • Overlapping instances for Flat.Class.Flat [a]
        arising from a use of ‘flat’
      Matching instances:
        instance [overlappable] Flat.Class.Flat a => Flat.Class.Flat [a]
          -- Defined in ‘Flat.Instances.Base’
        instance [overlapping] Flat.Class.Flat [Char]
          -- Defined in ‘Flat.Instances.Base’
      (The choice depends on the instantiation of ‘a’
       To pick the first instance above, use IncoherentInstances
       when compiling the other instance declarations)
    • In the second argument of ‘($)’, namely ‘flat pirP’
      In a stmt of a 'do' block:
        bsPir <- makeByteStringLiteral $ flat pirP
      In the expression:
        do flags <- GHC.getDynFlags
           famEnvs <- asks pcFamEnvs
           opts <- asks pcOpts
           nameInfo <- makePrimitiveNameInfo builtinNames
           ....
    |
289 |     bsPir <- makeByteStringLiteral $ flat pirP

**Comment by luigy** [comment]
@volodyad seems like you may be also missing one more dep for the bump in your [cabal.project](https://github.com/input-output-hk/plutus/blob/1e1c4d3dc74b7f27b0a7b3b6f209f05df8ab0b0a/cabal.project#L65-L69) ?
```
-- Drops an instance breaking our code. Should be released to Hackage eventually.
source-repository-package
  type: git
  location: https://github.com/Quid2/flat.git
  tag: 95e5d7488451e43062ca84d5376b3adcc465f1cd

```

**Comment by volodyad** [comment]
Thank you @luigy , it helped
