### ISSUE TITLE
assertAccumState failure if multiply contracts activated for the same wallet

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#3359]
I need to activate two contract instances via Trace.activateContractWallet,
I need to generate token via Currency.forgeCurrency and the activate my contract 

Trace.activateContractWallet w1 Currency.forgeCurrency
Trace.activateContractWallet w1 MyContract

In my test I use assertAccumState MyContract Trace.walletInstanceTag w1

It throws an error: 
Failed to decode a 'Response JSON.Value'. The event is probably for a different 'Contract'. This is often caused by having multiple contract instances share the same 'ContractInstanceTag' (for example, when  using 'activateContractWallet' repeatedly on the same wallet). To fix this, use 'activateContract' with a unique 'ContractInstanceTag' per instance.
      InstanceStateJSONDecodingError "empty" (Response {rspRqID = RequestID 1, rspItID = IterationID 1, rspResponse = Object (fromList [("tag",String "create"),("value",Object (fromList [("unEndpointValue",Object (fromList [("fnpTokenName",Object (fromList [("unTokenName",String "nonMarketNft")]))]))]))])})

**Comment by luigy** [comment]
`Trace.activateContractWallet` is convenient, but useful only for single contract instance per wallet which is not the case here. Instead use `Trace.activeContract` directly to enforce a unique contract instance tag. i.e.:
```hs
Trace.activateContract w1 Currency.forgeCurrency (fromString "forgeCurrency: " <> Trace.walletInstaceTag w1) 
Trace.activateContract w1 MyContract (fromString "MyContract: " <> Trace.walletInstaceTag w1) 
```

**Comment by volodyad** [comment]
Got it, thank you
