### ISSUE TITLE
plutus-starter-devcontainer fails on `cabal build`: undefined symbol: crypto_vrf_seedbytes

### ISSUE THREAD

**Issue by DanTup** [input-output-hk/plutus#3405]
I tried following the instructions here:

https://github.com/input-output-hk/plutus-starter

I cloned the repo, opened it in VS Code, agreed to reload in the container, created ~/.cabala/packages` on the host, then ran `cabal update` and `cabal build`. After some time, the build fails with:

> <command line>: /home/plutus/.cabal/store/ghc-8.10.4.20210212/cardano-crypto-praos-2.0.0-c472312d35bcc73cb6cf5cc50ee014b0c296bcdb54a194838b840d4b38151f9a/lib/libHScardano-crypto-praos-2.0.0-c472312d35bcc73cb6cf5cc50ee014b0c296bcdb54a194838b840d4b38151f9a-ghc8.10.4.20210212.so: undefined symbol: crypto_vrf_seedbytes

The full output is here: https://gist.github.com/DanTup/427bdc6b311721df78307868a8ecd173

**Comment by ak3n** [comment]
Looks like a missing library. Please try to install `libsodium libsodium-dev` in your system.

**Comment by DanTup** [comment]
@ak3n isn't the purpose of the [dev container](https://github.com/input-output-hk/plutus-starter#vscode-devcontainer) to include everything required and not need anything on the host? If this is missing, shouldn't the container be built with it?

**Comment by ak3n** [comment]
Yeah, that's right. Sorry, I missed how `devcontainer` is made.

**Comment by silky** [comment]
@DanTup - Can you confirm that you're using the plutus-container tagged v1.0.6 ( and if not, try it ) ? ( https://hub.docker.com/layers/inputoutput/plutus-starter-devcontainer/v1.0.6/images/sha256-189b674ac477eaea0e67b3ab78e0f21026342eb23304ec918896fa3ae48b88f0?context=explore )

( There's a PR to fix this - https://github.com/input-output-hk/plutus-starter/pull/16 )

**Comment by DanTup** [comment]
Yep, I was using 1.0.6. I think I didn't have this problem a few weeks ago using the previous one, but it seemed quite out of date so I had been waiting for an update.

I tried rebuilding the container, running `cabal update` etc., with no luck (though as a Haskell noob, I didn't understand enough about the error to know how to properly debug).

I also tried skipping the dev container and using the base `haskell` image directly and cloning the Plutus repo into it, but I hit a possibly-related issue doing that too:

```
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
```

For that one it seemed more reasonable that I should be installing dependencies myself (since it was a generic Haskell container, not one specifically created for Plutus) although I failed to fix that too (most of the fixes I found seemed macOS specific, or at least depended on specific paths that didn't exist in that container for me).

**Comment by silky** [comment]
@DanTup

Thanks for the quick response :)

Yes, running from the base Haskell container is probably a bit too hopeful an approach 😀 .

I think perhaps the reason it doesn't work with _only_ the 1.0.6 container is that you'll also need to update the other items as-per that PR; namely the cabal.project ( https://github.com/input-output-hk/plutus-starter/pull/16#discussion_r651997157 ) and the `devcontainer.json` change:

```
    "image": "docker.io/inputoutput/plutus-starter-devcontainer:v1.0.6",
```

If you're up for trying that; let me know what happens, and in the mean time I'll see if we can get that open PR merged and that should hopefully sort this problem out.

**Comment by DanTup** [comment]
I did

```
git remote add obsidiansystems git@github.com:obsidiansystems/plutus-starter.git
git checkout obsidiansystems/ll/bump-plutus
cabal update
cabal build
```

But it still failed in the same way.

```
[42 of 49] Compiling Cardano.Api.Block ( src/Cardano/Api/Block.hs, dist/build/Cardano/Api/Block.o, dist/build/Cardano/Api/Block.dyn_o )
<command line>: /home/plutus/.cabal/store/ghc-8.10.4.20210212/cardano-crypto-praos-2.0.0-c472312d35bcc73cb6cf5cc50ee014b0c296bcdb54a194838b840d4b38151f9a/lib/libHScardano-crypto-praos-2.0.0-c472312d35bcc73cb6cf5cc50ee014b0c296bcdb54a194838b840d4b38151f9a-ghc8.10.4.20210212.so: undefined symbol: crypto_vrf_seedbytes
cabal: Failed to build cardano-api-1.27.0 (which is required by
exe:plutus-starter-pab from plutus-starter-0.1.0.0). See the build log above
for details.
```

Full output is here:

https://gist.github.com/DanTup/0b8453d5aeeea46191ea3b7851a2fda6

To verify I had the right change:

```
[devcontainer]$ git log -n 1
commit 7b3a1c6b5139d28b2d1b1671f3258f4797175aff (HEAD, obsidiansystems/ll/bump-plutus)
Author: Luigy Leon <luigy.leon@obsidian.systems>
Date:   Tue Jun 15 10:49:34 2021 -0400

    Bump plutus
```

```
[devcontainer]$ git diff
diff --git a/.devcontainer/devcontainer.json b/.devcontainer/devcontainer.json
index aaea1e0..fe8bbe0 100644
--- a/.devcontainer/devcontainer.json
+++ b/.devcontainer/devcontainer.json
@@ -1,6 +1,6 @@
 {
     "name": "Plutus Starter Project",
-    "image": "docker.io/inputoutput/plutus-starter-devcontainer:latest",
+    "image": "docker.io/inputoutput/plutus-starter-devcontainer:v1.0.6",
 
     "remoteUser": "plutus",
 
[devcontainer]$ 
```

(I updated the devcontainer file to have the image version explicitly).

**Comment by michaelpj** [comment]
You may need to completely clear out `~/.cabal/store` after moving to the new devcontainer, otherwise cabal may retain some files in there that link to the wrong `libsodium`. (You can potentially be more discriminating, but it's tedious, nuking `~/.cabal/store` is easier).

**Comment by DanTup** [comment]
I'll give it a go tonight, although my understanding was that [only `~/.cabal/packages` from the host was amounted into the container](https://github.com/input-output-hk/plutus-starter/blob/fb1c5e245a491f570464839f675b8e9cb7623d14/.devcontainer/devcontainer.json#L11), so other folders would've been wiped out already with the container rebuild.

**Comment by michaelpj** [comment]
That's true, good point! Indeed the container rebuild should have got rid of that. That seems strange, then!

**Comment by DanTup** [comment]
Interestingly, I just nuked `~/.cabal` from my host, and all containers from Docker and started again. I did _not_ delete the cached Docker source images (only the containers VS Code had created and left around). When I opened the project, it said it was downloading v1.0.6 of the container image (suggesting it had not been cached locally).

I can't explain why rebuilding the container yesterday wouldn't have already fetched that, but perhaps it will help. It'll be a while before `cabal build` finishes, but I'll post back when it does if it made any difference or still has the same issue.

**Comment by DanTup** [comment]
Looks promising!

```
Building     cardano-api-1.27.0 (lib)
Installing   cardano-api-1.27.0 (lib)
Completed    cardano-api-1.27.0 (lib) <---
Starting     plutus-pab-0.1.0.0 (lib)
```

**Comment by DanTup** [comment]
(Yep, it all completed successfully! 🎉)

**Comment by silky** [comment]
Awesome @DanTup 

Yeah, when I've been playing around with vscode I've noticed it's quite hard to coax it to re-build the devcontainer image; glad you got it all working :)

**Comment by DanTup** [comment]
I was using the explicit "Rebuild Container" command and it did look like it rebuilt - although I wonder whether rebuild just reuses the same image it previously had, rather than looking at `devcontainer.json` again where I may have changed the tag.

In any case, it's working for me now (by using that PRs branch), and I presume the same will be true for everyone once the PR is merged and an updated container pushed.

Thanks for the help!
