### ISSUE TITLE
Is it possible to query blockchain datums, UTXOs by address over PAB API?

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3418]
## Area

[*] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

I'm writing an crypto-exchange platform. I would like to query the rate of exchange.
I can easily do it in the Contract monad by reading corresponding datum. but is it possible to query this info
over PAB servant API?

Am I missing some endpoint or is it not implemented yet?

**Comment by ak3n** [comment]
Well, there is nothing special for this kind of operations in PAB. But it can be implemented as usual endpoint if I got the idea.

There is [`Plutus.PAB.Webserver.API`](https://github.com/input-output-hk/plutus/blob/master/plutus-pab/src/Plutus/PAB/Webserver/API.hs#L42) that exports `NewAPI` — an interface for querying the contracts.

There is an example in `plutus-pioneer-program` in `week06`.

- The client that calls `funds` endpoint https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week06/app/swap-client.hs#L55
- Endpoint's implementation https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week06/src/Week06/Oracle/Swap.hs#L200

**Comment by anton-k** [comment]
Thanks, I see. I need to implement endpoint that saves the data that I need with tell of Contract monad.
And then I can fetch it with `status`-method
