### ISSUE TITLE
Specification of plutus core is outdated

### ISSUE THREAD

**Issue by GuillaumeGen** [input-output-hk/plutus#3420]
## Area

[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

The Plutus Core files generated using the `goldenPir` function (as well as the ones presented in the folder https://github.com/input-output-hk/plutus/tree/master/plutus-tx-plugin/test/Plugin ) do not respect the specification given in https://github.com/input-output-hk/plutus/tree/master/plutus-core-spec (a compiled version: https://hydra.iohk.io/build/6622610/download/1/plutus-core-specification.pdf ).
More precisely, the generated files contain keywords, like `let`, `datatypebind`, `termbind`, `vardecl` or `tyvardecl` which are not mentioned in specification.

**Comment by michaelpj** [comment]
That's not Plutus Core, that's Plutus IR.

**Comment by GuillaumeGen** [comment]
Thank you for your fast answer. It turns my remark into two questions:
 - Is there a specification of Plutus IR?
 - How can I generate Plutus Core files?
