### ISSUE TITLE
Running plutus playground

### ISSUE THREAD

**Issue by HT-Moh** [input-output-hk/plutus#3437]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

Trying to run Plutus playground on my `Ubuntu 21.04` laptop, I installed nix `sh <(curl -L https://nixos.org/nix/install)` , cloned the repository ( tested both master and 3746610e536), started the server successfully, however when trying to run the client `npm start`, it does not find the modules, all of them it seems. I suspect something wrong with path, but I am not sure.
where are the packages located? 
 
![image](https://user-images.githubusercontent.com/34759569/123447980-b9b27800-d5da-11eb-9178-c63bc21c6d63.png)

> Note the server is running without any problem 

![image](https://user-images.githubusercontent.com/34759569/123448100-d6e74680-d5da-11eb-9701-caa2c2066156.png)

**Comment by luigy** [comment]
Is this also happening with `npm start`? the screenshot it's showing a different command being invoked
I tested 2ae7a0293f0cfcbfb1d1a35ac84097239639a3fe and after entering a nix-shell and running `npm start` plutus playground is running fine. Make sure the directory is clean

**Comment by HT-Moh** [comment]
Yes I tested `npm start` and all modules not found. 
I started from scratch last version and I got the following error  (commit fd3a906b2bf5c2932d9d3d0e9366e3decf83a83a) 

![image](https://user-images.githubusercontent.com/34759569/123680388-ef5c9880-d848-11eb-9dbe-ffc0dcda8569.png)

**Comment by HT-Moh** [comment]
I tested as well now 2ae7a02 and both server and client are listening, however when navigate to 127.0.0.1:8009 - empty response 

![image](https://user-images.githubusercontent.com/34759569/123694367-8b8e9b80-d859-11eb-944b-1bb6825602fe.png)


![image](https://user-images.githubusercontent.com/34759569/123694334-7f0a4300-d859-11eb-86b2-b50ee7342e8e.png)

**Comment by luigy** [comment]
@HT-Moh try https. `npm start` prints the exact url, but could get lost with all the other output. It should say something like
`Project is running at https://localhost:8009`

**Comment by HT-Moh** [comment]
It does not work  because I am connecting to the machine remotely, running the browser on the machine it self it works. 
I guess the client listens on `127.0.0.1` not `0.0.0.0`. 
`https://127.0.0.1:8009/ ` this works 
`https://192.168.178.32:8009/ `  this does not work (server in the same LAN)

**Comment by HT-Moh** [comment]
To access the playground client remotely I added ` --host 0.0.0.0`  line 6 on `package.json` 

`"webpack:server": "webpack-cli serve --progress --inline --hot --mode=development --node-env=development --host 0.0.0.0"`
