### ISSUE TITLE
Extended integer math operations

### ISSUE THREAD

**Issue by arthurgreef** [input-output-hk/plutus#3449]
## Area

[X] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like
Extended integer mod operations: https://hackage.haskell.org/package/mod
It would also be great to add operations that test if an integer is a prime number.

A clear and detailed description of what you are suggesting.
Extend the basic integer math operations with modular operations necessary for crypto features.

## Describe alternatives you've considered
None.

None.

**Comment by ak3n** [comment]
Thanks for the request!

I guess it's possible to port it to Plutus, but effective implementation would require the extension of the builtins primitives which is undesired at the moment.

The community may port the library or vote on this issue to show interest.
