### ISSUE TITLE
PAB contract instance fails to recover after TX with InsufficientFunds error

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3459]
## Area

[*] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

If PAB instance got hit by TX that causes `InsufficientFunds` then the whole contract instance breaks and no further 
transactions can be submitted over it.

When I get this warning

```
[WARNING] Slot 637: W1: handleTx failed: InsufficientFunds "Total: Value (Map [(,Map
etc 
```
I can no longer submit any other TXs.

When TX is rejected by validation logic the instance stays functional.

## Expected behavior

Instance should recover and be responsive to further TXs

**Comment by anton-k** [comment]
AWhen TX is rejected by validation logic the instance stays functional.

**Comment by ak3n** [comment]
Please try to wrap your contract with `Plutus.Contract.Types.handleError`:

```
import Plutus.Contract

handleError logError $ contract
```

to handle the error properly.
