### ISSUE TITLE
"The connection was reset" when trying to use the playground client

### ISSUE THREAD

**Issue by athanclark** [input-output-hk/plutus#3484]
## Area

- [ ] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
- [ ] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
- [ ] *Marlowe* Related to Marlowe
- [x] *Other* Any other topic (Playgrounds, etc.)

## Summary

I'm trying to use the plutus playground, with respect to the instructions identified by [the week 1 exercise in the pioneer program](https://github.com/input-output-hk/plutus-pioneer-program#exercises). When attempting to view the playground at `http://localhost:8009` or `http://127.0.0.1:8009` while `npm run start` and `plutus-playground-server` are running in separate nix-shells, I am met with an empty reply from the npm client.

## Steps to reproduce

1. Checkout the hash `ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4` in the `plutus/` repo directory.
2. Run `nix-shell` to build & fetch dependencies, and open a second terminal, also running `nix-shell` in the plutus directory.
3. `cd plutus-playground-client` in both terminals, while in the nix shells.
4. Run `plutus-playground-server` in one terminal, waiting for the server to bind to port `8080` to continue.
5. Run `npm run start` in the other terminal, waiting for the notice that `Project is running at https://localhost:8009/` to continue.
6. Attempt to view the playground in a browser at `https://localhost:8009`.
7. Met with a "Connection reset" error in Firefox. Likewise, `curl http://localhost:8009` returns with `curl: (52) Empty reply from server`.

## Expected behavior

The playground loads so I may start testing smart contact code.

## System info (please complete the following information):

- OS: Ubuntu
- Version: 20.04
- Plutus version or commit hash: ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4

## Additional context

I'm not sure if this is related or not, but the `plutus-playground-server` executable generated by `nix-shell` doesn't seem to accept the `--help` argument, or any other argument - it just defaults to the `webserver` behavior. I'm not sure if this is added by default due to nix, or if the attribute in `default.nix` is pointing to a different version than what's inside the repository. I've tried to build the server manually with `cabal build`, and run the executable from within the `dist-newstyle` output directory, but there isn't a change in behavior.

__EDIT__: Here is the "offending" entry for the command made available by nix: https://github.com/input-output-hk/plutus/blob/master/plutus-playground-client/default.nix#L43 - it's intentionally built-in to run the webserver, while generating is performed at compile time (I'm pretty sure).

Likewise, just as a sanity check, I ran `sudo ufw allow from any to any port 8009 proto tcp` and did not see any positive results.

**Comment by mackarelfish** [comment]
I'm having this exact issue running Debian on WSL2, I thought this was a port issue (?)

**Comment by athanclark** [comment]
> I'm having this exact issue running Debian on WSL2, I thought this was a port issue (?)

I thought it was too, and tried opening the firewall, but am still met with empty replies from the npm server. I'm going to dig further and report my findings.

**Comment by mackarelfish** [comment]
> 
> 
> > I'm having this exact issue running Debian on WSL2, I thought this was a port issue (?)
> 
> I thought it was too, and tried opening the firewall, but am still met with empty replies from the npm server. I'm going to dig further and report my findings.

Found a fix, it's an issue with Firefox which wouldn't allow non-certified https, changing https: true to false in the webpack.config.js file on the plutus-playground-client fix the issue for me.

**Comment by athanclark** [comment]
@mackarelfish You're right! This fixed the issue for me too, I'm going to leave this issue open until I submit a PR for documenting it.
