### ISSUE TITLE
Contract's UTXOs are always marked as "unspent" in the second to last slot of playground-client's simulations

### ISSUE THREAD

**Issue by JunBird** [input-output-hk/plutus#3487]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

After a contract's simulation gets evaluated, the plutus-playground-client interface incorrectly shows in the second to last slot's output that an eventual contract's UTXO is marked as unspent, even though it then gets spent in the last slot.

## Steps to reproduce

The [first lecture of the Plutus Pioneer Program's second cohort](https://youtu.be/_zr3W8cgzIQ?t=2848) shows this bug multiple times with the sample [EnglishAuction](https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week01/src/Week01/EnglishAuction.hs) contract.

## Expected behavior

When a slot in a simulation outputs a UTXO, the interface should show when it will get spent in future slots. A UTXO should be marked as "unspent" only if it never gets spent during the simulation.

## System info

- OS: Ubuntu
- Version: 20.04
- Commit hash: ea0ca4e9f9821a9dbfc5255fa0f42b6f2b3887c4

## Screenshots and attachments

![image](https://user-images.githubusercontent.com/44647141/124465293-8a97c580-dd95-11eb-80f6-ec51454ee5c6.png)
![image](https://user-images.githubusercontent.com/44647141/124465319-92576a00-dd95-11eb-9f31-003b86940a78.png)

Notice how in the first screenshot the Wallet 1's UTXO is correctly marked as spent in slot 11, while the contract's UTXO is marked as unspent even though it is another one of the inputs of slot 11.

**Comment by luigy** [comment]
Thanks for the report! I was able to reprod and put up a fix
