### ISSUE TITLE
State Machine computational overhead

### ISSUE THREAD

**Issue by LendaDeAfonselio** [input-output-hk/plutus#3489]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

Hello, I have been coding smart contracts in Plutus to study the programming language and I regularly use the state machine library. 

I have some questions regarding it's efficiency, in particular is the state machine just as, or more efficient then contracts that do not use it? How will the overhead be for the network? Is there any way I can test this so I can have a good idea on which situations it might not be a very good idea to use the state machine and in which situations the state machine thrives since this is very important aspect in "realistic scenario"

I suggest making documentation for this of information easily available (maybe I'm missing it), if anyone can in the meantime answer some of my questions it would be greatly appreciated, thank you!

## Describe alternatives you've considered

N/A

## Additional context / screenshots

N/A

**Comment by ak3n** [comment]
Thanks for the question!

StateMachine is just a helpful abstraction written in Plutus. There is nothing specific about it (no any specific efficient implementation). It's the same code as logic implemented by yourself.

Yes, it's possible that in some rare situations StateMachine's logic might be less efficient than hand-written, but it's not because StateMachine is doing poorly, it means that the logic might be incorrect and needs a more detailed approach.

**Comment by LendaDeAfonselio** [comment]
> Thanks for the question!
> 
> StateMachine is just a helpful abstraction written in Plutus. There is nothing specific about it (no any specific efficient implementation). It's the same code as logic implemented by yourself.
> 
> Yes, it's possible that in some rare situations StateMachine's logic might be less efficient than hand-written, but it's not because StateMachine is doing poorly, it means that the logic might be incorrect and needs a more detailed approach.

Is there anyway I can test how "efficient" the code is (i.e. get metrics about usage of ram/cpu and times)?

**Comment by ak3n** [comment]
It's possible to use [`Plutus.V1.Ledger.Api.evaluateScriptCounting`](https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs#L209) to get the budget that will approximate the execution cost. But it might be hard to use it outside of the emulator at the moment.

The budget information will be provided in the emulator output in the near future.

**Comment by LendaDeAfonselio** [comment]
> 
> 
> It's possible to use [`Plutus.V1.Ledger.Api.evaluateScriptCounting`](https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs#L209) to get the budget that will approximate the execution cost. But it might be hard to use it outside of the emulator at the moment.
> 
> The budget information will be provided in the emulator output in the near future.

Thank you so much!
