### ISSUE TITLE
ByteString literals fail to compile

### ISSUE THREAD

**Issue by kozross** [input-output-hk/plutus#3518]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

``ByteString`` literals do not compile. For example, this will fail to compile:

```haskell
test :: CompiledCode ByteString
test = $$(compile [|| "snacks" ||])
```

## Steps to reproduce

1. Put the above example into a source file.
2. Try to compile it.
3. Watch the errors appear.
4. Lament your woes.

## Expected behavior

The `ByteString` literal should compile.

## System info (please complete the following information):

- OS: Arch
- Plutus version or commit hash: According to `cabal freeze` file:

```
any.plutus-contract ==0.1.0.0,
any.plutus-core ==0.1.0.0,
any.plutus-ledger ==0.1.0.0,
any.plutus-ledger-api ==0.1.0.0,
any.plutus-pab ==0.1.0.0,
any.plutus-tx ==0.1.0.0,
any.plutus-tx-plugin ==0.1.0.0,
any.plutus-use-cases ==0.1.0.0,
```

**Comment by ak3n** [comment]
Hi! Thanks for the issue! Yeah, it's a known problem (#3156). Should be fixed soon.

I'm closing this one as a duplicate.
