### ISSUE TITLE
Unable to scroll through results when using Haddock Quick Jump

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/plutus#3541]
## Area

[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

When using Quick Jump in the Plutus Haddock, if the list of results is long enough to go off the bottom of the page then a scroll bar is displayed but it is not possible to scroll down. Tried with mouse wheel, clicking on scroll bar and using arrow keys.

## Steps to reproduce

1. Go to https://staging.plutus.iohkdev.io/doc/haddock/index.html
2. Click on 'Quick Jump' in the top right corner
3. Type 'val'
4. See list of results that requires scrolling
5. Attempt to scroll...

## Expected behavior

Is possible to scroll down and view all results

## System info (please complete the following information):

- OS: Linux Mint 
- Version: 20 (Ulyana)
- Browser: Brave Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
- Plutus commit hash: bfc2e4a3f598115d50b3fa685089d97f2f5f30e9

## Screenshots and attachments

![image](https://user-images.githubusercontent.com/74595920/125466002-f402afe2-9ce9-4f38-83ed-668fa1906278.png)

**Comment by luigy** [comment]
I tested this works fine in Firefox, but not in Chromium.  This is an upstream haddock issue that was fixed by https://github.com/haskell/haddock/pull/1235 . I'll need to take a closer look how the docs are being generated in case we can patch this locally without much effort

**Comment by luigy** [comment]
@james-iohk I took a closer look at docs generation and put up a fix https://github.com/input-output-hk/plutus/pull/3542 . Would be great if you can give it a test
