### ISSUE TITLE
PAB setup results in "Error in $.pabWebserverConfig: parsing Plutus.PAB.Types.WebserverConfig(WebserverConfig) failed, key \"permissiveCorsPolicy\" not found"

### ISSUE THREAD

**Issue by lemmon-714** [input-output-hk/plutus#3551]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

Following the instructions here:
[https://github.com/input-output-hk/plutus/tree/master/plutus-pab](https://github.com/input-output-hk/plutus/tree/master/plutus-pab)
results in (multiple copies of)
`AesonException "Error in $.pabWebserverConfig: parsing Plutus.PAB.Types.WebserverConfig(WebserverConfig) failed, key \"permissiveCorsPolicy\" not found"`

Both locally (macOS) and in the Docker (more important; see below for details)

## Steps to reproduce

1. create Dockerfile:
```
FROM nixos/nix

#preliminaries
RUN nix-env -i git

RUN echo "substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/" >> /etc/nix/nix.conf
RUN echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" >> /etc/nix/nix.conf

RUN git clone https://github.com/input-output-hk/plutus.git

#build
WORKDIR /plutus/plutus-pab

RUN nix-build ../default.nix -A plutus.haskell.packages.plutus-pab

#run
RUN nix-build ../default.nix -A plutus-pab.demo-scripts
#plutus-pab: AesonException "Error in $.pabWebserverConfig: parsing Plutus.PAB.Types.WebserverConfig(WebserverConfig) failed,
#key \"permissiveCorsPolicy\" not found"
```
2. run
 `docker build -t pab .`

## Expected behavior

Builds without error.

## System info (please complete the following information):

- OS: [MacOS]
- Version [Big Sur]
- Plutus version or commit hash: latest

## Screenshots and attachments

- If applicable, add screenshots, config files and/or logs to help explain the problem.
- If the issue is related to the Plutus Playground, please include a link to a gist that reproduces the issue

## Additional context

Maybe my approach with setting up the Docker is wrong; if so, please let me know.

**Comment by luigy** [comment]
Thanks for the report! I was able to reproduce. Fix upcoming

**Comment by luigy** [comment]
Fix is merged. Thanks for the report
