### ISSUE TITLE
Failed to build plutus-core from alonzo-white sources

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#3567]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

I cannot build Alonzo-testnet sources from a plutus nix-shell. This used to be the only way I could get HLS integration working in the Atom editor.

In general, I seem to spend far too much time trying to setup a decent working environment. Given that this is likely multiplying for everyone trying to do stuff on the alonzo-white testnet, we should fix this.

Please work with me to get decent docs out. I personally have ...

* MacOS
* ghcup
* Atom

Related: https://github.com/input-output-hk/Alonzo-testnet/issues/27

```
[.../plutus]$ nix-shell
[nix-shell:plutus]$ cd .../Alonzo-testnet/resources/plutus-sources
[nix-shell:plutus-sources]$ cabal clean
[nix-shell:plutus-sources]$ cabal build all

...

Failed to build plutus-core-0.1.0.0. The failure occurred during the configure
step.
Build log (
/Users/tdiesler/.cabal/logs/ghc-8.10.4.20210212/plts-cr-0.1.0.0-d3d22b42.log
):
Configuring library for plutus-core-0.1.0.0..
cabal: The program 'happy' version >=1.17.1 is required but the version of
/Users/tdiesler/.cabal/store/ghc-8.10.4.20210212/hppy-1.20.0-c4936d37/bin/happy
could not be determined.

cabal: Failed to build plutus-core-0.1.0.0 (which is required by
exe:plutus-example from plutus-example-1.27.0, exe:plutus-alwayssucceeds from
plutus-alwayssucceeds-1.27.0 and others). See the build log above for details.
```

I'm still in the process of learning Haskell/Plutus - a decent user experience in the editor with working a HLS integration is essential for me.

**Comment by sorki** [comment]
I think I've managed to hit this as well and had to do `cabal update` in my fresh install to remedy this.

Also `cabal build all` recently failed for me on `plutus-metatheory` - if it happens to you, try smaller target like `cabal build plutus-use-cases` instead (and possibly report the issues you find!).

**Comment by tdiesler** [comment]
Checked out plutus rev [523f349f3d68db07c98150734793ed7003d1f562](https://github.com/input-output-hk/Alonzo-testnet/blob/main/resources/plutus-sources/cabal.project#L128) referenced in the testnet repo. Then a few times `cabal update` until I see ...

```
[nix-shell:~/git/Alonzo-testnet/resources/plutus-sources]$ cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2021-07-20T14:34:19Z
```

Then `cabal build all` ...

```
Failed to build plutus-core-0.1.0.0. The failure occurred during the configure
step.
Build log (
/Users/tdiesler/.cabal/logs/ghc-8.10.4.20210212/plts-cr-0.1.0.0-0a3fa957.log
):
Configuring library for plutus-core-0.1.0.0..
cabal: The program 'happy' version >=1.17.1 is required but the version of
/Users/tdiesler/.cabal/store/ghc-8.10.4.20210212/hppy-1.20.0-c4936d37/bin/happy
could not be determined.

cabal: Failed to build plutus-core-0.1.0.0 (which is required by
exe:plutus-example from plutus-example-1.27.0, exe:plutus-alwayssucceeds from
plutus-alwayssucceeds-1.27.0 and others). See the build log above for details.
```

**Comment by tdiesler** [comment]
The nix-shell accesses the user's local ~/.cabal folder. After reinstalling ghcup and carefully checking that nix stuff comes before ghcup stuff in the PATH, it worked.
