### ISSUE TITLE
Clarity on how `POSIXTimeRange` is handled by plutus, passing from `TxConstraints` to `TxInfo` 

### ISSUE THREAD

**Issue by t1lde** [input-output-hk/plutus#3606]
## Area

- [x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
- [ ] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
- [ ] *Marlowe* Related to Marlowe
- [ ] *Other* Any other topic (Playgrounds, etc.)

## Summary

So I'm working on updating the plutus version for our codebase. Since the conversion of `POSIXTime -> Slot` can no longer happen on-chain, I'm having some difficulty understanding how values are converted off-chain to on-chain.

Our handling of time goes like this, currently:

- Using
   `Contract.currentTime`
   to get the current `POSIXTime` off-chain, as I understand this is equivalent to  `slotToEndPOSIXTime def <$> Contract.currentSlot`
- We constrain the required width of the `txInfoValidRange` in order to get a sensible approximation of the current time' on-chain, so the transaction is constructed with something like `mustValidateIn (Interval (lowerBound currentTime) (strictUpperBound $ currentTime + delta)) `
- Then, on-chain, we check `width txInfoValidRange <= delta`.

This worked previously, checking with conversion to `SlotRange`, and using `Slot` over `POSIXTimeRange` in most of the on-chain logic. After changing to using `POSIXTime` everywhere, with the steps descried above, the validator fails on the `width txInfoValidRange <= delta` check. 

The log output in a failing test shows that the `txValidRange` is the same `SlotRange` as previously, but I can't see what the exact `POSIXTimeRange` passed to the validator in `TxInfo` is, as the trace output pretty prints `Tx` rather than `TxInfo`.

So it seems like going from `TxConstraints` -> `Tx` -> `TxInfo`, the `POSIXTimeRange` makes a lossy conversion round-trip -
**And indeed**, with `width txInfoValidRange - delta <= 1000`, the validator passes. It doesn't seem to be an off-by-one error either.

Other failing checks are leading me to believe it's not as simple as rounding to seconds, and it seems to be happening in the (inscrutable to me without spending a lot of time reading the whole codebase) `Cardano.Ledger.Alonzo.TxInfo` module.

Is there something weird going on with the `POSIXTime` conversion? or is there some other flaw in the way I'm using it?

## Version Info

plutus version: db4cf459bd2967d2ed480fd2ceb66a7ae1ee0864

Thanks in advance for any help on this :)

**Comment by michaelpj** [comment]
cc @koslambrou

**Comment by t1lde** [comment]
I've got fresh eyes on this this morning... I think I know how it's working:

the conversion round trip  `POSIXTimeRange -> SlotRange -> POSIXTImeRange` will round the `ivTo` field up to the end of a slot via `slotToEndPOSIXTime`, so something like `Interval (lowerBound x) (strictUpperbound $ x + delta)` will round the upperbound *up* to the end of the slot.

In the case of the `def` `SlotConfig`, with  ` scSlotLength = 1000` this appears to round up towards a second... but really this is subject to `SlotConfig` changes.

In terms of dealing with this on-chain, it's tricky since we can't rely on `SlotConfig`. I think the solution would be to (off-chain, in constructing the tx) round the `x + delta` such that it rounds down to the end of the previous slot.

**Comment by michaelpj** [comment]
Hmm, I think this might be a bug in the ledger. I think the ledger translates a slot-based validity interval with an upper bound of `s` into a time-based validity interval with an upper bound of `startTime s`, which isn't right, it should be the end time.

**Comment by michaelpj** [comment]
https://github.com/input-output-hk/cardano-ledger-specs/blob/master/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L177

**Comment by michaelpj** [comment]
Hmm, or maybe the upper bound is exclusive in which case it's fine?

**Comment by ak3n** [comment]
@t1lde could you please provide more details on what the value of `delta` is and how `width` is used?

I'm asking because `width` works with `SlotRange` values and not `POSIXTimeRange`, while you use `width` together with `delta` which might be incorrect (?).

**Comment by michaelpj** [comment]
Ledger validity interval upper bound is exclusive, and slots are contiguous. So it looks like it's not that.

**Comment by ak3n** [comment]
I agree that these conversions increase the pure `delta` difference, but as long as you stay in the default `scSlotLength = 1000` bracket you are okay with `width` function I guess (?).

Example:

```
> s <- currentSlot def
> s
Slot {getSlot = 31243540}

> currentTime = slotToEndPOSIXTime def s
> currentTime
POSIXTime {getPOSIXTime = 1627302631999}

> delta = 500
> i = (Interval (lowerBound currentTime) (strictUpperBound $ currentTime + delta))
> i
Interval {ivFrom = LowerBound (Finite (POSIXTime {getPOSIXTime = 1627302631999})) True, ivTo = UpperBound (Finite (POSIXTime {getPOSIXTime = 1627302632499})) False}
```

`mustValidateIn` will convert `POSIXTimeRange` to `SlotRange`:

```
    MustValidateIn timeRange ->
        unbalancedTx . tx . Tx.validRange %= (TimeSlot.posixTimeRangeToSlotRange def timeRange /\)
```

with `width = Just 1` 
 
```
> posixTimeRangeToSlotRange def i
Interval {ivFrom = LowerBound (Finite (Slot {getSlot = 31243540})) True, ivTo = UpperBound (Finite (Slot {getSlot = 31243541})) False}
> width $ posixTimeRangeToSlotRange def i
Just 1
```

Later, in `mkTxInfo`, `txInfoValidRange = TimeSlot.slotRangeToPOSIXTimeRange def $ txValidRange tx`:

```
> slotRangeToPOSIXTimeRange def $ posixTimeRangeToSlotRange def i
Interval {ivFrom = LowerBound (Finite (POSIXTime {getPOSIXTime = 1627302631000})) True, ivTo = UpperBound (Finite (POSIXTime {getPOSIXTime = 1627302632999})) False}
```

which means that our new`delta` is `1627302632999 - 1627302631000 = 1999`.

But since `width` is works only with `SlotRange` we still get the same difference:

```
> width $ posixTimeRangeToSlotRange def $ slotRangeToPOSIXTimeRange def $ posixTimeRangeToSlotRange def i
Just 1
```

---

And if the `delta` will be bigger than `1000`, then the width increases:

```
> delta = 1001
> i = (Interval (lowerBound currentTime) (strictUpperBound $ currentTime + delta))
> posixTimeRangeToSlotRange def i
Interval {ivFrom = LowerBound (Finite (Slot {getSlot = 31243540})) True, ivTo = UpperBound (Finite (Slot {getSlot = 31243542})) False}
> width $ posixTimeRangeToSlotRange def i
Just 2
```

**Comment by ak3n** [comment]
@michaelpj is there a reason why `txValidRange` of `data Tx` has type `SlotRange` and not `POSIXTimeRange`?

**Comment by michaelpj** [comment]
Because validity ranges on transactions *are* in terms of slots. But scripts get given an interval in terms of time.

**Comment by t1lde** [comment]
This makes sense, thanks for the info. 

I should have mentioned - to check the `width` on-chain I'm using a version of `width` that works with any `(PlutusTx.Enum a) => Interval a`. So something like the case you outlined with `width = 1999` is happening.

`delta` is 100_000. 

I'm worried about whether changes to `slotConfig` could cause certain on-chain logic to break. My assumption is that it would be an ouroborus protocol parameter, so if `scSlotLength` changed, then this could have a knock-on effect to the values in `txInfoValidRange`.

**Comment by michaelpj** [comment]
Part of the reason why scripts only work with time is that you cannot assume that slots have a fixed length. So in general you should *not* work with slots if you can possibly avoid it, and instead work with time.

**Comment by t1lde** [comment]
Looks like the solution I suggested where rounding down the `POSIXTimeRange` passed to `mustValidateIn` works for the problem I've run into :+1: . 
Thanks for the help!
