### ISSUE TITLE
`Builtins.error` should accepts a string as input

### ISSUE THREAD

**Issue by longngn** [input-output-hk/plutus#3608]
## Area

[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

Currently, many function in Plutus throw `Builtins.error ()` with no description which is very difficult to debug. We get cryptic errors such as: `WalletError (ValidationError (ScriptFailure (EvaluationError [])))` in phase 2 validation.
I suggest that `Builtins.error` should accept a description string as a parameter.
https://github.com/input-output-hk/plutus/blob/master/plutus-tx/src/PlutusTx/Builtins.hs#L190

**Comment by ak3n** [comment]
Hi! Thanks for the issue!

There is [`traceError`](https://github.com/input-output-hk/plutus/blob/master/plutus-tx/src/PlutusTx/Prelude.hs#L141) function that should suit your needs:

```
{-# INLINABLE traceError #-}
-- | Log a message and then terminate the evaluation with an error.
traceError :: Builtins.BuiltinString -> a
traceError str = error (trace str ())
```

Feel free to re-open or ask questions.

**Comment by longngn** [comment]
> Hi! Thanks for the issue!
> 
> There is [`traceError`](https://github.com/input-output-hk/plutus/blob/master/plutus-tx/src/PlutusTx/Prelude.hs#L141) function that should suit your needs:
> 
> ```
> {-# INLINABLE traceError #-}
> -- | Log a message and then terminate the evaluation with an error.
> traceError :: Builtins.BuiltinString -> a
> traceError str = error (trace str ())
> ```
> 
> Feel free to re-open or ask questions.

Yes, but there're lots of internal functions in Plutus libraries using `Builtins.error ()`, should those be changed to use `traceError`?
Example: https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/Plutus/V1/Ledger/Contexts.hs#L191

**Comment by ak3n** [comment]
@longngn Yep, that's a good idea for improvement. Thanks for bringing it up!
