### ISSUE TITLE
Distinguish in script validation code run time exceptions from return of False

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3619]
## Area

[*] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

If partial function throws exception on wring input like ownCurrencySymbol, or exception on parser of redeemers
and also successful execution taht returns False also returns `ScriptFailure (EvaluationError [])`.

It would be useful to distinguish those cases. Because given that we can not print any values to `traceIfFalse`
makes it very hard to debug and find the cause of the trouble.

## Expected behavior

It would be nice to be more descriptive on what caused the `ScriptFailure`.
It can be redeemer/datum parsing failure, or  partial function execution error (like `ownCurrencySymbol`)
or successful execution with False as result.

Otherwise it's painful to debug scripts with many reasons of failure grouped into single case.

**Comment by ak3n** [comment]
Please, check out #3618. It adds error messages to some internal functions, `ownCurrencySymbol` e.g.

While `traceIfFalse` may help to highlight the situation with `False` results, separating it from the other failures, isn't it?

**Comment by michaelpj** [comment]
You should have the log output from the tracing even if evaluation fails.

**Comment by anton-k** [comment]
> Please, check out #3618. It adds error messages to some internal functions, `ownCurrencySymbol` e.g.
> 
> While `traceIfFalse` may help to highlight the situation with `False` results, separating it from the other failures, isn't it?

Thanks that's going to be useful for this issue

**Comment by ak3n** [comment]
@anton-k is there anything else that we can do to improve the experience? Has the PR with `traceError` helped?

**Comment by ak3n** [comment]
Well, I think that the situation is better now with added `traceError` messages, so I'm closing this issue.

Feel free to reopen (or open a new one) if tracing works incorrectly or something is wrong.
