### ISSUE TITLE
Difficulty debugging freeze on `Plutus.Contract.currentTime`

### ISSUE THREAD

**Issue by emiflake** [input-output-hk/plutus#3669]
## Area

- [ ] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
- [x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
- [ ] *Marlowe* Related to Marlowe
- [ ] *Other* Any other topic (Playgrounds, etc.)

## Summary

`Plutus.Contract.currentTime` doesn't seem to yield. Locks up forever. Maybe I'm using it wrong? Note that `currentSlot` doesn't exhibit this behavior, it succesfully returns a slot.

## Steps to reproduce

Call `currentTime` in any contract.
```hs
contract :: forall eff. Contract () eff ContractError ()
contract =
  logInfo =<< currentTime
```
[Here's a gist that reproduces it fully](https://gist.github.com/emiflake/078d30aaa45fd2373670ad571b27cb27) 

## Expected behavior

We should get a POSIXTime returned, and it should log it out.

## Actual behavior

It locks up indefinitely.

## System info (please complete the following information):

- OS: NixOS 21.05
- Plutus commit: a93748066a65e95e9285dcd44af281f8238bf5c7

**Comment by luigy** [comment]
Thanks for the gist I was able to also repro on a more recent master a2ce64860f10cfacb48070a6efc737a131faee6a and put up a fix
