### ISSUE TITLE
Minting policy defined with Unit for redeemer compiles but fails validation

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/plutus#3708]
## Area

- [x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
- [ ] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
- [ ] *Marlowe* Related to Marlowe
- [ ] *Other* Any other topic (Playgrounds, etc.)

## Summary

A minting policy defined with Unit `()` instead of `BuiltinData` for unused redeemer compiles but fails local validation when building a transaction with cardano-cli. Plutus documentation provides this example of using Unit `()`: https://github.com/input-output-hk/plutus/blob/826c2514a40e962c2e4d56ce912803a434cc28fe/doc/plutus/tutorials/BasicPolicies.hs#L24

## Steps to reproduce
My working minting policy is here: https://github.com/input-output-hk/Alonzo-testnet/blob/f19f61ee60e8b4292d2ead231900bebbe9a8a3d5/resources/plutus-sources/plutus-example/src/Cardano/PlutusExample/MintingScriptPurple.hs#L46, but modifying it to use Unit `()` for unused redeemer will fail local validation.

## Expected behavior

Validation passes. Is there a problem with Plutus interpreter, or do we need to update tutorials and expectations?

## System info (please complete the following information):

- OS: Mint
- Version 20.2 (Uma)
- Plutus version or commit hash: 826c2514a40e962c2e4d56ce912803a434cc28fe

## Additional Notes
- Plutus Pioneer course also uses Unit `()` for unused redeemer in minting policy. https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week05/src/Week05/NFT.hs#L36
- This may also affect validator scripts but I haven't tried

**Comment by michaelpj** [comment]
You need to use `wrapMintingPolicy`, as the tutorial does.

**Comment by michaelpj** [comment]
This is why we have the typed interfaces... we should make one for minting policies.

**Comment by michaelpj** [comment]
Oh no, the thing you linked to does use it.

**Comment by michaelpj** [comment]
I need more information about what specifically you're doing. What does "will fail local validation" mean?

**Comment by james-iohk** [comment]
Apologies for the overlap with cardano-node, but this is what I do.
```CARDANO_NODE_SOCKET_PATH=node/node.sock cardano-cli transaction build \
--tx-in 5ff4ca7691cc2b9543bc1dab1ba6e5704ae445ae2799310961a61487ff510f59#1 \
--tx-in-collateral a938bbbcafccc1449fcfa7a0d53d781ad1cc0132cea5635bd2f68e1b7195dfe0#0 \
--tx-out "$(<acct.addr)+5000000+1 $(<minting-policy-purple.policyId).purple" \
--mint "1 $(<minting-policy-purple.policyId).purple" \
--mint-script-file minting-policy-purple.plutus \
--mint-redeemer-value 1 \
--witness-override 2 \
--change-address $(<acct.addr) \
--protocol-params-file pparams.json \
--out-file txbody \
--alonzo-era \
--testnet-magic $(cat node/db/protocolMagicId)
```
There's no change in the cmd above between the passing and failing scenarios, only the use of Unit `()` for redeemer in the minting policy. There's a possibility the failure is a result on providing redeemer value of `1`. Perhaps this issue should be moved to cardano-node so it can handle passing Unit data.

**Comment by michaelpj** [comment]
`1` does not decode as a value of type `()`, so yeah, that won't work. I would be against hard-coding any special cases in right now if we can avoid it...

**Comment by james-iohk** [comment]
I've now raised this here: https://github.com/input-output-hk/cardano-node/issues/3071
