### ISSUE TITLE
What is the purpose of PAB?

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3752]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

I wonder what is the end purpose of PAB? Is it going to be used in conjunction with test or mainnet?
Or is it only for testing and playground? I'm curious because on my current project there is a rival of two paradigms.
One is to build TXs with cardano-cli another is to use PAB. but is PAB also offer a way to post TX to real network?

It's just inquiry for more clarity on this topic.

**Comment by ak3n** [comment]
Please take a look at https://staging.plutus.iohkdev.io/doc/plutus/explanations/pab.html. It should answer the questions.
