### ISSUE TITLE
SHA224 or SHA256 for PolicyID/CurrencySymbol?

### ISSUE THREAD

**Issue by longngn** [input-output-hk/plutus#3758]
## Area

[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

In Plutus, CurrencySymbol is a SHA256 digest, however `cardano-cli transaction policyid` yields a SHA224 digest. Why there is this difference? Which hashing algorithm will be the final one?

## Versions
cardano-node: [alonzo-purple-1.0.1](https://github.com/input-output-hk/cardano-node/releases/tag/alonzo-purple-1.0.1)
plutus: 826c2514a40e962c2e4d56ce912803a434cc28fe

**Comment by luigy** [comment]
hi @longngn looks like you just missed the changes by a few commits from https://github.com/input-output-hk/plutus/pull/3559 in your plutus version which should make this consistent with your version of cardano-cli

**Comment by longngn** [comment]
> hi @longngn looks like you just missed the changes by a few commits from #3559 in your plutus version which should make this consistent with your version of cardano-cli

I used the Plutus version from the `cabal.project` file of `cardano-node` at revision `alonzo-purple-1.0.1` so I guess that Plutus version was outdated.
I'll close this issue now. Thank you

**Comment by j-mueller** [comment]
This was actually still an issue. It's fixed by https://github.com/input-output-hk/plutus/pull/3902.
