### ISSUE TITLE
Building on macOS with Apple Silicon (ARM64)

### ISSUE THREAD

**Issue by johnalanwoods** [input-output-hk/plutus#3765]
## Summary

I'm trying to build plutus-core.
I'm on macOS Big Sur with ARM64/Darwin (M1 chip).

Currently support for ARM64/Darwin is limited with GHC, 9.2 is supposed to bring ARM64 support.

I'm using cabal 3.4.0 and GHC 8.10.5

## Steps to reproduce

* Clone the plutus repo
* Issue `cabal build plutus-core`
* See compile time issues

```
[_11] fail (backjumping, conflict set: base, inline-r, marlowe-actus, vector)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: vector, primitive, base, inline-r,
pretty, marlowe-actus, cardano-api, template-haskell, hedgehog,
byron-spec-chain, microlens-th, Win32-network
```

## Expected behavior

Not sure if it should build on M1 based systems.

## System info (please complete the following information):

- OS: macOS 11 [11.5.1 (20G80)]
- Plutus version or commit hash [head]

**Comment by michaelpj** [comment]
I don't think any effort has been made to support M1 hardware, and as you say, GHC itself doesn't really support it. So it's likely broken and this is wontfix for now I'm afrraid.
