### ISSUE TITLE
Plutus starter instructions fail when locking Ada behind "eagle".

### ISSUE THREAD

**Issue by adrianmay** [input-output-hk/plutus#3781]
## Area

plutus-starter project (where I can't see a way to file issues)

## Summary

Following the instructions to play with the guessing game contract using nix, the process fails when trying to lock ada behind the secret.

## Steps to reproduce

Look at the readme at https://github.com/input-output-hk/plutus-starter.
Ignore the VSCode stuff.
Install nix and point at the binary cache as instructed.
Clone the plutus-starter repo and cd into it
Type nix-shell and wait.
cabal build plutus-starter-pab
cabal exec -- plutus-starter-pab # oops
cabal-update
cabal build plutus-starter-pab
cabal exec -- plutus-starter-pab
In another terminal on the same box, outside of nix-shell:
* curl -s http://localhost:8080/api/new/contract/definitions | jq
* curl -s -H "Content-Type: application/json" \
  --request POST \
  --data '{"caID": "GameContract", "caWallet":{"getWallet": 1}}' \
  http://localhost:8080/api/new/contract/activate | jq
* Put the guid in the output of the above into env var INSTANCE_1
* curl -s -H "Content-Type: application/json" \
  --request POST \
  --data '{"caID": "GameContract", "caWallet":{"getWallet": 2}}' \
  http://localhost:8080/api/new/contract/activate | jq
* Put the guid in the output of the above into env var INSTANCE_2
* Watch the slots go by in the nix-shell...

```
[INFO] Handling 1 requests for 435570f6-f69d-42fe-a192-8523cdeab3e7
           Iteration 107 request ID 1
           Request: Current slot
[INFO] Handling 1 requests for 435570f6-f69d-42fe-a192-8523cdeab3e7
           Iteration 108 request ID 1
           Request: Await slot: Slot 158
[INFO] Handling 1 requests for 4ae97b4f-9296-42a8-8da3-6c341eb62665
           Iteration 115 request ID 1
           Request: Utxo at: addressed to ScriptCredential: ef753eceae8d0ec35d231f0b4398e63bd9c4a47f9ef12eaa858a7ee525dbf43b (no staking credential)
[INFO] Handling 1 requests for 4ae97b4f-9296-42a8-8da3-6c341eb62665
           Iteration 116 request ID 1
           Request: Current slot
[INFO] Handling 1 requests for 4ae97b4f-9296-42a8-8da3-6c341eb62665
           Iteration 117 request ID 1
           Request: Await slot: Slot 159
[INFO] Handling 1 requests for 435570f6-f69d-42fe-a192-8523cdeab3e7
           Iteration 109 request ID 1
           Request: Utxo at: addressed to ScriptCredential: ef753eceae8d0ec35d231f0b4398e63bd9c4a47f9ef12eaa858a7ee525dbf43b (no staking credential)
```

* curl -s http://localhost:8080/api/new/contract/instance/$INSTANCE_1/status | jq
* curl -s http://localhost:8080/api/new/contract/instance/$INSTANCE_2/status | jq

That all works but then:

```
curl -H "Content-Type: application/json" \
   --request POST \
   --data '{"amount":{"getValue":[[{"unCurrencySymbol":""},[[{"unTokenName":""},90]]]]},"secretWord":"eagle"}' \
   http://localhost:8080/api/new/contract/instance/$INSTANCE_1/endpoint/lock
```

fails with

```
EndpointCallError (EndpointNotAvailable (ContractInstanceId {unContractInstanceId = a961f9c5-35ab-441e-81a9-5269f03f54cd}) (EndpointDescription {getEndpointDescription = "lock"}))
```

and the slots are still saying the same as before.

## Expected behavior

Dunno, the readme doesn't say, but probably not this. Proceeding to make a guess returns the same error.

## System info:

- OS: Archlinux with no previous nix installation.
- Version: rolling, updated about 2 months ago.
- Plutus version: today's

**Comment by sorki** [comment]
See discussion in #3781 and maybe also test my fix in https://github.com/input-output-hk/plutus-starter/pull/21

**Comment by adrianmay** [comment]
Sorry I'm not familiar with your workflow. Which commit would you like me to test?

**Comment by silky** [comment]
Hey @sorki and @adrianmay 

@adrianmay - Thanks for reporting this error! I'm in the process of preparing a new release of the plutus-starter container that will fix it.

@sorki Thanks so much for putting that PR together; it's been helpful for me in putting together a new release; I'll close it shortly once that's done!

**Comment by Vivek205** [comment]
+1
Facing the same issue.

**Comment by silky** [comment]
@adrianmay @Vivek205 - This is fixed by https://github.com/input-output-hk/plutus-starter/pull/26 ; Please give it a go now :) https://github.com/input-output-hk/plutus-starter

**Comment by adrianmay** [comment]
I got this during `cabal build plutus-starter-pab`

```
Failed to build plutus-core-0.1.0.0. The failure occurred during the configure
step.
Build log (
/home/ad/.cabal/logs/ghc-8.10.4.20210212/plutus-core-0.1.0.0-8926ab581341d136552bcc893a4e18c566bd455d2e5c0659ac08e3e1435debb8.log
):
Configuring library for plutus-core-0.1.0.0..
cabal: The program 'happy' version >=1.17.1 is required but the version of
/home/ad/.cabal/store/ghc-8.10.4.20210212/happy-1.20.0-e-happy-e8321ebe03b5dd9758faa47c76270a6cec70769a2606b242a91b1b82d312f61c/bin/happy
could not be determined.

cabal: Failed to build plutus-core-0.1.0.0 (which is required by
exe:plutus-starter-pab from plutus-starter-0.1.0.0). See the build log above
for details.
```

**Comment by Vivek205** [comment]
@silky 
Thanks for the Fix 👍 
It's working fine now.

**Comment by silky** [comment]
@adrianmay Do you mind opening a new issue for that?

**Comment by adrianmay** [comment]
OK. I was looking for a reopen button but that works too
