### ISSUE TITLE
Plutus starter won't build plutus-starter-pab

### ISSUE THREAD

**Issue by adrianmay** [input-output-hk/plutus#3788]
## Area

plutus-starter

## Summary

I got this during `cabal build plutus-starter-pab` within a nix-shell started in a clone of the plutus-starter repo:

```
Failed to build plutus-core-0.1.0.0. The failure occurred during the configure
step.
Build log (
/home/ad/.cabal/logs/ghc-8.10.4.20210212/plutus-core-0.1.0.0-8926ab581341d136552bcc893a4e18c566bd455d2e5c0659ac08e3e1435debb8.log
):
Configuring library for plutus-core-0.1.0.0..
cabal: The program 'happy' version >=1.17.1 is required but the version of
/home/ad/.cabal/store/ghc-8.10.4.20210212/happy-1.20.0-e-happy-e8321ebe03b5dd9758faa47c76270a6cec70769a2606b242a91b1b82d312f61c/bin/happy
could not be determined.

cabal: Failed to build plutus-core-0.1.0.0 (which is required by
exe:plutus-starter-pab from plutus-starter-0.1.0.0). See the build log above
for details.
```
nix-shell had already said the following, and I don't know if it's normal or not:
```                     
trace: To make project.plan-nix for haskell-project a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To materialize project.plan-nix for hlint entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To materialize project.plan-nix for cabal-install entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To materialize project.plan-nix for stylish-haskell entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
```

## Steps to reproduce

Look at the readme at https://github.com/input-output-hk/plutus-starter.
Ignore the VSCode stuff.
Install nix and point at the binary cache as instructed.
Clone the plutus-starter repo and cd into it
Type nix-shell and wait.
cabal build plutus-starter-pab

## Expected behavior

A successful build.

## System info (please complete the following information):

- OS: Archlinux with no previous nix installation.
- Version: rolling, updated about 2 months ago.
- Plutus version: today's

**Comment by silky** [comment]
Hey @adrianmay - Thanks for posting this.

Unfortunately, I'm unable to reproduce this issue.

Can you try a `cabal clean` and then `cabal build plutus-starter-pab` and see if the problem persists?

**Comment by adrianmay** [comment]
Hi Silky,

`cabal clean` didn't fix this, so I deleted and reinstalled nix completely, and then it worked. 

I think this can be repro.d as follows:

**Comment by silky** [comment]
Thanks @adrianmay for the comments about how to reproduce it; we'll close this issue for now and revisit if someone else bumps into it :)

Thanks for using the project!
