### ISSUE TITLE
Plutus Playground compiled failed on Local Deployment

### ISSUE THREAD

**Issue by trungswat** [input-output-hk/plutus#3793]
## Area

[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

Plutus Playground reports Compilation failed with "Data not found. Please try again or contact support for assistance."
But Plutus Server and Client running with no issues.

## Steps to reproduce

1. Run nix-shell "Plutus-Playground-Server" with port changed to 8085 to avoid conflict with 8080.
2. Running Plutus client with npm start. Also change host to 0.0.0.0 to connect from external.
3. Try to compile "Hello world" script.

## System info (please complete the following information):

- OS: [e.g. Ubuntu]
- Version [e.g. 20.04]
- Plutus version or commit hash

## Screenshots and attachments

- If applicable, add screenshots, config files and/or logs to help explain the problem.
- If the issue is related to the Plutus Playground, please include a link to a gist that reproduces the issue

**Comment by ak3n** [comment]
`Data not found` means `404` and it means that some urls are incorrect.

Does it work without changing the default settings?

**Comment by trungswat** [comment]
I have to change the port of plutus server from 8080 to 8085 to avoid some conflict.
I managed to fix "Data not found".  But it introduced another one.

`FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = "localhost", baseUrlPort = 8080, baseUrlPath = ""},"/runghc"), requestQueryString = fromList [], requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList [application/json;charset=utf-8,application/json], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = "POST"} (Response {responseStatusCode = Status {statusCode = 404, statusMessage = "Not Found"}, responseHeaders = fromList [("Content-Type","application/json; charset=utf-8"),("X-Runtime","0.044106"),("X-Request-Id","02d0e0c9-c740-4e2a-aa7b-b1fea1dc9df2"),("Content-Length","34")], responseHttpVersion = HTTP/1.0, responseBody = "{\"status\":404,\"error\":\"Not Found\"}"})`


if you guys have experienced with those, please let me know. Thanks

**Comment by trungswat** [comment]
Thank you, guys.
After spending a whole morning, my problem was fixed by rebuild web-ghc as well.
