### ISSUE TITLE
How to estimate TX-size prior to posting to test/main-net, is it possible?

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus#3796]
## Area

[X] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[X] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

As we know TX-size is limited. right now it's not enforced by Contract monad or in PAB, but it's enforced on test-net.
Can you please describe a correct way to estimate TX-size before posting it?
Or how to properly check it inside Contract monad or in tests that all Tx sizes are below given limit. 

I have noticed that TxOutTx contains TX as argument, I wonder is needed for posting to node?
How can we properly the estimate the Tx-size in presence of such things?
Can you please suggest the routine. 

right now I'm doing it by calculating the Tx with constraints and lookups after application of  `mkTx` I get UnbalancedTx. And then turn it to ByteString with serialize and calculate the length of it, but does it correspond to the actual size of Tx on blockchain?
and what operations are needed to strip away some redundant info that is not needed on blockchain?

**Comment by ak3n** [comment]
Hi! Thanks for this good question.

Unfortunately, it's not possible to determine the size of the transaction as there is no way to build a signed transaction (transaction that actually reaches the net) yet. 

The only way to check it is to submit and take a look if node rejects it or not. Maybe it can help to get some sense of the size of transactions.

**Comment by anton-k** [comment]
That's sad. It's better to have it or some way to do it at least approximately. To know how to optimize the TX for production.

**Comment by anton-k** [comment]
But if I have the cardano type TX what is the close to the cardano-node way to serialise it?
Can we at least estimate size by that? Is there some function to do it?

I've tried this way:

```haskell
    toSize = fromIntegral . BSC.length . C.textEnvelopeRawCBOR . C.serialiseToTextEnvelope Nothing
```

But I'm not sure weather it's correct way. Can you help me with that?

**Comment by ak3n** [comment]
>But I'm not sure weather it's correct way. Can you help me with that?

Yeah, that seems correct. 👍 

But be careful that the final tx size is going to be slightly larger because there will be additional inputs and outputs.

**Comment by anton-k** [comment]
We discussed tha tin the team it turns out that TX also have to be divided by 2 since TX is encoded in HEX.
