### ISSUE TITLE
Make ThreadToken compatible with PlutusTx.unstableMakeIsData (& its counterparts)

### ISSUE THREAD

**Issue by Fiftyw3bs** [input-output-hk/plutus#3798]
## Area

[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

StateMachines now come with type `ThreadToken` that helps identify it on-chain. However, working with ThreadToken appears to be limited because it is currently not an instance of the relevant types (e.g. ToData) needed to be able to apply `PlutusTx.unstableMakeIsData` to it.

## Describe alternatives you've considered

None

## Additional context / screenshots

None

**Comment by ak3n** [comment]
Hi! Thanks for the issue.

Could you please provide an example? I have tried `PlutusTx.unstableMakeIsData ''ThreadToken` and it works fine.

**Comment by Fiftyw3bs** [comment]
Hi, thanks for your reply

I have something like this:

[image: image.png]

When I apply PlutusTx.unstableMakeIsData ''MyType, it doesn't work and
complains about ThreadToken. (Sorry, I'm not on my dev pc, so I can't show
a precise error message)

But taking a look at the definition of Slot and that of ThreadToken (See
images below), it appears ThreadToken doesn't derive from the TypeClasses
that may allow  PlutusTx.unstableMakeIsData be applicable to it.

Btw, I'm using the Plutus Tag: plutus-starter-devcontainer/v1.0.7


[image: image.png]

[image: image.png]

**Comment by Fiftyw3bs** [comment]
Hi, thanks for your reply

I have something like this:

```
data MyType = MyType {
  subType1  :: Integer
  subtype2   :: !(Maybe ThreadToken)
} deriving (Show, Prelude.Eq)
```

When I apply `PlutusTx.unstableMakeIsData ''MyType`, it doesn't work and complains about `ThreadToken` and it not deriving from `PlutusTx.UnsafeFromData`. (Sorry, I'm not on my dev pc, so I can't show a precise error message)

But taking a look at the definition of `Slot` and that of `ThreadToken`, it appears ThreadToken doesn't derive from the TypeClasses that may allow  PlutusTx.unstableMakeIsData be applicable to it.

`Slot` derives `PlutusTx.ToData, PlutusTx.FromData and PlutusTx.UnsafeFromData` but `ThreadToken` token doesn't.

Btw, I'm using the Plutus Tag: plutus-starter-devcontainer/v1.0.7
