### ISSUE TITLE
Make Plutus Typeclasses instance of QuickCheck's Arbitrary

### ISSUE THREAD

**Issue by Fiftyw3bs** [input-output-hk/plutus#3822]
## Area

[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

Property-based testing is one of the best test strategies out there, especially when it comes to Haskell. However, trying to generate random custom datatypes with Plutus Typeclasses as subtypes throws such an error as follows:

```
No instance for (Arbitrary
                         plutus-ledger-api-0.1.0.0:Plutus.V1.Ledger.Slot.Slot)
        arising from a use of ‘arbitrary’
...
```

when using `QuickCheck`'s `generate`:

`generate $ MyType <$> arbitrary <*> arbitrary`

if `MyType` is defined as such:

```
data MyType = {
   subType1 :: Integer,
   subType2 :: Slot
}
```

It would greatly reduce the time taken to create test cases if Plutus Typeclasses would be instances of `Arbitrary` and I think the Team should please look into it.

**Comment by ak3n** [comment]
Please take a look at [`Plutus.PAB.Arbitrary`](https://github.com/input-output-hk/plutus/blob/master/plutus-pab/src/Plutus/PAB/Arbitrary.hs) module where you can find `Arbitrary` instance for `Slot` and other types as well.

**Comment by Fiftyw3bs** [comment]
Thanks for pointing me to the necessary module.

However, it appears `ThreadToken` is not yet an instance of `Arbitrary`

**Comment by ak3n** [comment]
Yeah, not all types have the instance as they might be not used in tests yet. You can define the instance the same way as in the aforementioned module by yourself for now:

```
instance Arbitrary ThreadToken where
    arbitrary = genericArbitrary
    shrink = genericShrink
```

**Comment by Fiftyw3bs** [comment]
Thanks for the suggestion.

After defining the following:

```
instance Arbitrary ThreadToken where
    arbitrary = genericArbitrary
    shrink = genericShrink
        
instance Arbitrary TxOutRef where
    arbitrary = genericArbitrary
    shrink = genericShrink
        
instance Arbitrary TxId where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Arbitrary CurrencySymbol where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Arbitrary BuiltinByteString where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Arbitrary ByteString where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Generic ByteString
```

I still ended up getting the following error:

```
src/Misc.hs:111:17: error:
    • No instance for (Test.QuickCheck.Arbitrary.Generic.GArbitrary
                         (GHC.Generics.Rep ByteString))
        arising from a use of ‘genericArbitrary’
    • In the expression: genericArbitrary
      In an equation for ‘arbitrary’: arbitrary = genericArbitrary
      In the instance declaration for ‘Arbitrary ByteString’
    |
111 |     arbitrary = genericArbitrary
    |                 ^^^^^^^^^^^^^^^^

src/Misc.hs:112:14: error:
    • No instance for (QuickCheck-2.14.2:Test.QuickCheck.Arbitrary.RecursivelyShrink
                         (GHC.Generics.Rep ByteString))
        arising from a use of ‘genericShrink’
    • In the expression: genericShrink
      In an equation for ‘shrink’: shrink = genericShrink
      In the instance declaration for ‘Arbitrary ByteString’
    |
112 |     shrink = genericShrink
    |              ^^^^^^^^^^^^^
```

Going further seems to be an endless rabbit hole :)

I think, when it comes to whether or not `ThreadToken` being an instance of `Arbitrary` is relevant for tests (at the moment) depends on how soon developers start using `StateMachine`. Because, since only one contract can initialize a `StateMachine`, the `ThreadToken`  must be available to other contracts interacting with the `StateMachine` (after initialization), which in turn would require that they provide the right `ThreadToken` in order to identify the `StateMachine` on-chain. And right now,

**Comment by ak3n** [comment]
But you don't need to define all these instances:

```
instance Arbitrary TxOutRef where
    arbitrary = genericArbitrary
    shrink = genericShrink
        
instance Arbitrary TxId where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Arbitrary CurrencySymbol where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Arbitrary BuiltinByteString where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Arbitrary ByteString where
    arbitrary = genericArbitrary
    shrink = genericShrink

instance Generic ByteString
```

They are already available via `Plutus.PAB.Arbitrary`. You need to import it and define instance for `TokenThread` only.

**Comment by Fiftyw3bs** [comment]
Ah yeah! You are right!

Thank you!
