### ISSUE TITLE
dApp Lifecycle enhancement

### ISSUE THREAD

**Issue by FrankC01** [input-output-hk/plutus#3830]
## Area

[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

Our ideal dApp workflow is:
1. Write haskell "program" in separate files
2. Invoke haskell-to-plutus compiler
3. Deploy result to local Cardano or testnet 
4. Invoke program transactions in testing

We can not find any documentation that supports this so: Is this being considered? If so, what ETA should we think about?

Regards
@FrankC01
@arthurgreef

**Comment by ak3n** [comment]
Yep, that's possible. Please checkout https://github.com/input-output-hk/Alonzo-testnet/blob/main/Alonzo-exercises/alonzo-purple/3_Alonzo-purple-exercise-3.md how to use `cardano-cli`.
