### ISSUE TITLE
QuickCheck generated action list length is affected by delay slots number 

### ISSUE THREAD

**Issue by Eggham** [input-output-hk/plutus#3843]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

I have been working on property based testing using QuickCheck on a state machine contract. I have observed an unusual and strange behaviour of QuickCheck. I have also reproduced the same behaviour in `plutus/plutus-use-cases/test/Spec/GameStateMachine.hs`. I observe that the length of the action lists is directly affected by the number of waiting slots defined within `nextState` method of the test.

If the number of waiting slots within `nextState` is large, then the generated action lists become short. If the waiting slots go larger than `120` then an action list will always contain at most one action. In this case, the generated action lists become inadequate for testing. If the waiting slots are small, e.g. 1 or 2 like what is in the existing code, the generated action lists contains a good number of actions, which is sufficient for testing purpose. 

I have neither been able to find any configuration that can change this behaviour nor been able to find relevant documentation on this behaviour.

## Steps to reproduce
In `plutus/plutus-use-cases/test/Spec/GameStateMachine.hs`, change `wait 2` or `wait 1` into `wait 120` within every `nextState` method; and change `delay 2` or `delay 1` into `delay 120` within `perform` method accordingly. The generated action lists will contain at most one action, e.g.:
```
Prelude Test.QuickCheck Plutus.Contract.Test.ContractModel Spec.GameStateMachine> sample (arbitrary :: Gen (Actions GameModel))
Actions 
 [Lock (Wallet 2) "hello" 1]
Actions 
 [Lock (Wallet 1) "hello" 2]
Actions []
Actions 
 [Lock (Wallet 2) "hunter2" 4]
Actions 
 [Lock (Wallet 3) "hello" 4]
Actions 
 [Lock (Wallet 3) "hello" 7]
Actions 
 [Lock (Wallet 3) "hello" 1]
Actions 
 [Lock (Wallet 1) "secret" 8]
Actions 
 [Lock (Wallet 3) "hello" 15]
Actions 
 [Lock (Wallet 3) "*******" 10]
Actions 
 [Lock (Wallet 1) "hunter2" 4]
```

On the contrary, if `wait 2` and `wait 1` within every `nextState` method remains unchanged and so do `delay 2` and `delay 1` within `perform` method, the generated action lists contain multiple actions, e.g.:
```
Prelude Test.QuickCheck Plutus.Contract.Test.ContractModel Spec.GameStateMachine> sample (arbitrary :: Gen (Actions GameModel))
Actions []
Actions []
Actions []
Actions 
 [Lock (Wallet 2) "*******" 1,
  Guess (Wallet 2) "hello" "hello" 1,
  GiveToken (Wallet 3),
  Guess (Wallet 3) "hello" "hello" 1]
Actions 
 [Lock (Wallet 3) "*******" 3,
  GiveToken (Wallet 3),
  Guess (Wallet 3) "hello" "hello" 1,
  Guess (Wallet 3) "hunter2" "secret" 3,
  Guess (Wallet 3) "secret" "hello" 2,
  GiveToken (Wallet 2),
  Guess (Wallet 2) "*******" "*******" 3,
  GiveToken (Wallet 2),
  GiveToken (Wallet 2),
  GiveToken (Wallet 3),
  GiveToken (Wallet 1)]
Actions 
 [Lock (Wallet 2) "secret" 7,
  GiveToken (Wallet 1)]
Actions 
 [Lock (Wallet 3) "hello" 3]
Actions 
 [Lock (Wallet 1) "hello" 2,
  GiveToken (Wallet 3),
  GiveToken (Wallet 3),
  GiveToken (Wallet 1),
  GiveToken (Wallet 1),
  Guess (Wallet 1) "hunter2" "hunter2" 2,
  GiveToken (Wallet 2),
  GiveToken (Wallet 3),
  Guess (Wallet 3) "hunter2" "hello" 1,
  Guess (Wallet 3) "secret" "hunter2" 2,
  Guess (Wallet 3) "*******" "hello" 2,
  Guess (Wallet 3) "*******" "hunter2" 1]
Actions 
 [Lock (Wallet 3) "hello" 6,
  GiveToken (Wallet 3),
  Guess (Wallet 3) "*******" "*******" 5,
  Guess (Wallet 3) "secret" "*******" 5,
  Guess (Wallet 3) "*******" "hunter2" 3,
  Guess (Wallet 3) "*******" "hello" 5,
  GiveToken (Wallet 1)]
Actions 
 [Lock (Wallet 2) "secret" 2,
  GiveToken (Wallet 1),
  GiveToken (Wallet 2),
  GiveToken (Wallet 3),
  GiveToken (Wallet 3),
  Guess (Wallet 3) "secret" "secret" 2,
  GiveToken (Wallet 1),
  GiveToken (Wallet 2),
  GiveToken (Wallet 3),
  GiveToken (Wallet 2),
  GiveToken (Wallet 3),
  GiveToken (Wallet 3)]
Actions 
 [Lock (Wallet 1) "hunter2" 7,
  Guess (Wallet 1) "secret" "hunter2" 6,
  GiveToken (Wallet 1),
  GiveToken (Wallet 3),
  GiveToken (Wallet 2),
  GiveToken (Wallet 1),
  GiveToken (Wallet 3),
  GiveToken (Wallet 2),
  Guess (Wallet 2) "hello" "secret" 7,
  Guess (Wallet 2) "secret" "*******" 3,
  Guess (Wallet 2) "hunter2" "hunter2" 5,
  Guess (Wallet 2) "*******" "hello" 2,
  GiveToken (Wallet 3),
  Guess (Wallet 3) "secret" "*******" 1]
```

## Expected behavior

It is expected that the length of action lists is not affected by the number of waiting slots. There are always a good number of actions within action lists. Or it is configurable about the maximum length of action lists. But the action list length should not be affected by the number of waiting slots. 

## System info (please complete the following information):

- OS: Ubuntu
- Version: 20.04
- Plutus version or commit hash: `master` branch with commit hash `6f834b5ca`

## Additional context
The same behaviour has been observed in another QuickCheck test code that I am working on. In this QuickCheck test, it is required for some actions to wait for a large number of slots. Hence this behaviour shows up and becomes a blocking issue. If it is not solved, then QuickCheck test become useless.

For complex contract, waiting for a large number of slots, e.g. more than 100 slots, is not uncommon. So it would be very nice to see the length of generated action lists are decoupled from the number of waiting slots. It would be even better to be able to configure the maximum length of action lists.

**Comment by ElvishJerricco** [comment]
This seems to be due to the `lastSlot` limit in `ModelState`: https://github.com/input-output-hk/plutus/blob/d87e2eb1c37b995af2c56c5197a68dc02ced2633/plutus-contract/src/Plutus/Contract/Test/ContractModel.hs#L522-L526

Using `propRunActionsWithOptions`, you can configure that. But just using `arbitrary`, you'll ultimately end up using this instance: https://github.com/input-output-hk/plutus/blob/d87e2eb1c37b995af2c56c5197a68dc02ced2633/quickcheck-dynamic/src/Test/QuickCheck/StateModel.hs#L113-L115

Since that just uses `initialState`, it'll always use `125`.

By using `wait/delay 120`, you're breaking the precondition of `ModelState`: https://github.com/input-output-hk/plutus/blob/d87e2eb1c37b995af2c56c5197a68dc02ced2633/plutus-contract/src/Plutus/Contract/Test/ContractModel.hs#L530-L531

**Comment by kozross** [comment]
@ElvishJerricco That sounds like a bug then - it essentially makes testing sequences of actions with long `wait`s impossible beyond trivially short sequences. Even if that precondition wasn't there, it'd still be a pain to work around, due to the `Arbitrary` instance you've mentioned there.

**Comment by awkure** [comment]
Yes, but the core problem is that `propRunActionsWithOptions` runs the already generated list of actions that is from `Arbitrary (Actions state)` instance and in this case the precondition appears to be always true when the maximum amount of slots is bigger than 125.
