### ISSUE TITLE
verifySignedMessageOnChain error

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#3855]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

When i try to validate signature on china, I have got error DatumMissing
In the source - initTest create unique token an send to the script, datum contains signed message
runTest - try to redeem the code and send signed message in the redeemer

In validator tried both use redeemer signed message or datum signed message
    --traceIfFalse "value signed" (isValueSigned $ cdSignedMessageId datum)
    traceIfFalse "value signed" (isValueSigned $ crMessage r)

In both cases have an error - DatumMissing hash ->  traceError "DatumMissing" 

Test Trace
#
```
testTrace = do
    curHdl <- Trace.activateContractWallet w1 createUniqueToken
    void $ Trace.waitNSlots 5
    currency <- extractAssetClass curHdl
    let tokenAssetClass = AssetClass (Currency.currencySymbol currency, testTokenName)
    initHdl <- Trace.activateContractWallet w1 $ initTestContract (walletPrivKey w1) tokenAssetClass
    void $ Trace.waitNSlots 5
    testHdl <- Trace.activateContractWallet w1 $ runTestContract (walletPrivKey w1) tokenAssetClass
    void $ Trace.waitNSlots 5
```

Contract  source code
```
module Contracts.Test1
    ( ContractParam(..)
    , initTest
    , runTest
    , address
    , testTokenName
    ) where

data ContractParam = ContractParam
    { cpSigner :: PubKey
    } deriving (Show, Generic, FromJSON, ToJSON, ToSchema, Haskell.Eq, Haskell.Ord)

PlutusTx.makeLift ''ContractParam

data ContractDatum = ContractDatum
    { cdMessageId       :: Integer
    , cdSignedMessageId :: Maybe (SignedMessage Integer)
    }
    deriving (Show, Generic, FromJSON, ToJSON, Haskell.Eq)

PlutusTx.unstableMakeIsData ''ContractDatum
PlutusTx.makeLift ''ContractDatum

data ContractRedeemer = ContractRedeemer
    { crMessage :: Maybe (SignedMessage Integer) }
    deriving Show
PlutusTx.unstableMakeIsData ''ContractRedeemer

{-# INLINABLE mkValidator #-}
mkValidator :: ContractParam -> ContractDatum -> ContractRedeemer -> ScriptContext -> Bool
mkValidator contractParam datum r ctx = 
    --traceIfFalse "value signed" (isValueSigned $ cdSignedMessageId datum)
    traceIfFalse "value signed" (isValueSigned $ crMessage r)
  where 
    verifyValueSigned :: Maybe (SignedMessage Integer) -> PubKey -> Maybe Integer
    verifyValueSigned smMaybe pk = case smMaybe of
        Just sm -> case verifySignedMessageOnChain ctx pk sm of
            Left err -> case err of
                SignatureMismatch sig pk hash -> traceError "SignatureMismatch"
                DatumMissing hash ->  traceError "DatumMissing"
                DecodingError -> traceError "DecodingError"
                DatumNotEqualToExpected -> traceError "DatumNotEqualToExpected"
            Right res -> Just res
        Nothing -> traceError "No signed message"

    isValueSigned message = isJust $ verifyValueSigned message (cpSigner contractParam)

data Test
instance Scripts.ValidatorTypes Test where
    type instance DatumType Test = ContractDatum
    type instance RedeemerType Test = ContractRedeemer

typedValidator :: ContractParam -> Scripts.TypedValidator Test
typedValidator contractParam = Scripts.mkTypedValidator @Test
    ($$(PlutusTx.compile [|| mkValidator ||]) `PlutusTx.applyCode` PlutusTx.liftCode contractParam)
    $$(PlutusTx.compile [|| wrap ||])
  where
    wrap = Scripts.wrapValidator @ContractDatum @ContractRedeemer

validator :: ContractParam -> Validator
validator = Scripts.validatorScript . typedValidator

validatorHash :: ContractParam -> Ledger.ValidatorHash
validatorHash testData = LedgerScripts.validatorHash . validator $ testData

address :: ContractParam -> Ledger.Address
address = scriptAddress . validator

testTokenName :: TokenName
testTokenName = "testTokenName"

initTest :: forall w s. ContractParam -> PrivateKey -> AssetClass -> Contract w s Text ()
initTest contractParam privateKey uniqueTokenAsset = do 

    let inst = typedValidator contractParam
        mrScript = validator contractParam
        addr = address contractParam
        messageId = 123
        uniqueTokenVal = assetClassValue uniqueTokenAsset 1
    let contractDatum = ContractDatum { cdMessageId = messageId, cdSignedMessageId = Just $ signMessage messageId privateKey }
    let lookups = Constraints.typedValidatorLookups inst 
                <> Constraints.otherScript mrScript

        tx      = Constraints.mustPayToTheScript contractDatum uniqueTokenVal

    ledgerTx <- submitTxConstraintsWith lookups tx
    void $ awaitTxConfirmed $ txId ledgerTx

runTest :: forall w s. ContractParam -> PrivateKey -> AssetClass -> Contract w s Text ()
runTest contractParam privateKey uniqueTokenAsset = do 
    logInfo @String "runTest"
    let inst = typedValidator contractParam
        mrScript = validator contractParam
        addr = address contractParam
        messageId = 123
        uniqueTokenVal = assetClassValue uniqueTokenAsset 1
        redeemer = Redeemer $ PlutusTx.toBuiltinData $ ContractRedeemer{ crMessage = Just $ signMessage messageId privateKey }

    pkh <- pubKeyHash <$> Contract.ownPubKey
    utxos <- utxoAt addr
    let xs = [ (oref, o)
            | (oref, o) <- Map.toList utxos
            , assetClassValueOf (txOutValue $ txOutTxOut o) uniqueTokenAsset == 1
            ]
    case xs of 
        [(oref, o)] -> do
            let lookups = Constraints.typedValidatorLookups inst 
                        <> Constraints.otherScript mrScript
                        <> Constraints.unspentOutputs (Map.singleton oref o)

                tx      = Constraints.mustSpendScriptOutput oref redeemer
                        <> Constraints.mustPayToPubKey pkh uniqueTokenVal
            ledgerTx <- submitTxConstraintsWith lookups tx
            void $ awaitTxConfirmed $ txId ledgerTx
        _ -> throwError "token not found"
   
```

**Comment by ak3n** [comment]
Could you please the full error message? You should have tracing messages.

**Comment by volodyad** [comment]
Emulator log:
      [INFO] Slot 0: TxnValidate 0636250aef275497b4f3807d661a299e34e53e5ad3bc1110e43d1f3420bc8fae
      [INFO] Slot 1: 00000000-0000-4000-8000-000000000000 {Contract instance for wallet 1}:
                       Contract instance started
      [INFO] Slot 1: W1: Balancing an unbalanced transaction:
                           Tx:
                             Tx 0993ee5303225eaf92f6142a2373a861525f8b3545091f0523661f1a373ad0cc:
                               {inputs:
                               collateral inputs:
                               outputs:
                                 - Value (Map [(,Map [("",1)])]) addressed to
                                   addressed to PubKeyCredential: 35dedd2982a03cf39e7dce03c839994ffdec2ec6b04f1cf2d40e61a3 (no staking credential)
                               mint: Value (Map [])
                               fee: Value (Map [])
                               mps:
                               signatures:
                               validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                               data:}
                           Requires signatures:
                           Utxo index:
                           Validity range:
                             (-∞ , +∞)
      [INFO] Slot 1: W1: Finished balancing. 5f85a195720951c4449731f120a2c02e38637b3cef237d402596229da141d99c
      [INFO] Slot 1: W1: Balancing an unbalanced transaction:
                           Tx:
                             Tx 53c138df704a9e5ca071074d84c63d9bbf22b506b340bf5d58d25271136cb804:
                               {inputs:
                                  - 0636250aef275497b4f3807d661a299e34e53e5ad3bc1110e43d1f3420bc8fae!6
      
                               collateral inputs:
                               outputs:
                               mint: Value (Map [(575e2c7cef9c1299614c0da50c57ab6c71c0e33a66af4261923af1dc,Map [("testTokenName",1)])])
                               fee: Value (Map [])
                               mps:
                                 MintingPolicy { <script> }
                               signatures:
                               validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                               data:}
                           Requires signatures:
                           Utxo index:
                             ( 0636250aef275497b4f3807d661a299e34e53e5ad3bc1110e43d1f3420bc8fae!6
                             , - Value (Map [(,Map [("",100000000)])]) addressed to
                                 addressed to PubKeyCredential: 35dedd2982a03cf39e7dce03c839994ffdec2ec6b04f1cf2d40e61a3 (no staking credential) )
                           Validity range:
                             (-∞ , +∞)
      [INFO] Slot 1: W1: Finished balancing. 1380dd6be7a7f0d8da1a689abd191682401ec9c6a67fa04966e7bb4e3fe97e40
      [INFO] Slot 1: W1: Submitting tx: 1380dd6be7a7f0d8da1a689abd191682401ec9c6a67fa04966e7bb4e3fe97e40
      [INFO] Slot 1: W1: TxSubmit: 1380dd6be7a7f0d8da1a689abd191682401ec9c6a67fa04966e7bb4e3fe97e40
      [INFO] Slot 1: TxnValidate 1380dd6be7a7f0d8da1a689abd191682401ec9c6a67fa04966e7bb4e3fe97e40
      [INFO] Slot 2: 00000000-0000-4000-8000-000000000000 {Contract instance for wallet 1}:
                       Contract instance stopped (no errors)
      [INFO] Slot 6: 00000000-0000-4000-8000-000000000000 {Contract instance for wallet 1}:
                       Sending contract state to Thread 0
      [INFO] Slot 7: 00000000-0000-4000-8000-000000000001 {Contract instance for wallet 1}:
                       Contract instance started
      [INFO] Slot 7: W1: Balancing an unbalanced transaction:
                           Tx:
                             Tx 470357bfdb3e222960c51c5a178bb6020b15912d60053ce94ef5f3d86121bfd4:
                               {inputs:
                               collateral inputs:
                               outputs:
                                 - Value (Map [(575e2c7cef9c1299614c0da50c57ab6c71c0e33a66af4261923af1dc,Map [("testTokenName",1)])]) addressed to
                                   addressed to ScriptCredential: c845fcab1bef319828e779c1c1f0c0da642e150e0da5f704974755e5 (no staking credential)
                               mint: Value (Map [])
                               fee: Value (Map [])
                               mps:
                               signatures:
                               validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                               data:
                                 <123,
                                 <<"\152\154\197T\130\SOH`\229\164\&5\169\219]\167$M=*\222\fX\241\251\ETB}\188\DC4^\136\138W\251\191k\141\&8qd\240 \224\215\185\251\177\156O\251\139\140\172\206\180\246\134\160\207h\154\b?\233\178\b",
                                 "e\138\176\224\245\253\239\216h\168\232\ENQ\209\SOH\169\140\195Z\181\ETB\233}\243\147q\130\218\fz\243\139=",
                                 123>>>}
                           Requires signatures:
                           Utxo index:
                           Validity range:
                             (-∞ , +∞)
      [INFO] Slot 7: W1: Finished balancing. d205d38ec7fefc1c683b33db1dea1716b8c3f7248d14a5087034d2f4b75a12e8
      [INFO] Slot 7: W1: Submitting tx: d205d38ec7fefc1c683b33db1dea1716b8c3f7248d14a5087034d2f4b75a12e8
      [INFO] Slot 7: W1: TxSubmit: d205d38ec7fefc1c683b33db1dea1716b8c3f7248d14a5087034d2f4b75a12e8
      [INFO] Slot 7: TxnValidate d205d38ec7fefc1c683b33db1dea1716b8c3f7248d14a5087034d2f4b75a12e8
      [INFO] Slot 8: 00000000-0000-4000-8000-000000000001 {Contract instance for wallet 1}:
                       Contract instance stopped (no errors)
      [INFO] Slot 12: 00000000-0000-4000-8000-000000000002 {Contract instance for wallet 1}:
                        Contract instance started
      [INFO] Slot 12: 00000000-0000-4000-8000-000000000002 {Contract instance for wallet 1}:
                        Contract log: String "runTest"
      [INFO] Slot 12: W1: Balancing an unbalanced transaction:
                            Tx:
                              Tx 944bd6b141d5cb0b6b9e50399ef0bcf39bef1774731e9b2cc726175180537b75:
                                {inputs:
                                   - d205d38ec7fefc1c683b33db1dea1716b8c3f7248d14a5087034d2f4b75a12e8!1
                                     <<<"\152\154\197T\130\SOH`\229\164\&5\169\219]\167$M=*\222\fX\241\251\ETB}\188\DC4^\136\138W\251\191k\141\&8qd\240 \224\215\185\251\177\156O\251\139\140\172\206\180\246\134\160\207h\154\b?\233\178\b",
                                     "e\138\176\224\245\253\239\216h\168\232\ENQ\209\SOH\169\140\195Z\181\ETB\233}\243\147q\130\218\fz\243\139=",
                                     123>>>
                                collateral inputs:
                                outputs:
                                  - Value (Map [(575e2c7cef9c1299614c0da50c57ab6c71c0e33a66af4261923af1dc,Map [("testTokenName",1)])]) addressed to
                                    addressed to PubKeyCredential: 35dedd2982a03cf39e7dce03c839994ffdec2ec6b04f1cf2d40e61a3 (no staking credential)
                                mint: Value (Map [])
                                fee: Value (Map [])
                                mps:
                                signatures:
                                validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                                data:
                                  <123,
                                  <<"\152\154\197T\130\SOH`\229\164\&5\169\219]\167$M=*\222\fX\241\251\ETB}\188\DC4^\136\138W\251\191k\141\&8qd\240 \224\215\185\251\177\156O\251\139\140\172\206\180\246\134\160\207h\154\b?\233\178\b",
                                  "e\138\176\224\245\253\239\216h\168\232\ENQ\209\SOH\169\140\195Z\181\ETB\233}\243\147q\130\218\fz\243\139=",
                                  123>>>}
                            Requires signatures:
                            Utxo index:
                              ( d205d38ec7fefc1c683b33db1dea1716b8c3f7248d14a5087034d2f4b75a12e8!1
                              , - Value (Map [(575e2c7cef9c1299614c0da50c57ab6c71c0e33a66af4261923af1dc,Map [("testTokenName",1)])]) addressed to
                                  addressed to ScriptCredential: c845fcab1bef319828e779c1c1f0c0da642e150e0da5f704974755e5 (no staking credential) )
                            Validity range:
                              (-∞ , +∞)
      [WARNING] Slot 12: W1: Validation error: Phase2 944bd6b141d5cb0b6b9e50399ef0bcf39bef1774731e9b2cc726175180537b75: ScriptFailure (EvaluationError ["Lc","Ld","DatumMissing"] "CekEvaluationFailure")
      [WARNING] Slot 12: 00000000-0000-4000-8000-000000000002 {Contract instance for wallet 1}:
                           Contract instance stopped with error: "WalletError (ValidationError (ScriptFailure (EvaluationError [\"Lc\",\"Ld\",\"DatumMissing\"] \"CekEvaluationFailure\")))"
        src/Plutus/Contract/Test.hs:241:
        test

**Comment by ak3n** [comment]
I suspect the problem is because of a missing datum.

`verifySignedMessageOnChain` uses `checkHashConstraints` that adds a `mustHashDatum` constraint with provided `osmMessageHash` and `Datum dt` from the `SignedMessage`. 

`osmMessageHash` should be the hash of the `Datum dt` and it should be in `TxInfo{txInfoData}`. `signMessage` builds `osmMessageHash` of the `Datum dt` correctly, but you wrap the `SignedMessage` with `ContractRedeemer` which seems to have a different hash. Therefore it can't find the `SignedMessage`'s datum.

**Comment by volodyad** [comment]
I have added source code https://github.com/volodyad/signissue 

Now I am trying datum  and my datum is type ContractDatum = SignedMessage MessageData
I have got the same error        [WARNING] Slot 12: W1: Validation error: Phase2 0cd82ca91216c023dbf53b8a8529661132b37844ff5ce7ded30dd2075a8f0788: ScriptFailure (EvaluationError ["Lc","Ld","DatumMissing"] "CekEvaluationFailure")
      [WARNING] Slot 12: 00000000-0000-4000-8000-000000000002 {Contract instance for wallet 1}:
                           Contract instance stopped with error: "WalletError (ValidationError (ScriptFailure (EvaluationError [\"Lc\",\"Ld\",\"DatumMissing\"] \"CekEvaluationFailure\")))"

**Comment by ak3n** [comment]
I was talking about `ContractRedeemer`, not `ContractDatum`. Please try again.

**Comment by volodyad** [comment]
Ok I have got your point, here is the working code https://github.com/volodyad/signissue/tree/working
I should send datum in plain, and then use redeemer with signed datum to verify. In that way it works

However it is not suitable for my use case, where I want datum to be signed and users provide in redeemer only Plublic Key. So the ouptut can be consumed only if datum/datum part was signed by proper key (e.g. contract owner) 

I see there is another method verifySignedMessageConstraints - which actually creates constraints, but does not verify them against context, it is marked as inlinable, so should work onchain

`{-# INLINABLE verifySignedMessageConstraints #-}
-- | Check the signature on a 'SignedMessage' and extract the contents of the
--   message, producing a 'TxConstraint' value that ensures the hashes match
--   up.
verifySignedMessageConstraints ::
    ( FromData a)
    => PubKey
    -> SignedMessage a
    -> Either SignedMessageCheckError (a, TxConstraints i o)
verifySignedMessageConstraints pk s@SignedMessage{osmSignature, osmMessageHash} =
    checkSignature osmMessageHash pk osmSignature
    >> checkHashConstraints s`

But when I try to run it I have got compilation error:
`GHC Core to PLC plugin: E042:Error: Unsupported feature: Irreducible type family application: GHC.Types.Any
Context: Compiling type: GHC.Types.Any
Context: Compiling expr: Ledger.Oracle.verifySignedMessageConstraints
                           @ Contracts.Test.ContractDatum @ GHC.Types.Any
Context: Compiling expr: Ledger.Oracle.verifySignedMessageConstraints
                           @ Contracts.Test.ContractDatum @ GHC.Types.Any @ GHC.Types.Any
Context: Compiling expr: Ledger.Oracle.verifySignedMessageConstraints
                           @ Contracts.Test.ContractDatum
                           @ GHC.Types.Any
                           @ GHC.Types.Any
                           ($cfromBuiltinData
                            `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                             <Contracts.Test.ContractDatum>_N)
                                    :: GHC.Types.Coercible
                                         (PlutusTx.Builtins.Internal.BuiltinData
                                          -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                         (PlutusTx.IsData.Class.FromData Contracts.Test.ContractDatum)))
Context: Compiling expr: Ledger.Oracle.verifySignedMessageConstraints
                           @ Contracts.Test.ContractDatum
                           @ GHC.Types.Any
                           @ GHC.Types.Any
                           ($cfromBuiltinData
                            `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                             <Contracts.Test.ContractDatum>_N)
                                    :: GHC.Types.Coercible
                                         (PlutusTx.Builtins.Internal.BuiltinData
                                          -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                         (PlutusTx.IsData.Class.FromData Contracts.Test.ContractDatum)))
                           (case contractParam of
                            { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                            ds_dIfK
                            })
Context: Compiling expr: Ledger.Oracle.verifySignedMessageConstraints
                           @ Contracts.Test.ContractDatum
                           @ GHC.Types.Any
                           @ GHC.Types.Any
                           ($cfromBuiltinData
                            `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                             <Contracts.Test.ContractDatum>_N)
                                    :: GHC.Types.Coercible
                                         (PlutusTx.Builtins.Internal.BuiltinData
                                          -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                         (PlutusTx.IsData.Class.FromData Contracts.Test.ContractDatum)))
                           (case contractParam of
                            { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                            ds_dIfK
                            })
                           r
Context: Compiling expr: case Ledger.Oracle.verifySignedMessageConstraints
                                @ Contracts.Test.ContractDatum
                                @ GHC.Types.Any
                                @ GHC.Types.Any
                                ($cfromBuiltinData
                                 `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                  <Contracts.Test.ContractDatum>_N)
                                         :: GHC.Types.Coercible
                                              (PlutusTx.Builtins.Internal.BuiltinData
                                               -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                              (PlutusTx.IsData.Class.FromData Contracts.Test.ContractDatum)))
                                (case contractParam of
                                 { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                 ds_dIfK
                                 })
                                r
                         of {
                           Data.Either.Left _ [Occ=Dead] ->
                             GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                           Data.Either.Right ds_dHUY [Occ=Once!] ->
                             case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                             GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                             }
                         }
Context: Compiling expr: case case Ledger.Oracle.verifySignedMessageConstraints
                                     @ Contracts.Test.ContractDatum
                                     @ GHC.Types.Any
                                     @ GHC.Types.Any
                                     ($cfromBuiltinData
                                      `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                       <Contracts.Test.ContractDatum>_N)
                                              :: GHC.Types.Coercible
                                                   (PlutusTx.Builtins.Internal.BuiltinData
                                                    -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                                   (PlutusTx.IsData.Class.FromData
                                                      Contracts.Test.ContractDatum)))
                                     (case contractParam of
                                      { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                      ds_dIfK
                                      })
                                     r
                              of {
                                Data.Either.Left _ [Occ=Dead] ->
                                  GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                                Data.Either.Right ds_dHUY [Occ=Once!] ->
                                  case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                                  GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                                  }
                              }
                         of {
                           GHC.Maybe.Nothing -> GHC.Types.False;
                           GHC.Maybe.Just _ [Occ=Dead] -> GHC.Types.True
                         }
Context: Compiling expr: case case case Ledger.Oracle.verifySignedMessageConstraints
                                          @ Contracts.Test.ContractDatum
                                          @ GHC.Types.Any
                                          @ GHC.Types.Any
                                          ($cfromBuiltinData
                                           `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                            <Contracts.Test.ContractDatum>_N)
                                                   :: GHC.Types.Coercible
                                                        (PlutusTx.Builtins.Internal.BuiltinData
                                                         -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                                        (PlutusTx.IsData.Class.FromData
                                                           Contracts.Test.ContractDatum)))
                                          (case contractParam of
                                           { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                           ds_dIfK
                                           })
                                          r
                                   of {
                                     Data.Either.Left _ [Occ=Dead] ->
                                       GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                                     Data.Either.Right ds_dHUY [Occ=Once!] ->
                                       case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                                       GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                                       }
                                   }
                              of {
                                GHC.Maybe.Nothing -> GHC.Types.False;
                                GHC.Maybe.Just _ [Occ=Dead] -> GHC.Types.True
                              }
                         of {
                           GHC.Types.False ->
                             PlutusTx.Builtins.Internal.trace
                               @ GHC.Types.Bool
                               (GHC.Magic.noinline
                                  @ (GHC.Base.String -> PlutusTx.Builtins.Internal.BuiltinString)
                                  PlutusTx.Builtins.Class.stringToBuiltinString
                                  (GHC.CString.unpackCString# "value signed"#))
                               GHC.Types.False;
                           GHC.Types.True -> GHC.Types.True
                         }
Context: Compiling expr: \ _ [Occ=Dead] ->
                           case case case Ledger.Oracle.verifySignedMessageConstraints
                                            @ Contracts.Test.ContractDatum
                                            @ GHC.Types.Any
                                            @ GHC.Types.Any
                                            ($cfromBuiltinData
                                             `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                              <Contracts.Test.ContractDatum>_N)
                                                     :: GHC.Types.Coercible
                                                          (PlutusTx.Builtins.Internal.BuiltinData
                                                           -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                                          (PlutusTx.IsData.Class.FromData
                                                             Contracts.Test.ContractDatum)))
                                            (case contractParam of
                                             { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                             ds_dIfK
                                             })
                                            r
                                     of {
                                       Data.Either.Left _ [Occ=Dead] ->
                                         GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                                       Data.Either.Right ds_dHUY [Occ=Once!] ->
                                         case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                                         GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                                         }
                                     }
                                of {
                                  GHC.Maybe.Nothing -> GHC.Types.False;
                                  GHC.Maybe.Just _ [Occ=Dead] -> GHC.Types.True
                                }
                           of {
                             GHC.Types.False ->
                               PlutusTx.Builtins.Internal.trace
                                 @ GHC.Types.Bool
                                 (GHC.Magic.noinline
                                    @ (GHC.Base.String -> PlutusTx.Builtins.Internal.BuiltinString)
                                    PlutusTx.Builtins.Class.stringToBuiltinString
                                    (GHC.CString.unpackCString# "value signed"#))
                                 GHC.Types.False;
                             GHC.Types.True -> GHC.Types.True
                           }
Context: Compiling expr: \ (r [Occ=Once] :: Contracts.Test.ContractRedeemer)
                           _ [Occ=Dead] ->
                           case case case Ledger.Oracle.verifySignedMessageConstraints
                                            @ Contracts.Test.ContractDatum
                                            @ GHC.Types.Any
                                            @ GHC.Types.Any
                                            ($cfromBuiltinData
                                             `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                              <Contracts.Test.ContractDatum>_N)
                                                     :: GHC.Types.Coercible
                                                          (PlutusTx.Builtins.Internal.BuiltinData
                                                           -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                                          (PlutusTx.IsData.Class.FromData
                                                             Contracts.Test.ContractDatum)))
                                            (case contractParam of
                                             { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                             ds_dIfK
                                             })
                                            r
                                     of {
                                       Data.Either.Left _ [Occ=Dead] ->
                                         GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                                       Data.Either.Right ds_dHUY [Occ=Once!] ->
                                         case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                                         GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                                         }
                                     }
                                of {
                                  GHC.Maybe.Nothing -> GHC.Types.False;
                                  GHC.Maybe.Just _ [Occ=Dead] -> GHC.Types.True
                                }
                           of {
                             GHC.Types.False ->
                               PlutusTx.Builtins.Internal.trace
                                 @ GHC.Types.Bool
                                 (GHC.Magic.noinline
                                    @ (GHC.Base.String -> PlutusTx.Builtins.Internal.BuiltinString)
                                    PlutusTx.Builtins.Class.stringToBuiltinString
                                    (GHC.CString.unpackCString# "value signed"#))
                                 GHC.Types.False;
                             GHC.Types.True -> GHC.Types.True
                           }
Context: Compiling expr: \ _ [Occ=Dead]
                           (r [Occ=Once] :: Contracts.Test.ContractRedeemer)
                           _ [Occ=Dead] ->
                           case case case Ledger.Oracle.verifySignedMessageConstraints
                                            @ Contracts.Test.ContractDatum
                                            @ GHC.Types.Any
                                            @ GHC.Types.Any
                                            ($cfromBuiltinData
                                             `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                              <Contracts.Test.ContractDatum>_N)
                                                     :: GHC.Types.Coercible
                                                          (PlutusTx.Builtins.Internal.BuiltinData
                                                           -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                                          (PlutusTx.IsData.Class.FromData
                                                             Contracts.Test.ContractDatum)))
                                            (case contractParam of
                                             { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                             ds_dIfK
                                             })
                                            r
                                     of {
                                       Data.Either.Left _ [Occ=Dead] ->
                                         GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                                       Data.Either.Right ds_dHUY [Occ=Once!] ->
                                         case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                                         GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                                         }
                                     }
                                of {
                                  GHC.Maybe.Nothing -> GHC.Types.False;
                                  GHC.Maybe.Just _ [Occ=Dead] -> GHC.Types.True
                                }
                           of {
                             GHC.Types.False ->
                               PlutusTx.Builtins.Internal.trace
                                 @ GHC.Types.Bool
                                 (GHC.Magic.noinline
                                    @ (GHC.Base.String -> PlutusTx.Builtins.Internal.BuiltinString)
                                    PlutusTx.Builtins.Class.stringToBuiltinString
                                    (GHC.CString.unpackCString# "value signed"#))
                                 GHC.Types.False;
                             GHC.Types.True -> GHC.Types.True
                           }
Context: Compiling expr: \ (contractParam [Occ=Once!]
                              :: Contracts.Test.ContractParam)
                           _ [Occ=Dead]
                           (r [Occ=Once] :: Contracts.Test.ContractRedeemer)
                           _ [Occ=Dead] ->
                           case case case Ledger.Oracle.verifySignedMessageConstraints
                                            @ Contracts.Test.ContractDatum
                                            @ GHC.Types.Any
                                            @ GHC.Types.Any
                                            ($cfromBuiltinData
                                             `cast` (Sym (PlutusTx.IsData.Class.N:FromData[0]
                                                              <Contracts.Test.ContractDatum>_N)
                                                     :: GHC.Types.Coercible
                                                          (PlutusTx.Builtins.Internal.BuiltinData
                                                           -> GHC.Maybe.Maybe Contracts.Test.ContractDatum)
                                                          (PlutusTx.IsData.Class.FromData
                                                             Contracts.Test.ContractDatum)))
                                            (case contractParam of
                                             { Contracts.Test.ContractParam ds_dIfK [Occ=Once] ->
                                             ds_dIfK
                                             })
                                            r
                                     of {
                                       Data.Either.Left _ [Occ=Dead] ->
                                         GHC.Maybe.Nothing @ Contracts.Test.ContractDatum;
                                       Data.Either.Right ds_dHUY [Occ=Once!] ->
                                         case ds_dHUY of { (res [Occ=Once], _ [Occ=Dead]) ->
                                         GHC.Maybe.Just @ Contracts.Test.ContractDatum res
                                         }
                                     }
                                of {
                                  GHC.Maybe.Nothing -> GHC.Types.False;
                                  GHC.Maybe.Just _ [Occ=Dead] -> GHC.Types.True
                                }
                           of {
                             GHC.Types.False ->
                               PlutusTx.Builtins.Internal.trace
                                 @ GHC.Types.Bool
                                 (GHC.Magic.noinline
                                    @ (GHC.Base.String -> PlutusTx.Builtins.Internal.BuiltinString)
                                    PlutusTx.Builtins.Class.stringToBuiltinString
                                    (GHC.CString.unpackCString# "value signed"#))
                                 GHC.Types.False;
                             GHC.Types.True -> GHC.Types.True
                           }
Context: Compiling definition of: Contracts.Test.mkValidator
Context: Compiling expr: Contracts.Test.mkValidator
Context: Compiling expr at "plutus-starter-0.1.0.0-inplace:Contracts.Test:(104,9)-(104,45)"
cabal: Failed to build plutus-starter-0.1.0.0 (which is required by
test:plutus-example-projects-test from plutus-starter-0.1.0.0).
`
source code https://github.com/volodyad/signissue/blob/error2/src/Contracts/Test.hs

**Comment by ak3n** [comment]
The compilation error happens because it's not clear what is the type of constraints. By ignoring the constraints you introduce `Any` type which is not supported by the plutus plugin.

You need to constraints or specify the type:

```
case verifySignedMessageConstraints pk sm of
            Left err -> Nothing
            Right (res, _ :: TxConstraints Void Void) -> Just res
```

**Comment by volodyad** [comment]
Thank you for help
