### ISSUE TITLE
Easier way to express Hashes into PlutusTx.BuiltinByteString

### ISSUE THREAD

**Issue by nhenin** [input-output-hk/plutus#3888]
Hi, to be able to mint tokens with a one-time policy on the Testnet, I had to find a way to create a `TxOutRef` myself to generate the monetary policy script. I ended up doing the following : 
```haskell
mkMyTokenMonetaryPolicyScript :: TxOutRef -> MintingPolicy
mkMyTokenMonetaryPolicyScript txOutRef = mkMintingPolicyScript $
    $$(PlutusTx.compile [|| \c -> Scripts.wrapMintingPolicy (monetaryPolicy c) ||])
        `PlutusTx.applyCode`
            PlutusTx.liftCode txOutRef
    where
        {-# INLINABLE monetaryPolicy #-}
        monetaryPolicy :: TxOutRef -> BuiltinData -> V.ScriptContext -> Bool
        monetaryPolicy a b c =  burningPolicy a b c || mintingPolicy a b c

        {-# INLINABLE mintingPolicy #-}
        mintingPolicy :: TxOutRef -> BuiltinData -> V.ScriptContext -> Bool
        mintingPolicy (TxOutRef refHash refIdx) _ ctx@V.ScriptContext{V.scriptContextTxInfo=txinfo}
            =  traceIfFalse "E1" {- Value minted different from expected (10^9 MyTokens)" -}
                (clapTotalSupply (V.ownCurrencySymbol ctx) == V.txInfoMint txinfo)
            && traceIfFalse "E2" {- Pending transaction does not spend the designated transaction output (necessary for one-time minting Policy) -}
                (V.spendsOutput txinfo refHash refIdx)

        {-# INLINABLE burningPolicy #-}
        burningPolicy :: TxOutRef -> BuiltinData -> V.ScriptContext -> Bool
        burningPolicy _ _ context@V.ScriptContext{V.scriptContextTxInfo=txinfo}
            = valueOf (V.txInfoMint txinfo) (V.ownCurrencySymbol context) (TokenName "MyToken") < 0


validator :: Validator
validator = Validator 
    $ unMintingPolicyScript 
    $ mkMyTokenMonetaryPolicyScript 
        (TxOutRef (M.fromJust $ A.decode "{\"getTxId\" : \"95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adb244\"}") 0)
```
Having some trouble building the following datatype : 
```haskell
newtype TxId = TxId { getTxId :: PlutusTx.BuiltinByteString }
    deriving (Eq, Ord, Generic)
    deriving anyclass (ToJSON, FromJSON, ToJSONKey, FromJSONKey, NFData)
    deriving newtype (PlutusTx.Eq, PlutusTx.Ord, Serialise)
    deriving (Show, Pretty) via LedgerBytes
```
I've used the `FromJSON` instance of `TxId` to solve my issue.

if we could express the same thing with hexadecimal integer literals , that way : 
```haskell 
(TxId . f) 0x4cebc6f2a3d0111ddeb09ac48e2053b83b33b15f29182f9b528c6491
``` 
I would find it useful. People participating in the Alonzo cohort are also reporting similar difficulties with `PubKeyHash` for example.

**Comment by ak3n** [comment]
Hi! Thanks for the issue!

I have added `IsString` instance in #3888. It will allow to use hashes as string literals:

```
> "95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adb244" :: TxId
95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adb244
```

The same behaviour has `PubKeyHash`. 

Is it enough to be a solution? Not sure about hexadecimal integer literals.

**Comment by nhenin** [comment]
> Hi! Thanks for the issue!
> 
> I have added `IsString` instance in #3888. It will allow to use hashes as string literals:
> 
> ```
> > "95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adb244" :: TxId
> 95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adb244
> ```
> 
> The same behaviour has `PubKeyHash`.
> 
> Is it enough to be a solution? Not sure about hexadecimal integer literals.

I was suggesting hexadecimal integer literals because if you do it that way  : 
"95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adb244" :: TxId
you can add characters that are not hexadecimals... btw what is the behaviour if I do "95f644032e4e2f516ddee5ae9ceb8d467f53f630c4d4f481771cb56063adbXXX" :: TxId ? 
using hexadecimals litterals makes your code more typed :-) (if it's possible to do it...)

**Comment by augucharles** [comment]
+1
