### ISSUE TITLE
Small infelicities in PlutusTx.Ratio

### ISSUE THREAD

**Issue by rjmh** [input-output-hk/plutus#3897]
[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

`PlutusTx.Ratio` exports
`  reduce :: Integer -> Integer -> Ratio Integer`
even though the comment says it is only used in this module. Surely it should not be exported? (It can cause an error, when the second argument is zero).

`PlutusTx.Ratio.recip` does not call `reduce `on its result. Consequently it accepts zero as an argument, and returns `0 :% 0`, violating the invariant that all rationals have a non-zero denominator.

I suggest removing `reduce `from the export list, and adding a call to `reduce` to the body of `recip`.

**Comment by j-mueller** [comment]
It's exported so that it can be used in the tests in `plutus-tx/test/Spec.hs`.

Good point about `recip` though!
