### ISSUE TITLE
Cannot find PubKeyHash in txInfoSignatories

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#3910]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

This snipit ... 

![image](https://user-images.githubusercontent.com/244946/133146836-70de6ceb-d72f-468a-99ae-fcb9fd9ec0c7.png)

fails with the usual 

```
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 1 (in the order of the TxIds) failed with The Plutus script evaluation failed: An error has occurred:  User error:
The provided Plutus code called 'error'.
```

The Tx is signed with `.../acc1/payment.skey`

Generally, I don't know how to debug this. Is there an issue that I can track for basic validation logging? I feel that I'm totally in the dark with these kind of issues. The same code used to work in the emulator during the pioneer program.

Related to: https://github.com/input-output-hk/Alonzo-testnet/issues/66

**Comment by tdiesler** [comment]
I found a workaround like this ...

![image](https://user-images.githubusercontent.com/244946/133227119-60a8293a-8875-4391-812f-5fe2cf858954.png)

It seems that the signatories are not the same as the PKHs derived from the input addresses.

**Comment by james-iohk** [comment]
Hi @tdiesler, this issue concerns the node-cli.
You need to include "required signatories" in the transaction, not just an actual witness. Please note, this is not supported in 1.29. https://github.com/input-output-hk/cardano-node/pull/3123 introduces `--required-signer` cli option to do this.

**Comment by tdiesler** [comment]
@james-iohk merci. May I ask why we need that extra option, isn't it redundant to the list of witnesses?

**Comment by james-iohk** [comment]
@tdiesler From my understanding it allows the script to still validate even if witnesses are stripped from the transaction. It allows `transaction build` cmd to validate before the transaction is signed too. There may be other reasons.

**Comment by tdiesler** [comment]
Of course - thanks

**Comment by hasufell** [comment]
> I found a workaround like this ...

What is `getInputAddresses`? This function doesn't exist anywhere.

**Comment by tdiesler** [comment]
I use this 

![image](https://user-images.githubusercontent.com/244946/135598699-de43bcb1-9f81-470d-b6aa-17b454bd8722.png)
