### ISSUE TITLE
Import cardano-cli verification key to Plutus

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#3913]
## Area

[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

I need to create plutus script to validate the user key

I have generated keys via clu

    cardano-cli address key-gen \
    --verification-key-file payment.vkey \
    --signing-key-file payment.skey

Generated key
```
{
    "type": "PaymentVerificationKeyShelley_ed25519",
    "description": "Payment Verification Key",
    "cborHex": "XYZ"
}
```

hash result via command 
`cardano-cli address key-hash --payment-verification-key-file payment.vkey`
returns - e48db7e1632ff216982c8a57dcfbbebaaf13f031ef816ec415c1d551

I have tried to pass XYZ as parameter to calculate it is hash

command 
`cabal exec -- run  "{\"getPubKey\":\"XYZ\"}"`

Source
```
main = do
  let pkMaybe = if nargs > 2 then decode(LB8.pack $ args!!0):: Maybe PubKey else Nothing

 case pkMaybe of 
        Nothing ->   putStrLn $ "Incorrect PK"
        Just pk -> do
            let pkh = pubKeyHash pk
            putStrLn $ "Out: " ++ show pkh
```

Result - Out: a50b6941a65be924ca60c92c46b1d1f64d79154d81708087e9cddeaa

Hashes are different, what should I pass as args 0 to correctly parse PubKey?

**Comment by luigy** [comment]
if you would like to go from the text envelope(payment.vkey) directly you could try the following. I may be missing other shorter helpers, but this should do it also

```hs
Prelude Cardano.Api Ledger P> Right vkey <- readFileTextEnvelope (AsVerificationKey AsPaymentKey) "/home/path/to/payment.vkey"
Prelude Cardano.Api Ledger P> PubKeyHash $ P.toBuiltin $ serialiseToRawBytes $ verificationKeyHash vkey
```

**Comment by volodyad** [comment]
Hello @luigy  it works, thank you, can I also extract PubKey?

**Comment by luigy** [comment]
@volodyad I have not tested this yet, but 
`PubKey $ Ledger.Bytes.fromBytes $ serialiseToRawBytes vkey` should be the PubKey

**Comment by luigy** [comment]
Oh indeed it is, I verified by comparing against `pubKeyHash $ PubKey $ Ledger.Bytes.fromBytes $ serialiseToRawBytes vkey`

**Comment by volodyad** [comment]
Thank you, it works
