### ISSUE TITLE
`utxoAt -> utxosAt` migration?

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/plutus#3928]
I've been using `utxoAt` (at tag `plutus-starter-devcontainer/v1.0.8`):

https://github.com/input-output-hk/plutus/blob/cc7bc06c4344cee6cd59bc170063fd627da25ed3/plutus-contract/src/Plutus/Contract/Request.hs#L222-L228

Which is now removed in tag `plutus-starter-devcontainer/v1.0.9` in favor of `utxosAt`:

https://github.com/input-output-hk/plutus/blob/73b21ed30e982b51f3debf69c55d3affe8642eb7/plutus-contract/src/Plutus/Contract/Request.hs#L353-L364

However `utxosAt` carries less information. The originating `Tx` is not recoverable. `UtxoMap` contains `TxOutTx`, which has both `Tx` and `TxOut`. `ChainIndexTxOut` just lets me get `TxOut`.

So, how do you migrate?

**Comment by ak3n** [comment]
There is

```
-- | Get unspent transaction outputs with transaction from address.
utxosTxOutTxAt ::
    forall w s e.
    ( AsContractError e
    )
    => Address
    -> Contract w s e (Map TxOutRef (ChainIndexTxOut, ChainIndexTx))
```

that also returns `ChainIndexTx`:

```
data ChainIndexTx = ChainIndexTx {
    _citxTxId            :: TxId,
    -- ^ The id of this transaction.
    _citxInputs          :: Set TxIn,
    -- ^ The inputs to this transaction.
    _citxOutputs         :: ChainIndexTxOutputs,
    -- ^ The outputs of this transaction, ordered so they can be referenced by index.
    _citxValidRange      :: !SlotRange,
    -- ^ The 'SlotRange' during which this transaction may be validated.
    _citxData            :: Map DatumHash Datum,
    -- ^ Datum objects recorded on this transaction.
    _citxRedeemers       :: Map RedeemerHash Redeemer,
    -- ^ Redeemers of the minting scripts.
    _citxMintingPolicies :: Map MintingPolicyHash MintingPolicy,
    -- ^ The scripts used to check minting conditions.
    _citxStakeValidators :: Map StakeValidatorHash StakeValidator,
    _citxValidators      :: Map ValidatorHash Validator
    } deriving (Show, Eq, Generic, ToJSON, FromJSON)
```

which is similar to the original `Tx`.

**Comment by hasufell** [comment]
`ChainIndexTx` doesn't seem to contain all fields of `Tx` and I don't see what `UtxoMap` is for anymore.

**Comment by ak3n** [comment]
`ChainIndexTx` got a field with the full original transaction `_citxCardanoTx`.

 https://github.com/input-output-hk/plutus/blob/master/plutus-chain-index/src/Plutus/ChainIndex/Tx.hs#L76

**Comment by Habacef** [comment]
this needs to be added to the documentation PLS! Not easy to find that out....
