### ISSUE TITLE
Unspecific error when data value does not match datum type

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#3938]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

With a validator signature like this ...

```
Integer -> Integer -> ScriptContext -> Bool
```

I passed in ...

```
  --tx-in-datum-value '{"bytes":"4173746f72"}' \
```

which doesn't match the Integer datum type.

The error that I got was rather unspecific

```
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 1 (in the order of the TxIds) failed with The Plutus script evaluation failed: An error has occurred:  User error: The provided Plutus code called 'error'.
```

This could perhaps be more descriptive of the root cause.

**Comment by ak3n** [comment]
Could you please test it against dd41fd3cfb58874c58fbeb47bf5d20915fe6ea02?

**Comment by tdiesler** [comment]
Sure, will do. It might take a while though - currently busy with other stuff

**Comment by hasufell** [comment]
I have a similar problem, see https://github.com/input-output-hk/plutus/issues/3991#issue-1005782758 and just built against master (f363c44bc96498ab8bb1dbdeff45bebc86037c4c), rebuilt the plutus script and tried again: Still getting `User error: The provided Plutus code called 'error'.`

**Comment by tdiesler** [comment]
out-of-date
