### ISSUE TITLE
Build project issue

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#3944]
## Area

[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

Error on project build
OS macOS bigSur

cloned plutus project and run nix-shell, after  build project

Configuring library for plutus-core-0.1.0.0..
cabal: The program 'happy' version >=1.17.1 is required but the version of
~/.cabal/store/ghc-8.10.4.20210212/hppy-1.20.0-a2383844/bin/happy
could not be determined.

**Comment by ak3n** [comment]
Please check your `nix` setup and that `PATH` is correct.

`which happy` in `nix-shell` should be something like

```
/nix/store/4klljapwi8g41xv815af7gfd7sv4rjws-happy-exe-happy-1.20.0/bin/happy
```

**Comment by volodyad** [comment]
Managed to fix by removing  ~/.cabal folder and rerunning cabal update
