### ISSUE TITLE
mustSpendScriptOutput with State machine

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#3954]
## Area

[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

I have queried TxOutRef offchain and sent as an input to the state machine,
I want to cosume script utxo within state machine and get the token form this utxo, so 
I have added next constraint to the state machine step

  ```
            let 
                redeemer = Redeemer $ PlutusTx.toBuiltinData $ (1 :: Integer)
                constraints = Constraints.mustSpendScriptOutput ref redeemer
                newState = State { stateData = Finished bets, stateValue = mempty }
            in Just (constraints, newState)
```

 constraints = Constraints.mustSpendScriptOutput setRed dummyRedeemer

It throws an error:
Contract instance stopped with error: StateMachineContractError (SMCContractError (ConstraintResolutionError (TxOutRefNotFound (TxOutRef {txOutRefId = 47519b1687ce54308ee4a3355a5b3fa8a92a354ea35e8829fc90a780e1e404d9, txOutRefIdx = 1}))))

Is this correct way to consume utxo within state machine, or other approach should be used?

**Comment by luigy** [comment]
hi @volodyad how does running the step look like? you may be missing additional lookups there
```hs
runStepWith ::
    => ScriptLookups (StateMachine state input)
    -- ^ Additional lookups
    -> TxConstraints input state
    -- ^ Additional constraints
    -> StateMachineClient state input
    -- ^ The state machine
    -> input
    -- ^ The input to apply to the state machine
    -> Contract w schema e (TransitionResult state input)

```

**Comment by volodyad** [comment]
Thank you, ScriptLookups helped
