### ISSUE TITLE
Confusion about --invalid-hereafter $TTL

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/plutus#3964]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

## Summary

I would like to set an expire date for funds that are locked by a script. In the UTxO associated datum I have a POSIX Time in millis which I obtain like this (i.e. 15min into the future)

```
INVALID_AFTER=$((`date +%s` + 60 * 15 * 1000))
```

The contract has logic like this, in which I verify that the timestamp associated with the UTXO comes after the Tx time range.

![image](https://user-images.githubusercontent.com/244946/134005251-87ac6e94-a6b7-49da-b4ee-7570b80391fa.png)

I construct the value for `--invalid-hereafter $TTL` like this (i.e. 300 slots or 5min into the future)

```
TTL=$(($(cardano-cli query tip --testnet-magic $TESTNET_MAGIC | jq .slot) + 300))
```

I expect validation to succeed for the next 10 min but not thereafter. However it seems to succeed always even if build the Tx well after the INVALID_AFTER time.

How does `txInfoValidRange info` relate to `--invalid-before/--invalid-hereafter` ?

I assume that `--invalid-before/--invalid-hereafter`  must be given in terms of absolute slot numbers, which the system then translates to a POSIXTimeRange in millis.

**Comment by tdiesler** [comment]
This also passes although `--invalid-hereafter` should well be after `tokenInvalidAfter`

![image](https://user-images.githubusercontent.com/244946/134036904-b1dbe268-82f7-4073-be04-3efdad86c2ae.png)

PS: I wish I could somehow debug these values

**Comment by james-iohk** [comment]
Hi @tdiesler, this issue concerns cardano-cli. See https://github.com/input-output-hk/cardano-node/issues/3090. Is has been fixed and will be applied in the protocol version upgrade at the next HF.

**Comment by tdiesler** [comment]
Yes, that's it. Will the cli still stick to slots or will it conveniently switch to POSIXTime millis as well?

**Comment by james-iohk** [comment]
Cli will continue to use slots. Only plutus scripts use the posix time. Conversion from slot to posix time comes from the consensus layer and the validity window is passed to plutus to use in validator/policy conditions.
