### ISSUE TITLE
WalletId not an instance of GHC.Enum.Enum

### ISSUE THREAD

**Issue by Fiftyw3bs** [input-output-hk/plutus#3992]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

Using `Wallet` in List Comprehension produces the following error:
```
    • No instance for (GHC.Enum.Enum WalletId)
        arising from the arithmetic sequence ‘1 .. 3’
    • In the expression: [1 .. 3]
      In a stmt of a list comprehension: w <- [1 .. 3]
      In the first argument of ‘Map.fromList’, namely
        ‘[(Wallet w, 
           case w of
             1 -> v
             _ -> v') |
            w <- [1 .. 3]]’
   |
49 |                                                                 _ -> v') | w <- [1 .. 3]]) def def
```

## Steps to reproduce

```haskell
    emCfg :: EmulatorConfig
    emCfg = EmulatorConfig (Left $ Map.fromList [(Wallet w, case w of
                                                                1 -> v
                                                                _ -> v') | w <- [1 .. 3]]) def def
```

## Expected behavior

Expected it to work like it used to.

## System info (please complete the following information):

- OS: Ubuntu (WSL)
- Version 20.04
- Plutus version or commit hash: `f4aa043660eb8f137796f6e2d6684cf8d0418c1e`

**Comment by kelizarov** [comment]
Since recent update `WalletId` contains either private key for mock wallets and pub key hash for actual wallets. Having `Enum` for wallet id would not make sense, as it doesn't work with integers anymoore. 

You can use `knownWallets :: [Wallet]` from `Wallet.Emulator.Wallet` module instead.

**Comment by ak3n** [comment]
Yep, @kelizarov is right (thanks for the answer). `WalletId` was changed in 58c8b4bde7177a18cd6761ba328bc105e5c82a47. 

If you want to enumerate wallets you should use `knownWallets :: [Wallet]` or `knownWallet :: Integer -> Wallet`.
