### ISSUE TITLE
IOHK binary cache is required (not optional)

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/plutus#4003]
I thought the binary cache is optional but it turned out without setting it I got these errors when using `nix-shell`. Perhaps this should be stressed in `README.md`?

```
building '/nix/store/9r1pmppnyi1x8djsbrrr5b59d0w64n1w-download_file?file_path=purty-6.2.0-osx.tar.gz.drv'...

trying https://bintray.com/joneshf/generic/download_file?file_path=purty-6.2.0-osx.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   162    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (22) The requested URL returned error: 403
error: cannot download download_file?file_path=purty-6.2.0-osx.tar.gz from any mirror
builder for '/nix/store/9r1pmppnyi1x8djsbrrr5b59d0w64n1w-download_file?file_path=purty-6.2.0-osx.tar.gz.drv' failed with exit code 1
building '/nix/store/dyk21njpkva3dvq12kgcz6ghhl64zx8d-easy-file-lib-easy-file-0.2.2-config.drv'...
cannot build derivation '/nix/store/na623a8blp9ggfiyx0yjfl8y7v3055dr-purty-6.2.0.drv': 1 dependencies couldn't be built
```

**Comment by michaelpj** [comment]
I think it's emphasized enough:

> DO NOT IGNORE THIS

> If you want to use Nix with this project, make sure to set up the IOHK binary cache. If you do not do this, you will end up building GHC, which takes several hours. If you find yourself building GHC, STOP and fix the cache.

**Comment by L-as** [comment]
The relevant derivation should probably be fixed, if you care about reproducibility.

**Comment by delicious-lemon** [comment]
I also read the binary cache as being optional - the warning as I read it implies the build will just take longer.  Reproducibility from source is something many users will expect from Nix so I think this is worth addressing even if the solution is just to update the warning (though fixing the derivation would be preferable). Can we reopen the issue @michaelpj?

**Comment by delicious-lemon** [comment]
Thanks for taking the time to respond Michael. I appreciate the clarification that this is just a temporary issue and agree that prioritizing it may not be the best use of time. I have built without `cache.nixos.org` once upon a time and it was quite slow -  I've had no problems building using the iohk cache (I like fast builds).
