### ISSUE TITLE
`cabal configure` in `nix-shell --pure` fails, unknown package `filemanip`

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4020]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Summary

In a freshly cloned `plutus`, commit 75aa0d6158aef2bac834a714029e12acf60b5dae, `cabal repl`, etc. fail to work because configuring (`cabal configure`) fails. I deleted `~/.cabal` before trying, and don't have my own GHC in the environment.

## Steps to reproduce

1. Make sure your environment is empty, e.g. a new NixOS container
2. `git clone https://github.com/input-output-hk/plutus`
3. `cd plutus`
4. `nix-shell --pure` (`--pure` isn't actually relevant since we're in a mostly empty environment anyway)
5. `cd plutus-ledger-api`
6. `cabal configure`

## Expected behavior

It should work.

## System info (please complete the following information):

- OS: NixOS
- Version: https://github.com/NixOS/nixpkgs/tree/483b311b17efa6e42cd5a48736d6578af357bcfe
- Plutus version or commit hash: 75aa0d6158aef2bac834a714029e12acf60b5dae

## Screenshots and attachments

You should get something like the following:
```
\[\][nix-shell:~/plutus/plutus-ledger-api]$\[\] cabal configure
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.RemoteRepo {remoteRepoName = RepoName
"hackage.haskell.org", remoteRepoURI = http://hackage.haskell.org/,
remoteRepoSecure = Just True, remoteRepoRootKeys =
["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}
Warning: Requested index-state 2021-08-14T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state ().
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] unknown package: filemanip (user goal)
[__0] fail (backjumping, conflict set: filemanip)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: filemanip
```

**Comment by michaelpj** [comment]
> Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.

**Comment by L-as** [comment]
Thanks! I tried with `cabal update` once, and it failed midway with no error message: https://gist.github.com/L-as/3b075d7d12f6dc36f24be3dc3c116165 (I have more than enough memory too), so I assumed you weren't supposed to do `cabal update`, as with the Haskell infrastructure in Nixpkgs. Unfortunate that I have to build some of the dependencies myself to use the REPL.
