### ISSUE TITLE
plutus-ledger build fails due to errors in src/Ledger/Tx.hs

### ISSUE THREAD

**Issue by rubicola** [input-output-hk/plutus#4022]
## Area

[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

`plutus-ledger` build is currently erroring for me, and these errors can be resolved by reverting commit 1efbb276ef1a10ca6961d0fd32e6141e9798bd11 

I was able to run `plutus/plutus-chain-link` locally from a nix-shell up until today when I pulled the latest from the plutus repo master branch.  I started getting build errors on `plutus-ledger`, specifically in `src/Ledger/Tx.hs` (see stack trace below). I updated my cardano-node to 1.30.1, but the errors persisted. I tried to run the `plutus-chain-link` again however I still got errors trying to build the `plutus-ledger` app.

I checked recent commits and noticed the change to plutus-ledger/src/Ledger/Tx.hs in 1efbb276ef1a10ca6961d0fd32e6141e9798bd11

Reverting that commit got things running again for me, but would appreciate any insights if I've missed updating something.

## Steps to reproduce

1. Pull the latest from plutus master branch
2. Have your cardano node running
3. Enter a nix-shell
4. Navigate to plutus-chain-index folder
5. Start with: `cabal run plutus-chain-index -- --network-id 1097911063 --socket-path <yoursocketpath> start-index`

Build will fail on plutus-ledger.

Then if you revert https://github.com/input-output-hk/plutus/commit/1efbb276ef1a10ca6961d0fd32e6141e9798bd11 you can see that it works as expected.

## Expected behavior

Expect that the plutus-chain-index will start without errors.

## System info (please complete the following information):

- OS: macOS
- Version BigSur
- Plutus version or commit hash 33d1f7029c58b7c6e3687064f7fb9a76978e0c18

## Screenshots and attachments

Example error output:

```
Building library for plutus-ledger-0.1.0.0..
[16 of 26] Compiling Ledger.Tx       

src/Ledger/Tx.hs:152:14: error:
    • Could not deduce (ToJSON (C.EraInMode era C.CardanoMode))
        arising from a use of ‘.=’
      from the context: C.IsCardanoEra era
        bound by a pattern with constructor:
                   SomeTx :: forall era.
                             C.IsCardanoEra era =>
                             C.Tx era -> C.EraInMode era C.CardanoMode -> SomeCardanoApiTx,
                 in an equation for ‘toJSON’
        at src/Ledger/Tx.hs:150:11-29
    • In the expression: "eraInMode" .= eraInMode
      In the first argument of ‘object’, namely
        ‘["tx" .= C.serialiseToTextEnvelope Nothing tx,
          "eraInMode" .= eraInMode]’
      In the expression:
        object
          ["tx" .= C.serialiseToTextEnvelope Nothing tx,
           "eraInMode" .= eraInMode]
    |
152 |            , "eraInMode" .= eraInMode
    |              ^^^^^^^^^^^^^^^^^^^^^^^^

src/Ledger/Tx.hs:169:3: error:
    • No instance for (FromJSON (C.EraInMode C.ByronEra C.CardanoMode))
        arising from a use of ‘parseSomeCardanoTx’
    • In the expression:
        parseSomeCardanoTx
          "Failed to parse ByronEra 'tx' field from SomeCardanoApiTx"
          (C.AsTx C.AsByronEra)
      In an equation for ‘parseByronInCardanoModeTx’:
          parseByronInCardanoModeTx
            = parseSomeCardanoTx
                "Failed to parse ByronEra 'tx' field from SomeCardanoApiTx"
                (C.AsTx C.AsByronEra)
    |
169 |   parseSomeCardanoTx "Failed to parse ByronEra 'tx' field from SomeCardanoApiTx"
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Note - does this last error for all eras.

I then get:
```<no location info>: warning: [-Wunused-packages]
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - plutus-tx-plugin-0.1.0.0
      - mtl-2.2.2
      - cardano-api-1.30.0
      - base16-bytestring-1.0.1.0
cabal: Failed to build plutus-ledger-0.1.0.0 (which is required by
exe:plutus-chain-index from plutus-chain-index-0.1.0.0).
```

I can see that the commit I reverted removed code from `Tx.hs` that had todo comment saying the code should be moved to cardano-api. Perhaps it is present in that package but my build excluded it `cardano-api-1.30.0` as noted above? I'm fairly new to cabal and haskell projects so apologies if I've overlooked something.

**Comment by ak3n** [comment]
Could you please run `cabal clean` or `rm -rf dist-newstyle` and try again? It should help.

**Comment by rubicola** [comment]
> Could you please run `cabal clean` or `rm -rf dist-newstyle` and try again? It should help.

Thanks so much, that fixed it.

Thanks for being patient - I'm quite new to Haskell.
