### ISSUE TITLE
PAB webserver not working

### ISSUE THREAD

**Issue by Fiftyw3bs** [input-output-hk/plutus#4034]
My app compiles and runs. But connecting to port `8080` returns `Error: connect ECONNREFUSED 127.0.0.1:8080` and port 9080, `404 Not Found`

I can't seem to figure out where the problem lies.

```
$ cabal run myapppab-pab
Warning: The package list for 'hackage.haskell.org' is 47 days old.
Run 'cabal update' to get the latest list of available packages.
Warning: Requested index-state 2021-07-07T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-07-06T21:17:46Z).
Resolving dependencies...
Up to date
[INFO] Slot 0: TxnValidate b135806142f3d020fc68e9e72fa6e8e7c8fce34b2a0f17fd23b633641f58944a
[INFO] Starting myapppab PAB webserver on port 8080. Press enter to exit.
[INFO] Starting PAB backend server on port: 9080
```

Plutus version: `eaa1c149dd1a7e002a11a45a54fdaea7176bb3e1`
OS: Ubuntu 20.04 (WSL)

**Comment by ak3n** [comment]
There is no endpoint for `/` that's why it returns 404.

`curl -v -H 'content-type: application/json' localhost:9080/api/healthcheck` should respond with 200.
