### ISSUE TITLE
Minimal Promise endpoint doesn't run in Playground

### ISSUE THREAD

**Issue by ssadler** [input-output-hk/plutus#4037]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

The `hello` endpoint doesn't run when called in Plutus Playground.

```haskell
import qualified Data.Text           as T
import           Playground.Contract
import           Plutus.Contract
import           PlutusTx.Prelude
import qualified Prelude             as Haskell


hello :: AsContractError e => Promise () HelloSchema e ()
hello = endpoint @"hello" $ \_ -> do
    logInfo @Haskell.String "Hello called"
    Haskell.undefined

endpoints :: Contract () HelloSchema T.Text ()
endpoints = awaitPromise hello

type HelloSchema = Endpoint "hello" ()

mkSchemaDefinitions ''HelloSchema

$(mkKnownCurrencies [])
```

## Steps to reproduce

1. Checkout plutus at current master (30b293767d61a556586d16634c66bd0ce2b816da)
2. `nix-shell` followed by `cd plutus-playground-client; plutus-playround-server` in one terminal
3. `nix-shell` followed by `cd plutus-playground-client; npm run start` in another terminal
3. Navigate to https://localhost:8009/
4. Paste above code in editor, compile
5. Click Simulate, add a "hello" action from one of the wallets, Evaluate

## Expected behavior

See "Hello called" in the logs, followed by error due to `Haskell.undefined`.

## System info (please complete the following information):

- OS: Ubuntu
- Version 20.04
- Plutus: 30b293767d61a556586d16634c66bd0ce2b816da

**Comment by ak3n** [comment]
Actually it does run. It just fails with an error called by `undefined` that gets thrown immediately skipping the contract interpreter. In contracts you should use `throwError` instead.

**Comment by ssadler** [comment]
Ok; however, logs are still quite incomplete when using the playground. The Error Handling example doesn't produce any logs if just one action takes place. So it's not really usable for development at the moment. Should I make another issue?

**Comment by ak3n** [comment]
>quite incomplete

What might be lacking?

>The Error Handling example doesn't produce any logs if just one action takes place.

Sounds like adding a wait action should help in this case.

**Comment by ssadler** [comment]
Ok, adding a wait action at the end was the solution. The log message is visible and the `undefined` is shown as an error. So I suppose this was not obvious to me, from a usability perspective there might be a benefit in tacking on an extra wait at the end of a list of actions. Thanks for your help...
