### ISSUE TITLE
Test suite allows only one action per wallet?

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/plutus#4053]
## Area

[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Summary

Using the plutus test suite with the emulator, you can only run one action per wallet. The others will be silently ignored.

## Steps to reproduce

1. `git clone https://github.com/hasufell/plutus-bug.git`
2. `cd plutus-bug`
3. `cabal run --enable-tests plutus-bug-tests`

## Expected behavior

The test succeeds.

## System info

- OS: Fedora Linux
- Version: 34
- Plutus version or commit hash: 7a89dff7b4b734f23ce1f4874cd6b70fb9902340

## Screenshots and attachments

* Code: https://github.com/hasufell/plutus-bug/blob/541bf9eb6c5ea106204d290afc676d810e0ac44f/test/UnitTests.hs#L51-L63
* Failure log: https://gist.github.com/hasufell/73b1c2c22e4228ee82232602068c8106

**Comment by luigy** [comment]
hi @hasufell thanks for the report. Looked at the [contract](https://github.com/hasufell/plutus-bug/blob/541bf9eb6c5ea106204d290afc676d810e0ac44f/src/PlutusBug.hs#L79-L80) and noticed that one of the endpoint would be handled at most once as implemented. See the [plutus-starter example](https://github.com/input-output-hk/plutus-starter/blob/a85818c27926f34d627225636f463cc6698706fc/examples/src/Plutus/Contracts/Game.hs#L166-L169) on how to continuously listen for the endpoints

**Comment by hasufell** [comment]
I can confirm this fixes the minimal repro case.
