### ISSUE TITLE
How to debug CekEvaluationFailure

### ISSUE THREAD

**Issue by phadej** [input-output-hk/plutus#4079]
## Area

[x] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

During testing the contract, I get an error in `EmulatorTrace` like:

```
  Contract log: Object (fromList [("contents",Object (fromList [("contents",Object (fromList [("contents",Object (fromList [("contents",Object (fromList [("contents",Object (fromList [("contents",Array [Array [String "L4",String "Ld",String "S5",String "PT5"],String "CekEvaluationFailure"]),("tag",String "EvaluationError")])),("tag",String "ScriptFailure")])),("tag",String "ValidationError")])),("tag",String "WalletError")])),("tag",String "SMCContractError")])),("tag",String "ExampleContract_state_machine_error")])
```

which looks like something which shouldn't happen, but it's unclear whether the error is in our onchain code or in the haskell-to-plutus compiler. 

After some trial&error I figured out that the state `transition` required `Tx.mustBeSignedBy` for wrong key, but it's surprising.
Shouldn't the contract offline code reject to construct such transation in the first place (or doesn't it apply to emulator traces?). Even so, in testing it would be nice to see which constraint wasn't satisfied. (Compare with writing `traceIfFalse`, which are very descriptive but don't fit into `Plutus.Contract.StateMachine` setup.

**Comment by ak3n** [comment]
Not yet, they change over time. It was a quick solution to reduce the size of the contracts and to see how it will work. Not an established practice yet.
