### ISSUE TITLE
Plutus Core decompiler

### ISSUE THREAD

**Issue by voland62** [input-output-hk/plutus#4115]
Hi.
I just wonder, is there any possibility to decompile Plutus Core? Could we, for instance, save clear secrets inside the blob (passing them as args to PlutusTx.compile for ex.)?

Thanks.

**Comment by kk-hainq** [comment]
It is not recommended to store any kind of secrets in the scripts as they can be easily deserialized and read by anyone.

**Comment by sseefried** [comment]
Why do you say it's essentially impossible to decompile Plutus Core given that decompilers for other languages are possible (despite difficulties)?

**Comment by michaelpj** [comment]
- There are no textual names on-chain
- The encoding of pattern-matching etc. is fairly obscure
- The code gets optimized significantly, including after later compilation steps

**Comment by michaelpj** [comment]
You're welcome to give it a try, but it's not something I'd spend resources on.

**Comment by sseefried** [comment]
@michaelpj Thanks for your prompt and thoughtful comments
