### ISSUE TITLE
ContractModel checks for contents of a script address

### ISSUE THREAD

**Issue by v0d1ch** [input-output-hk/plutus#4144]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

I haven't found a way to check for `Datum` contents in tests. Are there any plans of including such checks/assertions or am I missing something?

My SC relies on heavy usage of datums to carry it's _state_ over time and I think it would be useful to have something that can 
prove that it is performing correctly.

**Comment by ak3n** [comment]
Please take a look at https://github.com/input-output-hk/plutus/blob/35f6773c6ba8394345000b57e9bf149d092347a1/plutus-contract/src/Plutus/Contract/Test.hs#L327

Is that what are you looking for?
