### ISSUE TITLE
Readthedocs gone (with recent commit?)

### ISSUE THREAD

**Issue by manonthemat** [input-output-hk/plutus#4150]
## Summary

Documentation is empty at https://plutus.readthedocs.io

## Steps to reproduce

1. Go to https://plutus.readthedocs.io
2. See implicit error (missing documentation)

## Expected behavior

Being able to see and browse the documentation.

## Screenshots and attachments

![2021-10-21_07-41](https://user-images.githubusercontent.com/5065940/138301203-c488ae01-5b76-4633-8b09-84f33458d657.png)

**Comment by michaelpj** [comment]
Actually, I'll leave this open until it's sorted.
