### ISSUE TITLE
On-chain `dataHash :: BuiltinData -> BuiltinByteString`

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4167]
## Describe the feature you'd like

I assume this is already implementable if you do the serialization on-chain, but it would be
wasteful compared to supporting it as a built-in function.

## Describe alternatives you've considered

Is it perhaps possible to get the undeserialized datum for an input on-chain?
That would already cover some of the potential use cases.

## Additional context / screenshots

Some times you want to be able to compute the hash of a transformation of some
data (e.g. a datum), without storing the transformation in the transaction, in order
to save space.

**Comment by ak3n** [comment]
Thanks for the issue!

Yeah, this is a desired feature but not implemented yet.
