### ISSUE TITLE
GCOmpare instances for DefaultUni and ValueOf

### ISSUE THREAD

**Issue by phadej** [input-output-hk/plutus#4178]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

GCompare, and Ord instances for DefaultUni and ValueOf

## Describe alternatives you've considered

Orphans:

```haskell
deriveGCompare ''DefaultUni

instance (GCompare uni, Closed uni, uni `Everywhere` Ord, uni `Everywhere` Eq) => GCompare (ValueOf uni) where
    ValueOf uni1 x1 `gcompare` ValueOf uni2 x2 =
        case uni1 `gcompare` uni2 of
            GLT -> GLT
            GGT -> GGT
            GEQ -> do
                bring (Proxy @Ord) uni1 $ case compare x1 x2 of
                    EQ -> GEQ
                    LT -> GLT
                    GT -> GGT
```

**Comment by michaelpj** [comment]
Thoughts @effectfully

**Comment by effectfully** [comment]
:+1: 

The instances make perfect sense, we just didn't need them.

@phadej I'm curious: what are doing that requires them? Using `Term`s as keys in a `Map`?

**Comment by phadej** [comment]
> Using Terms as keys in a Map?

Something like that yes.

**Comment by phadej** [comment]
Thanks!
