### ISSUE TITLE
Convert payment.skey to Leger.Crypto.PrivateKey

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus#4182]
## Summary

I have tried next code to parse

```
import           Cardano.Crypto.Wallet           (xprv)

signerKeyEither <- readFileTextEnvelope (AsSigningKey AsPaymentKey) "payment.skey"
 case signerKeyEither of
          Left _ -> do
              putStrLn $ "Error"
          Right sKey -> do
              let signKeyE = xprv  $ serialiseToRawBytes sKey
```
 signKeyE = Left "error: xprv needs to be 128 bytes"

What is the correct way to parse skey to Plutus PrivateKet?

**Comment by ak3n** [comment]
You can take a look at how `cardano-cli` works. Here is the exact function responsible for reading the signing key file https://github.com/input-output-hk/cardano-node/blob/5faa1d2bb85ae806ec51fa4c576dec2670c67c7a/cardano-cli/src/Cardano/CLI/Shelley/Run/Key.hs#L608

**Comment by volodyad** [comment]
I extract the key via readFileTextEnvelope (AsSigningKey AsPaymentKey) "payment.skey", but how to convert it to Plutus Private key?

**Comment by luigy** [comment]
>           Right sKey -> do
>              let signKeyE = xprv  $ serialiseToRawBytes sKey

@volodyad `PrivateKey $ Ledger.Bytes.fromBytes $ serialiseToRawBytes sKey` should prob do it

**Comment by volodyad** [comment]
I have tried this, it returns  error 
• Data constructor not in scope:
        PrivateKey :: Plutus.LedgerBytes -> t
as I understand Ledger.Crypto does not export constructor

   • Data constructor not in scope:
        PrivateKey :: Plutus.LedgerBytes -> t

```
module Ledger.Crypto
    ( module Export
    , PrivateKey
```

I need Ledger.Crypto.PrivateKey to do signMessage
