### ISSUE TITLE
Cannot parse textual pir

### ISSUE THREAD

**Issue by phadej** [input-output-hk/plutus#4198]
E.g. when trying to parse `future.pir` (in the `plutus-use-cases/test/Spec`), I get the following error:

```
  pir/future.pir: pir/future.pir:204:10:
    |
204 |         (datatypebind
    |          ^^^^^^^
unexpected "datatyp"
expecting "abs", "builtin", "con", "error", "iwrap", "lam", "let", or "unwrap"
```

**Comment by kk-hainq** [comment]
I think overall the pretty-printer and parser are not complete and production-ready as mentioned in #3445. We have a customized parser for PLC but not PIR. And I guess the recommended way, for now, is to deserialize the binary representation.

**Comment by phadej** [comment]
Is there a variant of `goldenPir` which produces binary representation?

**Comment by kk-hainq** [comment]
I think setting this flag is a quick way anywhere:
```haskell
{-# OPTIONS_GHC -fplugin-opt PlutusTx.Plugin:dump-pir-flat #-}
```

**Comment by phadej** [comment]
> {-# OPTIONS_GHC -fplugin-opt PlutusTx.Plugin:dump-pir-flat #-}

That is not the same as `goldenPir`, won;t make tests fail.

**Comment by kk-hainq** [comment]
Yeah, I don't think there is any. Maybe you could break the test with the pretty-printed version, then find the corresponding PIR to parse...

**Comment by ak3n** [comment]
>Is there a variant of goldenPir which produces binary representation?

Unfortunately there is no a version for binary. There are functions that read or dump flat data so it should be possible to write a `goldenFlat` for that purposes.

I'm closing this issue because of #3445 if you don't mind. Feel free to reopen.

**Comment by phadej** [comment]
I mind. The #3445 is about producing well-typed Core. This issue that even well-typed PIR won't be parsed.

**Comment by michaelpj** [comment]
I'm happy to leave this open. You're all right:
- It is bad that the PIR parser and prettyprinter are not up-to-scratch. I would like us to fix this, but it's not a top priority, because...
- The textual parsers are not in (our) production pathway and won't ever be. We use them only for testing, and we recommend you similarly don't rely on them for anything else. 
- The issue here arises from trying to do testing, which is indeed what we use the parser for, and it is indeed pretty annoying that it doesn't work.

So I think this is a legit bug that hopefully we will fix in due course.

**Comment by effectfully** [comment]
@thealmarty you implemented parsing of `datatypebind` and other PIR things, right? If so, please close this issue.

**Comment by thealmarty** [comment]
After PR #4349  and a few follow up PRs more PIR things (including [datatypebind](https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-ir/src/PlutusIR/Parser.hs#L58)) can theoretically be parsed. However no tests were added. It was not considered to be high priority at the time.  I think it's best to close this after tests are added?

**Comment by effectfully** [comment]
@thealmarty thank you.

> I think it's best to close this after tests are added?

Good point, let's do that.

**Comment by effectfully** [comment]
@thealmarty do you happen to know the status of this issue?

**Comment by thealmarty** [comment]
There are tests that contains "datatypebind" in our codebase now. E.g., [here](https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-ir/test/transform/inline/letFunConstBool#L15). This may be good to close?

**Comment by effectfully** [comment]
Seems like it then! Thanks a lot, closing as resolved.
