### ISSUE TITLE
Unsupported feature: Type constructor: GHC.Prim.Addr#

### ISSUE THREAD

**Issue by phadej** [input-output-hk/plutus#4201]
I'm experimenting with various GHC flags, and now the `plutus-tx` throw this at me.

I wonder if `BuiltinByteString` could be backed up by `ByteArray#`. It wouldn't make builtin implementation more complex, but would be more robust. (EDIT: in fact, `Addr#` literals could be compiled to builtin bytestring, couldn't they?)

OTOH, `Integer` doesn't have nice `Integer#` behind it, so I might get `S#` and `J#` related errors (or does `plutus-tx-plugin` know about them?)

EDIT: This error happens when I place a bang on `BuilinByteString` argument:

```haskell
foo :: BuiltinByteString -> ...
foo !bs = ...
```

**Comment by michaelpj** [comment]
Related: https://github.com/input-output-hk/plutus/issues/4193

We're walking a line of usability versus robustness here. Maybe we could make `BuiltinBytestring` more opaque and have a `BuiltinInteger` similarly, but it would make interoperability more painful. But the errors certainly suck when GHC looks through our "opaque" definitions.

**Comment by phadej** [comment]
`BuiltinInteger` will definitely be not convenient as it would propage to `Value` etc.

**Comment by ak3n** [comment]
The issue looks very similar to #4193. Should we close this one?
