### ISSUE TITLE
Long compilation time of plutus scripts

### ISSUE THREAD

**Issue by marcinbugaj** [input-output-hk/plutus#4204]
## Summary

Compilation of scripts that have many variables in scope takes a lot of time.

## Steps to reproduce

Compile the following minting policy. Having more variables in scope (`l20`, `l21` etc) causes the compilation time to double.

```
mkPolicy _ ctx =
  let l = length $ Ledger.txInfoInputs $ Ledger.scriptContextTxInfo ctx
      l1 = l + 1
      l2 = l + 2
      l3 = l + 3
      l4 = l + 4
      l5 = l + 5
      l6 = l + 6
      l7 = l + 7
      l8 = l + 8
      l9 = l + 9
      l10 = l + 19
      l11 = l + 11
      l12 = l + 12
      l13 = l + 13
      l14 = l + 14
      l15 = l + 15
      l16 = l + 16
      l17 = l + 17
      l18 = l + 18
      l19 = l + 19
   in -- l20 = l + 20
      l == 0
        && l1 == 0
        && l2 == 0
        && l3 == 0
        && l4 == 0
        && l5 == 0
        && l6 == 0
        && l7 == 0
        && l8 == 0
        && l9 == 0
        && l10 == 0
        && l11 == 0
        && l12 == 0
        && l13 == 0
        && l14 == 0
        && l15 == 0
        && l16 == 0
        && l17 == 0
        && l18 == 0
        && l19 == 0
-- && l20 == 0
```

## Expected behavior

Fast compilation - non dependent on number of variables.

## System info:

- OS: Ubuntu
- Version 21.04
- plutus version: 58c093a49eb7a369865e361179d649264fc817a4

## Additional context

That's a minimal scenario. Not really sure if number of variables in scope or && operator or sth else is a culprit here.

Measurements:
number of variables / compilation time
variables up to l10 uncommented  - 4s
variables up to l15 uncommented  - 17s
variables up to l16 uncommented  - 30s
variables up to l17 uncommented  - 60s
variables up to l18 uncommented  - 110s
variables up to l19 uncommented  - 230s

**Comment by marcinbugaj** [comment]
Any update on this one?

**Comment by ak3n** [comment]
The fix is in progress.

**Comment by michaelpj** [comment]
Well, we're investigating *a* possible fix.
