### ISSUE TITLE
Can we install all of these plutus modules in our local ghc packages ?

### ISSUE THREAD

**Issue by manishdhakal** [input-output-hk/plutus#4214]
I am currently using vscode for programming. I want plutus IntelliSense to work in my workspace, so I can look up the definitions of the functions directly from my IDE. I think it will be possible if I can install these modules in my ghc packages.

PS: Because my GHC compiler does not recognize these modules there is always warning like this

![Screenshot_2021-11-13_10-29-22](https://user-images.githubusercontent.com/36515191/141606069-c0808f61-ad61-44aa-ae7a-e368900f94a5.png)
:

**Comment by kk-hainq** [comment]
Have you tried something like https://github.com/aloiscochard/codex or https://github.com/elaforge/fast-tags? I don't use it but my friend at work documented this:

> Navigate Plutus source code in `dist-newstyle` via Codex:
> 1. Install `codex` via `cabal install codex`.
> 2. Edit `~/.codex` and set `tagsFileName: .tags`.
> 3. Go to your project directory and run `codex update`.
> 4. Install `ctagsx` extension in VS Code. Reload the editor, then you can navigate to Plutus source code via the “Go to definition“ action.

**Comment by ak3n** [comment]
Thanks @kk-hainq for the reply! I hope it helps.

Closing the issue. Feel free to reopen.
