### ISSUE TITLE
Support SECP256K signature verification

### ISSUE THREAD

**Issue by Benjmhart** [input-output-hk/plutus#4233]
## Describe the feature you'd like

In order to support decentralized bridge technologies for the ERC20 token converter project and other bridging projects, it is clear that the SECP256k signature scheme is needed - likely as a low-level call from the plutus interpreter directly

## Describe alternatives you've considered

We've done some initial research on this at MLabs, and one of our researchers pointed to this existing implementation:
https://github.com/Chia-Network/bls-signatures

which has FFI bindings in Haskell:
https://github.com/hexresearch/hschain/tree/master/bls-signatures

**Comment by michaelpj** [comment]
The main thing we need is a high-quality, trustworthy implementation that we're comfortable linking into the Cardano node stack.

The linked implementation doesn't fill me with confidence:

> NOTE: THIS LIBRARY IS NOT YET FORMALLY REVIEWED FOR SECURITY

Are there any others?

**Comment by Benjmhart** [comment]
https://github.com/bitcoin-core/secp256k1 - Bitcoin's implementation

https://hackage.haskell.org/package/secp256k1 - another Haskell binding i quickly found

**Comment by Benjmhart** [comment]
If you can enumerate your standards, happy to dig deeper on this.

**Comment by michaelpj** [comment]
It would also be helpful to explain some of the usecases a bit more clearly, also so we know we're actually providing the right primitives.

**Comment by L-as** [comment]
https://github.com/haskoin/secp256k1-haskell seems to be of OK quality.

**Comment by Benjmhart** [comment]
@michaelpj - this actually comes from the ERC20 token converter team, who hopes to use the technology of Wanchain or similar to bridge tokens onto cardano in a decentralized fashion.

These technologies break up the private key among multiple validators, so that only by working in concert, can they properly sign a transaction.

Since the default transaction-level signature is incompatible, they  wish to provide the signature in Datum to be validated at the smart contract level.

**Comment by kozross** [comment]
@michaelpj Now that the PR to `cardano-base` is done (and nearly merged), what should be the next step? There's already a `VerifySignature` builtin, but it's hardcoded to a specific algorithm. Should I add another builtin, or generalize the existing one?

**Comment by michaelpj** [comment]
New builtin. It's unfortunate that we gave `verifySignature` such a generic name, it should really have been `verifyEd25519Signature`. The challenge will be costing it, but for now I think just leave the costing function as `mempty`.

**Comment by L-as** [comment]
Can't you rename it to that, and make the old name in PlutusTx.Builtins a deprecated alias of that?

**Comment by michaelpj** [comment]
That won't change the name in Plutus Core. We can potentially do something like that at the library level.

**Comment by michaelpj** [comment]
BTW: I'm not going to insist that we follow https://github.com/cardano-foundation/CIPs/pull/215 before getting this merged (unless you want to!), but I _would_ be keen to collaborate on a retroactive CIP. Partly to enshrine the motivation etc., and partly just to put more examples through the process.

**Comment by kozross** [comment]
@michaelpj I'd be happy to collaborate on a retroactive CIP. How would you like to do this?

**Comment by michaelpj** [comment]
I'll share a google doc with you. It's not the best editor for this, but it's good for collaboration and we can port it to markdown later.

**Comment by KowsarAtz** [comment]
@michaelpj We have a [related](https://github.com/input-output-hk/plutus/issues/4575) issue that I have opened 4 days ago and I would appreciate it if you take a look at it. We need to recover a public key from a signature (produced with an ethereum address) and a message hash. What we need is basically the exact implementation of **ethereum ecrecover function** which can be implemented using functions provided by libsecp256k1.

**Comment by KowsarAtz** [comment]
@michaelpj There is a https://github.com/input-output-hk/plutus/issues/4575 that I would appreciate it if you take a look at it. We need to recover a public key from a signature (produced with an ethereum address) and a message hash. What we need is basically the exact implementation of ethereum ecrecover function which can be implemented using functions provided by [libsecp256k1](https://github.com/bitcoin-core/secp256k1).

**Comment by KowsarAtz** [comment]
@michaelpj There is a related issue (https://github.com/input-output-hk/plutus/issues/4575) that I would appreciate it if you take a look at it. We need to recover a public key from a signature (produced with an ethereum address) and a message hash. What we need is basically the exact implementation of ethereum ecrecover function which can be implemented using functions provided by [libsecp256k1](https://github.com/bitcoin-core/secp256k1).
