### ISSUE TITLE
Spec: CK halting state

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#424]
I added an extra state (a big square) to the CK machine in the spec so that the machine can say that it's finished, and what the final result is. This happens when the stack is empty:  I just added it to make it obvious to the reader when the machine is finished.  We can take this back out, but we should still say somewhere that an empty stack means that the machine halts.  I don't think this was mentioned explicitly before.

**Comment by kwxm** [comment]
Maybe we can sort this out when everybody's made their contributions.

**Comment by effectfully** [comment]
I like it as well.

**Comment by kwxm** [comment]
I think the real reason I added this is that I wrote down similar descriptions of the CEK machine and the lazy machine in the document that I wrote about lazy evaluation, and there you need not just a term to make sense of the output of the machine, but also an environment, and a heap as well in the case of the lazy machine, and I needed a way to return those to the caller as well.  The square was supposed to suggest something like the stop button on a VCR, if anyone remembers those, or maybe the "Halmos symbol" for end of proof.

I think we did discuss what the machine should return to the caller, but never came to a 
conclusion.  If you end up with a term and an environment in the CEK machine, you might want to substitute the stuff in the environment into the term to get a closed term which is what the user actually sees.  This might matter if you're testing the machine and want to see what the result is, but I'm not sure what the situation is for a machine running on the blockchain.

**Comment by kwxm** [comment]
I thought this was the only technical change I'd made to the spec, but I now recall that I also corrected what I thought was a typo in the rules for validity of contexts.  I'll open a separate issue for that.

**Comment by michaelpj** [comment]
> and there you need not just a term to make sense of the output of the machine, but also an environment, and a heap as well in the case of the lazy machine, and I needed a way to return those to the caller as well

I think I'd always assumed that the "result" of the machine was just its state? So you run the state machine until it halts and then just look at the state. Doesn't that handle all of these cases uniformly?
