### ISSUE TITLE
What guarantees are there about Value structure on chain?

### ISSUE THREAD

**Issue by treeowl** [input-output-hk/plutus#4258]
It appears that every `Value` on chain (i.e., in a UTXO, mint result, etc.) has an Ada field (whether there are Ada or not). Is it possible for any other asset classes to be present in a `Value` on chain with quantity 0?

Are there any guarantees about the order of asset classes within a `Value` on chain?

**Comment by michaelpj** [comment]
There are no guarantees about either of these things in general. Even if we did provide guarantees about the representation as it appears in the `ScriptContext`, the operations on `Value` that we provide do not attempt to maintain any particular representation, so long as it is semantically correct.

**Comment by effectfully** [comment]
> It appears that every Value on chain (i.e., in a UTXO, mint result, etc.) has an Ada field (whether there are Ada or not).

Yes, see #5039 for more context.

> Is it possible for any other asset classes to be present in a Value on chain with quantity 0?

It seems this question was never answered. I asked the team. 

> Are there any guarantees about the order of asset classes within a `Value` on chain?

Michael already answered this question with "there are no guarantees", but I'd like to point out that there's an entire ticket dedicated to this discussion: #4509.

**Comment by effectfully** [comment]
> Is it possible for any other asset classes to be present in a Value on chain with quantity 0?

The answer is "no". From what I was able to gather ([1](https://github.com/input-output-hk/plutus/issues/4509#issuecomment-1084581604), [2](https://github.com/input-output-hk/plutus/issues/5039#issuecomment-1380082020)) you can put `0` there, but the ledger will simply treat it as a missing entry.

Closing, since these topics are better discussed in #5039 and #4509.
