### ISSUE TITLE
Consistent transaction examination whether it is a draft `TxInfo` or completed `Tx`

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/plutus#4276]
## Describe the feature you'd like

`TxInfo` represents planned transaction, when `Tx` represents a completed, signed transaction.
They have very similar data, but many access functions with different interface.

For example `Tx` has `lookupDatum`, when `TxInfo` has `findDatum` with a different interface.
Event mapping of `DatumHash` to `Datum` is performed in a different way.

It would be nice to either normalize treatment of these two, or provide a type class that abstracts these differences.

## Describe alternatives you've considered

Current alternative is to lookup, examine twice the interface for the same activity on `Tx` and `TxInfo`.

## Describe the approach you would take to implement this 

Easiest way would be to attempt to add functions that correspond to the other function with the same interface,
and mark inconsistent interfaces as deprecated in the long run.

**Comment by michaelpj** [comment]
`Tx` and friends moved to `plutus-apps`, and indeed have been replaced with `cardano-api` transaction types. I'm not sure what the status of something like this is now, but it would need to be reassessed there.

**Comment by koslambrou** [comment]
Confirming that in `plutus-apps`, we completely removed `Tx` and friends, and we use instead the `Tx` type of `cardano-api`. Therefore, if you have any issues with the new `Tx`, you should open an issue in the `cardano-node` repo (which contains `cardano-api`).
