### ISSUE TITLE
Why is MkPairData `Data -> Data -> Pair Data Data`?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4278]
https://github.com/input-output-hk/plutus/blob/master/plutus-metatheory/src/Algorithmic.lagda#L150

Perhaps I'm misunderstanding how `Data` maps to CBOR and backward.

I'm wondering why it's not `a -> b -> Pair a b`.

**Comment by ak3n** [comment]
`Data <-> CBOR` serialization/deserialization is defined at `PlutusCore/Data.hs`:

https://github.com/input-output-hk/plutus/blob/da4f85cdd2a3a261ce540e8dc51d2a3c5fa89ed2/plutus-core/plutus-core/src/PlutusCore/Data.hs#L56-L59

> I'm wondering why it's not `a -> b -> Pair a b`.

There is a [note about functions over built-in types](https://github.com/input-output-hk/plutus/blob/da4f85cdd2a3a261ce540e8dc51d2a3c5fa89ed2/plutus-core/plutus-core/src/PlutusCore/Constant/Typed.hs#L317) mentioned at `MkPairData` definition that goes into details.

https://github.com/input-output-hk/plutus/blob/da4f85cdd2a3a261ce540e8dc51d2a3c5fa89ed2/plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs#L104-L110

I hope that helps.

**Comment by L-as** [comment]
Thanks!
