### ISSUE TITLE
Contract ownership

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#428]
This problem is related to the [validating the next data script](https://github.com/input-output-hk/plutus/issues/426) problem in that I came across it when attempting to implement solution (3) described there. 

## Problem

Suppose we have a contract with two participants, A and B. Some of the actions supported by the contract only affect one of the participants' stake in the contract. For example, in the interest rate swap either participant is able to increase their margin/deposit or transfer ownership of their stake in the contract to a third party. It should be possible to do this without involving the other participant (because that would give them a effectively a veto). At the same time, if there is an action that affects both parts of the contract then either participant should be able to perform that action regardless of any changes that have been made to the other part. 

We want to avoid a requirement for B to know the most recent value of the state of A's part of the contract, because the only way that could be achieved is through de-serialisation of the data script (which we don't support at the moment) or by asking A to communicate the state through an external channel to B (which brings up trust and usability issues). We would like to get by with treating A's state as a binary blob that we don't need to touch.

## Proposed solution

How can we implement this in the state machine? 

At this point we shall introduce some terminology. We will say "role" to mean a part of the contract (the right to perform some actions on that contract) and "actor" to mean the individual, identified by a public key, who currently has that role. The roles of a contract stay the same, and are known before the contract begins, while the actors may change.

The first idea is to spread the contract across several addresses, namely one for each role. In the swap example, we have two roles, `Floating` and `Fixed`. An action that affects only one role is "transfer ownership", and an action that affects both role is "make payment". So we get the types `Role = Floating | Fixed` and `Action = TransferOwnership PubKey | MakePayment OracleValue`. We can then parameterise the validator script with the `Role` value, resulting in two distinct hashes for what is otherwise the same script. The validator script (still a state machine) now checks if the input it receives affects both roles, or just one of them. In case of `TransferOwnership` we can verify that no outputs from the other role's address are consumed, and in case of `MakePayment` we check that outputs at both addresses are spent and produced. 

![Diagram 1](https://i.imgur.com/AV5AITo.png)

In this diagram, the circles are transaction inputs/outputs and the rectangles are transactions. Each horizontal lane corresponds to one of the two addresses of the contract. t1 and t3 are `TransferOwnership` actions and t2 and t4 are `MakePayment`s. 

Transaction t2 is submitted by the Floating actor. Let's look at its inputs and outputs. A and B are the data scripts of the inputs it consumes, and A' and B' are the data scripts of its outputs. If t2 changes the states of the Fixed and Floating roles, then A' != A and B' != B. However, when the Fixed actor wants to create t3 then they need to know B'. So we are back to where we started. 

One potential solution is to split up the roles even further, into an "internal" and an "external" address. The script at the internal address records the role's current actor, and the script at the external address contains the rest of the role's state. Whenever we modify the state, we look at the value at the role's internal state to make sure that the transaction is legitimate. 

![Diagram 2](https://i.imgur.com/pNOkb0j.png)

In this diagram I used coloured squares to indicate the actor that submits a transaction. At the beginning, Orange is the Fixed actor and Green is the Floating actor. In t1, Orange transfers their role to Yellow. In t2, Green performs the `MakePayment` action. This transaction consumes outputs from all four addresses. The internal data scripts stay the same, so A=E and C=G. 

This is what I am implementing right now. The tricky part is that the validator script needs to consider four cases for each possible input (namely, Fixed-Internal, Fixed-External, Floating-Internal, Floating-External). Also I'm not entirely sure yet if we can prevent Green from tampering with the contract by producing their own version of "A" to the Fixed-Internal address. But I think that can be solved in the validator script.

**Comment by j-mueller** [comment]
Looking at the diagram I just had another idea that could make it easier to construct the validator script.

If we think of the validator script as returning `Bool` instead of `()` and `error` then the four inputs to `t2` together form a conjunction `val_A ∧ val_B ∧ val_C ∧ val_D`. Meaning that the transaction is only valid of the entire formula is true. Now, if we can manage to write the invariants of the contract as a proposition using a boolean algebra (with some uninterpreted "Theory" primitives like in an SMT solver) then we can convert that proposition to CNF, and each clause of the CNF corresponds to one of the addresses. So we could generate a validator script that knows which clause corresponds to which address, and only checks that its own clause is true (+ makes sure that all the other addresses are present in the transaction).

That should make it possible to describe the contract as a set of rules, and then generate the validator script and the contract endpoints from those rules using Template Haskell. Also we could feed the rules directly to Z3 and prove some properties about it.

**Comment by michaelpj** [comment]
I'm not sure if this works, but I think if we could make it work it would be useful in a number of contexts:

What if we could define a unique "token" to represent "being the floating party" as an *asset*. The idea would be that to perform an operation as the floating party you need to provide the token to prove that you have that role, and it is passed through the transaction unchanged. Selling your stake is then just a case of selling the asset.

However, this has a number of problems:
- You need to create an asset that can't be cloned, including by someone who can see the whole blockchain state.
    - I think this means it can't be data, it has to be something like ADA where linearity is ensured by the ledger rules.
- The token needs to be easily tradeable.

**Comment by michaelpj** [comment]
I think we might actually need a new token for my idea, i.e. multi-currency support of some kind.

**Comment by j-mueller** [comment]
> I think we might actually need a new token for my idea, i.e. multi-currency support of some kind.

yes that could work, issuing a new token for each contract.

(On the other hand, if we find a solution that doesn't require multi-currency support from the ledger then we can implement multi-currency with the existing system)

**Comment by j-mueller** [comment]
Another approach would be to assume that the initial owners of the contract are known to each other at the beginning, and we encode their identities in the validator script. In the data script we keep track of the changes of ownership that have happened, and whenever somebody does `ChangeOwnership` we add that to the list with a signature of the current owner. So at any point we can verify that the entire chain of transfers is legitimate. (A bit like a miniature blockchain inside the contract)

The only problem with this is that in order to verify the signature we'd need to be able to serialise a value inside Plutus (similar to solution (1) in #426 )

**Comment by michaelpj** [comment]
> A bit like a miniature blockchain inside the contract

Nice idea (also, vile). We'd essentially make a virtual asset for each role, and the contract would additionally function as a ledger tracking ownership of the asset.

Where do we need to serialize a value in this approach?

**Comment by j-mueller** [comment]
> Where do we need to serialize a value in this approach?

I was thinking of something like this (in Haskell):

```haskell
data Signed a = Signed { signature :: ByteString, value :: a }
data OwnershipChain = InitialOwner PubKey | TransferTo PubKey (Signed OwnershipChain)

signedBy :: Serialise a => PubKey -> Signed a -> Bool
signedBy pk (Signed sig vl) = checkSig pk sig (serialise vl)
-- assuming checkSig :: PubKey -> ByteString -> ByteString -> Bool

currentOwner :: OwnershipChain -> PubKey
currentOwner = \case
    InitialOwner pk -> pk
    TransferTo pk _ -> pk

isLegit :: Serialise a => PubKey -> OwnershipChain -> Bool
isLegit initPk = \case
    InitialOwner pk -> pk == initPk
    TransferTo newOwner sg = signedBy (currentOwner (value sg)) sg && isLegit initPk (value sg)
```

**Comment by michaelpj** [comment]
Sure, but you can write that serialization function yourself in Plutus Tx, I think. We don't need to serialize arbitrary other PLC programs, which was the issue before.

**Comment by j-mueller** [comment]
True... I'm going to try that out now

**Comment by j-mueller** [comment]
> You need to create an asset that can't be cloned, including by someone who can see the whole blockchain state. 

That's really the fundamental problem, and I'm a bit stuck at the moment, because every solution that I come up with has the problem that you could simply copy the output and modify the data script in your favour. For example, for the "mini blockchain" approach you could also put in a fake blockchain with bogus keys and matching signatures, and the script has no way of knowing that these are the actual keys of the past owners of the tokens.

I also thought about something you mentioned a while ago @michaelpj , namely a "master transaction" that sets up a pool of tx outputs, and each interaction with the contract consumes one of those outputs. But even that can be manipulated by producing a bad output to the address!

**Comment by j-mueller** [comment]
This looks similar to what I'm trying to build: https://eips.ethereum.org/EIPS/eip-721

**Comment by j-mueller** [comment]
Multi-currency is implemented on the mockchain (https://github.com/input-output-hk/plutus/pull/866), and with that we can write NFTs which can be used to encode the ownership of contracts.
