### ISSUE TITLE
PubKeyHash constructed by ScriptContext and hardcoded PubKeyHash not equal

### ISSUE THREAD

**Issue by ZDust482** [input-output-hk/plutus#4282]
Area
-
[x] Plutus Foundation Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code

Summary
-
I attempt to construct a simple validator script that only passes if signed by the given (hashed) key:
```
12f2f3e44e6e310abc78802d7078ec1fd0fa220ff47ad1bdb43397e2
```
There are issues when comparing bytestrings from ScriptContext to hard-coded bytestrings.

Steps to Reproduce
-

```
{-# INLINABLE getHolder #-}
getHolder :: PubKeyHash
getHolder = PubKeyHash "12f2f3e44e6e310abc78802d7078ec1fd0fa220ff47ad1bdb43397e2"

{-# INLINABLE mkValidator #-}
{-# INLINABLE mkValidator #-}
mkValidator :: BuiltinData -> BuiltinData -> ScriptContext -> Bool
mkValidator _ _ ctx = txSignedBy info getHolder
    where
        info :: TxInfo
        info = scriptContextTxInfo ctx
```

When attempting to build the transaction using the CLI and signing using `--required-signer payment.skey`, the validator unexpectedly fails with:

```
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 0 (in the order of the TxIds) failed with: 
The Plutus script evaluation failed: An error has occurred:  User error:
The provided Plutus code called 'error'.
```

Attempting to debug, I use the following validator in an attempt to log the signature provided in the script context:

```
{-# INLINABLE mkValidator #-}
mkValidator :: BuiltinData -> BuiltinData -> ScriptContext -> Bool
mkValidator _ _ ctx = traceError $ decodeUtf8 $ getPubKeyHash $ P.head signatories
    where
        info :: TxInfo
        info = scriptContextTxInfo ctx

        signatories :: [PubKeyHash]
        signatories = txInfoSignatories info
```
This gives the following output:
```
The provided Plutus code called 'error'.
Caused by: [
  (builtin decodeUtf8)
  (con bytestring #12f2f3e44e6e310abc78802d7078ec1fd0fa220ff47ad1bdb43397e2)
]
```
Which confirms that the correct public key is being used, but internally the BuiltinByteStrings do not seem to match.

**Comment by ak3n** [comment]
Thanks for the issue.

Please, try

```
getHolder :: PubKeyHash
getHolder = "12f2f3e44e6e310abc78802d7078ec1fd0fa220ff47ad1bdb43397e2"
```

as `PubKeyHash` has a special `IsString` instance.

**Comment by ZDust482** [comment]
> Thanks for the issue.
> 
> Please, try
> 
> ```
> getHolder :: PubKeyHash
> getHolder = "12f2f3e44e6e310abc78802d7078ec1fd0fa220ff47ad1bdb43397e2"
> ```
> 
> as `PubKeyHash` has a special `IsString` instance.

Thanks, this worked!

**Comment by colll78** [comment]
This does not work anymore, and should be reopened.
