### ISSUE TITLE
evaluateScript: include result term

### ISSUE THREAD

**Issue by srid** [input-output-hk/plutus#4290]
### Describe the feature you'd like

We would like to use Plutus to evaluate a custom-generated UPLC `Program`[^1].

`Plutus.V1.Ledger.Scripts` exposes `evaluateScript` and `applyArguments` which are useful for this, however the former is throwing away the term result, which we need.

The proposal is to change the type to:

```haskell
evaluateScript 
  :: forall m . (MonadError ScriptError m) 
  => Script -> m (PLC.ExBudget, [Text], Term Name uni fun ())
```

If accepted, I can open a PR.

[^1]: Generated both by [Pluto](https://github.com/Plutonomicon/pluto) and [Plutarch](https://github.com/Plutonomicon/plutarch) -- an assembly language and an eDSL respectively compiling to UPLC.

### Describe alternatives you've considered

We copy-pasted `evaluateScript` in our project and modified it, but that's not ideal because upstream can change.

**Comment by michaelpj** [comment]
You can just use the underlying functions. The function in the `plutus-ledger-api` is designed to be exactly what the ledger needs and no more.

**Comment by srid** [comment]
@michaelpj I forgot to state that `mkError` (used by `evaluateScript` to wrap user evaluation errors) is not exposed by the module. What do you think of exposing `mkError`? It would gives free improvements to Plutus' error handling improvements (eg: when #4270 gets addressed).

**Comment by michaelpj** [comment]
Why? Just use the evaluator yourselves directly and you can do whatever you want.
