### ISSUE TITLE
Timeline for support for newer GHC releases?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4303]
### Describe the feature you'd like

Currently we're stuck on GHC 8.10.*. It would be nice if we could use newer versions.

**Comment by michaelpj** [comment]
There are two issues:
- `haskell.nix` has to support the new version.
- Realistically, we will want to move most of IOHK's Haskell codebases in sync. That's a significant organizational undertaking.

**Comment by michaelpj** [comment]
Oh, and to be clear: Plutus is tightly bound to GHC versions since we provide a compiler plugin. So we're not likely to  support more than one major version of GHC at a time, at least in the short term.

**Comment by L-as** [comment]
Thanks! FWIW it seems like @locallycompact got it working with a newer GHC without the plugin seemingly.

**Comment by michaelpj** [comment]
I don't necessarily expect it to be that difficult, but I haven't tried. From a brief chat internally it seems like we might try to migrate once 9.2.2 is out.

**Comment by locallycompact** [comment]
I haven't done plutus or the plugin yet, it's next. The rest of the cardano stack is building.

**Comment by michaelpj** [comment]
I'm pretty sure that all of our projects would accept backwards-compatible patches for 9.2 support, FWIW.

**Comment by locallycompact** [comment]
cardano-prelude https://github.com/input-output-hk/cardano-prelude/pull/162

**Comment by locallycompact** [comment]
Win32-network https://github.com/input-output-hk/Win32-network/pull/10

**Comment by locallycompact** [comment]
ouroboros-network https://github.com/input-output-hk/ouroboros-network/pull/3490
