### ISSUE TITLE
Spec: validity of contexts

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#431]
Figure 3 in the Plutus Core specification has rules for the validity of contexts.  Only the rule for the empty context has a conclusion saying that it was valid; should the other two rules be changed to conclude that the things on the bottom are valid as well?  [When I opened this issue I thought I'd changed this in the spec, but it seems not.]

This also raises the question of why we need validity.  I don't think it's actually used anywhere else, so what purpose does it serve?  Do we want to prove that the typing rules only allow you to construct valid contexts?  Do we want to say that some rules are only applicable when the contexts are valid?

**Comment by effectfully** [comment]
I think it's common to define validity of context and then say that all contexts appearing in all rules are assumed to be valid. And there is probably a meta-theorem stating that conclusions of rules preserve validity of contexts, but I don't remember seeing one.

**Comment by wadler** [comment]
Yes, the other two rules should have "valid" at the bottom.

Roman is correct. We want lemmas such as:
  if \Gamma valid and \Gamma \vdash x \ni A then \Gamma \vdash A :: (type)

Sometimes, there are extra hypotheses in \Gamma \vdash x \ni A to guarantee
  if \Gamma \vdash x \ni A then \Gamma valid
but this system has not been formulated that way.

**Comment by kwxm** [comment]
Done.
