### ISSUE TITLE
Tests for new Rational

### ISSUE THREAD

**Issue by kozross** [input-output-hk/plutus#4315]
### Describe the feature you'd like

This is pending the landing of #4284. As [requested](https://github.com/input-output-hk/plutus/pull/4284#discussion_r778775751), a port of [MLabs' extensive tests](https://github.com/Liqwid-Labs/plutus-extra/tree/master/plutus-numeric/test) for the new `Rational` upstream is a good idea. There are some outstanding questions:

* What should we do about the size tests? This has a related issue in #4314.
* We use a lot of QuickCheck-driven law tests for various Plutus type classes, but the tests in Plutus seem to be Hedgehog-based. Should these be ported too, along with their attendant scaffolding?

### Describe alternatives you've considered

Not having these tests is not a good alternative, and the port was only not done previously due to previously-described issues.

**Comment by michaelpj** [comment]
> We use a lot of QuickCheck-driven law tests for various Plutus type classes, but the tests in Plutus seem to be Hedgehog-based.

Sigh. We do generally use hedgehog by preference. It wouldn't be the end of the world to have both, it just makes it more of a pain to maintain. My gut feeling is that translating simple examples is quite mechanical (and I can't imagine there are fancy generators for `Rational`), so maybe it's not too bad to just port them to hedgehog?

**Comment by michaelpj** [comment]
> What should we do about the size tests?

As I commented in the other issue, I think you could have perfectly good size tests just using AST size measures, which are easily available.

**Comment by kozross** [comment]
Porting to Hedgehog isn't really a problem - I'm familiar with both, and they're structurally quite similar.

**Comment by kozross** [comment]
Done in #4340
