### ISSUE TITLE
Not in scope: type constructor or class 'GHC.Tickish'

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus#4318]
### Summary

Using head of plutus with lts-18.21 via haskell.nix I get:

```
src/PlutusTx/Compiler/Expr.hs:75:16: error:
    Not in scope: type constructor or class ‘GHC.Tickish’
    Perhaps you meant one of these:
      ‘GHC.Tick’ (imported from GhcPlugins),
      ‘GHC.CmmTickish’ (imported from GhcPlugins),
      ‘GHC.CmmTickish’ (imported from CoreSyn)
    Neither ‘Class’, ‘CoreSyn’, ‘CostCentre’, ‘GhcPlugins’,
            ‘MkId’ nor ‘PrelNames’ exports ‘Tickish’.
   |
75 | type Tickish = GHC.Tickish
   |                ^^^^^^^^^^^
```

Branch here https://gitlab.homotopic.tech/templates/plutus-starter/-/tree/up-plutus

### Steps to reproduce the behavior

As above

### Actual Result

As above

### Expected Result

This form is stupid

### System info

This form is stupid

**Comment by ak3n** [comment]
Yeah, it's a known patch in haskell.nix.

#4299 should have help with this but it seems it doesn't. I guess #4325 should help this time.

**Comment by kk-hainq** [comment]
I am very sorry, should have been more thoughtful of `haskell.nix` users too :smiling_face_with_tear:.

**Comment by kk-hainq** [comment]
Thankfully #4331 fixed this for good now!
