### ISSUE TITLE
Unable to extract smart contract bytecode to textual format

### ISSUE THREAD

**Issue by SchmErik** [input-output-hk/plutus#4329]
### Summary

Hello, I am trying to gather a large body of untyped plutus programs as a part of a test suite for a project. The project goal is to write a semantics for untyped plutus in K. Anyway, I have looked at the tests in this repository and now I would like to scrape cardanoscan for popular smart contracts and save them as a part of the test suite.

Here is an example of an entry showing the smart contract: https://cardanoscan.io/transaction/8a541f04e9ef10e78c4dc4707e0582a24ae0c6c95d2c7c7ee9d146d093598019?tab=contracts
I am trying to copy/paste the bytecode to a text file and somehow decode this to a textual untyped plutus program. I tried using the `uplc convert` program but it doesn't seem like this encoding is supported. My colleague and I were discussing this and he believes that this might be in the CBOR format. Although this was removed from tools like uplc, it looks like several mentions of CBOR remain in the v1 api here: https://github.com/input-output-hk/plutus/blob/b4adeb6cb5d4fbb4f94cf2d65e6ac961534c4fcd/plutus-ledger-api/src/Plutus/V1/Ledger/Api.hs#L199
it's likely that cardanoscan used API's that were using the CBOR deserialize function.

Either way, I am having a difficult time generating a textual representation of smart contracts and I was wondering if you had any suggestions on what I could do. If this is indeed the CBOR format, could you possibly add the conversion capability back to uplc? Is there a different website that you recommend where the smart contract is encoded in a format that is supported by `uplc convert`?

### Steps to reproduce the behavior

1 go to the cardanoscan link above
2 save the contract bytecode to a text editor
3 use `uplc convert` to convert the bytecode to a textual (or flat) format

### Actual Result

There aren't any formats supported in `uplc convert` to translate this format to a textual format

### Expected Result

To be able to use `uplc convert` to convert smart contracts living on the cardano mainnet to a textual format.

### System info

Ubuntu 21.04

**Comment by SchmErik** [comment]
For the time being, one solution to get me going is for me to build this commit and try to run the proper uplc command:
```
commit 6727c37beaa5189db6d93b3fa944e32f1ff88395 (HEAD)
Author: Kenneth MacKenzie <kwxm@inf.ed.ac.uk>
Date:   Mon Jul 12 09:17:27 2021 +0100

    Kwxm/record flat bm results (#3529)
```

When I check out this commit and build, I get the following result:

```
# cabal build plutus-core
Warning: Requested index-state 2021-07-07T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-07-06T21:17:46Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] trying: base-4.14.1.0/installed-4.14.1.0 (dependency of Win32-network)
[__2] trying: lobemo-scribe-systemd-0.1.0.0 (user goal)
[__3] next goal: libsystemd-journal (dependency of lobemo-scribe-systemd)
[__3] rejecting: libsystemd-journal-1.4.5 (conflict: pkg-config package
libsystemd>=209, not found in the pkg-config database)
[__3] rejecting: libsystemd-journal-1.4.4 (conflict:
base==4.14.1.0/installed-4.14.1.0, libsystemd-journal => base>=4.6 && <4.13)
[__3] skipping: libsystemd-journal-1.4.3, libsystemd-journal-1.4.2,
libsystemd-journal-1.4.1, libsystemd-journal-1.4.0, libsystemd-journal-1.3.4,
libsystemd-journal-1.3.3, libsystemd-journal-1.3.1, libsystemd-journal-1.3.0,
libsystemd-journal-1.2.0, libsystemd-journal-1.1.0, libsystemd-journal-1.0.0
(has the same characteristics that caused the previous version to fail:
excludes 'base' version 4.14.1.0)
[__3] fail (backjumping, conflict set: base, libsystemd-journal,
lobemo-scribe-systemd)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, libsystemd-journal,
lobemo-scribe-systemd, Win32-network
Try running with --minimize-conflict-set to improve the error message.
```
I'm not sure how to resolve these messages as I am not very fluent with haskell/haskell tools. @kwxm or @jmchapman could you help me?

**Comment by jmchapman** [comment]
Are you running inside a nix-shell?

**Comment by jmchapman** [comment]
ok good, maybe you need to run `cabal update` before doing any building then.

**Comment by SchmErik** [comment]
I re-lauched the nix-shell and it's taking a while to initialize. I think my issue is similar to this thread: https://forum.cardano.org/t/win32-network-preventing-cabal-build-of-caradano-node/36936
Once I'm able to get into the nix-shell up and running, I'll try building again and following the instructions listed in this link. I'll let you know if I get stuck... Thanks!

**Comment by ashisherc** [comment]
@SchmErik the Plutus contract when built using, `cabal build` produces a CBOR of the compiled Plutus contract bytes. Those bytes are actually 2 times CBOR encoded. But when it is used in a transaction, it is decoded 1 time only. So the bytes you see on Cardanoscan, is actually CBOR encoded compiled bytes, but if you need the exact version as `cabal build`, you will need to byte encode it one time.

Lemme know if that made any sense, or else I will try to paste some examples here.

**Comment by SchmErik** [comment]
@ashisherc thanks for your reply. Could you post step by step examples? I'm not 100% clear on what commands I would write to get the results that you're saying. I think it would be great to document this process somewhere on cardanoscan. At this time, it's really hard for someone new to understand how to make sense of the content on the cardanoscan so you might get more questions like this in the future.

**Comment by SchmErik** [comment]
Friendly ping - hi @ashisherc! Do you have any updates on this?

**Comment by ashisherc** [comment]
Hey @SchmErik, It is not something specific to Cardanoscan, we use the Plutus bytes as they appear in the witness section of the tx. I was detailing the spec how Plutus script bytes are encoded when produced by the cabal, below are more details,

consider the bytes that appear in the witness set (and hence Cardanoscan) for a Plutus script - `43102345`

now if you want to get the bytes that are produced by the cabal command, you need to byte encode them once. you can use cbor.me site or any cbor lib for this, after encoding it should look like below,

`4443102345` - as produced by cabal

**Comment by SchmErik** [comment]
taking this conversation to a different channel. closing
