### ISSUE TITLE
Plutus Language Spec: builtin types and functions in chapter 5 does not match implementation

### ISSUE THREAD

**Issue by SchmErik** [input-output-hk/plutus#4332]
### Summary

The `uplc` program supports more constructs than mentioned in the current specification. Please update chapter 5 of the specification (aka the chapter titled "built in types, functions, and values") to reflect the V1 implementation.

### Steps to reproduce the behavior

1 look at spec chapter 5
2 look at haskell files that correspond to builtin implementations

### Actual Result

The information presented in chapter 5 should match the haskell file that corresponds to the builtin types and function

### Expected Result

Chapter 5 is missing several builtin types and functions

### System info

Does not matter

**Comment by kwxm** [comment]
This is fixed in the forthcoming new version of the specification.
