### ISSUE TITLE
Plutus Language Spec: Update flat format encoding to account for all builtins

### ISSUE THREAD

**Issue by SchmErik** [input-output-hk/plutus#4333]
### Summary

Appendix D does not cover all builtin types and functions that are supported by the implementation. Please update this section.

### Steps to reproduce the behavior

1 go to appendix D
2 go to flat format parser implementation

### Actual Result

appendix D should contain the same information present in the implementation

### Expected Result

Appendix D should contain the same information present in the implementation

### System info

does not matter

**Comment by kwxm** [comment]
This will be fixed in the forthcoming new version of the specification.
