### ISSUE TITLE
Plutus Language Spec: Grammar for program version does not match uplc implementation

### ISSUE THREAD

**Issue by SchmErik** [input-output-hk/plutus#4334]
### Summary

Grammar for the program version does not match what UPLC expects. Uplc expects 3 natural numbers separated by `.` the spec states something like this:
```
Version ::= [0-9]+(.[0-9]+)*
```
It should be something like this:
```
Version ::= [0-9]+.[0-9]+.[0-9]+
```

Here's an example where I run `uplc evaluate` with version values that corresponds to the first grammar:
```
$ echo "(program 1.2.3 (con integer 5))" | ./uplc evaluate
(con integer 5)
$ echo "(program 1.2 (con integer 5))" | ./uplc evaluate
uplc: Unexpected '(' at line 1, column 14
$ echo "(program 1 (con integer 5))" | ./uplc evaluate
uplc: Unexpected '(' at line 1, column 12
$ echo "(program 1.2.3.4 (con integer 5))" | ./uplc evaluate
uplc: Unexpected '.' at line 1, column 15
```
Looks like `uplc` only accepts the latter grammar. The specification needs to be updated to match this behavior. The grammar is listed in "Figure 1: Lexical grammar of Plutus"

### Steps to reproduce the behavior

see summary

### Actual Result

see summary

### Expected Result

see summary

### System info

ubuntu 21.04

**Comment by kwxm** [comment]
This is fixed in the forthcoming new version of the specification.
