### ISSUE TITLE
Plutus Language Spec: CEK machine rules for Untyped Plutus Core are incomplete

### ISSUE THREAD

**Issue by SchmErik** [input-output-hk/plutus#4336]
### Summary

The CEK machine rules listed in Appendix C (A CEK machine for type-erased Plutus Core) is incomplete. The existing rules in spec version 2.1 do not allow computation of programs such as application of identity functions and computation of builtins. Here are input programs that we have tried: 
```
[(lam x x) (con Int 0)]
```
and
```
[(builtin subInt) (con Int 55) (con Int 11)]
```
If we were to only use the rules listed in Appendix C, both program terms get stuck. We have recorded our findings here: https://github.com/runtimeverification/plutus-core-semantics/issues/57
https://github.com/runtimeverification/plutus-core-semantics/issues/58

@jmchapman has also mentioned the following over our shared slack channel: _the version of CEK in figure 23 has closures defined as pairs of values and environments C = (V,rho). We use a more efficient version of CEK that fuses values and environments together.  An additional reason to use the new version is to avoid mistakes with manipulating the environments._

Please update the spec to match the behavior that is mentioned by James.

### Steps to reproduce the behavior

-

### Actual Result

-

### Expected Result

-

### System info

-

**Comment by kwxm** [comment]
This should be fixed in the forthcoming new version of the speciification.
