### ISSUE TITLE
Dead links to wallet-api module in the multi-currency notes

### ISSUE THREAD

**Issue by discosultan** [input-output-hk/plutus#4339]
### Summary

The links to the Plutus wallet-api module seem to be outdated:

https://github.com/input-output-hk/plutus/blob/5836bf435ad09ae32d473481ca4b1cfe6cd17fc2/notes/multi-currency/multi-currency.md

### Steps to reproduce the behavior

N/A

### Actual Result

N/A

### Expected Result

N/A

### System info

N/A

**Comment by michaelpj** [comment]
`notes` is notes, not maintained documentation, I'm afraid.
