### ISSUE TITLE
Plutus.V1.Ledger.Ada.adaValueOf does not compile

### ISSUE THREAD

**Issue by ch1bo** [input-output-hk/plutus#4344]
### Summary

The function `adaValueOf` in the `Plutus.V1.Ledger.Ada` module is using `Data.Fixed.Micro` and fails to compile with error:

```
       uncaught exception: ErrorCall
       Error: Unsupported feature: Kind: forall k. k -> *
       Context: Compiling definition of: Plutus.V1.Ledger.Ada.adaValueOf
       Context: Compiling definition of: Hydra.Contract.Initial.validator
```

This is surprising, as it is located next to other functions intended to be used in Plutus code.

https://github.com/input-output-hk/plutus/blob/2a2a7f634e06440de45638c6c613c5428ed7c97d/plutus-ledger-api/src/Plutus/V1/Ledger/Ada.hs#L112-L118

### Steps to reproduce the behavior

For example by trying to compile this plutus validator:

```
validator _datum _redeemer context@ScriptContext{scriptContextTxInfo = txInfo} =
  valueProduced txInfo == adaValueOf 8_000_00
```

### Actual Result

Compilation error:
```
       uncaught exception: ErrorCall
       Error: Unsupported feature: Kind: forall k. k -> *
       Context: Compiling definition of: Plutus.V1.Ledger.Ada.adaValueOf
       Context: Compiling definition of: Hydra.Contract.Initial.validator
```

### Expected Result

Maybe this function should not have been included in PlutusV1 and we should now at least mark it as deprecated / not usable? For example `lovelaceValueOf` could be used if the provided value is an `Integer`

### System info

Plutus: 2a2a7f634e06440de45638c6c613c5428ed7c97d

**Comment by michaelpj** [comment]
Dupe: https://github.com/input-output-hk/plutus/issues/4275

Yes, there's lots of stuff in there that should not be in there...

**Comment by effectfully** [comment]
@michaelpj 

> Yes, there's lots of stuff in there that should not be in there...

Do you happen to know if it's still the case?

**Comment by michaelpj** [comment]
It's gone.
