### ISSUE TITLE
Do not use lazy `ByteString`s for variable names

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#436]
[The docs](https://hackage.haskell.org/package/bytestring-0.10.8.2/docs/Data-ByteString-Lazy.html) state:

> A key feature of lazy ByteStrings is the means to manipulate large or unbounded streams of data without requiring the entire sequence to be resident in memory. To take advantage of this you have to write your functions in a lazy streaming style, e.g. classic pipeline composition. The default I/O chunk size is 32k, which should be good in most circumstances.

so we shouldn't use lazy `ByteString`s for variables names, because names are small.

Moreover, we probably shouldn't use any pinned-memory-based data structures for name handling, because they [cause memory fragmentation](https://ghc.haskell.org/trac/ghc/ticket/13630) when there are many of them and we don't want to analyze whether we have "many" names or not, because it's error-prone.

Our best bet is probably [`ShortText`](https://hackage.haskell.org/package/text-short-0.1.1/docs/Data-Text-Short.html) (which is defined in terms of `ShortByteString` which is not pinned-memory-based). [Related blog post](https://markkarpov.com/post/short-bs-and-text.html).

**Comment by vmchale** [comment]
@mchakravarty is this pertinent given the use of `Unique`s? 

Is there any evidence of the above issues occurring when performing profiling or benchmarking?

**Comment by effectfully** [comment]
> A `Text` value uses unpinned memory - meaning that it is controlled by the GHC garbage collector and can be moved around at will. -- [string-types](https://haskell-lang.org/tutorial/string-types)

So we can go with just strict `Text` for now and try `ShortText` later in a benchmark-driven way if we have time for that.

**Comment by vmchale** [comment]
> A Text value uses unpinned memory - meaning that it is controlled by the GHC garbage collector and can be moved around at will. -- string-types

That's not relevant in our case.

**Comment by effectfully** [comment]
> That's not relevant in our case.

Why not? Pinned memory is leaky, unpinned memory is not. Seems relevant to me.
