### ISSUE TITLE
OverloadedStrings for Ledger.TokenName / Ledger.Crypto.PubKeyHash (onchain)

### ISSUE THREAD

**Issue by kindofdev** [input-output-hk/plutus#4404]
### Describe the feature you'd like

I think it would nice to be able to use **OverloadedStrings** for **Ledger.TokenName** in onchain code. I've checked in the source of **Ledger.TokenName** that **fromString** doesn't have INLINABLE pragma (maybe the error comes from this). 

On the other hand, I see that the mechanism works properly in offchain code. 

As an example, the code below fails when template Haskell tries to convert it to Plutus core. 

```
{-# LANGUAGE OverloadedStrings   #-}

{-# INLINABLE mkPolicy #-}
mkPolicy :: TokenName -> () -> ScriptContext -> Bool
mkPolicy tn () _ = 
    let expected = "foo" :: TokenName 
    in  traceIfFalse "fromString for TokenName doesn't work in onchain code" $ tn == expected
```

It's something really minor but it would save time for beginners trying to understand why **OverloadedStrings** for **TokenName** doesn't work in onchain code. 

Many thanks and congratulations on Plutus. 
 

### Describe alternatives you've considered

As I mentioned in the feature box, it's something really minor. 
I can get the same functionality doing:

```
{-# LANGUAGE OverloadedStrings   #-}

{-# INLINABLE mkPolicy #-}
mkPolicy :: TokenName -> () -> ScriptContext -> Bool
mkPolicy tn () _ = 
    let expected = TokenName "foo"  -- here OverloadedStrings for BuiltinString works properly.
    in  traceIfFalse "fromString for TokenName doesn't work in onchain code" $ tn == expected
```

**Comment by kindofdev** [comment]
Same thing happens for  **PubKeyHash**.

**Comment by ak3n** [comment]
Thanks for the suggestion!

Unfortunately, due to the technical reasons plutus plugin doesn't support `OverloadedStrings` with newtypes.

Maybe, to make it less confusing, it's worth to remove `IsString` instances for the on-chain newtypes.
