### ISSUE TITLE
nix build gives 503 error ... guessing this can't be done so easily on ubuntu

### ISSUE THREAD

**Issue by greggdourgarian** [input-output-hk/plutus#442]
warning: unable to download 'https://cache.nixos.org/nar/074xjadzxz09k69jnh4j2889w8k4wb8h7r2l0wgg3904cbnbk8ch.nar.xz': HTTP error 503; retrying in 283 ms

recommending any nix hosting service?

**Comment by michaelpj** [comment]
A 503 from the main nixos cache is an upstream problem if anything. This should work fine on Ubuntu, though.
