### ISSUE TITLE
Ability to Query the Node from Plutus Contracts. 

### ISSUE THREAD

**Issue by AI-madman** [input-output-hk/plutus#4439]
### Describe the feature you'd like

Hello,

I have been attempting to make a systematic Deadman Switch, but it requires the ability to get query information into the contract from the blockchain. This is basily trying to take the ability of DB-sync servers and build them into Plutus.

I understand that you may not have much time to devote to this project, but as it is necessary to port several subsets of projects over from other chains I think we need to do this urgently, so if you can give the references required to do this I am willing to build the ability into Plutus and submit the codebase for a general update.

**Comment by michaelpj** [comment]
On-chain scripts can only access local information through the transaction context that's passed in to them. If you want to make a concrete suggestion for what to add to the transaction context, you can open a specific issue and ultimately make a [CIP](https://github.com/cardano-foundation/CIPs/pull/215).
