### ISSUE TITLE
ghc-8.8.4-aarch64-deb9-linux.tar.xz  404 not found Haskell.nix

### ISSUE THREAD

**Issue by Mercurial** [input-output-hk/plutus#4440]
### Summary

When I clone the Plutus repo and try to do 

`nix build -f default.nix plutus.haskell.packages.plutus-core.components.library --extra-experimental-features nix-command` to build nix I get an error

```
curl: (22) The requested URL returned error: 404
error: cannot download ghc-8.8.4-aarch64-deb9-linux.tar.xz from any mirror
error: builder for '/nix/store/lwdg02y5q2vhk2vdxpc4dsivz9y8wi6c-ghc-8.8.4-aarch64-deb9-linux.tar.xz.drv' failed with exit code 1;
```

it seems that the url: `https://haskell.org/ghc/dist/8.8.4/ghc-8.8.4-aarch64-deb9-linux.tar.xz` doesn't exist anymore and it means Plutus can't be built in arm64 linux as of now

### Steps to reproduce the behavior

clone the repo and build nix

### Actual Result

curl: (22) The requested URL returned error: 404
error: cannot download ghc-8.8.4-aarch64-deb9-linux.tar.xz from any mirror
error: builder for '/nix/store/lwdg02y5q2vhk2vdxpc4dsivz9y8wi6c-ghc-8.8.4-aarch64-deb9-linux.tar.xz.drv' failed with exit code 1;

### Expected Result

It should build successfully

### System info

Ubuntu 20.04 Arm64 (Guest VM) on Parallels for MacOS M1

**Comment by hamishmack** [comment]
That should be fixed by https://github.com/input-output-hk/haskell.nix/pull/1390.

If you are still getting this error, please try `nix flake lock --update-input haskell-nix` to get a newer Haskell.nix version.

**Comment by Mercurial** [comment]
> That should be fixed by [input-output-hk/haskell.nix#1390](https://github.com/input-output-hk/haskell.nix/pull/1390).
> 
> If you are still getting this error, please try `nix flake lock --update-input haskell-nix` to get a newer Haskell.nix version.

thanks! will test and report back if Its working for me

**Comment by jfischoff** [comment]
I'm still getting this after `nix flake lock --update-input haskell-nix`

**Comment by ak3n** [comment]
@Mercurial I assume it worked. If not, please, re-open the issue.
