### ISSUE TITLE
Please stop giving ByteString orphan JSON instances

### ISSUE THREAD

**Issue by chessai** [input-output-hk/plutus#4441]
### Describe the feature you'd like

In `"plutus-ledger-api" Plutus.V1.Ledger.Orphans`, Data.ByteString.ByteString is given an orphan JSON instance, which encodes and decodes from base16. This forces all users of plutus to either adhere to this instance's behaviour, or provide newtypes. What's worse, is if users decide to use a package which provides aeson orphans, the instances will clash, and the user's code won't compile at all. I believe what plutus should do instead is decode from a Base16-encoded bytestring using a helper function or newtype, not impose an orphan instance on all users

**Comment by michaelpj** [comment]
It's already been deleted.
