### ISSUE TITLE
Monomorphism Restriction error with makeIsDataIndexed

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus#4453]
### Summary

Hi. I have this error when trying to use makeIsDataIndexed with a higher-kinded type. I find this odd because it's isomorphic to Maybe and I just copied how I saw that in the source.

```
data IdentRedeemer a = Step a | Finish

PlutusTx.makeIsDataIndexed ''IdentRedeemer [('Step,0),('Finish, 1)]
```

```
src/Plutus/Validators/Ident.hs:18:1: error: [-Wmonomorphism-restriction, -Werror=monomorphism-restriction]
    • The Monomorphism Restriction applies to the binding
      for ‘consCase_ah4E’
        Consider giving it a type signature
    • In the expression:
        let consCase_ah4E = \ arg_ah4A t_ah4D -> ...
        in ((PlutusTx.Builtins.matchList args0_ah4w) Nothing) consCase_ah4E
      In an equation for ‘indexMatchCase_ah4C’:
          indexMatchCase_ah4C
            = let consCase_ah4E = ...
              in ((PlutusTx.Builtins.matchList args0_ah4w) Nothing) consCase_ah4E
      In the expression:
        let
          fallthrough_ah4B = Nothing
          indexMatchCase_ah4C
            = let ...
              in ((PlutusTx.Builtins.matchList args0_ah4w) Nothing) consCase_ah4E
        in
          (((PlutusTx.Builtins.Internal.ifThenElse
               (index_ah4v
                  `PlutusTx.Builtins.Internal.equalsInteger` (0 :: Integer)))
              (Haskell.const indexMatchCase_ah4C))
             (Haskell.const fallthrough_ah4B))
            PlutusTx.Builtins.Internal.unitval
   |
18 | PlutusTx.makeIsDataIndexed ''IdentRedeemer [('Step,0),('Finish, 1)]
```

### Steps to reproduce the behavior

Source is here: https://gitlab.homotopic.tech/plutus/validators/ident

nix build

### Actual Result

See above

### Expected Result

See above

### System info

NixOS

**Comment by michaelpj** [comment]
Well, obviously we don't use `-Wmonomorphism-restriction`! I guess we could try and fix the generated code, but in general I don't think it's easy to promise that all TH-generated code will be warning-free for all possible warnings...

**Comment by locallycompact** [comment]
Oh, I thought this was implied by -Weverything. Never mind me.

**Comment by michaelpj** [comment]
Generating a type signature for the generated binding probably wouldn't be too bad... but if it's not a serious problem I'm not sure it's worth the effort.
