### ISSUE TITLE
Create versioned releases or tags of Plutus

### ISSUE THREAD

**Issue by MatthewCroughan** [input-output-hk/plutus#4538]
### Describe the feature you'd like

It seems like Plutus is not versioned in releases or git tags. How can I make an application if I don't know what version of Plutus I'm using, beyond a commit hash which is not human readable? I know people who are making lookup tables of known-good commits of this repository, which means they're effectively doing the job of releasing this code on behalf of IOHK. An example of a well released and versioned repository from IOHK is cardano-node, which has tagged releases. Why should Plutus be any different?

I'd love to hear from people on why this kind of releasing/versioning has never happened, or whether it should/shouldn't. Thank you.

**Comment by L-as** [comment]
https://github.com/input-output-hk/plutus/tree/release/1.0.0

**Comment by MatthewCroughan** [comment]
@L-as Has this always existed? You cannot find it by searching here:
https://github.com/input-output-hk/plutus/releases
https://github.com/input-output-hk/plutus/tags

**Comment by L-as** [comment]
Thank you!
