### ISSUE TITLE
Ethereum ecrecover support

### ISSUE THREAD

**Issue by KowsarAtz** [input-output-hk/plutus#4575]
According to [this commit](https://github.com/input-output-hk/plutus/commit/45cae06a94c1b35eea7e2e916c769dfbf37dbb4c), an initial secp256k1 support has been added to plutus-tx recently. I was wondering if there is going to be an implementation of Ethereum "ecrecover" any time soon since we need it in a project we are currently working on and the current secp256k1 builtins in plutus-tx will not be enough.

**Comment by L-as** [comment]
What do you need exactly and whi can't you implement it yourself?

**Comment by KowsarAtz** [comment]
> What do you need exactly and whi can't you implement it yourself?

I need to implement the verifySignature function defined [here](https://etherscan.io/address/0xe4f8d9a30936a6f8b17a73dc6feb51a3bbabd51a#code#F2#L86). The implementation is straightforward except for the last step which uses the ecrecover function. I have implemented ecrecover here which depends on below functions from libsecp256k1 (a library that cardano-base also depends on):

- secp256k1_ecdsa_recoverable_signature_parse_compact
- secp256k1_ecdsa_recover
- secp256k1_ec_pubkey_serialize

The point is that I'm not able to use my implementation directly inside the on-chain part of a plutus-contract since the way I have implemented it and the dependencies I have used, may violate the "INLINABLE" condition. So before starting to modify the implemented function, I had to make sure whether t[here](https://github.com/KowsarAtz/schnorr-secp256K1-haskell/blob/4ad3ee3b6f228255196c584d9a322082ca5214fb/src/SchnorrSecp256K1.hs#L164) are any plans to add more utilites to plutus-tx builtins that depend on libsecp256k1 including ecrecover implementation and If not, perhaps the first step would be importing the three functions mentioned above in here.

**Comment by michaelpj** [comment]
We won't be adding additional builtins in Vasil. You can make a CIP to propose adding additional ones, see:
- The process CIP: https://cips.cardano.org/cips/cip35/
- The CIP for the current SECP functions: https://github.com/cardano-foundation/CIPs/pull/250

**Comment by effectfully** [comment]
Such requests should go through the CIP route, hence I'm closing the issue.
