### ISSUE TITLE
Building on macOS Monterey Fails

### ISSUE THREAD

**Issue by jfischoff** [input-output-hk/plutus#4577]
### Summary

When trying to build with nix of macOS Monterey with an M1 the following error occurs: 

```
error: Desired GHC (8.8.4) is older than the bootstrap GHC (8.10.7) for this platform (aarch64-apple-darwin).
```

### Steps to reproduce the behavior

```
nix build -f default.nix plutus.haskell.packages.plutus-core.components.exes.traceToStacks 
```

### Actual Result

```
error: Desired GHC (8.8.4) is older than the bootstrap GHC (8.10.7) for this platform (aarch64-apple-darwin).
```

### Expected Result

Build succeeds

### Describe the approach you would take to fix this

I think the minimum bootstrap GHC for aarch64-apple-darwin must be 8.10.7

### System info

OS: macOS Monterey 12.1
Arch: aarch64-apple-darwin

**Comment by effectfully** [comment]
Got a response from @michaelpj on slack, quoting verbatim:

> Historically we haven't had any builders for aarch64-darwin, so we had no way of either a) caching the builds, or b) making sure that they worked. So we de-facto did not support it, and the answer was to use Rosetta. However, we're now on Moritz's hydra, which does have some aarch64-darwin builders, so we could consider adding support.

For now we're going to consider this a low priority issue.

**Comment by effectfully** [comment]
@jfischoff feel free to reopen if your issue persists.
