### ISSUE TITLE
"User-friendly" description of type system in Plutus Core specification.

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#465]
Before PlutusFest it was suggested that we should try to make the spec more user-friendly, and @mchakravarty proposed a plan here:

https://input-output-rnd.slack.com/archives/C21UF2WVC/p1543403856559300

I think the only thing that's still outstanding is explanation of the type system.  Could you have a go at this please, Rebecca?

We've just been merging stuff with the master branch without pull requests, the idea being that we would try to get it roughly into shape and then polish it when everyone was done.  I did quite a bit of fiddling with the Latex to try and get the figures into the right place.

**Comment by kwxm** [comment]
We should finish this.

**Comment by mchakravarty** [comment]
@jmchapman Could you work with @kwxm on this, please?

**Comment by jmchapman** [comment]
Sure.

**Comment by kwxm** [comment]
This is pretty much complete now, with just a couple of things needing clarification.  I don't think all of James' work on the type-system section is merged yet though.

**Comment by kwxm** [comment]
Let's close this now. The spec will require further work (eg, to remove sizes), but the current version is OKish.
