### ISSUE TITLE
Bigger size limit for `BuiltinByteString`

### ISSUE THREAD

**Issue by gege251** [input-output-hk/plutus#4697]
### Describe the feature you'd like

Currently `BuiltinByteString`s have 64 bytes size limit, but after some testing I found that it's actually less than that:
```
The Plutus script evaluation failed: DeserialiseFailure 175 "BadEncoding (0x00000042000d60ff,S {currPtr = 0x00000042000d60da, usedBits = 0}) \"Used more than 64 bytes decoding the constant: (con\\n  bytestring\\n  #048379352db5140c4a39137dd08c69193af732a7ceee3e6ff8cb07e37ce82e035579551734d7d9e4b6853d45c4a7846d5ef570e56f0353f83dad3b478a5f6699\\n)\""
```
The new `verifySchnorrSecp256k1Signature` and `verifyEcdsaSecp256k1Signature` functions however expect a 64 byte verification key, and we currently have to split that into two parts off-chain, and concatenate them on-chain. This is a problem that many developers will likely be facing, so we should add some documentation at least, and ideally raise the size limit.

### Describe alternatives you've considered

I can't see any sensible alternative. It's possible to use these functions with the above mentioned hack, but it adds unnecessary complexity.

**Comment by michaelpj** [comment]
The limit is there for legal reasons to prevent illegal data being included on the chain easily. We can however change the limit, and we have some ideas for tweaking the binary format so that it won't be needed at all. However, it's too close to the Vasil HF for any such improvements to make it in, unfortunately.

**Comment by gege251** [comment]
Thank you @michaelpj for the quick response!
I will create a PR with some documentation with the "bytestring splitting hack". I want to link some gh issue there to be able track the status of this.

**Comment by gege251** [comment]
Maybe we could add this to https://github.com/input-output-hk/plutus/issues/4476. However, BuiltinByteStrings *can* be longer that 64 bytes as long as they are not hardcoded or used in datums and redeemers, so I'm not sure, where and what sort of validation would make sense.

**Comment by michaelpj** [comment]
After inspecting the binary format again, we convinced ourselves that the structure of it is good enough to provide us with the protection that we need, and so the limit is actually unnecessary. I ripped it out and I think it's just barely going to sneak into Vasil. Phew.
