### ISSUE TITLE
Wrong semantics for `PlutusLedgerApi.V1.Value.gt` and `lt`

### ISSUE THREAD

**Issue by Niols** [input-output-hk/plutus#4707]
### Summary

I stumbled upon this bug while working on Hachi's [dynamic analysis toolkit for Plutus Core](https://blog.hachi.one/post/an-overview-of-hachi-s-security-toolkit-for-plutus-core/). Thank you @sjoerdvisscher for the very quick confirmation!

Everything is in the title. The implementations of `gt` and `lt` lead to curious behaviours where:
- `gt` is *not* the same as ~`not leq` or~ `geq and not eq` (edit: scratch `not leq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))
- `lt` is *not* the same as ~`not geq` or~ `leq and not eq` (edit: scratch `not geq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))
- `gt` and `lt` can change behaviour when adding zeroes in their `Value`s

I have not tried, but I feel it might actually lead to validators written in a defensive way (eg. “if the value is lower than this threshold then raise an error”) accepting values which they really should not as long as these values mention additional currencies at 0. I'll try to come up with a toy example at some point.

### Steps to reproduce the behavior

```haskell
$ nix-shell --run 'cabal repl plutus-ledger-api:plutus-ledger-api'
> :set -XOverloadedStrings
> import PlutusLedgerApi.V1.Value
> import PlutusTx.AssocMap qualified as Map
> cs1 = CurrencySymbol "CS1"
> cs2 = CurrencySymbol "CS2"
> tn1 = TokenName "TN1"
> tn2 = TokenName "TN2"
> v1 = Value $ Map.singleton cs1 $ Map.singleton tn1 33
> v1' = Value $ Map.fromList [(cs1, Map.singleton tn1 33), (cs2, Map.singleton tn2 0)]
> v1 == v1'
True
> v2 = Value $ Map.singleton cs1 $ Map.singleton tn1 22
> v1 `gt` v2
True
> v1' `gt` v2
False                                  -- here!
> v1' `geq` v2 && not (v1' == v2)
True
```

### Actual Result

- `v1` is equal to `v1'` as expected,
- `v1` is greater than `v2` as expected,
- but `v1'` is *not* greater than `v2`.

### Expected Result

`v1'` is equal to `v1` and should therefore behave in the same way. In this case, it should probably also be greater than `v2`. `gt` should also be logically equivalent ~to `not leq` and~ to `geq and not eq`.  (edit: scratch `not leq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))

### Describe the approach you would take to fix this

The issue comes from the fact that `gt` (and similarly `lt`): https://github.com/input-output-hk/plutus/blob/1877215dff03ceaf2c6d5882dd9e0fff8edab143/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L348-L352 relies on `checkBinRel`: https://github.com/input-output-hk/plutus/blob/1877215dff03ceaf2c6d5882dd9e0fff8edab143/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L330-L340 which “[checks] whether a binary relation holds for value pairs of two `Value` maps, supplying 0 where a key is only present in one of them.” In the case where a key is present in only one of them, bound to a value of `0`, the binary relation will then be checked on `0` and `0`. For `(<)` and `(>)`, this will then trivially fail.

I see three approaches to fix it:
1. `gt` could simply be defined ~as `not leq` or~ as `geq and not eq`,  (edit: scratch `not leq`; cf @michaelpj's comment [below](https://github.com/input-output-hk/plutus/issues/4707#issuecomment-1157650128))
2. `gt` could eliminate all bindings leading to `0` before calling `checkBinRel`, or
3. `gt` could rely on an alternative version of `checkBinRel` that does not call its predicate argument in case of `This 0`, `That 0` and `These 0 0`.

### System info

OS: NixOS unstable
Commit: tested on last commit on `master` as we speak: 1877215dff03ceaf2c6d5882dd9e0fff8edab143

**Comment by michaelpj** [comment]
Yep, this is absolutely a bug. I suggest we take approach 1. Note that `not leq` is incorrect, as the order is a partial order not a total order, so we have to do `geq and not eq`.

**Comment by Niols** [comment]
You're absolutely right about `not leq`! I edited my report to scratch occurrences to it.
