### ISSUE TITLE
Failed to deserialise our own program

### ISSUE THREAD

**Issue by Mr-Andersen** [input-output-hk/plutus#4709]
### Summary

Receiving

```
FAIL
      But it didn't.
      Result: ExecutionResult {outcome = Left (CaughtException Failed to deserialise our own program! This is a bug, please report it. Caused by: BadEncoding (0x0000000001cf9537,S {currPtr = 0x0000000001cf94d3, usedBits = 3}) "usedBits /= 0"), txStats = ContractStats {estimatedBudgets = fromList []}, contractState = ()}
```

while running seemingly innocent test

### Steps to reproduce the behavior

1. `git clone git@github.com:Mr-Andersen/plutus-bug-report && cd plutus-bug-report`
2. If you want to compile `constantPolicy`:
   
   ```
   nix build -L .#onchain:exe:onchain
   ./result/bin/onchain offchain/oneshot-policy/contracts/
   ```

   Prebuilt result is already in `./offchain/oneshot-policy/contracts/`

3. To run the test:

   `nix develop .#offchain -c bash -c "cd offchain && cabal test"`

### Actual Result

```
Building test suite 'offchain-test' for offchain-0.1..
Running 1 test suites...
Test suite offchain-test: RUNNING...
Fake NFT minting
  Plutarch.Contracts.Constant.mintContract
    Contract should succeed:
The tip of the local node: SlotNo 0
Connecting to the node using socket: /tmp/nix-shell.OPa8l1/test-cluster341934/node/node.socket
Starting webserver on port 9083
A Swagger UI for the endpoints are available at http://localhost:9083/swagger/swagger-ui
Syncing (100%)
FAIL
      But it didn't.
      Result: ExecutionResult {outcome = Left (CaughtException Failed to deserialise our own program! This is a bug, please report it. Caused by: BadEncoding (0x0000000001cf9537,S {currPtr = 0x0000000001cf94d3, usedBits = 3}) "usedBits /= 0"), txStats = ContractStats {estimatedBudgets = fromList []}, contractState = ()}
```

### Expected Result

Test is completed

### System info

> nixos-version
22.05.915.9ff91ce2e4c (Quokka)

Plutus rev: 6cceda4793ee125dc700c63ff780593e387696b0 (taken from flake.lock)

**Comment by michaelpj** [comment]
It looks like you're creating your scripts with `plutarch`, not our tools, so my guess is it's a bug in their stuff.

**Comment by Mr-Andersen** [comment]
@michaelpj so "Failed to deserialise our own program" actually means just "Failed to deserialise a program"?

**Comment by michaelpj** [comment]
It used to only be possible to fail there if the plugin was broken, but now there is `loadFromFile` it will fail like that if you give it a bad program.

**Comment by michaelpj** [comment]
We should fix the error.
