### ISSUE TITLE
Compressability of Plutus Core

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#471]
Code size has come up a few times as a potential issue for core nodes. An obvious way to mitigate this is good compressability of Plutus Core, both within a program and ideally across programs (if you are compressing the data for a series of transactions).

Compression algorithms love identical subequences, and at the moment we make things unnecessarily hard for them, at least two reasons:
- Actually identical terms won't have the same serialization, because their variables are identified by uniques, and so their serialization is affected by *where* they appear in the enclosing program.
    - The only good solution I can think of for this would be to switch to de Bruijn indices instead of uniques.
    - We could potentially do this just for serialization if we wanted. Being parametric over the types of names helps us!
    - This would also help with our current issue about debug printing in tests: we want to see distinct variables as distinct, but the particular uniques keep changing! Not a problem with de Bruijn indices.
- Terms that are identical up to variable names won't have the same serialization, because we serialize variable names (and annotations, but they're always unit, so that's okay).
    - This is easy to solve: just have a serialization mode that discards names, or run a pass over the program to discard them before serializing.

**Comment by michaelpj** [comment]
I actually really like the idea of having a different `Name` type for de Bruijn indices. Then we just write `debruijnify :: Term TyName Name a -> Term TyIndex Index a` and we're done.

**Comment by vmchale** [comment]
Do you have measurements of such a compression advantage? I can't see why de Bruijn indices would help. In either case it's just an `Int`.

**Comment by michaelpj** [comment]
No, just conceptual based on what I know about compression. But let me spell it out. 

Consider the unit type: `(all a (fun a a))`. Suppose it occurs twice in a program P. With uniques we'll get two terms `(all a_u1 (fun a_u1 a_u1))` and `(all a_u2 (fun a_u2 a_u2))`. Serializing those will use the uniques, producing two non-identical byte sequences. They represent the same type, but the poor compression algorithm doesn't know that.

Now, suppose we use de Bruijn indices. In this case both occurrences are `(all _ (fun 1 1))`. Serialization uses the index, and so they are both serialized to an identical byte sequence.

(This has made me notice a problem with my proposal to just have a different kind of name - in the de Bruijn representation the binders are nameless, so there isn't really anything to put there. We could just put 0 to mean "this index", I guess.)

**Comment by vmchale** [comment]
Ah okay, thanks.

**Comment by nau** [comment]
This is excellent idea.

**Comment by kwxm** [comment]
1.  @effectfully has a pull request to remove uniqueness for booleans (and presumably also units) at https://github.com/input-output-hk/plutus/pull/268 (we discovered that renaming slows things down significantly, and it's not necessary for built-in values), so that might cause part of this problem to go away.

2. Do you know for a fact that using unique names really does make things significantly less compressible?  It would be good to see some evidence that this really is a problem before attempting to solve it.

3. Plutus Core is kind of weird, and I wonder if we could come up with a custom compression method (although that might be a difficult and time-consuming task).  I have a vague memory of hearing about a compression scheme for Java bytecode that only allowed the encoding of verifiable code, so if decompression succeeded you'd be guaranteed to have something that the verifier would accept.  Unfortunately I can't find that at the moment.  I wonder if it's conceivable that we could come up with a compression scheme that would only work on well-typed PLC?  That would be very interesting, but it could be a difficult problem.

**Comment by effectfully** [comment]
> The only good solution I can think of for this would be to switch to de Bruijn indices instead of uniques.

Agreed.

> This would also help with our current issue about debug printing in tests: we want to see distinct variables as distinct, but the particular uniques keep changing! Not a problem with de Bruijn indices.

This is great. We do not lie in golden files, no parsing is required, we do not need to perform any checks over terms and yet this is as reliable as it can be. I'm all for it.

**Comment by michaelpj** [comment]
@kwxm 

> @effectfully has a pull request to remove uniqueness for booleans (and presumably also units) at #268 (we discovered that renaming slows things down significantly, and it's not necessary for built-in values), so that might cause part of this problem to go away.

That just means we don't rename them before we put them in the program initially, I'm pretty sure we still do a global renaming pass before typechecking. So I don't think that will make any difference.

> Do you know for a fact that using unique names really does make things significantly less compressible? It would be good to see some evidence that this really is a problem before attempting to solve it.

Not sure what I can do other than implement it and have a see ;) Guess I'll try that. 

> Custom compression method.

Maybe, but all I'm proposing is that we avoid making ourselves unnecessarily difficult for normal compression algorithms to handle. I think that should get us a lot of benefit, tbh.

**Comment by kwxm** [comment]
@michaelpj 

I guess the point I was trying to make is that standard compression algorithms are about compressing linear sequences of bytes (where indeed recurring subsequences are good for compressibility), whereas PLC terms are really _trees_,  and other compression methods may be more appropriate. Whether de Bruijn indices would help with that kind of thing I'm not sure. I suppose I should really go and find out, instead of just talking nonsense...

I agree that being parametric over the types of names is really helpful because then at least we can keep readable names in situations where they'd be useful: if we went 100% de Bruijn we'd be waving goodbye to the final vestiges of debuggability.

**Comment by michaelpj** [comment]
Given that usually when you serialize trees you lay out subtrees sequentially (as we do), compressing recurring sequences of bytes is perfectly good for compressing repeated subtrees too.

Maybe there is something better, of course!

**Comment by michaelpj** [comment]
> It sounds like you're replacing names with both empty strings and de Bruijn indices, which seems contradictory.

Our names have both strings (derived from parsing) and uniques attached. The strings do nothing except affect how it's printed.`debruijn` turns the uniques into indices, and keeps the strings; `strip` turns all the strings into `""`.

> Also, if we have things with large repeated subtrees, should we think about doing that in memory, with a DAG instead of a tree? 

I don't think we need to worry about *memory* usage. These things are still pretty small, it's just if you have millions of transactions that you might care.

**Comment by mchakravarty** [comment]
Is using merkelized abstract syntax trees (e.g., [Section 4.2 in "Simplicity: A New Language for Blockchains"](https://blockstream.com/simplicity.pdf)) not a better way to save space? One big advantage of MASTs is that we don't need to decompress. Traditional compression only saves transmission costs, but nowhere else.

**Comment by mchakravarty** [comment]
> That seems relevant. It seems decompression is a bottleneck in the plutus use cases test suite.

Interesting.

As on-chain scripts a very much automata-style code with lots of conditionals, MAST seem to promise a very significant reduction of the size of script code that needs to be attached to transactions.

**Comment by michaelpj** [comment]
Transmission *and* storage costs. They're a big deal, though! People are already complaining about the size of the chain even before we start adding scripts to it.

MASTs may be nice: however what I'm proposing here is:
- Easy
- Compatible with what people are going to be doing anyway

People are going to compress the chain - they would be crazy not to. All this does is make that work better for little cost to us. If you don't like manually compressing and decompressing things, you can use zfs which will transparently compress things for you at the filesystem level. Even better!

> It seems decompression is a bottleneck in the plutus use cases test suite.

I thought you said it was deserialization? That's unrelated, no?

**Comment by mchakravarty** [comment]
> People are already complaining about the size of the chain even before we start adding scripts to it.

Scripts don't make the chain that much bigger. Remember that redeemer *and* validator are transmitted with the spending transaction. The locked output only has the validator hash (and not the whole script). After validation, of a block, there is also no need to store the scripts.

Data scripts are a different matter, though. They need to accompany the transaction they are attached to. Hence, they also need to be stored. (MAST also doesn't help for data scripts.) 

Anyway, it is of course good if we can make PLC easier to compress without making it more complex. However, the big win is going to come from MAST.

**Comment by michaelpj** [comment]
> Scripts don't make the chain that much bigger.

Ah yes, they do make the chain bigger but don't make the UTxO set much bigger. That is good! Although presumably people will occasionally store chunks of full chain too, to check other people's work if nothing else.

> However, the big win is going to come from MAST.

I'm sceptical, but happy to be shown wrong :)

(If MAST doesn't help for data scripts, and data scripts are going to be responsible for the majority of script-related space usage, doesn't that suggest the opposite?)

**Comment by kwxm** [comment]
See also #1592.

**Comment by kwxm** [comment]
I'm going to close this now.  See https://github.com/input-output-hk/plutus/tree/master/docs/plutus-core/Merklisation for lots of experimental results.  The outcome is that (after some simplification) untyped Plutus Core is highly compressible, but Merklisation doesn't help a lot.
