### ISSUE TITLE
Plutus context list to maps undocumented?

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/plutus#4718]
It seems that in the Plutus V2 context, some types were switched from lists to maps, but this isn't mentioned anywhere. What was the rationale for this change?

Plutus V2 context: https://github.com/input-output-hk/plutus/blob/65fa7ce05a810947f565ac59b4d4e35b3cd5d1b3/plutus-ledger-api/src/PlutusLedgerApi/V2/Contexts.hs#L87

Plutus V1 context:  https://github.com/input-output-hk/plutus/blob/65fa7ce05a810947f565ac59b4d4e35b3cd5d1b3/plutus-ledger-api/src/PlutusLedgerApi/V1/Contexts.hs#L108

Seems this change was introduced without more context here: https://github.com/input-output-hk/plutus/pull/3952

**Comment by michaelpj** [comment]
`Map` is more accurate, it was an oversight that they weren't before.

**Comment by effectfully** [comment]
> but this isn't mentioned anywhere

We now have a changelog, so breaking changes like that should end up there. Otherwise there doesn't seem to be anything else that we could do here, so I'm closing. Feel free to reopen if you disagree.
