### ISSUE TITLE
What is the point of `defaultVersion` and versions?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#4754]
I can't find a reference to `Version ann 2 0 0` or similar, it seems like there's only one such "version", even though there are three Plutus versions.

**Comment by michaelpj** [comment]
Currently it is unused. In future, if we change the actual language e.g. by adding or removing features, we may use it to distinguish such cases.

**Comment by michaelpj** [comment]
https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-core/src/PlutusCore/Core/Type.hs#L94

**Comment by L-as** [comment]
Thanks!
