### ISSUE TITLE
Backport NoThunks instances to release branch

### ISSUE THREAD

**Issue by Soupstraw** [input-output-hk/plutus#4760]
### Describe the feature you'd like

Ledger would like to have #4687 backported to the release branch so that we can run `NoThunks` tests on the whole chain state. Related issue: [cardano-ledger/#2853](https://github.com/input-output-hk/cardano-ledger/issues/2853)

### Describe alternatives you've considered

Currently we disabled `NoThunks` tests for `EvaluationContext` on ledger.

**Comment by zliu41** [comment]
Done in #4761
