### ISSUE TITLE
Playground releases

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#480]
There are at least two external tutorials for PlutusTx now, and some of the code in those tutorials will stop working soon due to changes such as https://github.com/input-output-hk/plutus/pull/474 (renaming `PendingTx'` to `PendingTx`). 

The API is not finalised yet and further changes are unavoidable. To prevent a situation where a lot of the documentation is outdated before Plutus is even available on the blockchain we should 

* Show the current version in the Playground (commit ref + date would be enough)
* Record all changes in the changelog
* Link from Playground to the deployed version on Github

**Comment by michaelpj** [comment]
I think this is in a good place now.
