### ISSUE TITLE
Plutus Ledger API haddocks incorrectly state that SHA256 is being used.

### ISSUE THREAD

**Issue by peter-mlabs** [input-output-hk/plutus#4801]
### Summary

According to a comment from @JaredCorduan [here](https://github.com/input-output-hk/cardano-ledger/issues/2941#issuecomment-1203012829), all hashes in the cardano-ledger should be blake2b. 

Areas where I _know_ that SHA256 is referenced in the haddocks:

- `ScriptHash`
-  `DatumHash`
- `ValidatorHash`
-  `RedeemerHash` 
- `MintingPolicyHash`
-  `StakeValidatorHash`
- `TxId`.

I'm not sure whether all of these _should_ be blake2b, but Jared has confirmed that at least TxId should be.

### Steps to reproduce the behavior

Look at the source in `src/PlutusLedgerApi/V1/Scripts.hs`, `src/PlutusLedgerApi/V1/Contexts.hs`, `src/PlututsLedgerAPI/V1/Tx.hs`.

### Actual Result

References to `Digest SHA256` and `(...) using a SHA256 hash` appear.

### Expected Result

These should most likely say blake2b, sometimes 224 and sometimes 256.

### Describe the approach you would take to fix this

- Determine which hashes _should_ be blake2b, and which variants.
- `grep -rie "sha256"` and make sure that all of the relevant instances have been updated.

### System info

Latest master (commit 107d7e7ec5a1c033228c402ee221794117566d15)

**Comment by JaredCorduan** [comment]
The only hash that is used in the cardano ledger is blake2b. This includes _all_ the hashes listed above. See appendix A.1 of the Shelley ledger spec.

In particular, we use blake2b 224 for hashing scripts (including the minting policy ID), and blake2b 256 for hashing datums.
