### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/plutus#4951]
### Describe the feature you'd like

This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

Include the Standard Code of Conduct
Identify the Core Maintainers

**Comment by thealmarty** [comment]
Hi, we link to the code of conduct [here](https://github.com/input-output-hk/plutus/blob/master/CODE_OF_CONDUCT.md) and we list the core maintainers [here](https://github.com/input-output-hk/plutus/blob/master/CONTRIBUTING.adoc#project-roles-and-responsibilities).

**Comment by effectfully** [comment]
The request was answered, I'm closing the issue. If you disagree, feel free to reopen.
