### ISSUE TITLE
Unreachable links in Readme

### ISSUE THREAD

**Issue by DavidLeoni** [input-output-hk/plutus#4981]
Hi, 

I noticed several links in https://github.com/input-output-hk/plutus/blob/master/README.adoc  point to `cicero.ci.iog.io/api/fact` which redirects to google services requiring authentication, for example for 

Plutus Technical Report (draft) https://cicero.ci.iog.io/api/fact/cd621238-b1b5-49b3-8971-cac97f27824d/binary

I get this message:

```
Access blocked: Production can only be used within its organization

Production is restricted to users within its organization. If you think you should have access, you can contact the developer. Learn more about this error
If you are a developer of Production, see error details.
Error 403: org_internal
```

in particular check all links in  

- [Specifications and design section](https://github.com/input-output-hk/plutus/blob/master/README.adoc#specifications-and-design)
- [Academic papers section](https://github.com/input-output-hk/plutus/blob/master/README.adoc#academic-papers): has both cicero and also links to paywalls like https://doi.org/10.1007/978-3-030-33636-3_15

**Comment by michaelpj** [comment]
Unfortunately this seems to be caused by our recent move to cicero. I don't know if there's a way to make those links publicly available, which is annoying. I've asked internally to see if there's a way to regain the old behaviour :(

**Comment by Niols** [comment]
Any news on this front?

**Comment by thealmarty** [comment]
> Any news on this front?

We have moved back to Hydra. Could you please try again?

**Comment by michaelpj** [comment]
It still won't work. They need to point to the new hydra.

**Comment by thealmarty** [comment]
Sorry about this. I've tagged some relevant people I'll make sure it's high on their list. It's not good that you can't even read the readme!

**Comment by michaelpj** [comment]
They're back!

**Comment by SmaugPool** [comment]
Some docs are still missing, for example the "Design Specification for Delegation and Incentives in Cardano":

https://hydra.iohk.io/build/790053/download/1/delegation_design_spec.pdf

Or is it elsewhere @michaelpj ?

**Comment by michaelpj** [comment]
No idea, sorry.

**Comment by dostrelith678** [comment]
All links in the "Specifications and design" section and almost all links in the "Academic papers" section are unreachable again.

e.g. https://ci.zw3rk.com/job/input-output-hk-plutus/master/x86_64-linux.plutus-core-spec/latest/download/1

```
404 Not Found
Jobset ‘master’ doesn't exist.
```
