### ISSUE TITLE
`NoThunks` instance for `Data`

### ISSUE THREAD

**Issue by lehins** [input-output-hk/plutus#4983]
### Describe the feature you'd like

In ledger we currently define an orphan instance, which would have a better home here, think. Would it be possible to move it here?

Either deriving any class:

```haskell
deriving instance NoThunks Plutus.Data
```
or using generic:

```haskell
instance NoThunks Plutus.Data
```

https://github.com/input-output-hk/cardano-ledger/blob/94d1a85919edeff0a2c38a551fe7ed4c922f71eb/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Data.hs#L107

**Comment by michaelpj** [comment]
Yes absolutely.
