### ISSUE TITLE
Value checking and checking whether types are normalized

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#499]
There are several problems in `Language.PlutusCore.Check.Normal` 

1. An infinite loop:

```haskell
checkTerm :: (AsNormalizationError e TyName Name a, MonadError e m) => Term TyName Name a -> m ()
checkTerm p = void $ throwingEither _NormalizationError $ checkTerm p
```

2. Why does checking that all types appearing in a term are normalized require return the term back?

```haskell
checkT :: Term tyname name a -> Either (NormalizationError tyname name a) (Term tyname name a)
```

It can be just

```haskell
checkT :: Term tyname name a -> Either (NormalizationError tyname name a) ()
```

Same for `termValue`, `typeValue`, etc.

3. `NormalizationError` is misleading: we do not normalize there, only check whether things are already normalized.

4. We have the problem that `eqInteger {s} x y` is considered a value. This is a long-standing problem which we can't solve right now, because we're not yet settled on whether builtins are saturated or not or maybe we want to throw static builtins away entirely (which is another argument for doing that).

5. Checking whether a term is a value also entails checking that all types in it are normalized. Those should be two distinct checks, because sometimes we want the former and not the latter and vice versa.

6. Names like `checkT` and `preCheck` are not helpful.

7. Checking whether a term is a value is also defined in `View.hs`. We need to merge the two versions (possibly by just throwing away `isValue` from `View.hs`).

**Comment by kwxm** [comment]
@effectfully Can we close this?  The file looks quite different now.

**Comment by michaelpj** [comment]
It could still do with a tidy, it's weirdly structured.
