### ISSUE TITLE
Use tagref?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/plutus#5004]
### Describe the feature you'd like

Found https://github.com/stepchowfun/tagref on the [Haskell subreddit](https://old.reddit.com/r/haskell/comments/zgndwz/spj_on_the_note_system_used_in_the_ghc_codebase/izi5p7c/).

**Comment by thealmarty** [comment]
Thanks for your suggestion. We've made a note and talked about it. We currently don't feel a strong need for this. Have you tried it in other projects? What's your user experience?

**Comment by zliu41** [comment]
It would be better if tags can be customized, since we use `Note [title]` and `See Note [title]` throughout the repo.

**Comment by L-as** [comment]
I have not tried this. I just thought it's interesting.

**Comment by thealmarty** [comment]
Closing this for now.
