### ISSUE TITLE
Pattern match fails but if-then-else works

### ISSUE THREAD

**Issue by fallen-icarus** [input-output-hk/plutus#5017]
### Summary
Using pattern matching to control program flow failed while using if-then-else instead worked. This seems like a compile error.

I have the relevant type synonym here:
``` Haskell
-- | Swap Datum
type Price = Rational  -- ^ From PlutusTx.Prelude
```

and the relevant on-chain code here:
``` Haskell
    -- | ValidatorHash of this script
    scriptValidatorHash :: ValidatorHash
    scriptValidatorHash = ownHash ctx

    emptyVal :: Value
    emptyVal = lovelaceValueOf 0

    parseInputDatum :: TxOut -> Price
    parseInputDatum o = case txOutDatum o of
      (OutputDatum (Datum d)) -> unsafeFromBuiltinData d
      NoOutputDatum -> 
        traceError $ "No datum found in input: " 
          <> decodeUtf8 ( getPubKeyHash 
                        $ (\(PubKeyCredential pkh) -> pkh) 
                        $ addressCredential 
                        $ txOutAddress o
                        )
      _ -> traceError "Failed to parse input datum."

    -- | How much of the offered asset is available in this utxo input and for what price.
    priceTier :: TxOut -> (Integer,Price)
    priceTier o = 
      ( valueOf (txOutValue o) (fst offerAsset) (snd offerAsset)
      , parseInputDatum o
      )

    -- | Separate script input value from rest of input value (can be from other scripts).
    --   Throws an error if there is a ref script among script inputs.
    --   Get the weighted average price for all the utxo inputs from this script. This will
    --   throw an error if the datum is not an inline datum or if it is not a price.
    --
    --   returns (Total Value from Script,(Total Offered Asset in Inputs,Weighted Price))
    scriptInputInfo :: (Value,(Integer,Price))
    scriptInputInfo =
      let inputs = txInfoInputs info
          foo (si,(on,wp)) i = case addressCredential $ txOutAddress $ txInInfoResolved i of
            ScriptCredential vh ->
              -- check if it belongs to swap script
              if vh == scriptValidatorHash
              then -- check if input contains a ref script from swap script
                   if isJust $ txOutReferenceScript $ txInInfoResolved i
                   then traceError "Cannot consume reference script from swap address."
                   else let o = txInInfoResolved i
                            -- | Throws an error if datum is invalid
                            (offeredInInput,price') = priceTier o
                            newAmount = on + offeredInInput
                            -- | This can throw an error if first script input
                            --   doesn't contain any offered asset. But basic
                            --   usage assumes it does. Therefore failure here is okay.
                            newWeightedPrice = 
                              unsafeRatio on newAmount * wp + 
                              unsafeRatio offeredInInput newAmount * price'
                        in ( si <> txOutValue (txInInfoResolved i)
                           , (newAmount,newWeightedPrice)
                           )
              else (si,(on,wp))
            PubKeyCredential _ -> (si,(on,wp))
      in foldl foo (emptyVal,(0,fromInteger 0)) inputs
```
The key thing here is that I am pattern matching off the result of `addressCredential` in the `foo` function. When it is a script, it checks whether the script is this validator script. If yes, it does some stuff but most importantly, it calls `priceTier` which tries to parse the inline datum attached to that input. The inline datum is the on-chain encoding for `Price` which is just `Rational`. The parsing is done by `parseInputDatum`. The parsing here should only be attempted if `addressCredential` matches `ScriptCredential`.

The issue is that this turns out to be false. `parseInputDatum` was being executed even if `addressCredential` matched `PubKeyCredential`. I confirmed this by altering `parseInputDatum` (to the version shown above) to display the pubkey hash when it encounters `NoOutputDatum`. The way it is written, it should throw a different error when `NoOutputDatum` is encountered with `ScriptCredential`.

Here is the error message I encountered when I tested it:
``` Txt
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 0 (in the order of the TxIds) failed with: 
The Plutus script evaluation failed: An error has occurred:  User error:
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
Caused by: [
  (builtin decodeUtf8)
  (con bytestring #fe90abc294e5f876d44f9b39583f2e6d905322c4735e3bda2928342f)
]
Script debugging logs: 
```
`fe90abc294e5f876d44f9b39583f2e6d905322c4735e3bda2928342f` is the pubkey hash of my test user who was trying to execute the script. They supplied an input utxo to pay the fee. This input did not contain a datum. It was the only input that did not contain a datum. All other inputs were from the script address and contained the proper inline-datum.

I found a workaround described below.

### Steps to reproduce the behavior

Try using the above code with the below system info.

### Actual Result

`parseInputDatum` is executed even when `addressCredential` matches `PubKeyCredential`.

### Expected Result

No parsing should be attempted when `addressCredential` matches `PubKeyCredential`.

### Describe the approach you would take to fix this

I have found a workaround that may help debug the original issue. All else being equal, I changed the code for `scriptInputInfo` to this:
``` Haskell
    scriptInputInfo :: (Value,(Integer,Price))
    scriptInputInfo =
      let inputs = txInfoInputs info
          addrCred i = addressCredential $ txOutAddress $ txInInfoResolved i
          foo (si,(on,wp)) i = 
            if ScriptCredential scriptValidatorHash == addrCred i
            then -- check if input contains a ref script from the swap script
                 if isJust $ txOutReferenceScript $ txInInfoResolved i
                 then traceError "Cannot consume reference script from swap address."
                 else let (offeredInInput,price') = priceTier $ txInInfoResolved i
                          newAmount = on + offeredInInput
                          -- | This can throw an error if the first script input
                          --   doesn't contain any offered asset. But basic
                          --   usage assumes it does. Therefore failure here is okay.
                          newWeightedPrice =
                            unsafeRatio on newAmount * wp +
                            unsafeRatio offeredInInput newAmount * price'
                      in ( si <> txOutValue (txInInfoResolved i)
                         , (newAmount,newWeightedPrice)
                         )
            else (si,(on,wp))
      in foldl foo (emptyVal,(0,fromInteger 0)) inputs
```
The only difference is I am using if-then-else for the address credential check instead of pattern matching. (For completion sake, I also removed the `o = txInInfoResolved i` before `priceTier` was called.) Everything else was the same.

This worked as it should. The fact that this worked led me to believe this is a compiler issue which is why I am opening the issue here.

### System info

OS: Ubuntu 20.04 LTS
GHC: 8.10.7

I am using the nix-shell from within the plutus-apps cloned repo with the latest release checked out. I then `cd` into my directory like in the Plutus Pioneer's Course.

My compiled code was optimized using plutonomy.

I have attached my cabal.project file, .cabal file, the source code for the broken on-chain code, and the source code for the fixed on-chain code. There are some redundant functions in the on-chain code from me trying to diagnose the issue.

[cabal.project.gz](https://github.com/input-output-hk/plutus/files/10239483/cabal.project.gz)
[cardano-swaps.cabal.gz](https://github.com/input-output-hk/plutus/files/10239484/cardano-swaps.cabal.gz)
[CardanoSwaps(broken).hs.gz](https://github.com/input-output-hk/plutus/files/10239486/CardanoSwaps.broken.hs.gz)
[CardanoSwaps(fixed).hs.gz](https://github.com/input-output-hk/plutus/files/10239487/CardanoSwaps.fixed.hs.gz)

Edit:
Added two sentences at the very beginning to convey the problem asap.

**Comment by zliu41** [comment]
> parseInputDatum was being executed even if addressCredential matched PubKeyCredential

I can't think of any reason for this to happen. @fallen-icarus could you also provide the exact input to the validator (datum, redeemer, script context) that led to this behavior? We need them to reproduce it.

**Comment by fallen-icarus** [comment]
@zliu41 I realized I never directly tested whether the issue is with plutonomy or not, so I just tested it. I'm glad I did because the bug is definitely in plutonomy. The original `TypedValidator` script works correctly. The bug is introduced after optimizing it with plutonomy's `optimizeUPLC`.

My apologies for not testing it sooner. This issue can be closed.
