### ISSUE TITLE
Documentation accessed from cicero.ci.iog.io is blocked (Specifications and design, Academic papers, etc.)

### ISSUE THREAD

**Issue by SmaugPool** [input-output-hk/plutus#5025]
### Summary

The `plutus` repo README includes links to important documentation like the [Plutus Core Specification](https://cicero.ci.iog.io/api/fact/e620956c-f0f9-4605-bb06-e3d92cc92b6b/binary) and [Extended UTXO Model](https://cicero.ci.iog.io/api/fact/ffdcd1ee-97e2-4661-936d-4b41086d646a/binary).

These documentations cannot be accessed currently as they ask to login to Google then refuses access with the error "Access blocked: Production can only be used within its organization".

### Steps to reproduce the behavior

1. Go to https://github.com/input-output-hk/plutus
2. Click the [Plutus Core Specification](https://cicero.ci.iog.io/api/fact/e620956c-f0f9-4605-bb06-e3d92cc92b6b/binary) link

### Actual Result

Once logged to Google, error "Access blocked: Production can only be used within its organization" is returned (maybe except for IOG/IOHK members).

### Expected Result

The documentation should be displayed.

### System info

OS: all
Repo commit: d79f67eb296348c37ddafc4b18aafa7221322348

**Comment by SmaugPool** [comment]
Note that hydra.iohk.io is down, so the documentation that was also available there is not anymore, like the Plutus Core Specification: https://hydra.iohk.io/build/14133599/download/1/plutus-core-specification.pdf.

**Comment by michaelpj** [comment]
Dupe: https://github.com/input-output-hk/plutus/issues/4981#issuecomment-1329186819
