### ISSUE TITLE
Merkelized abstract syntax trees

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#506]
This is something we may want to consider to reduce, e.g., data transmission costs. (See also [Simplicity](https://blockstream.com/simplicity.pdf).)

**Comment by michaelpj** [comment]
See https://github.com/input-output-hk/plutus/tree/master/docs/plutus-core/Merklisation for notes.

**Comment by kwxm** [comment]
Superseded by #1592.
