### ISSUE TITLE
[plutus-ledger-api] Expose mkTermToEvaluate or fromSerialisedScript

### ISSUE THREAD

**Issue by ch1bo** [input-output-hk/plutus#5133]
### Describe the feature you'd like

As the Hydra team, we want to profile our fully applied plutus-tx scripts.

For this, we have cobbled together a way to get the actual scripts from transactions we create in [this PR](https://github.com/input-output-hk/hydra/pull/721/files#diff-d5c861d76b1d4c0f37308f18a620ccb49518112fed2bdb2e3f1a8923edde8384R180-R184).

The current approach uses a ledger function to collect the scripts and the `plutus-ledger-api` `mkTermToEvaluate` function to apply datum, redeemer and context arguments to the validator function. This function was exposed in the `plutus` version we use (`plutus-ledger-api-1.0.0.0`) via module `Plutus.ApiCommon`.

This function is not exposed anymore on master.

### Describe alternatives you've considered

We would consider vendoring the contents of `mkTermToEvaluate`, but that would require `fromSerialisedScript` which is also not exposed.

If we do it wrong in the first place, any suggestions other than exposing and using these functions are welcome!

**Comment by effectfully** [comment]
I've created #5143, not entirely sure if I got your request right, so please review.
