### ISSUE TITLE
Define a release process

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#514]
We need a process to manage and execute updates to Plutus Playgrounds that include changes to the Playgrounds UI and/or changes to the API for writing Plutus contracts. For the moment, this revolves mainly around Plutus Playgrounds, but will become more broadly important once we are integrating into Cardano core. This needs to address the following issues:

* Release QA (requires staging version)
* Change log (maybe have a GitHub tag to flag PRs that include user-visible changes)
* Error messages that help users migrate their Plutus code
* Deployment (both the online version and Docker image)
* Frequency of releases
* Announcing the release

The purpose of this issue is to serve as a place to discuss the various aspects of the release process. To discharge this issue, commit a markdown document defining the concrete release process.

**Comment by michaelpj** [comment]
Other things we need to think about:
- Versioning scheme
    - Semantic versioning etc.
    - Are the playgrounds versions always identical to those of the libraries they depend on?
        - This is important if we're also releasing the libraries to Hackage.
        - At the moment a deployment of the playgrounds is always going to be using the corresponding version of the libs in git.
        - Can be awkward if we use semver.
- Deployments/releases
    - Does the playgrounds version increment for every deployment?
- Do we write the changelog on release, or incrementally?
- How does the rest of the company publish releases/changelogs, and should we be doing the same?
- Who cuts releases?

**Comment by mchakravarty** [comment]
See also #480
