### ISSUE TITLE
The `IdentifierState` data type used in lexing/parsing

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#527]
I changed `IntMap` to `UniqueMap` (a new data type, not on master yet) in `IdentifierState`, updated `newIdentifier`, called `stack test language-plutus-core` to see where things break during lexing/parsing, but to my surprise I got no failure. So are those `IntMap`s ever used anywhere?

Since we now have `Text` everywhere including tokens:

```haskell
data Token a = LexName { loc        :: a
                       , name       :: T.Text
                       , identifier :: Unique -- ^ A 'Unique' assigned to the identifier during lexing.
                       }
                       | ...
```

Can we change `M.Map BSL.ByteString Unique` to `M.Map T.Text Unique` as well?

Also, can we make `IdentifierState` a real data type rather than a tuple?

**Comment by michaelpj** [comment]
It can also move to the lexer proper. It used to be use by the renamer, which is why it is where it is, I think.

As to your observation: it's a bidirectional map, and I think that the `Bytestring -> Unique` direction is used during lexing, and maybe the `Unique -> Bytestring` direction was only used by the renamer so is now dead.

**Comment by effectfully** [comment]
> It can also move to the lexer proper.

Would be good.

**Comment by vmchale** [comment]
`IdentifierState` is used in the lexer. I'm not sure what `parseST` and whatnot are used for - they may be dead code. 

The `IdentifierState` doesn't matter much once lexing is done (which co-occurs with parsing).

**Comment by effectfully** [comment]
What I'm saying is that it seems `IdentifierState` contains redundant information that is never used.

**Comment by vmchale** [comment]
Oh, it's used in `handle_identifier`. If you try to replace it with `()` then things fail.

**Comment by michaelpj** [comment]
`handle_identifier` just calls `newIdentifier` which uses the forward direction of the map and updates but does not use the reverse direction of the map.

**Comment by vmchale** [comment]
Ah okay, yes that is now redundant.
