### ISSUE TITLE
Upgrade plutus to build with ghc-9.6

### ISSUE THREAD

**Issue by erikd** [input-output-hk/plutus#5301]
[x] Make it build
[ ] Add it to CI
[ ] Upload to CHaP

**Comment by erikd** [comment]
PR is https://github.com/input-output-hk/plutus/pull/5286

**Comment by angerman** [comment]
@michaelpj would you be able to review this?

**Comment by michaelpj** [comment]
I'm aware of it. I've also got the CI bit more-or-less ready to go.

I think we might want to make some individual sub-tasks for the stuff we need to do to get it on CHaP. There are a *lot* of dependencies that need updating.

**Comment by angerman** [comment]
@michaelpj 
> I think we might want to make some individual sub-tasks for the stuff we need to do to get it on CHaP.

fully agreed. @erikd can you create the subtasks? I doubt there are _real_ subtasks in GH, but we can just create multiple tickets and link them here, I believe.

**Comment by michaelpj** [comment]
I've narrowed down the problems to just a few. Lots has been fixed on Hackage recently. Listing the remaining ones here:
- https://github.com/well-typed/cborg/issues/311 blocks basically everything on 9.6 on aarch64-darwin, but WT know about it
- https://github.com/typeclasses/hex-text/issues/7 . Just needs a revision.
- https://github.com/mokus0/th-extras/pull/20 . Just needs a revision.
- `int-cast` is basically unmaintained, just needs a revision, but probably we should just purge it
- `inline-r` need more than just bound relaxation alas. But all the stuff we need is in master, so it just needs a release. https://github.com/tweag/HaskellR/issues/415
- The known `foundation` issue

I've commented/opened issues throughout, will try and act on `int-cast` soonish.

**Comment by erikd** [comment]
Still need to upload this to CHaP.

**Comment by michaelpj** [comment]
We do a release at the end of every sprint.

**Comment by erikd** [comment]
When is that?
