### ISSUE TITLE
Look into upgrading to `flat ^>= 0.6` on master and check that the script dump test continues to pass

### ISSUE THREAD

**Issue by erikd** [input-output-hk/plutus#5309]
> @bezirg could you look into upgrading to `flat >= 0.6` on master and check that the script dump test continues to pass?

_Originally posted by @michaelpj in https://github.com/input-output-hk/plutus/pull/5286#discussion_r1184884346_

**Comment by bezirg** [comment]
Yes, I am taking a look now.

**Comment by erikd** [comment]
@bezirg I think the constraint needs to be `flat ^>= 0.6`.

**Comment by erikd** [comment]
@bezirg I understand this is complete and everything checked out ok?
