### ISSUE TITLE
Expose sized integers in Plutus Tx

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#532]

**Comment by effectfully** [comment]
> The main downside of this would be that it would be quite annoying to work with!

I'd really expect it to be more helpful than annoying. I've used [`GHC.TypeLits`](http://hackage.haskell.org/package/base-4.12.0.0/docs/GHC-TypeLits.html) in production, it all goes very nicely if you do not need to match on those type literals in a dependently-typed way (which I think we don't need).

I think, we can omit singleton sizes on the Haskell side and pass them implicitly via classes as how [it's usually done](https://stackoverflow.com/a/27030038/3237465).

[Data.Reflection](http://hackage.haskell.org/package/reflection-2.1.4/docs/Data-Reflection.html) is also related.

**Comment by michaelpj** [comment]
No sizes any more!
