### ISSUE TITLE
Abstracting across multiple Plutus Tx scripts is tedious

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#533]
This refers to [CGP-299](https://iohk.myjetbrains.com/youtrack/issue/CGP-299). I like to keep this open for now, so we'll revsit after some more experience with contracts.

**Comment by michaelpj** [comment]
I'm going to copy over my last comment from that thread:

> I've become less convinced that we should do something more here. Here are some things that would be true about a strategy that uses unfoldings:
> 
> - You would not be able to use arbitrary functions, especially from external libraries.
>      - Dad pointed out to me that there is an "include all unfoldings" flag, and you could recompile all your dependencies with that... but that seems unpalatable.
>  - In order to be sure you can use a function, you would need to annotate it in some way (either our own special annotation or INLINEABLE)
>  - Function bodies are inlined, so you want to be careful about what you use.
> 
> However, the current TH solution is really no worse than this!
> 
>  - You can't use arbitrary functions, you can only use TH quoted functions.
>  - In order to be sure you can use a function, you need to export it as a TH quoted version.
>      - But this requires no pragmas, just using the right types, so it's very obvious whether it will or won't work.
>  - Function bodies are inlined.
>      - But this is exactly what normally happens with TH, and is familiar from other code-generating approaches, like Feldspar.
> 
> So the tradeoff seems to be between things sometimes "just working", versus things consistently being a bit different. I think I actually prefer just always using TH, which also has the benefit of being familiar and not requiring us to explain or rely upon more internal GHC features.
>

**Comment by michaelpj** [comment]
I wonder whether we should try the `-fexpose-al-unfoldings` approach a try. Things we would need to do:
- I would need to work out how to reliably get the unfoldings (seemed not to work before).
- We'd need to transitively recompile all the dependencies with this flag.

Concerns:
- Apparently `-fexpose-all-unfoldings` differs from `INLINEABLE` in that it can put in *post*-optimization unfoldings (https://ghc.haskell.org/trac/ghc/ticket/12963). This is worrying - we're mostly dealing with pre-optimization Core, and I'm not sure we can necessarily deal with post-optimization Core.
- We're sensitive to any use of features we don't support in transitive dependency. One transitive dep uses GADTs? Boom.

**Comment by michaelpj** [comment]
(My change in feeling has been prompted by having to reimplement a Map suitable for use in Plutus Tx)

**Comment by j-mueller** [comment]
> One transitive dep uses GADTs? Boom.

Or polymorphic let bindings

**Comment by michaelpj** [comment]
Someone else was talking on #ghc about doing a Core -> something else whole-program compiler (which is what we're doing), and https://gitlab.haskell.org/ghc/ghc/issues/10871 came up. This is pretty interesting, and I think would let us do what we want to do in a more principled way. 

If there are other people interested in this, and people like Edward behind the design, maybe we can revive it.

**Comment by j-mueller** [comment]
But with that we still wouldn't be able to compile code that uses typeclasses and GADTs, right?

**Comment by michaelpj** [comment]
Sure, but my main goal is to get rid of the need for everything to be TH splices.
