### ISSUE TITLE
Derive Aeson instances for Plutus datatypes

### ISSUE THREAD

**Issue by uhbif19** [input-output-hk/plutus#5368]
### Describe the feature you'd like

Derive `ToJSON/FromJSON` instances inside plutus codebase.

### Describe alternatives you've considered

For now we are using orphan instances:

https://github.com/mlabs-haskell/hydra-auction/blob/staging/src-utils/HydraAuctionUtils/Extras/PlutusOrphans.hs

**Comment by effectfully** [comment]
@zliu41 @michaelpj any objections to adding `ToJSON` and `FromJSON` instances to `plutus-tx` and `plutus-ledger-api`?

**Comment by michaelpj** [comment]
We don't need it, and there are in principle multiple ways to do it. And since we're not using them, it would be hard for us to guarantee that they're any good and/or don't change in ways people don't like.

On the other hand, it's relatively cheap to do, and `aeson` is certainly in everyone's dependency closure regardless.

**Comment by zliu41** [comment]
I've always disliked the `ToJSON` and `FromJSON` typeclasses, since as Michael pointed to, there's no canonical way of encoding something in JSON. I would suggest that downstream packages add their own functions for converting to/from JSON when needed.

**Comment by uhbif19** [comment]
> it would be hard for us to guarantee that they're any good and/or don't change in ways people don't like

Encoding classes do have laws, that may be checked automatically.
For `change in ways` client package might just use golden tests.

> as Michael pointed to, there's no canonical way of encoding something in JSON.

That is one of the reasons why having some default implementation is useful.

> I would suggest that downstream packages add their own functions for converting to/from JSON when needed.

Okay, I will try to make some `plutus-aeson` package from our code then.
