### ISSUE TITLE
Multi-module contracts

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#542]
We eventually need to support having a contract split across multiple modules in the Playrgounds. This requires the following:

* [ ] selector box to switch between the different modules in the editor area,
* [ ] transmitting multiple modules in requests,
* [ ] backend dealing with multiple modules during type checking and contract execution, and
* [ ] sensible error reporting in the presence of multiple modules.

**Comment by michaelpj** [comment]
> We eventually need to support having a contract split across multiple modules in the Playrgounds

Why? Generally I think there's a slippery slope towards "write our own web IDE", and I think we should resist going down it.

At some point we have to say "go develop this on your local machine with the real tools", and in some ways the longer we postpone this the more annoying it is to migrate things.

**Comment by mchakravarty** [comment]
> Why? Generally I think there's a slippery slope towards "write our own web IDE", and I think we should resist going down it.

Yes, the question is where to stop? This has no easy answer, of course.

I do think, we should support multiple modules, though. I don't think, we should add any features that make it easier to work with many modules (that would be too far down the IDE road IMHO). However, being able to decompose a bit is nice and FWIW Remix also supports multiple files.

**Comment by mchakravarty** [comment]
> What's the point of adding multiple modules if we don't make it easy to work with them? ;)

I didn't say we don't make it easy to work with multiple modules. I said, we don't make it easy to work with *many* modules. I think, having a handful of modules is useful in the playgrounds. Having a huge project is a different matter and definitely not where we want to go. (Just as a concrete example, multi-file search (and replace) is something we don't want to do.)

I am happy to leave this as a low priority item, but I am pretty sure, we'll come back to it.
