### ISSUE TITLE
The links in "Specifications and design" are broken

### ISSUE THREAD

**Issue by nielstron** [input-output-hk/plutus#5441]
### Summary

The links in the section [Specifications and design](https://github.com/input-output-hk/plutus#specifications-and-design) to [Plutus Technical Report (draft)](https://ci.zw3rk.com/job/input-output-hk-plutus/master/x86_64-linux.plutus-report/latest/download/1) and [Plutus Core Specification](https://ci.zw3rk.com/job/input-output-hk-plutus/master/x86_64-linux.plutus-core-spec/latest/download/1) and [Extended UTXO Model](https://ci.zw3rk.com/job/input-output-hk-plutus/master/x86_64-linux.extended-utxo-spec/latest/download/1) are broken.

### Steps to reproduce the behavior

1) Check the readme
2) click on links

### Actual Result

404

### Expected Result

Some papers I would like to read

### Describe the approach you would take to fix this

Fix the links, but I don't know where the documents are

### System info

Any

**Comment by effectfully** [comment]
@michaelpj are you the right person to ping on this one or do you happen to know who that would be?
