### ISSUE TITLE
`PlutusTx.loadFromFile` using a runtime parameter

### ISSUE THREAD

**Issue by KristianBalaj** [input-output-hk/plutus#5451]
### Describe the feature you'd like

I want to load validator from file by using a runtime parameter (i.e. parameter based on user input of the running program).

I'd like to do something like this where the `path` is coming from e.g. a command line argument:
```haskell
myValidator :: P.FilePath -> PlutusTx.CompiledCode UntypedValidator
myValidator path = $$(PlutusTx.loadFromFile path)
```

Of course it doesn't work resulting in the following error:
```
• GHC stage restriction:
    ‘path’ is used in a top-level splice, quasi-quote, or annotation,
    and must be imported, not defined locally
• In the typed splice: $$(PlutusTx.loadFromFile path)
```

Is there any trickery available with Template haskell to be able to do this somehow?

### Describe alternatives you've considered

I've found an alternative to use this package https://hackage.haskell.org/package/th-env and pass the path via env variables.

**Comment by zliu41** [comment]
Hi @KristianBalaj, TH code runs at compile time, so it cannot depend on a runtime parameter. If you need to load CompiledCode from a path at runtime, how about `do { s <- Data.ByteString.readFile path; pure (SerializedCode s Nothing mempty) }`?

**Comment by effectfully** [comment]
@KristianBalaj it looks to me like @zliu41 answered your question. As such, I'm closing this issue. Please do feel free to reopen it if there's still something you'd like to discuss here.
