### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by dostrelith678** [input-output-hk/plutus#5459]
### Summary

The [Specification and design section](https://github.com/input-output-hk/plutus#specifications-and-design) links are broken.

### Steps to reproduce the behavior

1. Check the readme
2. Click on links

### Actual Result

```
500 Internal Server Error
Caught exception in Hydra::Controller::Build->download "warning: 'ls-store' is a deprecated alias for 'store ls'
error: opening file '/run/agenix/nix': Permission denied
```

### Expected Result

The links work normally.

### System info

Any browser.

**Comment by michaelpj** [comment]
Cannot reproduce? I'm confused.

**Comment by dostrelith678** [comment]
> Cannot reproduce? I'm confused.

Yes, they are working now for me too. I guess I can close this. 🤷‍♂️
