### ISSUE TITLE
Some Haskell constructs tend to produce things that violate the value restriction

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#546]
List literals:

> GHC converts list literals into repeated applications of cons, i.e. a redex.
>
> GHC converts list literals of integer literals into a polymorphic redex. It does this not only for [1,2,3]::[Int] but also for [1::Int, 2::Int, 3::Int], annoyingly. These are illegal because of the value restriction, even though they're immediately instantiated to Int.
>
> The only thing I've found that works is (1::Int):(2::Int):(3::Int):[], which is tedious.

Polymorphic let bindings without a type signature. From our tests:
```
newtype EmptyRose = EmptyRose [EmptyRose]
...
let map _ []     = []
        map f (x:xs) = f x : map f xs
        go (EmptyRose xs) = EmptyRose (map go xs)
in go
```
This gets interpreted as a polymorphic let-binding of a *monomorphic* function, i.e. the foralls are outside the let binding. But let bindings are compiled into redexes, so this violates the value restriction.

Adding a type signature to `map` fixes it.

(IMO this is just more reason we should drop the value restriction)

**Comment by effectfully** [comment]
I wonder whether automatic eta-expansion [that we talked about before](https://github.com/input-output-hk/plutus/pull/473#issuecomment-453570400) can help here as well. To me, the strictness we have is so counter-intuitive that I constantly get it wrong and end up evaluating arguments of non-saturated functions which has always been nonsense for my use cases, so I'd really like automatic eta-expansion for this reason. And it seems like automatic eta-expansion can free us from recursion mangling. So if it helps here as well, that would be another argument. But I do not immediately see how it applies here, it's just that the value restriction and eta-expansion are related topics.

**Comment by michaelpj** [comment]
Automatic eta-expansion won't help if you're not defining something of function type. And I'm not convinced that there's a general algorithm that does what we want (or I didn't understand it).

I agree that strictness is counter-intuitive sometimes, but it seems like what you're trying to do is automatically make things behave more like you expect... i.e. lazier! If we want things to be lazy let's make the language lazy, but I don't want to put it in if it's not semantically necessary atm.

**Comment by effectfully** [comment]
> Automatic eta-expansion won't help if you're not defining something of function type.

True. List literals are off and we do want list literals.

> but it seems like what you're trying to do is automatically make things behave more like you expect... i.e. lazier! If we want things to be lazy let's make the language lazy, but I don't want to put it in if it's not semantically necessary atm.

I only want laziness in one particular place: an argument of an unsaturated function does not get computed. This is not full-scale laziness at all.

I do not propose to implement or even discuss eta-expansion right now, because if anything else I do not have a well-defined proposal (what is a "saturated function"?). Just leaving a mention here in case we'll want to consider it later.

**Comment by kwxm** [comment]
@jmchapman says he'd like to get rid of the value restriction in the Agda version, so maybe we should revisit this.

**Comment by michaelpj** [comment]
The value restriction is gone, so this is fixed.
