### ISSUE TITLE
Parser for Plutus IR

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#549]
Nobody is really supposed to write PIR textually, but there are two main exceptions to that:
- Testing: it's helpful to be able to write examples literally rather than tediously constructing the AST
- Debugging: if you print out the PIR for something it's nice to be able to feed that back in via a parser

Then if we did this we could also have a `pir` executable like the `plc` one that exposes parsing/typechecking/compiling which would be nice.

**Comment by michaelpj** [comment]
Note that PIR is a superset of PLC, so this also means we need a PLC parser. We'll probably need to write another one, since the main one uses happy/alex which afaik isn't easy to embed into another parser.

**Comment by vmchale** [comment]
You should be able to export such a parser and embed it I believe - it might require everything to be in the same module though, which I suppose we do not want, but is easier than rewriting the parser.

**Comment by m-alvarez** [comment]
PR: https://github.com/input-output-hk/plutus/pull/592

**Comment by michaelpj** [comment]
Done.
