### ISSUE TITLE
Check documentation for broken links in CI

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#550]
This is one of those things that's very easy to miss and makes you look bad. We should be able to do this fairly mechanically.

Annoyingly, it needs network access and is non-deterministic, so Nix won't like it. Maybe we could do it as a buildkite job.

Tools:
- https://github.com/smallhadroncollider/brok, not on Hackage yet though.

**Comment by michaelpj** [comment]
+Jann because I'm now terrified of the many links in the tutorial.

**Comment by j-mueller** [comment]
good idea. There are quite a few links now but the number of target sites is low (mostly our own repository, haddocks on github-pages, the Haskell wiki, and GHC documentation).

The only problem I see with making it part of CI is that it can cause builds to fail even if the change that is being tested has nothing to do with the failure. Maybe it should only emit a warning instead, or send an email?

**Comment by michaelpj** [comment]
Sure, but e.g. I want to get a warning if we move something and it break the Haddock links.

I agree it's maybe not best as a PR check, but not sure where else it should go.
