### ISSUE TITLE
Multi-contract playgrounds

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#556]
**NB:** This is rather speculative at the moment and needs to be refined.

Currently, there is only one contract in the playground at any time (and all wallets possess the same contract endpoints). Do we want to eventually relax this restriction? If so, what do we need to do to realise this and how can we adapt the Playgrounds UI?

**Comment by j-mueller** [comment]
> and all wallets possess the same contract endpoints

Somewhat related, I was thinking that endpoints could change over the course of the contract, based on the current state. I don't know how to handle that in the Plaground UI though.
