### ISSUE TITLE
raw terms in Agda and conversion from plutus syntax

### ISSUE THREAD

**Issue by jmchapman** [input-output-hk/plutus#559]

**Comment by jmchapman** [comment]
I discovered that size checking of constants happens during parsing, so even a raw term in agda should have a proof that that the value is in bounds in it.

**Comment by michaelpj** [comment]
IMO this is a mistake and should happen in a later apss.

**Comment by jmchapman** [comment]
I expected it to be part of the typing rules. It is not in the typing rules in the spec - the typing rule for term constants refers to figure 11, I think it should refer to figure 12. However, neither figure has the check in it. I can't find it anywhere else either.

**Comment by jmchapman** [comment]
I have moved size checking (and witness generation) to the scope checking phase for the moment.

**Comment by kwxm** [comment]
I think this should be done during typchecking, the reason being that if we only do it during parsing then one could construct a fake AST containing an integer constant whose type lies about its size (like 2^1000000 claiming to be an 8-bit integer).  That could then be sent to the chain and used to initiate an expensive calculation.  Builtins do perform dynamic bound checks, but (I think) this only happens at the end of the calculation, to make sure the result hasn't overflowed.  So you could pay a small amount to have your script run and then do something really expensive that evades the gas check.
