### ISSUE TITLE
Additions to plutus-ledger-api

### ISSUE THREAD

**Issue by lehins** [input-output-hk/plutus#5613]
### Describe the feature you'd like

In ledger we would like to drop direct dependency on `plutus-core` in favor of `plutus-ledger-api` and avoid defining orphan instances for Plutus types. Here is a list of things that would help us do that:
* Expose `fromSatInt` (`SatInt` is already exposed)
* ~`enumerate`, because we need to do the same thing in our tests: https://github.com/input-output-hk/plutus/blob/d3f1377d98b5aad7e9078f90d11e6f79e87d99ea/plutus-ledger-api/test/Spec/CostModelParams.hs#L69-L71~
* Add instances:
  * `NFData` and `NoThunks` for `CostModelApplyError`

**Comment by effectfully** [comment]
See #5618.

> `enumerate`, because we need to do the same thing in our tests

I didn't do that, because I'm not sure how sensible it is to expose an arbitrary auxiliary function from `plutus-ledger-api`, particularly given that it's a one-liner. I don't mind doing that, just don't know if it's right. @zliu41 @michaelpj opinions?

**Comment by lehins** [comment]
> We don't even define enumerate, it's from

Good to know. We'll use `extra` then :smile:

**Comment by effectfully** [comment]
Resolved by #5621 and #5618.
