### ISSUE TITLE
Documentation about origin / state of indices of BuiltinFun / AST terms etc

### ISSUE THREAD

**Issue by nielstron** [input-output-hk/plutus#5670]
### Describe the feature you'd like

The current standard of flat encoding UPLC implies that terms are distinguished by the order of their constructor. This makes i.e. finding the correct index for AddInteger very painful. Indeed [the definition order](https://github.com/input-output-hk/plutus/blob/b5492cbbe48121124c078be127fb48fa770305f8/plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs#L53) does not match [the indices](https://github.com/aiken-lang/aiken/blob/825e65d7a305296486d91e1cb7916b9158897691/crates/uplc/src/builtins.rs#L12) which makes me wonder where actually one could read up which builtin function has which index?

IMO the index of elements should be independently documented and made sure that the haskell implementation fulfils the standard. The current approach of simply having the Haskell code as the standard is brittle (indexes can change and thus flat decoding will have potentially subtle errors, just by re-ordering elements) and hard to assess for outsiders and third party implementations of uplc such as https://github.com/opshin/uplc

**Comment by kwxm** [comment]
> ... which makes me wonder where actually one could read up which builtin function has which index?

Look at Tables C.3, C.4, and C.5 on pp 56-57 in the Plutus Core [specification](https://github.com/input-output-hk/plutus/tree/master/doc/plutus-core-spec) (pdf [here](https://ci.iog.io/build/1230997/download/1/plutus-core-specification.pdf)).  

In the Haskell source, the tags are defined [here](https://github.com/input-output-hk/plutus/blob/b5492cbbe48121124c078be127fb48fa770305f8/plutus-core/plutus-core/src/PlutusCore/Default/Builtins.hs#L1831), which admittedly isn't very easy to find.
