### ISSUE TITLE
Remove blockheight from PLC builtins

### ISSUE THREAD

**Issue by mchakravarty** [input-output-hk/plutus#568]

**Comment by effectfully** [comment]
@mchakravarty, we do not have `blockheight`, we have `BlockNum`. Remove that?

**Comment by mchakravarty** [comment]
@effectfully Yes (to track https://github.com/input-output-hk/plutus/commit/690117000b7ea20d8a2253ad9676d3e93edddb3e)

**Comment by michaelpj** [comment]
Also `txhash` which is apparently still there.

**Comment by effectfully** [comment]
(I thought, it's supposed to close automatically)

**Comment by michaelpj** [comment]
It has, hasn't it? It only says I did it because I merged the PR.
