### ISSUE TITLE
Make the Plutus Core specification and implementation agree

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#583]
There seem to be a number of places where the spec and the implementation disagree.  I had to look at the parser source to see what the current syntax is.

- [x] The spec says `fix`, the implementation says `ifix`.
- [x]  The spec says `wrap`, the implementation says `iwrap`.
- [x] The spec now has types like `(con integer 5)`, but the parser doesn't accept that: it still wants `[(con integer) (con 5)]`.
- [x] The spec says you can optionally say `(con integer 5bytes)` for clarity, but I don't think that's implemented.
- [ ] According to the spec, built-in functions now take multiple arguments, but I think that internally they're still implemented via curried application. Fixing this would probably make evaluation more efficient, but it might make life difficult for Roman since it interacts with his infrastructure for dynamic built-ins.
- [x] Don't call them dynamic built-ins!  We've got dynamic built-in types now, which could be misleading.  Could we call them something like "extensible basis functions / types"?
- [x] I think the evaluator's now reporting errors using de Bruijn indices: you get messages like **Variable 9 is free at 17:53**.  This is distinctly cryptic, so if the real names are still available it might be helpful to report them as well.
- [x] In addition, I think it might be useful to have a few moderately complex PLC programs in the repository to (a) check that the parser accepts what it's supposed to, and (b) make it easier for people (me, for instance) to see what the current input syntax looks like.  This has changed a few times and it can take a little while to work out how programs have to change so that they parse/typecheck properly.

**Comment by effectfully** [comment]
> The spec says `fix`, the implementation says `ifix`.
> The spec says `wrap`, the implementation says `iwrap`.

Discussed in [Resolve remaining issues with `ifix`](https://github.com/input-output-hk/plutus/issues/423#issuecomment-456338858).

> According to the spec, built-in functions now take multiple arguments, but I think that internally they're still implemented via curried application. Fixing this would probably make evaluation more efficient, but it might make life difficult for Roman since it interacts with his infrastructure for dynamic built-ins.

I think I know how to make evaluation more efficient without making this change (those napkins at PlutusFest were really helpful!). I also think that implementing what is currently in the spec is not as easy as it seems. But it's probably not a right time to have this discussion, because if we're moving to the all-builtins-are-dynamic approach, then this problem turns into something else.

> Don't call them dynamic built-ins! We've got dynamic built-in types now, which could be misleading. Could we call them something like "extensible basis functions / types"?

I dislike "dynamic builtin names/types" as well, but I'm hoping for something shorter than that.

> In addition, I think it might be useful to have a few moderately complex PLC programs in the repository to (a) check that the parser accepts what it's supposed to, and (b) make it easier for people (me, for instance) to see what the current input syntax looks like. This has changed a few times and it can take a little while to work out how programs have to change so that they parse/typecheck properly.

For this reason our executable, `plc`, supports the `example` command, see `plc example --help`. E.g. you can run `plc example --single succInteger` and you'll get

```
(program 1.0.0
  (abs
    s
    (size)
    (lam
      i
      [(con integer) s]
      [
        [ { (builtin addInteger) s } i ]
        [
          [
            { { (builtin resizeInteger) (con 1) } s }
            [ { (builtin sizeOfInteger) s } i ]
          ]
          (con 1 ! 1)
        ]
      ]
    )
  )
)
```

But there are only very simple examples right now.

**Comment by vmchale** [comment]
I will handle the parser bit.

**Comment by vmchale** [comment]
I don't think the poor error messages are due to de Bruijn indices - it's just that the `FreeVariable` constructor should take a label rather than just a `Unique`.

**Comment by vmchale** [comment]
Looks like we should also update the example in the spec - we use `[(con bytestring) (con 5)]` there.

**Comment by kwxm** [comment]
> Looks like we should also update the example in the spec - we use `[(con bytestring) (con 5)]` there.

Fixed.

**Comment by kwxm** [comment]
I think that the parser and printer are dealing with sizes incorrectly.  My understanding (which I now realise was previously somewhat confused) is the following:

* For each positive integer s, we have a type size_s, denoted by `(con size s)` in the concrete syntax.

* Each type size_s is a singleton type, with a unique inhabitant: this is denoted by s in the specification and `(con s)` in the concrete syntax.  

This means that a call to resizeInteger should look like this:
```
    [{(builtin resizeInteger) (con size 3) (con size 5)}  (con 5) (con 3!200)]
```

Here the first two `con`s are types instantiating the type arguments of `resizeInteger` and `(con 5)` is a runtime size argument that tells the evaluator the size to attach to the new integer object.

At present it seems that `(con 5)` is used at both the type and term level.  The evaluator doesn't accept the thing above, but does accept this:

```
 [{(builtin resizeInteger) [(con size) (con 3)] [(con size) (con 5)]} (con 5) (con 3!200)]
```

However, it looks like sizes are going, so all of this is completely irrelevant.

**Comment by kwxm** [comment]
Let's close this.  I think everything's been fixed now.
