### ISSUE TITLE
Add a way to collapse pretty-printing output to something predefined

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/plutus#609]
This is in order to show stuff like `forall a. a -> a -> a` as `boolean`.

**Comment by michaelpj** [comment]
I'm not keen on this.

If you want to get readable output in PLC you can bind your type to a name so you see the name in the main code. This is what you get if you compile from PIR.

If you want to have even more readable output then generate PIR and print that.

The one thing this doesn't help with is the booleans produced by builtins, but IMO these are a fairly minor case.

**Comment by effectfully** [comment]
Makes sense to me.
