### ISSUE TITLE
Actually implement verifySignature

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#617]
This, along with the easier `intToByteString`, are the last unimplemented builtins from the spec. We should implement it, especially since we want to validate our claims about how much time is spent doing crypto in a typical smart contract.

However, when looking at the spec I note that it does *not* specify what cryptographic scheme is used for keys, which is something we need to decide!

**Comment by vmchale** [comment]
Should we put something about this on the mailing list? Which cryptographic scheme seems like a big deal.

**Comment by michaelpj** [comment]
It should presumably be the same as the one Cardano uses, whatever that is.

**Comment by kwxm** [comment]
Google suggests that we're using an elliptic curve scheme based on a curve called [Ed25519](https://en.wikipedia.org/wiki/EdDSA).  There's a repository here with an implementation: https://github.com/input-output-hk/cardano-crypto

We should ask someone who actually knows though: it does seem kind of fundamental.

**Comment by michaelpj** [comment]
Done.
