### ISSUE TITLE
PIR parser fails occasionally

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#624]
Here is a build with associated seed for the test suite: https://hydra.iohk.io/build/613408/nixlog/1

**Comment by m-alvarez** [comment]
The problem: the parser expects bytestring literals to have an even number of digits, e.g. `#00` is valid but `#0` is not. This is easily fixable, but I thought it was the desired behavior. 

The current PLC parser behaves in exactly the same way, so if this is indeed a bug then both need to be fixed.

**Comment by m-alvarez** [comment]
The same behavior can be triggered in the PLC parser with:

    language-plutus-core-test --hedgehog-replay "Size 82 Seed 15812606119386308263 110159750707462013"

**Comment by m-alvarez** [comment]
Fix in #628
