### ISSUE TITLE
Example that uses verifySignature

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#636]
There are other ways to benchmark `verifySignature` vs. the evaluation/typechecking/etc., but it would be sensible to have an example for engineering purposes as well - for instance, identifying bottlenecks in serialization etc.

**Comment by j-mueller** [comment]
I think this can be closed now. `verifySignature` is used by the following examples from `plutus-use-cases`:

* CrowdFunding.hs
* MultiSig.hs
* PubKey.hs

**Comment by michaelpj** [comment]
I wrote some benchmarks for this.
