### ISSUE TITLE
Playground Security

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#649]
For the first version of the playground, we made the decision that the risk of attacks was too low and the effect of an attack was not significant enough to worry about. With the next version ready for the Miami summit, this is no longer the case. We need to at a minimum:
- [x] make sure that a malicious user cannot use the playground as a vehicle for further attacks to the AWS account
- [x] minimize the effect of a denial of service attack
- [x] minimize the down time caused by a DOS attack

This involves:

- [x] effective sandboxing of the playground process
- [ ] monitoring to alert us of an issue asap
- [ ] ability to scale quickly
- [ ] tuning of timeouts to ensure that there is enough time to run any contract but we avoid users accidentally DOS the playground
- [x] ensure that submitting a contract multiple times doesn't send multiple requests at the same time

**Comment by shmish111** [comment]
submitting a contract multiple times is not possible by accident, the submit button is disabled while a request is being processed.

**Comment by shmish111** [comment]
Two basic forms of monitoring should be added:
1. regularly compile a basic contract and push the time it took to datadog
2. monitor real request times, status codes and especially timeout values so we can see if timeouts happen.

Additionally we should:
1. increase the timeout for now, it is quite low and we can tune once we have a graph of average response times
2. Add alarms in datadog

**Comment by michaelpj** [comment]
> submitting a contract multiple times is not possible by accident, the submit button is disabled while a request is being processed.

What if I re-enable it by messing with the HTML? ;)

**Comment by shmish111** [comment]
This is absolutely possible but the point of this is that it can't be done by accident. This would require the user to be actively malicious. They could just curl to do this anyway.

**Comment by shmish111** [comment]
TBH I think protecting a system like this from malicious DOS attacks is pretty much impossible without spending money on a proprietary DOS protection system. As usual with security it's about cost vs reward and I think in our case as long as we remove the chances of accidental DOS we can take the risk of malicious DOS.

I suppose we could blacklist IPs if we get attacked as a minimal stance, I think that's pretty simple with AWS so I just need to make sure that the request IPs are visible. This should protect against simple random attacks which is probably worth it.

**Comment by michaelpj** [comment]
Seems like a reasonable threat model to me.

**Comment by shmish111** [comment]
Oh, looks like nginx has nice rate limiting built in, I think that should be sufficient.

**Comment by shmish111** [comment]
nginx, add `limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/s;` [see here](https://www.nginx.com/blog/rate-limiting-nginx/)

**Comment by shmish111** [comment]
for sandboxing add the following to the systemd services
```
DynamicUser=
ProtectKernelTunables=true
ProtectControlGroups=true
ProtectKernelModules=true
PrivateDevices=true
SystemCallArchitectures=native
CapabilityBoundingSet=~CAP_SYS_ADMIN
```
see https://www.freedesktop.org/software/systemd/man/systemd.exec.html

**Comment by shmish111** [comment]
For monitoring we can use a combination of

http://hackage.haskell.org/package/ekg
http://hackage.haskell.org/package/servant-ekg-0.2.0.0
http://hackage.haskell.org/package/ekg-statsd

This should send all the basics to the dogstatsd service for which nixos has a module.

**Comment by shmish111** [comment]
After the things mentioned above we will only require some refactoring of terraform and nixops to make scaling up and down easy.

**Comment by shmish111** [comment]
Metrics in https://github.com/input-output-hk/plutus/pull/663

Next I will refactor deploy code to make scaling easier and reduce duplication
After that I will look into creating datadog alarms etc with nixops

**Comment by shmish111** [comment]
Also need to add a health check that compiles a basic contract so we can set an alarm if the time taken is too high

**Comment by shmish111** [comment]
I'm not sure what we can do for "minimize the down time caused by a DOS attack", perhaps this is just a matter of documenting possible procedures including stoping machines and scaling both horizontally and vertically.

**Comment by shmish111** [comment]
It looks like we may be moving on to prometheus rather than datadog so I won't look into datadog monitors and dashboards yet. @disassembler is going to talk to me next week about what we will need to do but since everything uses statsd there should be not much work in getting things set up.

**Comment by shmish111** [comment]
health check added in https://github.com/input-output-hk/plutus/pull/668
I think the final thing to do (until prometheus is ready) is to add a bit more documentation around what to do when things go wrong.

**Comment by shmish111** [comment]
I'm going to close this issue now, we have https://github.com/input-output-hk/plutus/issues/669 open and when that is done we should also write some sort of runbook for when things go wrong and how to  know early with monitoring etc. It doesn't really make sense to write something detailed until the monitoring side is finished.
