### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#653]
Several things to consider:

- [ ] Clean up & separate benchmarks for renamer, deserializer, and typechecker
- [ ] Improve performance of renamer and typechecker; examine performance of deserializer as well
- [ ] Gather more thorough heap profiles for everything so that we are assured that there is no pathological behavior w.r.t. garbage collection or whatnot
- [ ] Consider using something besides lazy bytestrings internally. Maybe [Bytes](http://hackage.haskell.org/package/memory-0.14.18/docs/Data-ByteArray.html#t:Bytes)? We don't want our users to complain about our Crypto being slow. 

cc @kwxm

**Comment by michaelpj** [comment]
These are still things we need to do, but let's split this up into more issues when we revisit it.
