### ISSUE TITLE
playground /version endpoint doesn't work

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#667]
https://prod.playground.plutus.iohkdev.io/version shows `UNKOWN`

**Comment by j-mueller** [comment]
@krisajenkins is there any chance of fixing this before the summit? Knowing the version would be extremely helpful for dealing with the feedback we're going to get.

**Comment by shmish111** [comment]
I'm going to look into it this afternoon but it has proved to be tricky in the past.

**Comment by shmish111** [comment]
Fixed with https://github.com/input-output-hk/plutus/pull/690
