### ISSUE TITLE
Better tests for mockchain

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#672]
Most of the tests are unit tests, we should really add some property tests

**Comment by m-alvarez** [comment]
This seems like a good use case for `quickcheck-state-machine` - Michael and I were thinking about rewriting some tests with it in preparation for eventually pushing the LTL stuff, what do you think?

**Comment by j-mueller** [comment]
Sounds good!

**Comment by m-alvarez** [comment]
For the record, here's where this is happening
https://github.com/m-alvarez/plutus/tree/wallet-api-property-tests
