### ISSUE TITLE
Aliases in wallets and the Playground

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#673]
We want to have some kind of alias support in both wallets and the Playground, so that when users are issuing commands and looking at outputs they can see a human-readable identifier rather than a hash.

We probably want these for:
- Public keys (users)
- Currency ids
- Transaction ids?

**Comment by michaelpj** [comment]
Aliases for transaction ids just occurred to me. It might actually be quite nice - we could auto-generate a fairly-unique but memorable string (e.g. using the "correct horse battery staple" approach), which would then at least make it easier to see when things are referring to each other.

**Comment by michaelpj** [comment]
I think aliases should be local to a wallet, here's why.

Aliases seems like an example of somewhere we need a petname system: http://www.skyhunter.com/marcs/petnames/IntroPetNames.html

Consider public key addresses:
- The hash is a *key*: global and secure
- If we have a public registry of aliases so people can talk about/discover them, then these would be *nicknames*: global and memorable
- Local aliases are *petnames*: secure and memorable

Where does this provide benefit? Consider:
- You get Bob's address from the registry
- You save the address to your registry with a petname of "That Bob guy"
- "Bob" is taken over in the registry by a malicious user who requests that you send them money
- You wallet alerts you that this is not a recognized address, in particular not  "That Bob guy"

Also as a minor convenience point, we allow people to use whatever names they like for hashes.

The playgrounds are an unusual example, since the user controls the entirety of what would normally be a multi-party system. So in that case we could just enforce that everyone's petname mappings are the same.

**Comment by mchakravarty** [comment]
If we where to use petnames, we’d at least have to pre-populate them with some global default name. For the case of currencies (fungible ones), you really just want to get the currency name that everybody else uses.

Generally speaking, petnames seem to make much more sense for non-fungible tokens than fungible ones.

**Comment by michaelpj** [comment]
I think we absolutely want a global nickname registry too.

**Comment by mchakravarty** [comment]
> I think we absolutely want a global nickname registry too.

Ok, and then petnames shadow nicknames?

**Comment by michaelpj** [comment]
Ideally you don't use nicknames except in clearly marked circumstances ("You've just received a payment from .... (nickname: "Bob"). Would you like to add them as "Bob" to your address book?").

**Comment by mchakravarty** [comment]
@krisajenkins & @j-mueller What is the story with aliases for the Summit version?
