### ISSUE TITLE
Reduce proliferation of sample contracts?

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#695]
Some contracts (guessing game, crowdfunding, vesting) currently exist in three places:

1. `plutus-use-cases`
2. `plutus-tutorials`
3. `plutus-playground-server`

That's not ideal. On the other hand, in each place there are slightly different requirements that affect how the contract is written. For example, in the tutorials and playground samples there is a policy of "no `$`, no `.`". The playground samples also include the `mkFunction [...]` calls (which are not available in the other two locations because `mkFunction` is defined in `plutus-playground-lib`) and various JSON and Swagger instances.

Also, all three locations are at least typechecked during CI builds so the contracts always stay up to date with API changes. 

So I'm not sure what to do about this.

**Comment by michaelpj** [comment]
I think it would be good if they were at least all defined next to each other. Maybe we can use the same simplified versions for the tutorial and the playgrounds? I'd be okay with programmatically stitching on the `mkFunction` calls to make that work...

**Comment by michaelpj** [comment]
I was updating the playground use cases and was reminded of how annoying this is.

**Comment by michaelpj** [comment]
We now have even more copies, in that we have the book.

I think it would make sense for all of the use cases to appear in an appendix of the book as extended examples. That would mean writing them up a little bit with some literate Haskell and including them, and moving the tests.
