### ISSUE TITLE
Make it easy to use the Plutus libraries

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#704]
Installing the Plutus libraries locally is not straightforward. Besides the libraries not being published to Hackage there is an issue with the `cryptonite-openssl` library on Windows that requires users to install OpenSSH separately (I haven't been able to find the correct version of OpenSSH yet).

**Comment by michaelpj** [comment]
I think we want to be on Hackage, but not too soon. In particular:
- It ties us down to actual versioning.
- It makes renaming/merging/splitting of packages harder.

Ideally we should provide instructions for all of Cabal, Stack, and Nix.

**Comment by vmchale** [comment]
I think a large barrier here is the haddocks. So far we have Michael as the main library user, and we would like a clean (not too much redundant/distracting stuff) API that is not too restrictive.
