### ISSUE TITLE
Transform client code to state passing style

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#709]
The client code of each contract is going to be compiled to an executable, the contract runtime. The contract runtime should be a stateless component. Therefore we need to transform all actions in the `WalletAPI` monad into functions that take the current state and produce a new state plus some events (register triggers, create transactions, etc.)

**Comment by michaelpj** [comment]
Note: to do this in strictly monadic style we'd need to serialize a continuation back to the client, which we almost certainly don't want to do.

Instead, we probably want applicative style computations, so all the client-side effects we want can be done up front. We could use selective functors to improve this further.

**Comment by j-mueller** [comment]
I had a look at the selective functors paper and it seems to be a great fit for what we're trying to do.

**Comment by j-mueller** [comment]
Implemented in https://github.com/input-output-hk/plutus/pull/1013
