### ISSUE TITLE
"Abstract machine failed" in playground

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#719]
Here are two contracts that only differ in the validator script: https://gist.github.com/j-mueller/4deb385ace0064e08bac8843fffabeb8

When running the trace below, `DoesntWork.hs` fails with this error:

![grafik](https://user-images.githubusercontent.com/1771361/54454426-b83a4a00-4759-11e9-8d60-e1f8b1f994ed.png)

and `Works2.hs` works.

![grafik](https://user-images.githubusercontent.com/1771361/54454481-d9029f80-4759-11e9-966c-0a2cc9723d78.png)

Diff between `DoesntWork` and `Works`:

![grafik](https://user-images.githubusercontent.com/1771361/54454525-f5064100-4759-11e9-86d5-244b9d5f9be0.png)

(ie. the pattern match)

The error doesn't happen when `DoesntWork.hs` is run locally on the mockchain in GHCi.

**Comment by j-mueller** [comment]
This is on the plutus playground docker image tagged `plutus-playgrounds:yn7h7m5qdjnnj9rxv8cgkvvwjkkcdnvp`

The /Version route says `ff1825cba961ff8e57def44d1f1fe725dbc108df` which doesn't appear to be a commit on master (?)

**Comment by j-mueller** [comment]
The order of arguments in validator scripts was changed by this commit: https://github.com/input-output-hk/plutus/commit/6a9914a94b2b6f63b9f3ce6b62511abe9c40cdd3

The docker image was made before this commit so it still expects arguments to be in the old order. When I ran this version of the solution (old order) it worked fine: https://gist.github.com/j-mueller/a30eeb0e702015217cdaa6802f473eea

**Comment by michaelpj** [comment]
And here's why it doesn't fail at typechecking! https://github.com/input-output-hk/plutus/blob/master/wallet-api/src/Ledger/Types.hs#L649

**Comment by kwxm** [comment]
Do you know exactly why it's failing? The (not terribly helpful) message "Cannot reduce a not immediately reducible application" appears when the CEK machine tries to apply a function to an argument which isn't a value, and that should never happen because it's supposed to reduce all arguments to values before starting to apply the function.  I can't quite work out what's going on from the error report above.  

It does say "contact support for assistance", so maybe I should try that...

**Comment by michaelpj** [comment]
@kwxm see above: that error shouldn't occur if the program typechecks, but we hadn't been typechecking the application of the validator script to the data and redeemer script, so when Jann changed the order of arguments, we made a non-typechecking program.

**Comment by kwxm** [comment]
Yes, but I'd like to understand what the (ill-typed) term is that's making it fail.  The error message above refers to some things whose definitions we can't see.  In particular, what is `ds_256: Signature_221`?  It looks as if the overall term is trying to instantiate a big lambda at a small lambda, but I'm not sure if the latter is at the type level or the term level.  Is the problem that the big lambda is coming from the validator and its argument is from one of the other scripts?

**Comment by michaelpj** [comment]
Presumably it's giving you the term it's evaluating without the current environment. 

I'm not sure that trying to dissect this term will bring much enlightenment :man_shrugging:

**Comment by kwxm** [comment]
Looking at it more closely, I'm still not sure what's causing the machine error. I think that that particular message should only appear if there's a function application with an argument which isn't a value, but I can't see anything in the term that it's complaining about which would cause that.

**Comment by kwxm** [comment]
Oh well, never mind.  I was trying to reproduce this using the evaluator on the command line, but couldn't do it.  It may be that the parser is rejecting things that would cause it to fail, but when things are composed on-chain the parser isn't involved.  I'm reasonably sure that that message should never appear (even with ill-typed terms) unless there's something wrong with the evaluator, but maybe bypassing the parser lets you construct terms that are malformed in other ways, like having an application with no arguments (although even that shouldn't cause this particular message).

**Comment by kwxm** [comment]
We should come back and check this when we eventually do have typechecking during validation.

**Comment by effectfully** [comment]
@kwxm,

> I think that that particular message should only appear if there's a function application with an argument which isn't a value, but I can't see anything in the term that it's complaining about which would cause that.

>  I'm reasonably sure that that message should never appear (even with ill-typed terms) unless there's something wrong with the evaluator

I think this message also should appear if the head of application is neither lambda nor a builtin. I.e. if you apply a constant (like `1!1`) to a value (or a bunch of them), you'll get this error message, but I haven't checked.
