### ISSUE TITLE
Track gas usage throughout.

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#722]
Currently, we do not stop executing or throw an error when we run out of gas. We should do so, and it should take the cost model functions as an argument.

**Comment by michaelpj** [comment]
Notes:
- We need to calculate gas for builtins based on the arguments to the builtin, so that e.g. the cost of integer operations is proportional to the size of the integer.
    - For dynamic builtins this means the type of the cost model function for a given builtin depends on the type of that builtin. So we probably need to bundle these up into `DynamicBuiltinMeaning`.
- We need to calculate gas cost and check the threshold *before* doing a potentially expensive operation.
