### ISSUE TITLE
Release tutorial along with API docs to GH pages

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#726]
We should release the tutorial at a specific version and not via our repository so that people don't get confused. We can put them next to the API docs on GH pages.

Releasing them can go along with releasing the playground/API docs.

**Comment by j-mueller** [comment]
This would also be a good target for the "Tutorial" and "API" links in the Playground

**Comment by michaelpj** [comment]
We did this by deploying the docs along with the playground.
