### ISSUE TITLE
Multi currency support in Playground

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#727]
We are planning to implement [the multi-currency proposal](https://github.com/input-output-hk/plutus/blob/master/docs/multi-currency/multi-currency.md) in the mockchain for the summit. This issue is for tracking the changes that need to be made to the Playground UI to make it (relatively) easy to work with multiple currencies.

Values of a user-defined currency will look like this:

```haskell
type TokenId       = ByteString
type CurrencyValue = Map TokenId Int
```

`CurrencyValue` maps can have any number of entries. Their `TokenId`s are defined by the author of the currency.

Currencies themselves are identifed by their `ScriptHash`. Unlike `TokenId`, which can be any ByteString, `ScriptHash` has to be a validator script hash - the hash of the currency's monetary policy script (the script that controls how much of a currency can be forged). 

```haskell
type Currency = Map ScriptHash CurrencyValue
```

# Examples

There are two examples we definitely want to support:

## Example 1. Regular Currency

A new currency called MuellerCoin. There is an endpoint that forges an initial amount 1000 MuellerCoins. (This means there is a transaction whose `txForge :: Map ScriptHash CurrencyValue` field looks like `Map.singleton <script hash> (Map.singleton "MuellerCoin" 1000)`. We would like to run the following trace:

1. Use the `forge` for wallet 1, resulting in the creation of 1000 MuellerCoins
2. Use the `payToPubKey_` endpoint for wallet 1 to transfer 300 MuellerCoins to wallet 2. We currently have an argument of type `Ada` for `payToPubKey_`, this should be of type `Currency` and the user needs to enter the value `Map.singleton <script hash> (Map.singleton "MuellerCoin" 300)`
3. Use the `payToPubKey_` endpoint for wallet 2 to transfer 100 MuellerCoins to wallet 3. Here we need to enter `Map.singleton <script hash> (Map.singleton "MuellerCoin" 100)`

## Example 2. Tokens for Contract Roles

Smart contracts can have multiple roles, for example "Contributor" and "Owner" in the crowdfunding campaign, and "Long" (buyer) and "Short" (seller) in the swap contract. We would like to represent these roles using Non-Fungible Tokens (NFTs). We should be able to run the following trace for the swap contract. (This may be too ambitious given the constraints we have during the summit, but we can do a simpler version of this for the vesting contract):

1. Use the `setupSwap` endpoint for wallet 1. The outcome of this is a transaction whose `txForge` field looks like `Map.singleton <script hash> (Map.fromList [("Long", 1), ("Short",1))
2. Use `payToPubKey_` for wallet 1 to transfer the "Long" token to wallet 2. So the user needs to enter the value `Map.singleton <script hash> (Map.singleton "Long" 1)` as an argument.
3. Wallet 1 uses the `initialiseShort` and wallet 2 uses the `initialiseLong` endpoint to set up the relevant triggers
4. We wait for 20 slots during which some money is exchanged automatically (via trigger mechanism)
5. We use `payToPubKey_` on wallet 1 to transfer the "Short" token to wallet 3. (user needs to enter the value `Map.singleton <script hash> (Map.singleton "Short" 1)` as an argument)
6. We use `initialiseShort` on wallet 3.
7. Wait another 20 slots to finish the contract.

The outcome is for the first 20 slots the contract is between wallet 1 and wallet 2. For the remaining slots the contract is between wallet 3 and wallet 2. The key in this trace is the transfer of the "Short" token in step 5, which represents the transfer of a role (stake) in the contract.

We could also write a contract that combines Ex.1 and Ex.2 (for example, a currency where the right to forge more of it is represented by a token). But for the demo we only need these two distinct cases.

# UI Support

The Playground UI should offer a way for users to interact with currencies and currency values. In particular
* The `payToPubKey_` contract endpoint should be able to transfer any `CurrencyValue` of any currency to any pubkey address
* The final balances should be be grouped by currency
* (Ideally) the UTXO visualisation should reflect currencies. I'm not sure about the best way to do this. In the sankey diagram this could be done by only ever showing the flows of one currency, and adding a selection box to switch between currencies. In the new (boxes and arrows) visualisation we could simply write out the maps in text form.

Users should be able to define a set of known currencies with their contract. 

# How does the Playground know which currencies are interesting?

Each currency will be identified by a hash. Since entering hashes into a textbox is not very user-friendly there should be a list of "known currencies" for a contract: 

```haskell
data KnownCurrency = KnownCurrency { hash :: ValidatorScriptHash, friendlyName :: String, knownTokens :: NonEmpty TokenId }
```

then we need something like `mkFunctions` that defines a list of `KnownCurrencies`:

```
$$(mkCurrencies [KnownCurrency ...])
```

That way the Playground knows which currencies to show in the UI, even before a transaction that forges the currency has been encountered.

**Comment by shmish111** [comment]
@j-mueller all this is optional, right? So a user only needs to `mkCurrencies` if they want to? And we will require them to do this if they want to use a currency in a trace. Is there any default currency that should always be available (Ada)?

**Comment by j-mueller** [comment]
You're right, `mkCurrencies` is optional and there will be a default currency that's always available.

**Comment by j-mueller** [comment]
Also, just to clarify, the endpoint in step 6 of the "Tokens for Contract Roles" example might end up being something other than `initialiseShort`. I haven't written the endpoints yet so I'm not completely certain that we can use the same endpoint after the contract has started (although it would be nice if we could!)

**Comment by shmish111** [comment]
https://github.com/input-output-hk/plutus/pull/747
