### ISSUE TITLE
Explain relevant bits of Template Haskell

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#736]
One of the findings from the recent Plutus course was that Template Haskell and how it is used in Plutus need to be explained better, and we can't make any assumptions about prior knowledge in this area. 

The topic is mentioned in various places in the tutorials but it would be better to have a specific chapter dedicated to it. This could replace or subsume the current PlutusTx tutorial. 

We need to talk about

* Compiling vs lifting
* Why the standard library exports all of its definitions as TH quotes, and how to use it in on-chain code
* Haskell features that don't work in on-chain code

This all should be suitable for the Playground. This means we can't have multiple files (and it disqualifies the existing PlutusTx and TH tutorials)

**Comment by michaelpj** [comment]
Basically no TH now!
