### ISSUE TITLE
Wallet backend for smart contracts

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#744]
(This is about the [wallet API](https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/specifications/api/swagger.yaml) in `cardano-wallet`, not the `WalletAPI` class in `wallet-api`)

The interface should support the following interactions with the smart contract backend

* Balance transactions (by adding additional pay-to-pubkey inputs or outputs, using coin selection).
* Submit signed transactions to the network.
* Keep track of interesting pay-to-script addresses. Any transactions that spend or produce outputs at an interesting address should be made available to the smart contract backend. 

We need a mockchain executable that implements this interface.

**Comment by michaelpj** [comment]
Our `WalletAPI` class is *nearly* `WalletBackendAPI`. I think we should have a class for that too.
