### ISSUE TITLE
Add way to configure fees in the playground

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#757]
It would be nice to be able to set fees in the playground, so that you can see coin-selection in action. This could be set as part of the trace.

**Comment by j-mueller** [comment]
FYI you can already see coin selection in action, for example in this trace:

![grafik](https://user-images.githubusercontent.com/1771361/54910287-4fd33180-4eec-11e9-91b3-811cb5477683.png)

The transaction 0b52e0ca consumes all of wallet 2's funds and produces a utxo for wallet 1 and another one for wallet 2:

![grafik](https://user-images.githubusercontent.com/1771361/54910352-75603b00-4eec-11e9-8776-728314416cca.png)

(It's true that we need to have non-zero fees in the Playground though!)

**Comment by michaelpj** [comment]
Ah yes - of course we do have coin selection, and not just for change.

**Comment by mchakravarty** [comment]
We won’t have a resource fee model for the Summit; so, I don’t think, anything else is going to happen on this for the forthcoming release, or am I missing anything?

**Comment by michaelpj** [comment]
Fees for transactions can still be non-zero even without script execution costs! I just think it would be nice to be able to set them to e.g. a constant value just so you can see how that affects things.
