### ISSUE TITLE
Plutus Core Validation Server

### ISSUE THREAD

**Issue by vmchale** [input-output-hk/plutus#765]
This will initially use JSON to make requests; it will return whether the result is valid or not. As inputs, it will receive the validator, redeemer, and data script. 

- [x] Have a canonical JSON conversion
- [x] Write the server
- [x] Use wallet API to determine validity
- [ ] Fix `runScript` in `wallet-api` to do typechecking

**Comment by michaelpj** [comment]
An alternative to having:
```
isValid :: Validator -> Redeemer -> Transaction -> Bool
```
is to have an API more like in Bruno's paper, i.e. we provide
```
-- typechecker, or maybe this is part of `runScript`, even
validScript :: Script -> Bool
applyScript :: Script -> Script -> Script
runScript :: Script -> Bool
```
Then the node can still implement the whole validity checking algorithm and is only parameterized over the primitive operations on scripts.

Might not be so good for a server implementation, but has the advantage of corresponding more obviously to the spec.

**Comment by vmchale** [comment]
We should have some tests for this (as examples if nothing else)

**Comment by michaelpj** [comment]
Closing this since there's been no interest from the Rust team, and we'll probably want to rethink it when we come back to it.
