### ISSUE TITLE
Underscores in Numeric Literals

### ISSUE THREAD

**Issue by takenobu-hs** [input-output-hk/plutus#8]
I am sorry if this is not the right place.

How about changing the syntax of numeric literals in plutus?
Haskell/GHC has recently adopted an extension that enables underscores in numeric literals:
  * https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0009-numeric-underscores.rst

### Current syntax

In my understanding, the current specification of numeric literals in plutus is below:
  * https://cardanodocs.com/technical/plutus/types/#ints-floats-and-byte-strings

```
<int> ::= "-"? <digit>+
<float> ::= "-"? <digit>+ <fractExponent>
<digit> = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<fractExponent> ::= <fraction> <exponent>? | <exponent>
<fraction> ::= "." <digit>+
<exponent> ::= ("e" | "E") ("-" | "+") <digit>+

<bytestring> ::= "#" <byte>*
<byte> ::= <nybble> <nybble>
<nybble> ::= <digit>
           | "a" | "b" | "c" | "d" | "e" | "f"
           | "A" | "B" | "C" | "D" | "E" | "F"
```

### Proposed change syntax

How about changing it as follows?
This improves the readability, quality and expressiveness, especially for large numeric literals.

```
- <int> ::= "-"? <digit>+
+ <int> ::= "-"? <digit> ("_"* <digit>)*

- <float> ::= "-"? <digit>+ <fractExponent>
+ <float> ::= "-"? <digit> ("_"* <digit>)* <fractExponent>

- <fraction> ::= "." <digit>+
+ <fraction> ::= "." <digit> ("_"* <digit>)*

- <exponent> ::= ("e" | "E") ("-" | "+") <digit>+
+ <exponent> ::= ("e" | "E") ("-" | "+") <digit> ("_"* <digit>)*

- <bytestring> ::= "#" <byte>*
+ <bytestring> ::= "#" (<byte> ("_"* <byte>)*)?
```

### Example

The followings are examples of this proposal:

```
lovelace = 0.000_001 :: Float
ada = 1_000_000 :: Int
```

**Comment by michaelpj** [comment]
This doesn't seem important, given that PLC is not really intended for humans to write or read.
