### ISSUE TITLE
Review layout of Meadow 2.0

### ISSUE THREAD

**Issue by palas** [input-output-hk/plutus#802]
The original design of Meadow 2.0 was very stylish but after many technical tweaks there are some aspects that start to look a bit messy.

It would be desirable for the design team to review the current state of Meadow and offer improvement suggestions.

Some examples that clearly could use some improvement:
* Table column sizes in Simulator make little sense.
* Fonts and font styles in errors look inappropriate.
* Colors, layout, and borders in errors are probably inconsistent with playgrounds and other style guidelines.

**Comment by shmish111** [comment]
- [ ] input boxes in input composer become unstyled sometimes
- [ ] if you make an error in the contract editor you need to refocus to fix the error
- [ ] input composer should have some text when there are no actions available
- [ ] state table looks messy
