### ISSUE TITLE
Update cabal-install in nix-shell to 2.4

### ISSUE THREAD

**Issue by hamishmack** [input-output-hk/plutus#815]
Currently `cabal new-repl plutus-tutorial` fails because the cabal version in the path is 2.2.

```
[nix-shell:~/iohk/plutus]$ cabal new-repl plutus-tutorial
cabal: TODO: add support for fetching and reading local tarballs, remote
tarballs, remote repos and passing named packages through
```

Fix might be to adding `cabal-install` to `extradeps` in `stack.yaml` and running `pkgs/generate.sh`.

**Comment by hamishmack** [comment]
Work around is to install cabal-install 2.4 and use the full path to that version when starting `new-repl`.  If you are crazy enough to use Leksah you can remove it from [here](https://github.com/input-output-hk/plutus/blob/master/default.nix#L251) so Leksah will find the one in your system PATH.

**Comment by michaelpj** [comment]
No, we are getting cabal from our snapshot, it's just old because we're still on an 8.4 snapshot. I'm planning to upgrade us to 8.6 especially for a newer cabal, but stuff keeps getting in the way.

**Comment by michaelpj** [comment]
(I did deliberately put a `cabal` in the shell environment because we were having issues with people having different versions.)

**Comment by j-mueller** [comment]
This is fixed now. `nix-shell` and `cabal --version` gives `2.4.1.0`.
