### ISSUE TITLE
dev.scripts.regeneratePackages is not cached on macOS?

### ISSUE THREAD

**Issue by hamishmack** [input-output-hk/plutus#816]
I was looking at #815 and noticed that when running `pkgs/generate.sh` nix started rebuilding (rather than downloading) ghc 8.4.3.

**Comment by vmchale** [comment]
Is your nix setup configured to use IOHK's cache? I ran into a similar problem but it was fixable using the instructions [here](https://github.com/input-output-hk/plutus#Binary-caches).

**Comment by hamishmack** [comment]
I do seem to have the cache set up ok.

I think this is just on macOS though.  Running the following triggers a build of GHC 8.4.3:
```
nix build -f default.nix dev.scripts.regeneratePackages```
```

Running the following (to use the local docker nix build agent) fetched it GHC 8.4.3 from hydra.iohk.io:
```
nix build -f default.nix --system x86_64-linux dev.scripts.regeneratePackages
```

**Comment by michaelpj** [comment]
Are you on latest master? I fixed this recently to add `regeneratePackages` to the derivations that hydra builds, e.g. [here](https://hydra.iohk.io/build/732033) is a recent build of it on darwin. 

Not sure what else could be going on...

**Comment by michaelpj** [comment]
Oh I see, you're getting the cache hit for the linux one, but not the macOS one. That's weird, since I added them at the same time...

(You might wonder: don't I already have GHC 8.4 built for other stuff? And you would be right... blame `iohk-nix`. I tried to band-aid over that by at least making hydra do the work!)

**Comment by michaelpj** [comment]
I suspect this is fine now, feel free to reopen if not.
