### ISSUE TITLE
Tutorial url is wrong in playground

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#845]
Currently points to https://github.com/input-output-hk/plutus/blob/master/plutus-tutorial/tutorial/Tutorial/02-wallet-api.md which does not exist, @j-mueller where should this point to?

**Comment by j-mueller** [comment]
Here: https://github.com/input-output-hk/plutus/blob/master/plutus-tutorial/doctest/Tutorial/02-validator-scripts.md

**Comment by shmish111** [comment]
Is there a reason why this link points to such a specific page, shouldn't it just point to https://github.com/input-output-hk/plutus/blob/master/plutus-tutorial/doctest/Tutorial/ ?

**Comment by michaelpj** [comment]
Also it should really point to the tutorial at the deployed commit, otherwise it'll get out of sync easily.

**Comment by shmish111** [comment]
@michaelpj this was included in https://github.com/input-output-hk/plutus/pull/690

**Comment by j-mueller** [comment]
> shouldn't it just point to https://github.com/input-output-hk/plutus/blob/master/plutus-tutorial/doctest/Tutorial/ ?

Yeah you're right, that's better.

**Comment by shmish111** [comment]
Fixed in https://github.com/input-output-hk/plutus/pull/861
