### ISSUE TITLE
`resizeByteString` broken

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#851]
Compiling this program:

```haskell
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE ScopedTypeVariables #-}
module Test where

import Language.PlutusTx.Plugin
import qualified Language.PlutusTx            as P

f :: CompiledCode (P.SizedByteString 0 -> P.SizedByteString 1)
f = $$(P.compile [|| $$(P.resizeByteString) ||])
```

results in 

```
[6 of 6] Compiling Test             ( Test.hs, interpreted )
GHC Core to PLC plugin: Error: Error from the PLC compiler:
       Type mismatch at () in term
         '(builtin resizeByteString)'.
       Expected type
         '(all s0_80 (size) (all s1_81 (size) (fun [(con size) s1_81] (fun [(con bytestring) s0_80] [(con bytestring) s1_81]))))',
       found type
         '(all s1_76 (size) (all s2_77 (size) (fun [(con bytestring) s1_76] [(con bytestring) s2_77])))'
Context: Converting expr at "plutus-tx-0.1.0.0-inplace:Test:(11,8)-(11,48)"

```

To reproduce, checkout the `resize-bytestring` branch, then

```
nix-shell
cabal new-repl plutus-tx:plutus-tx
:l Test.hs
```

**Comment by michaelpj** [comment]
Ugh, I forgot that the resize functions need to pass term-level size values...

**Comment by michaelpj** [comment]
Argh, this is actually somewhat difficult.

**Comment by michaelpj** [comment]
So, term-level sizes are a pain because they're multi-part constants including a constant natural size that we can't supply separately. This makes them a complete pain.

So here's my horrible idea:
- Implement sized integers
- Use sized integers on the Haskell size instead of size literals, and use `sizeOfInteger` when converting to PLC to get an appropriate size.

**Comment by michaelpj** [comment]
Producing integer literals at a particular size is essentially just as hard, oy vey.

**Comment by j-mueller** [comment]
Closing this as we don't have sizes in Plutus Core anymore.
