### ISSUE TITLE
`Builtins.equalsByteString redeemerHash redeemerHash` hangs

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#852]
On the `anemish/actus-bond` branch, `equalsByteString` hangs when a hashed bytestring is involved. The problem goes away after commenting out `Hash.sha2` from `plcSHA2_256`.

**Comment by j-mueller** [comment]
@nau I poked around the `anemish/actus-bond`  branch some more. I added a test specifically for the hash function (see my commit  fcfea58f337bf9d7f48e30bb595ee1eff64d1ca0 on that branch) which didn't reveal anything unusual. Also I noticed that the problem does not go away anymore after commenting out `Hash.sha2` so I'm not sure whether hashing has anything to do with it now. 

Then I tried to isolate the loop but I don't understand the marlowe code well enough - could you try to narrow down the bug to a smaller example?

**Comment by michaelpj** [comment]
Closing unless we can reproduce it now.
