### ISSUE TITLE
move git-rev from a compile time value to a run time value that can be set in the invoker script

### ISSUE THREAD

**Issue by shmish111** [input-output-hk/plutus#885]
Currently we use an overlay to change a Haskell file and provide it with the current git rev being built. The issue with this is that any tiny change to the repository (e.g. some unrelated documentation) will cause the whole playground module to be rebuilt. This is unavoidable if the revision is compiled in however if we set it in the invoker script as an env var or something then we would only need to rebuilt that script (which is basically free).

The issue we would still have is displaying it on the front end but that will require a different ticket.

**Comment by michaelpj** [comment]
I'm relatively happy with the current state. We're still rebuilding the client code on every commit, which isn't ideal, but it's better than it was. David, close if you're happy.

**Comment by shmish111** [comment]
I don't think we use this in the client any more, I'll have a look and see if we can just remove it
