### ISSUE TITLE
Clarify the meaning of each demo contract

### ISSUE THREAD

**Issue by mearafGitHub** [input-output-hk/plutus#887]
1) It would be less confusing if there could be a drop down menu as list of items for the currency field in the wallets; like Ada, and other currencies that you may want to consider.  
2) for the ease of use to non-technical users, it might be good to some how display the high lights of the main rules for the 'Game' and others models(Vesting, Message and Crowd funding).

**Comment by j-mueller** [comment]
(1) has been addressed in the multi-currency update (to be deployed today)
(2) will be added soon.

**Comment by mearafGitHub** [comment]
Thank you j-muler. Yes the first one has been addressed.
