### ISSUE TITLE
Come up with a nicer DSL for contracts

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#892]
The sample contracts are starting to become more modular so there should be a nice language for composing them (built on top of `WalletAPI`). For example

* We can get the current state of the contract from the UTXO set so there should be a `MonadReader` like interface
* There should be something like `ContT` for dealing with callbacks from the blockchain trigger mechanism (useful for composing contracts in time)

**Comment by michaelpj** [comment]
I think we should explore expressing contracts as state machines. Listening can then be higher-level too - we can listen for "machine is in state X".

**Comment by j-mueller** [comment]
Here's an example that uses `ContT` with the wallet API:

https://github.com/input-output-hk/plutus/commit/d5e8a511301249ad02e9ce410086bc472cbb10bb

I think we can build the state machine on top of that.

**Comment by j-mueller** [comment]
I've been playing around with this a little more and I settled on [this](https://github.com/input-output-hk/plutus/compare/master...j-mueller:j-mueller/892-cont#diff-8bc1db6efa4e45c3984e1efa3f597581R50):

```haskell
data Contract i a =
    Waiting (ContractQuery i) (ContractInput (Input i) -> Contract i a)
    | Done
    | Emit Tx (Contract i a) -- produce a transaction (unbalanced, no signatures). 
    | Pure a
    deriving (Functor)
```

This gives us all we need for the app platform integration (event based)

**Comment by michaelpj** [comment]
Looks a lot like some of the types that pop up in `machines`, from what I recall. E.g. compare with the description of `Plan`: http://hackage.haskell.org/package/machines-0.7/docs/Data-Machine-Plan.html

That makes me wonder whether we could reuse some library that does a similar thing.

**Comment by michaelpj** [comment]
Also, how committed are we to the event-based interaction model thus far?

**Comment by j-mueller** [comment]
> Looks a lot like some of the types that pop up in machines

Yes I hope we will be able to use something that already exists if we decide to go with this. But for `machines` in particular, the `Applicative` instance will be a problem because it should really compose the `ContractQuery` values in parallel and that doesn't seem to be what `machines` is doing. I also had a look at `haxl` but its focus is on the scheduling and execution of queries on different backends which isn't relevant for the contract language. Another option could be parser combinators: We write a parser for a `[Input]`, and we could use [`Control.Applicative.Permutations`](https://hackage.haskell.org/package/parser-combinators-1.0.3/docs/Control-Applicative-Permutations.html) to realise the parallel bits.

> Also, how committed are we to the event-based interaction model thus far?

The main motivation for this is the app platform, where we have to present the contract like a state machine that accepts user inputs (contract endpoints) and blockchain events, and produces transactions and triggers. The `Contract i a` models that exactly. See also #709 - I think we can write an `instance WalletAPI (Contract WalletInput)` so the event-based interaction would not change the API too much.

**Comment by michaelpj** [comment]
Sure, I just want to check whether we'd done any further design discussion with the app platform folks.

**Comment by j-mueller** [comment]
I see - there haven't been any further discussions (call last week was cancelled)

**Comment by michaelpj** [comment]
Well, continuations in particular always tie my head in knots, so if we can use a library where someone else has done the tricky bits, that would make me feel a bit less head-melty :)

**Comment by effectfully** [comment]
I think those are "benign" continuations. Not as alien as `ContT`.

**Comment by michaelpj** [comment]
I think this issue is more or less "done" by the contract api.
