### ISSUE TITLE
Ledger.Index.NegativeValue

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#921]
Transactions that involve a value created using `Ada.toValue` or `Ada.adaValueOf` may fail validation with a `NegativeValue` error.

**Comment by j-mueller** [comment]
The version that's deployed is `e6636a27bfed394f15fc501c89275b9f2aa56443`  (you can get this information from https://prod.playground.plutus.iohkdev.io/version). This doesn't include PR #920 yet, which changes the inputs to the game and vesting contracts to `Value`. After #920 you should not get the `NegativeValue` error anymore. 

The cause of this error is that the `Value` produced by `Ada.adaValueOf :: Int -> Value`  is different from the `Value` you get when you enter an `ada` value in the frontend. The reason for this behaviour is that the `Ada` currency in the playground backend is not correct (the token name should be the empty string, not "ada"). This is fixed by #923.

**Comment by pkellyiohk** [comment]
FYI, the Crowdfunding contract is also affected.

![negative value](https://user-images.githubusercontent.com/36407925/56237023-01cbcc80-6059-11e9-9ede-203af438616c.JPG)
