### ISSUE TITLE
Game demo seems to be broken if following "Testing the contract in the Playground" instructions 

### ISSUE THREAD

**Issue by oofp** [input-output-hk/plutus#922]
I followed steps from 2. Testing the contract in the Playground at
https://github.com/input-output-hk/plutus/blob/3785ed43fe66b59bb8ea3378c7942dfb0015e975/plutus-tutorial/doctest/Tutorial/02-validator-scripts.md
and got the following error:
Logs
Validating transaction: 9f18fa18261821184418fa184818b418360318db18be181a187118b818ba183c0018b818c3189218ca18bf1878189818cb187a18ba18ac18b9181d189c18cbff
Add slot #1
Add slot #2
Submitting transaction: 9f0818da18b0187d18c4186a18bd1850091894188d185418b1188a18db18da186b18551830182918b309181c186618e918eb18b614186718850318dcff
Validation failed for transaction: 9f0818da18b0187d18c4186a18bd1850091894188d185418b1188a18db18da186b18551830182918b309181c186618e918eb18b614186718850318dcff
 Ledger.Index.NegativeValue (Ledger.Tx.Tx {txFee: Ledger.Ada.TH.Ada {getAda: 0}, txForge: Ledger.Value.TH.Value {getValue: Ledger.Extra.LedgerMap []}, txInputs: [Ledger.Tx.TxInOf {txInRef: Ledger.Tx.TxOutRefOf {txOutRefId: Ledger.TxId.TxIdOf {getTxId: "9f18fa18261821184418fa184818b418360318db18be181a187118b818ba183c0018b818c3189218ca18bf1878189818cb187a18ba18ac18b9181d189c18cbff"}, txOutRefIdx: 1}, txInType: Ledger.Tx.ConsumePublicKeyAddress (Ledger.Crypto.PubKey {getPubKey: "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025"})}], txOutputs: [Ledger.Tx.TxOutOf {txOutAddress: Ledger.Tx.AddressOf {getAddress: "9f0318d20018a8181e18e018fe18ac18e818fb1884185e185e18c9185018a618f918ad18d81837091824184f187b1881131846185413189f184118a4ff"}, txOutType: Ledger.Tx.PayToPubKey (Ledger.Crypto.PubKey {getPubKey: "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025"}), txOutValue: Ledger.Value.TH.Value {getValue: Ledger.Extra.LedgerMap [Data.Tuple.Tuple (Ledger.Value.TH.CurrencySymbol {unCurrencySymbol: "5fff"}) (Ledger.Extra.LedgerMap [Data.Tuple.Tuple (Ledger.Value.TH.TokenName {unTokenName: "ada"}) 10]), Data.Tuple.Tuple (Ledger.Value.TH.CurrencySymbol {unCurrencySymbol: ""}) (Ledger.Extra.LedgerMap [Data.Tuple.Tuple (Ledger.Value.TH.TokenName {unTokenName: ""}) -8])]}}, Ledger.Tx.TxOutOf {txOutAddress: Ledger.Tx.AddressOf {getAddress: "9f171874186d18a41881183e1834182018af188518a418e318d7189c1876187b189b185918fb188318f7186a183d18db18b818451889181f1858186f18621875ff"}, txOutType: Ledger.Tx.PayToScript (Ledger.Scripts.DataScript {getDataScript: "f6f6010000c3f6c3f6c5f6c1f6f6714d61696e5f486173686564537472696e6703c0f6c2f6f6714d61696e5f486173686564537472696e6705c1f6c7f6c4f6c0c5f61820c0f6f6714d61696e5f486173686564537472696e6703c2f6f6776d617463685f4d61696e5f486173686564537472696e6704c1f6c0f6f6714d61696e5f486173686564537472696e6703c3f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6c1f6c1f6c7f6c4f6c0c5f61820c0f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6f6756f75745f4d61696e5f486173686564537472696e6706c3f6c0f6f6714d61696e5f486173686564537472696e6705c4f6c1f618205820fb3e740bd0819ab6a49dd85cf082423c6a3ec1b77c4a9eaf9a18880973f6c275c3f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6c1f6c1f6c7f6c4f6c0c5f61820c0f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6f6756f75745f4d61696e5f486173686564537472696e6706c2f6f6656172675f3009c7f6c4f6c0c5f61820c1f6f6756f75745f4d61696e5f486173686564537472696e6707c0f6c2f6f676636173655f4d61696e5f486173686564537472696e6708c1f6c7f6c4f6c0c5f61820c0f6f6756f75745f4d61696e5f486173686564537472696e6707c3f6c0f6f676636173655f4d61696e5f486173686564537472696e6708c0f6f6656172675f3009c2f6f661780ac3f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6c1f6c1f6c7f6c4f6c0c5f61820c0f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6f6756f75745f4d61696e5f486173686564537472696e6706c0f6f661780a"}), txOutValue: Ledger.Value.TH.Value {getValue: Ledger.Extra.LedgerMap [Data.Tuple.Tuple (Ledger.Value.TH.CurrencySymbol {unCurrencySymbol: ""}) (Ledger.Extra.LedgerMap [Data.Tuple.Tuple (Ledger.Value.TH.TokenName {unTokenName: ""}) 8])]}}], txSignatures: Ledger.Extra.LedgerMap [Data.Tuple.Tuple (Ledger.Crypto.PubKey {getPubKey: "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025"}) (Ledger.Crypto.Signature {getSignature: "3fe9caf1a2a3c1d61bb08c700ea9b58a2e3403920ebe6701da4556701cdd93127b9bbe49988ad662d70ea9d30bbd1513950a36dcf817f19e51b4b97587b3a704"})], txValidRange: Ledger.Interval.Interval {ivFrom: Data.Maybe.Nothing, ivTo: Data.Maybe.Nothing}})
Add slot #3
Message from wallet #1: Attempting to collect transaction outputs from 'AddressOf {getAddress = 17746da4813e3420af85a4e3d79c767b9b59fb83f76a3ddbb845891f586f6275}', but there are no known outputs at that address. An empty transaction will be submitted.
Submitting transaction: 9f18c318f31886188a18ca188118c518f018341860187218c2188a18c9185d183a13187018b7189618a2188c1891185f189e07189518de18f218a918a709ff
Validating transaction: 9f18c318f31886188a18ca188118c518f018341860187218c2188a18c9185d183a13187018b7189618a2188c1891185f189e07189518de18f218a918a709ff
Add slot #4

**Comment by j-mueller** [comment]
Should be fixed by #923

**Comment by j-mueller** [comment]
Game demo is fixed now on https://prod.playground.plutus.iohkdev.io/

(see the simulation in this gist: 9e54fde6ffb19d73236e07a1f78b8d02)
