### ISSUE TITLE
Blockchain graph not aligning inputs correctly

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#927]
Gist: 47b1dcfbfb1478537acf3aa505ffb0cb
Version: e6636a27bfed394f15fc501c89275b9f2aa56443

After running simulation 1, the graph looks like this:

![grafik](https://user-images.githubusercontent.com/1771361/56288991-ebbc1b80-60ed-11e9-8925-47499185be2b.png)

There are two transaction "Tx ->" arrows that don't have an output directly above them. In the screenshot I marked the outputs that they should be aligned with,

**Comment by dorin100** [comment]
another similar example

gist: 2f4f82bf8a8e9c5be5dc5d66663e38c5

![game](https://user-images.githubusercontent.com/29144964/56640299-5552a180-667b-11e9-9861-85b63003f367.jpg)

All column values (with the exception of first 2 (Fee and Forge)) seems to be translated to the right.

**Comment by j-mueller** [comment]
Seems to be a duplicate of #883
