### ISSUE TITLE
Transaction costs can be changed by coin selection

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#941]
Suppose you have a validator which iterates over the list of transaction inputs. You run it with your partial transaction to work out how much gas you need, and then you run coin selection to add inptut to cover the gas.

Except now the list of inputs is bigger, so your program takes longer!

We can iterate this process, but there's no guarantee it will converge (although it probably will). Possible solutions:
- Explicitly mark the fee inputs and don't provide those to the validator
    - Conceptually they're part of a commitment to pay the validating node for its time, so arguably they aren't part of the "real" transaction.
- Round up our calculated gas fees and hope that covers any variation.

**Comment by j-mueller** [comment]
I'm strongly in favour of (1) because with (2) we lose the ability to precisely determine the gas cost of our scripts before submitting the transaction

**Comment by michaelpj** [comment]
cc @dcoutts
