### ISSUE TITLE
"Ledger.Index.NegativeValue" error after evaluating any Crowdfunding contract

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/plutus#942]
Gist: 08939bd52d6fd4fd8d35a20e0326db60 (or use any Crowdfunding contract)

The below error can be seen into the Transactions tab:

![image](https://user-images.githubusercontent.com/29144964/56659748-9613e000-66a6-11e9-823f-4d0514028d2c.png)

**Comment by j-mueller** [comment]
This is fixed by #940
