### ISSUE TITLE
Discrepancies in semantics of Plutus Core `error` term.

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#948]
Figure 8 of the PLC spec says that `(error A)` propagates outwards, changing its type as it goes.  The CK machine description suggests (perhaps somewhat unclearly) that the machine should stop immediately, returning `(error A)` without changing the type.  We should make these consistent.  

Depending on what we do, this may also require some modification of the CK/CEK machine implementations.

**Comment by michaelpj** [comment]
There are implicitly two versions of the CEK machine. A typed one, which makes sure to do all type substitutions and would need to do things like ensure it returned a correctly-typed `error`, and an untyped one, which just ignores types in terms. The untyped one is effectively evaluating the erased version of PLC.

I believe our current CEK machine is really implementing the untyped strategy - it doesn't maintain any type information.

Possibly we would benefit from making this clearer. I think it would be good to include something about erasure in the spec generally.

**Comment by kwxm** [comment]
There was some stuff in the spec about erasure, but it appears to have been, er, erased at some point.  I guess Rebecca started on that at some point and commented it out because it was incomplete.

**Comment by michaelpj** [comment]
My understanding on what we need to do here is:
- Replace the reduction rules for typed PLC in the spec with rules that do type substitutions. @kwxm is going to do this.
- Work out a justification for why the current behaviour of the abstract machine is okay (it's not quite just "erase as you go"). @jmchapman is going to do this.

**Comment by kwxm** [comment]
I think we still need to fix this.  If #1524 happens then we'll have plenty more to worry about along the same lines.

**Comment by michaelpj** [comment]
I now think this is fine: the machines as specified do not produce typed error terms and I think we can just be okay with that.

**Comment by jmchapman** [comment]
I am reexamining this. Currently, in the Agda formalisation an error term is any term that contains an error in it. The spec has exactly one error term (`error`) and has a catchall reduction rule that reduces any term to error when one of its subterms reduces to error. I am going to try the spec approach as it has the advantage that a term can either be error _exclusive or_ it can reduce. In the currently formalisation these a term can be an error term _and_ reduce.
