### ISSUE TITLE
Split up `wallet-api`

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/plutus#951]
The `wallet-api` package should be split into two: Emulator (mockchain) and the wallet API itself.

**Comment by michaelpj** [comment]
Arguably three - I think we could probably have our own `ledger` package. E.g. that's what the validation server should depend on.

**Comment by michaelpj** [comment]
Although arguably we have too many packages!

**Comment by j-mueller** [comment]
maybe we should wait until cabal 3.0 comes out with multiple public libraries per package?

**Comment by michaelpj** [comment]
I definitely think we'll want to use that, but I wouldn't hold your breath for it :) perhaps for things like `ledger` it's better to just put them as an internal library inside `wallet-api` and re-export the modules? That at least lets us explicitly state its smaller set of dependencies and keep it separate physically.
