### ISSUE TITLE
'Ledger.Index.NegativeValue' error after evaluating Vesting contract

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/plutus#952]
Gist: 38b8da6050070934dfa2f710f4b153f7
When evaluating the above Vesting contract we receive the below error:

![image](https://user-images.githubusercontent.com/29144964/56720836-57386580-674c-11e9-88a1-fd8e892345b7.png)

Another discrepancy related to the other contracts is that vestingOwner is still requiring a public key instead of a wallet ID (int).

**Comment by j-mueller** [comment]
fixed by https://github.com/input-output-hk/plutus/pull/1207
