### ISSUE TITLE
Revive the "fat interface files" GHC patch

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#982]
https://gitlab.haskell.org/ghc/ghc/issues/10871

This would give us a more principled way of getting unfoldings from our dependencies, rather than requiring things to be manually marked `INLINEABLE`.

**Comment by michaelpj** [comment]
@input-output-hk/tools

**Comment by angerman** [comment]
@michaelpj, @luite: we should outline the expectations (usecases) we hope this would solve just to make sure we keep this focused and on track. Also to cut this short if we learn it would not yield the expected results and a different approach is needed.

**Comment by michaelpj** [comment]
https://github.com/ghc-proposals/ghc-proposals/pull/262
