### ISSUE TITLE
Extended UTXO specification

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/plutus#984]
We should write a specification.

**Comment by kwxm** [comment]
There's now an early draft, based on the Zahnentferner papers and @mchakravarty and @j-mueller 's documents at https://github.com/input-output-hk/plutus/blob/e454fd73a6058956fd65a77c9e4483c99abf1832/docs/extended-utxo/README.md , https://github.com/input-output-hk/plutus/blob/e454fd73a6058956fd65a77c9e4483c99abf1832/docs/multi-currency/multi-currency.md and https://github.com/input-output-hk/plutus/issues/426 , amongst other things.

**Comment by michaelpj** [comment]
I think this is "done", future work will be specific additions and fixes.
