### ISSUE TITLE
Migrate build to use haskell.nix

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/plutus#999]
@angerman has been working on this, just opening as a tracking issue.

My belief is that this is currently blocked on the reinstallable `lib:ghc` work?

**Comment by angerman** [comment]
It's blocked mostly on cross-compilation of plugins :-)

**Comment by angerman** [comment]
See #648 and https://hydra.iohk.io/jobset/Cardano/plutus-pr-648#tabs-jobs.
It's also missing the current customizations from the plutus default.nix :-/

**Comment by michaelpj** [comment]
I'd be keen to get the migration work done even if we simply don't do any cross-compilation for now. Most other projects seem to have made it to `haskell.nix` now, I'd like to be on the same infrastructure as everyone else!

It looks like some of those builds are segfaulting?

**Comment by angerman** [comment]
Yes. Segfaults are due to loading the lib:ghc twice. This could be fixed by not building lib:ghc again.
The cross ones fail due to being unable to load the plugin. Not using lib:ghc fails for doctest stuff. It's a bit of a tricky moat. If you feel like adding the existing extra nix logic from to that PR feel free to do so.

I would try to see if we can do `lib:ghc` only for those that use doctest.

**Comment by michaelpj** [comment]
If you can get me something that builds all the haskell modules that I can import into a larger `default.nix` then I can look at gluing it into the existing stuff.

There isn't much customization of the Haskell stuff:
- There's a thing to make Hydra put the haddocks up as build artifacts, which AFAICT nobody has ever looked at, so can probably be ignored.
- There's the split test stuff, which we no longer need.
- There's some hacks to add doctest stuff.

We *do* need the doctests. I don't mind having special custom derivations to run them, so long as we can work out how to write those.

**Comment by angerman** [comment]
> If you can get me something that builds all the haskell modules that I can import into a larger `default.nix` then I can look at gluing it into the existing stuff.

What do you mean exactly by "build all the haskell modules"? Packages? Components? or really module level?

**Comment by michaelpj** [comment]
Sorry, I was being vague, I just meant: build and test all the Haskell code that we currently do.

**Comment by michaelpj** [comment]
The equivalent of what's currently defined as `localPackages`.

**Comment by angerman** [comment]
Ok, just to make sure I understand this correctly, we have:
https://github.com/input-output-hk/plutus/blob/58a49dcb00a4b161912f79c60e3c99a5fe4bda8f/lib.nix#L24-L43

And anything in that list is considered `isPlutus`. And this is then used to filter the `haskellPackages`
https://github.com/input-output-hk/plutus/blob/58a49dcb00a4b161912f79c60e3c99a5fe4bda8f/default.nix#L142-L144

to produce the `localPackages`?

Looking at the names we have in https://hydra.iohk.io/jobset/Cardano/plutus-pr-648#tabs-jobs, it seems I'm missing some packages but most of them are in the `nix-tools.libs`, `nix-tools.exes`, `nix-tools.tests` and `nix-tools.benchmarks` namespaces.  As haskell.nix produces components as derivations we won't be able to have a 1:1 match with `localPackages`, but could probably try to lump them all together.

I'll try to get them all (except for cross) to build.

**Comment by michaelpj** [comment]
I'm not attached to the structure of the attributes, I'd actively prefer to use the nix-tools standard. Ideally we'd have the nix-tools template to one side and then just import it into default.nix.

**Comment by michaelpj** [comment]
What's the status of this?

**Comment by angerman** [comment]
Let’s talk at zuriHac about this.

**Comment by michaelpj** [comment]
:+1:

**Comment by michaelpj** [comment]
Finally done!
